### ISSUE TITLE
Pandas support - Reading from csv

### ISSUE THREAD

**Issue by UniqASL** [hgrecco/pint#1001]
Dear all,

I tried to reproduce the example "Reading from csv" described [here](https://pint.readthedocs.io/en/latest/pint-pandas.html) but I get the following 

> AttributeError: 'DataFrame' object has no attribute 'pint'

when running 

`df_ = df.pint.quantify(level=-1)`

Any advice on where the error might come from?

Thank you in advance for the reply.

Best regards,

**Comment by jules-ch** [comment]
You need to install `pint-pandas` package. For unit support in pandas with pint you need this package. For any issue put an issue there.

See : https://github.com/hgrecco/pint-pandas

You can look at the examples in the notebooks directory.

**Comment by keewis** [comment]
I think the [pandas support page](https://pint.readthedocs.io/en/latest/pint-pandas.html), it should mention that it requires `pint-pandas`.

**Comment by jules-ch** [comment]
@keewis yes it's not the first time we should be more explicit & redirect to the proper package in the docs.

**Comment by UniqASL** [comment]
@jules-ch and @keewis. Thank you for that. It works now. Unfortunately the documentation was not very clear on that point.
