### ISSUE TITLE
Pandas support - Cannot operate with Quantity and Quantity of different registries

### ISSUE THREAD

**Issue by UniqASL** [hgrecco/pint#1003]
Dear all,

I ran the example described in the section _Reading from csv_ [described here](https://pint.readthedocs.io/en/latest/pint-pandas.html) with the following additional line:

`ureg = pint.UnitRegistry()`
`test = df_["fuel flow rate"] * 10 * ureg["minute"]`

I was getting the error mentioned in the title:

> ValueError: Cannot operate with Quantity and Quantity of different registries.

To solve it I tried the solution described [here](https://pint.readthedocs.io/en/latest/pint-pandas.html):

`pint.PintType.ureg = ureg`

but I got the following error:

> AttributeError: module 'pint' has no attribute 'PintType'

Any advice on that last error?

Thank you in advance and best regards,

**Comment by keewis** [comment]
that would be another bug in the documentation:
```python
pintpandas.PintType.ureg = ureg
```
shoud be used instead.

As you might have noticed, `pintpandas` is not really stable yet, so I guess these issues are to be expected. To lower the expectations, we should probably add a big warning at the top of the `pint-pandas` support page, along with the install instructions.

**Comment by hgrecco** [comment]
@keewis Agreed. Can you submit a PR?

**Comment by UniqASL** [comment]
@keewis, thanks again!
