### ISSUE TITLE
`test_result_type_numpy_func` assumes 64-bit architecture

### ISSUE THREAD

**Issue by toddrme2178** [hgrecco/pint#1006]
The test `TestNumpyUnclassified.test_result_type_numpy_func` assumes it is running on a 64bit architecture.  This causes the test to fail on a 32bit architecture, I suspect because it expects an `int64` while numpy defaults to using an `int32`.  The full failure is below:

```
______________ TestNumpyUnclassified.test_result_type_numpy_func _______________

self = <pint.testsuite.test_numpy.TestNumpyUnclassified testMethod=test_result_type_numpy_func>

    @helpers.requires_array_function_protocol()
    def test_result_type_numpy_func(self):
>       self.assertEqual(np.result_type(self.q), np.dtype("int64"))
E       AssertionError: dtype('int32') != dtype('int64')
```

**Comment by hgrecco** [comment]
Please submit a PR

**Comment by 5igno** [comment]
I am running in the same problem when I run pytest on pint's master branch, without any changes. When I replace `np.dtype("int64")` with `np.dtype("int32")` or `np.dtype("int")`, the test is passed.

What should be the correct numpy datatype for the test? Would `np.dtype("int")` be ok, or should `np.dtype("int64")` be maintained?
