### ISSUE TITLE
Equality of kilobytes and gigabytes

### ISSUE THREAD

**Issue by nightm4re94** [hgrecco/pint#1007]
First of all, thank you for this amazing package - it makes life so much easier!
There is one odd issue converting between information units which I don't consider to be intentional. Have a look at this example where I define identical amounts of information in different units.
```python
ureg = UnitRegistry()

r1 = 1000000 * ureg.kB
r2 = 1000 * ureg.MB
r3 = 1 * ureg.GB

test1 = (r1==r2)
test2 = (r2==r3)
test3 = (r1==r3)
```
where 
```python
test1 = True
test2 = True
test3 = False
```

This means that 
- 1000000 kilobytes is equal to 1000 megabytes (```test1```)
- 1000 megabytes is equal to 1 gigabyte (```test2```)
- 1000000 kilobytes is **not** equal to 1 gigabyte (```test3```)

Is there any intention or reason for this? Why can't you directly check for equality of kilobytes and gigabytes?

**Comment by hgrecco** [comment]
It is a rounding error,
```python
>>> (r3 - r1).m
-2.220446049250313e-16
```

It should be improved when the #1000 is merged. But in any case, comparing equality for floats is in many case unreliable. That is why numpy has methods like [allclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html)

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.

**Comment by fogx** [comment]
now that #1000 is merged, can you elaborate what the correct solution would be?
```
from decimal import Decimal
ureg = UnitRegistry(non_int_type=Decimal)
```
?

**Comment by hgrecco** [comment]
The idea is that `non_int_type` is used to parse any number which are no ints (this includes definitions and user provided quantities as strings in magnitudes and exponents)
```python
>>> from decimal import Decimal
>>> ureg = pint.UnitRegistry(non_int_type=Decimal)
>>> r1 = ureg('1_000_000 kB')
>>> r2 = ureg('1_000 MB')
>>> r3 = ureg('1 GB')
>>> r1.magnitude
Decimal('1000000.0')
>>> r1 == r2
True
>>> r2 == r3
True
>>> r1 == r3
True
```
There are still things to fix, in particular when using Fraction as `non_int_type` and a lot of display things but this idea.
**IMPORTANT**: you need to make sure that types that you use are interoperable. For example:
```python
>>> r1 + 1 * ureg.byte
<Quantity(1000000.0010000, 'kilobyte')>
>>> r1 + 1.0 * ureg.byte
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
```
The first works because `int` works fine with `Decimal`, but the second fails because `float does not.
