### ISSUE TITLE
Presume exponentiation when pint encounters unit followed by number without any operators

### ISSUE THREAD

**Issue by lukelbd** [hgrecco/pint#1009]
I often encounter NetCDF datasets with `'units'` attributes formatted like this:

* `'J/m2'`
* `'m/s2'`
* `'m3'`
* etc.

Is there any way to presume exponentiation when the `pint.UnitRegistry.parse_expression` parser encounters floats following unit strings without any operators?

As a workaround I tried:

```python
import pint
ureg = pint.UnitRegistry()
ureg.define('m2 = m**2')
```

but this does not seem to work. For example:

```python
>>> ureg('m2') / ureg('m')
1.0 <Unit('m2 / meter')>
```

Awesome package btw!

**Comment by jthielen** [comment]
I've run into this exact issue before: https://github.com/hgrecco/pint/issues/851! In short, the way to do this is to add a custom "preprocessor" to your registry to parse this particular syntax. Here's an example:

```python
import re
import pint

def convert_udunits_power(expression):
    return re.sub(
        r"(?<=[A-Za-z])(?![A-Za-z])(?<![0-9\-][eE])(?<![0-9\-])(?=[0-9\-])",
        "**",
        expression
    )

ureg = pint.UnitRegistry(preprocessors=[convert_udunits_power])
```

so that you now have

```python
>>> ureg('m/s2')
1.0 <Unit('meter / second ** 2')>
```

**Comment by dalito** [comment]
Why do you think "this does not seem to work"?

Pint just does not simplify immediately unless you open the UnitRegistry with `auto_reduce_dimensions=True`.

```
>>> ureg = pint.UnitRegistry(auto_reduce_dimensions=True)                                                     
>>> ureg.define('m2 = m**2')                                                                                  
>>> a=ureg('m2') / ureg('m')                                                                                  
>>> a                                                                                                         
<Quantity(1.0, 'meter')>                                                                                      
```

**Comment by lukelbd** [comment]
@jthielen Very cool, thanks! (Also that's one hell of a regex.) Makes sense that this syntax probably should not be the "default" due to ambiguities.

@dalito Did not know about that option, thank you. I was confused because e.g.

```python
>>> ureg('m ** 2') / ureg('m')
1.0 <Unit('meter')>
```

...but I see since `m2` becomes its own "unit" distinct from `'meter'`, a more comparable example would be e.g.

```python
>>> ureg('km') / ureg('m')
1.0 <Unit('kilometer / meter')>
```

Anyway these answers resolve the issue for me.

**Comment by hgrecco** [comment]
By default, same units are simplified by units with the same dimensions do not. `m2` is a new unit that you have defined (not different from `inch` or `foot`). So it is not simplified by defaul.t

Regarding the other thing: Indeed, the spirit in Pint is `do not guess user intention`. So when there are ambiguities we do not implement that feature by default. (but we show you how you can do it!)
