### ISSUE TITLE
Release 0.11 on Feb 18, 2020

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1011]
I have proposing to release version 0.11 in two weeks. I have added a few milestones of things tha I would like to include in that release. Full decimal support is postponed on purpose as it is rather a large change and I would like to test it further.

Please comment or suggest

**Comment by jthielen** [comment]
Right now, #883 is tagged for 0.11, but I very much doubt that it will be ready by Feb 18. Would you want to bump #883 to 0.12 or hold the release until it is ready? I have no preference either way. I unfortunately do not have a good estimate on when I'd be able to get it done, although I am hopeful that it could be late February/early March.

Also, my availability to help with #947 will also be limited until then.

**Comment by hgrecco** [comment]
I would bump it to 0.12. Hopefully this will help us to do a monthly release! Also I hope to have improvements in the numpy coverage as described in #981

**Comment by jthielen** [comment]
https://github.com/pydata/xarray/issues/3266 reminded me that the `PINT_ARRAY_PROTOCOL_FALLBACK` is due to become the intended behavior in this version. I should be able get a short PR in for this soon. Sorry for discovering this at the last minute!

**Comment by jthielen** [comment]
Also, @hgrecco, would you like the NEP 18 `BehaviorChangeWarning` removed for this version?

**Comment by hgrecco** [comment]
@jthielen Go ahead!
