### ISSUE TITLE
Pickled Quantity Changes Type

### ISSUE THREAD

**Issue by SimonBoothroyd** [hgrecco/pint#1017]
Pickling and un-pickling a quantity will cause type coercion between the dynamic `Quantity` class defined by a `UnitRegistry` and the global `Quantity` class. 

This leads to exceptions being raised when comparing quantities which have been pickled with those that haven't:

## Steps to Reproduce the Problem

```
import pint
import pickle

ureg = pint.UnitRegistry()
pint.set_application_registry(ureg)

x = 1.0 * ureg.kelvin
y = pickle.loads(pickle.dumps(x))

z = x > y
```
(tested with `pint ==0.10.1`)

## Exception Raised

```
Traceback (most recent call last):
  File "xxx/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1f849a21d3d1>", line 10, in <module>
    z = x > y
  File "xxx/python3.7/site-packages/pint/quantity.py", line 1484, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
  File "xxx/python3.7/site-packages/pint/quantity.py", line 106, in wrapped
    result = f(self, *args, **kwargs)
  File "xxx/python3.7/site-packages/pint/quantity.py", line 1471, in compare
    raise ValueError("Cannot compare Quantity and {}".format(type(other)))
ValueError: Cannot compare Quantity and <class 'pint.quantity.Quantity'>
```

**Comment by SimonBoothroyd** [comment]
I guess the simple fix for this would be to replace all instance of `isinstance(XXX, self.__class__)` within the `pint.quantity.Quantity` with `isinstance(XXX, Quantity)` (like in `__eq__`), but I'm not sure if this is a particularly robust solution.

**Comment by pcatach** [comment]
I don't think this is solved, I still get the same exception when I execute the steps on `pint==0.11`

**Comment by GeneDesign** [comment]
I am having the same exception, on the latest version of pint.
