### ISSUE TITLE
Error when converting motor voltage constant from V*s/rad in mV*min

### ISSUE THREAD

**Issue by thehalftruth** [hgrecco/pint#1018]
I wanted to convert a motor voltage constant from V\*s/rad in mV\*min, but I get the wrong result.
```
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity
a = Q_(0.32, "V*s/rad")
b = a.to(ureg.parse_expression("mV*min"))
print(a, "==", b)
```

Output:
0.32 second * volt / radian == 5.333333333333334 millivolt * minute

But this is wrong, 33.51 mV\*min is correct:
0.32 (V\*s)/rad \* (2\*pi) = 2.01 V\*s 
2.01 V\*s / 60 = 0.03351 V\*min
0.03351 V\*min \* 1000 = 33.51 mV\*min

**Comment by jules-ch** [comment]
It is expected, pint assume all calculation with radian.

if you put your code like this in your case : 

```python
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity
a = Q_(0.32, "V*s")
b = a.to("mV/rpm")
print(a, "==", b)
```

You need to be explicit when dealing with things like rpm, rad/s.

You get the expected result : 

```python
>>> 0.32 second * volt == 33.510321638291124 millivolt / revolutions_per_minute
```

For atomicity when dealing with this, you can also use `turn` to get the 2 pi conversion.
Like so : 
```
a.to("mV*min/turn")
```

Can you add some context, it seems you're dealing with motor voltage so rpm seems like a good match.

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.
