### ISSUE TITLE
Numpy pad keyerror

### ISSUE THREAD

**Issue by mark-boer** [hgrecco/pint#1026]
Hey all,

First of all, really cool project. I ran into the following issue: when calling `numpy.pad` on a numpy array based quantity I ran into the following error:

```
np.pad(np.array([1,1]) * ureg.meter, pad_width=1)
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in pad
  File "/usr/local/lib/python3.7/site-packages/pint/quantity.py", line 1513, in __array_function__
    return numpy_wrap("function", func, args, kwargs, types)
  File "/usr/local/lib/python3.7/site-packages/pint/numpy_func.py", line 889, in numpy_wrap
    return handled[name](*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pint/numpy_func.py", line 668, in _pad
    kwargs["constant_values"] = _recursive_convert(kwargs["constant_values"], units)
KeyError: 'constant_values'
``` 

The problem lies in the following lines, it is not checked if `kwargs` does contain "constant_values" or "end_values". Adding the check `and "constant_values" in kwargs` should probably work.
```
if mode == "constant":
    kwargs["constant_values"] = _recursive_convert(kwargs["constant_values"], units)
elif mode == "linear_ramp":
    kwargs["end_values"] = _recursive_convert(kwargs["end_values"], units)
```

**Comment by hgrecco** [comment]
Indeed, this works in master:
```python
>>> np.pad(np.array([1,1]) * ureg.meter, pad_width=1, constant_values=0)
<Quantity([0 1 1 0], 'meter')>
```

Maybe we can replace `kwargs["constant_values"]` by `kwargs.get("constant_values", 0)` which (I think) is the numpy default.  What do you think @jthielen ?

**Comment by jthielen** [comment]
> Maybe we can replace `kwargs["constant_values"]` by `kwargs.get("constant_values", 0)` which (I think) is the numpy default. What do you think @jthielen ?

Yes, that seems like the best fix. When implementing it, I had missed that there was a default value! `end_values` should be treated likewise.

**Comment by hgrecco** [comment]
@mark-boer Would you like to submit a PR?

**Comment by mark-boer** [comment]
Sure, but I will first try to get my Dask PR merged. 1 thing at a time 😊
