### ISSUE TITLE
micro prefix incompatibility with babel

### ISSUE THREAD

**Issue by matt-m-herndon** [hgrecco/pint#1030]
The mu prefix returned by babel cannot be interpreted by pint. 

```python
import pint
import unicodedata

ureg = pint.UnitRegistry()

# symbol used internally by pint, this works
ureg(unicodedata.lookup('MICRO SIGN'))

# symbol returned by babel, fails
ureg(unicodedata.lookup('GREEK SMALL LETTER MU'))
```

**Comment by hgrecco** [comment]
Not sure where babel goes into this. But, there is a definition file that include the prefix and their aliases. Adding this prefix to that file should fix it.
