### ISSUE TITLE
Multiplication of quantity by dictionary-like object

### ISSUE THREAD

**Issue by bmlivin** [hgrecco/pint#1032]
I want to multiply a `quantity` by a `dict`-like object which has its own multiply defined. I would like for `pint` to return a `NotImplemented` when it tries to multiply a `quantity` by an object of my type, forcing the multiply to be done using my object's multiply. Here's what currently happens:

```python
import collections
import pint

ureg = pint.UnitRegistry()
q = 5 * ureg.s
c = collections.Counter({1:2, 3:4})
q * c
AttributeError: 'NotImplementedType' object has no attribute '_REGISTRY'
```
I understand that `collections.Counter` doesn't have its own multiply defined, but the error I get is the same if I attempt to multiply the `quantity` by my object with the `quantity` on the left (if the `quantity` is on the right, my object's multiply is used). The actual error here occurs in `pint.quantity.ireduce_dimensions`, when the result of calling the input function `f` is `NotImplemented`.

**Comment by hgrecco** [comment]
What is the expected result of this operation?

Hernan

**Comment by jthielen** [comment]
As a workaround, have you tried adding your dictionary-like type to [the list of upcast types to which Pint defers](https://pint.readthedocs.io/en/0.10.1/numpy.html#Technical-Commentary)? E.g., something like

```python
import pint

pint.compat.upcast_types.append(MultiplicativeDict)
```

I am guessing that the right solution here will be to modify the `ireduce_dimensions` wrapper to either:
- directly return `NotImplemented` when `result` is `NotImplemented`, or
- make the `result._REGISTRY.auto_reduce_dimensions` check be something like `hasattr(result, "_REGISTRY") and result._REGISTRY.auto_reduce_dimensions`

**Comment by bmlivin** [comment]
> What is the expected result of this operation?
> 
> Hernan

If `collections.Counter` had a multiply, I would want the result to be `collections.Counter({1:10 second, 3: 20 second})`.

**Comment by bmlivin** [comment]
> As a workaround, have you tried adding your dictionary-like type to [the list of upcast types to which Pint defers](https://pint.readthedocs.io/en/0.10.1/numpy.html#Technical-Commentary)? E.g., something like
> 
> ```python
> import pint
> 
> pint.compat.upcast_types.append(MultiplicativeDict)
> ```
> 
> I am guessing that the right solution here will be to modify the `ireduce_dimensions` wrapper to either:
> 
>     * directly return `NotImplemented` when `result` is `NotImplemented`, or
> 
>     * make the `result._REGISTRY.auto_reduce_dimensions` check be something like `hasattr(result, "_REGISTRY") and result._REGISTRY.auto_reduce_dimensions`

Yes, I am currently using that workaround, and yes, I had something like that in mind for what I would do for a solution.

**Comment by keewis** [comment]
interestingly, the error you encounter only gets raised if you inherit from `dict`, if you use composition, `pint` will wrap your object.
