### ISSUE TITLE
Non integer types for accurate calculation (post PR #1000 discussion)

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1035]
With the default registry
```python
>>> import pint
>>> ur = pint.UnitRegistry()
>>> ur.Quantity(1, 'uM').m_as('nM')
999.9999999999999
>>> ur.Quantity(1, 'nM').m_as('uM')
0.0010000000000000002
```

Now that #1000 has been merged you can write this code:
```python
>>> from decimal import Decimal
>>> import pint
>>> ureg = pint.UnitRegistry(non_int_type=Decimal)
>>> ureg.Quantity(Decimal(1), 'uM').m_as('nM') # this is correct
Decimal('1000')
>>> ureg.Quantity(Decimal(1), 'nM').m_as('uM') # precision does not fix this but improves it
Decimal('0.001000')
```
*the default value for `non_int_type` is `float`*
And parse expression is also aware of this:
```python
>>> ureg.parse_expression('1 uM').m_as('nM')
Decimal('1000')
>>> ureg.parse_expression('1 nM').m_as('uM')
Decimal('0.001000')
```

but you have to be consistent. This is not a good idea
```python
>>> ureg = pint.UnitRegistry(non_int_type=Decimal)
>>> q = 3.14 * ureg.meter
>>> type(q.m)
<class 'float'>
```
as it will fail:
```python
>>> q.to('km')
Traceback (most recent call last):
...
    value = value * factor
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
```

Basically because the units, prefixs, etc are **INTERNALLY** stored in the selected type. So interoperability with float is something that the user must check (or use the selected type for all magnitudes)

Any numerical datatype is supported:
```python
>>> from fractions import Fraction
>>> ureg = pint.UnitRegistry(non_int_type=Fraction)
>>> ureg.parse_expression('1 uM').m_as('nM')
Fraction(1000, 1)
>>> ureg.parse_expression('1 nM').m_as('uM')
Fraction(1, 1000)
```

This issue is now open for discussion about this new feature:
- unexpected problems
- ideas
- documentation
- handling `use_decimal` deprecation

**Comment by tovrstra** [comment]
I prefer the current behavior that one cannot accidentally multiply `float` and `Decimal`. It follows the behavior of the underlying types. For example, `5.0 * Decimal("5.0")` produces the same exception. That exception is part of the design of the `decimal` module, presumably to avoid that one accidentally runs into the problem the `decimal` module tries to solve: 

```python
>>> str(1.1 + 2.2)
'3.3000000000000003'`
```

I would not encourage casting Decimal instances into floats inside `pint`. That would be the equivalent of:

```python
>>> str(1.1 + float(Decimal("2.2")))
'3.3000000000000003'`
```

That would defeat the purpose of `Decimal`.
