### ISSUE TITLE
Addition of a Quantity to a float

### ISSUE THREAD

**Issue by ayushsgupta** [hgrecco/pint#1040]
Apologies in advance if this question has been asked/discussed previously. Normally when adding a float to a `Quantity` object, a `DimensionalityError` is raised. I was wondering if there is a mode in pint that is not as strict in checking units for addition and subtraction. When adding two numbers, if one is not a `Quantity`, then the units can be inferred. For example, `Quantity(1.0, 'eV') + 1.0` would return `Quantity(2.0, 'eV')` instead of an error. If this sort of feature doesn't exist yet, do you think it would be useful or not?

**Comment by hgrecco** [comment]
One of the mottos of pint has always been: "do not guess user intentions". This is a typical example in which is not possible to say if this is a desired behavior or a mistake. 

The closest things are contexts, but these are specific for certaint transformations and do not apply here.
