### ISSUE TITLE
taking the logarithm of a quantity

### ISSUE THREAD

**Issue by jacopo-chevallard** [hgrecco/pint#1043]
Hi everyone, congrats for this nice project !! ;)

I see that in #71 you're discussing about logarithmic units, and perhaps my question is related to that issue: when I try to compute
```
import numpy as np
from pint import UnitRegistry
ureg = UnitRegistry()
A = 10. * ureg.meter
np.log10(A)
```
I get the error 
```
DimensionalityError: Cannot convert from 'meter' ([length]) to 'dimensionless' (dimensionless)
```
Does this mean that standard arithmetic operations such as exp, log, pow, ... are unsupported when using a pint Quantity? In many situations you may want to compute the log of a quantity, do something, then revert back to linear units with exponentiation, so that the final and inital units are unchanged, although the final unit is really 10**(log10(unit))

Digging into the CHANGES file I see that version 0.8.0 discussed some possibly related things, e.g.
```
- NumPy exp and log keeps the type
  (Issue #95)
```

**Comment by hgrecco** [comment]
A `DimensionalityError` is the correct result. The logarithm is only defined for a dimensionless number.

**Comment by jacopo-chevallard** [comment]
I disagree, how come the most used measurement system (magnitudes) in astronomy is a logarithmic one? 
From my perspective a software should be developed with use cases in mind, without putting too much importance on what is formally allowed or not.

In science (at least astronomy) people take logarithms of quantities with units all the time (log mass, log time, ...) for the simple reason that logarithms are very useful to work with numbers covering multiple orders of magnitude. Not allowing such computations would severely restrict the usage of a module like pint...

**Comment by hgrecco** [comment]
Pint is not developed with a particular application in mind. In fact it has users and developers coming from all areas of science and technology. 

We do put importance in what is formally allowed: pint aims (among other things) to help avoiding calculations mistakes. We need to enforce correcteness.

I am really no aware of common cases in which the log of a quantiy is conventionally used. In every case that I can think of you have to build a dimensionless quantity. To give some astronomy examples. 
- When calculating the apparent magnitude of a star, you divide the intensity by a reference intensity before taking the logarithm: you are constructing a dimensionless quantity.
- When calculating the relative magnitude of a star, you take the logarithm of the distance measured in parsecs which is basically the distance (in any units) divided by one parsec: again a dimensionless quantity.

Correctness is a feature, as it allows you to reason better the computations that you are trying to make and avoid mistakes.

Take a look at this: http://math.ucr.edu/home/baez/physics/General/logs.html

**Comment by jacopo-chevallard** [comment]
I am sorry, but I don't see how preventing taking the logarithm of a dimensional quantity would prevent mistakes. If you take any astronomy paper dealing with galaxy mass functions, you'll find the mass function expressed in units of log mass. Perhaps this is not formally correct, but it is done all the time.

I agree that you must be careful when moving back and forth from linear to log scale (as the link you provided suggests), but the only effect I see of the choice of not supporting log, exp, ... is that some people will not use pint, thus their work will be more exposed to calculation mistakes.

Perhaps there is something I'm not getting right, but which mistakes are you worried that people will make when, for instance, taking the log of a quantity for some intermediate calculations, to then revert to a linear quantity? You should certainly keep track that the ``unit`` has (temporarily) become ``log unit`` (or ``exp unit``, etc...), so that people will not try to sum ``unit`` with ``log unit`` with ``exp unit``, and allow operations on units, so that ``10 ** log unit = unit``. Maybe this would add too much complexity to the code (I haven't looked into it yet), but I think that it would be a very useful feature (perhaps an optional one) that would indeed prevent many calculation mistakes...

**Comment by hgrecco** [comment]
I am not an expert in that field, but if I recall correctly to calculate the galaxy mass functions you need to use a reference value or have the quantity expressed in specific units. (The same as for magnitude). If you do not use a reference value or the magnitude is not in those specific units, it is wrong. That is exactly the type of mistakes this prevents. And it makes sense because log is not defined for quantities.

If you provide a concrete example, we can discuss it.

**Comment by hgrecco** [comment]
I am closing this for now. Feel free to reopen.

**Comment by 5igno** [comment]
@jacopo-chevallard: if you want to, you can check our the code in here:

https://github.com/hgrecco/pint/pull/1027

It's not quite done yet, but it goes in some direction you might be interested in.
If it does at least partially, you can also comment on how you would like pint with log units.
