### ISSUE TITLE
Gauss dimensions don't match magnetic flux density.

### ISSUE THREAD

**Issue by pbeeken** [hgrecco/pint#1048]
The unit of 1 gauss = 10^-4 tesla?  Simply stated:
```
import pint
SI = pint.UnitRegistry(system="mks")  # loads the default SI units

tesla_as_mfd = (1.0*SI.tesla)
print(f"{tesla_as_mfd.dimensionality}")
# --> [mass] / [current] / [time] ** 2

gauss_as_mfd = (1.0*SI.gauss)
print(f"{gauss_as_mfd.dimensionality}")
# --> [mass] ** 0.5 / [length] ** 0.5 / [time]  ?????  

tesla_as_mfd.to(SI.gauss)
# --> should produce 10000*gauss but produces a dimensionality error.
```
At the very least there should be some kind of a unit of current (Biots) or charge flow in the gauss dimension. Wikipedia had this wrong BTW, I have submitted an edit. Tesla properly converts:
```
tmfd.to(ureg.gram / ureg.biot / ureg.sec**2)
# --> \[10000.0\ gram/(biot\ second^2)\]
```
which does produce the expected results.

**Comment by Jellby** [comment]
I'm not an expert, but I've spent some time trying to understand Gaussian (cgs) units. I can't say I've completely succeeded. The problem with Gaussian units is that they are not commensurate (they don't have the same dimensions) with SI, and commonly encountered conversion factors hide this problem by making it look simpler than it is. See e.g. https://en.wikipedia.org/wiki/Centimetre%E2%80%93gram%E2%80%93second_system_of_units#Electromagnetic_units_in_various_CGS_systems

In the `defaults_en.txt`, the gauss is defined as:

    gauss = dyne / franklin = G

where the franklin is the "esu unit of charge", with the awkward definition of:

    franklin = erg ** 0.5 * centimeter ** 0.5 = Fr = statcoulomb = statC = esu

because in the Gaussian system there's no Coulomb constant (1/(4 pi eps_0)).

To try to work around this problem, in `pint` you can use the `Gau` context:
```
tesla_as_mfd.to(SI.gauss, 'Gau')
# <Quantity(9999.99999725799, 'gauss')>
# not 10000 due to floating point errors.
```
or with the new `pint-convert` script:
```
pint-convert tesla
1 tesla = 1 kg/A/s²
pint-convert gauss
1 gauss = 0.316227766017 kg⁰.⁵/m⁰.⁵/s
pint-convert tesla gauss
1 tesla = 9999.99999726(77) G
```

**Comment by pbeeken** [comment]
I absolutely agree that cgs has issues.  I remember wrestling with energy conversions $\esu^2 / cm^2 \implies \erg$.  It is because of this ambiguity and change in the choice of what is considered 'fundamental' (as I point out to my students, 'fundamental' is what is easier to measure with precision): 

  - charge as coulomb [a fundamental property] (SI deprecated) or 
  - [current]$\cdot$[time] (SI defines current and time as fundamental, charge is a 'compound' unit)

I can have my students define the unit alternatively but I'd rather encourage sticking with SI exclusively.  Thank you for your time.

**Comment by Jellby** [comment]
By the way, this would probably a better link: https://en.wikipedia.org/wiki/Gaussian_units#Electromagnetic_unit_names

According to it, G has indeed dimensions of M^1/2 / L^1/2 / T (I think it was this page I used to make sure I got at least most of the conversions right).

To reiterate, the problem with Gaussian units is not simply what is considered fundamental or derived, it's that the dimensions themselves are different, even the physical equations are different. There is just no charge/current axis in the Gaussian system!

**Comment by pbeeken** [comment]
Again, I totally understand where you are coming from.  I was working off the very brief discussion at the end of Jackson's '**Classical Electrodynamics**'. In this tome the cgs unit is based on the [AbAmpere](https://en.wikipedia.org/wiki/Abampere) or Biot.  This definition is consistent with Ampere's Law.  This is clearly a place where even the experts disagree. It is why the 'gauss' is more of a friendly term (and definitely 'old school'.) When I was a kid I remember the term being used a lot.  Many years later when I was in the magnetic recording research group at IBM we rarely, if ever, used the unit.  Chickazumi's '**Physics of Magnetism**' never uses the units even once in passing although in terms of value magnitudes it would be convenient for presentation.  

All fine and well.
