### ISSUE TITLE
standard cubic feet for natural gas 

### ISSUE THREAD

**Issue by mfindley** [hgrecco/pint#1069]
...any thoughts on how to best extend Pint to include standard cubic feet (scf) of natural gas (https://en.wikipedia.org/wiki/Standard_cubic_foot)?

It seems like creating an additional "natural_gas_industry" context might be just the thing to convert scf to moles.  I could set up some parameters for the standard temperature and pressure used to do the conversion.  Am I off-base with this?

.. related to this, the gas measurement folks in this sector have some novel prefixes to handle order of magnitude.  MMscf is for million standard cubic feet and Mscf is for thousand standard cubic feet (The Roman numeral for 1000 is M).  Adding an additional M- prefix might cause a name collision with the symbol for SI-unit's Mega prefix.
My question is this:  Can Pint change the definition of a prefix within the scope of a context?  The read-the-docs write up talks about over-riding units within a context, but not a prefix.  Can we override the SI-unit M prefix only within the context of natural gas sector conversions?

thanks,  Matt

**Comment by hgrecco** [comment]
Changing the unit defintions is not possible (without forcing the internals). You can create a new definition file easily.

Regarding a natural gas industry context, sounds good.

**Comment by mfindley** [comment]
... attempted to create a context file that would allow conversion between moles of natural gas and standard cubic feet of natural gas, but hit a snag.  I think it relates to using units of measure for the context's parameters.  Here's what I put together, but it doesn't seem to load:

```
@context(pressure=14.696 psi, temperature=519.67 R) nat_gas_sector = nat_gas_sector
    # pressure (sea level) and temperature (60 deg F) are standard conditions for the gas.
    [volume] -> [substance]: value * R * temperature / pressure
    [substance] -> [volume]: (value * pressure) / (R * temperature)
@end
```

Thoughts?

**Comment by mfindley** [comment]
... noticed that the issue of using units of measure for the parameters in a context is discussed in issue #792, so better understand the issue now.

Rather than creating a context for standard cubic feet of natural gas, a simpler and more effective way to go is to define a supplemental unit definition and set of prefixes:
```
#supplemental units definition file for Pint.
#this definition file adds units and prefixes that are specific to the natural gas industry.

#see: Gas Processors Association (GPA) Standard 2145-16, 
#Table of Physical Properties for Hydrocarbons and 
#Other Compounds of Interest to Natural and Natural Gas Liquids Industries
#they use 60 deg F and 14.696 psia (normal sea level air pressure) as standard conditions for a gas.
#see also: https://en.wikipedia.org/wiki/Standard_cubic_foot

#there are 1.1953 moles of gas per standard cubic feet.
standard_cubic_foot = mole / 1.1953 = scf = standard_cubic_feet
#natural gas industry uses prefixes based on roman numerals:
hundred - = 1e2 = c-
thousand - = 1e3= M-
million - = 1e6 = MM-
billion - = 1e9 = B-
trillion - = 1e12 = T-
```

**Comment by c4rnot** [comment]
I am having problems here myself.  I can get it to convert volumes to energies and vice versa, but if the unit set has anything more than volumes, lets say currency/volume, it wont convert for me.

Any idea how to get around this?

I have the following in my definitions:
pence = GBP /100 = p
cent = USD / 100 = c
eurocents = EUR / 100 = c

@context FX
    EUR = 1.10026 USD
    GBP = 1.11540 EUR
@end


cubic_meter = meter ** 3 = m3 = cu_m
cubic_foot = ft ** 3 = cu_ft = = ft3 = cubic_feet


mmbtu_per_hour = 1000000 * BTU / hour

nat_gas_energy_vol_density = 38960000 * joule * m^-3
nat_gas_energy_mass_density = 52596000 * joule / kg
nat_gas_density = 0.721 * kg / m**3

@context natural_gas = natgas
   [volume] -> [energy] :  value * nat_gas_energy_vol_density
   [energy] -> [volume] : value / nat_gas_energy_vol_density
   [mass] -> [energy] :  value * nat_gas_energy_mass_density
   [energy] -> [mass] : value / nat_gas_energy_mass_density
 @end

**Comment by hgrecco** [comment]
Closing now. But feel free to reopen or open a new issue.
