### ISSUE TITLE
Why is the registry a private attribute once created?

### ISSUE THREAD

**Issue by TomNicholas** [hgrecco/pint#1071]
I'm currently making my first serious forays into pint, as I would really love to see it working fully with xarray.

If I'm loading data and quantifying it with pint, it makes sense to initialise the unit registry as part of that loading process. However, if I do that within a function, I won't have access to the namespace in which the `UnitRegistry` instance was created. I will almost certainly need the object again though, say if I want to convert my data to any other specific units. I noticed that `Unit` instances have ` _REGISTRY` private attribute containing the registry, so I can still get to it that way. But is there a reason why this isn't publicly-advertised?

Also, from a usage point of view, what are your opinions on immediately putting the registry into a global variable for later access? Is that against the design philosophy of pint somehow?

**Comment by jthielen** [comment]
It would be great to have @hgrecco chime in here, but the typical usage of Pint that I've seen is to create a registry in a global namespace, and then use that throughout the project/library (e.g., [Pint docs](https://pint.readthedocs.io/en/0.11/tutorial.html), [MetPy](https://github.com/Unidata/MetPy/blob/master/src/metpy/units.py)). But, I could also see an argument for `_REGISTRY` being made part of the public API on `Unit` and `Quantity`.

Also, would the application registry functionality from #880 be of help in what you need?

**Comment by hgrecco** [comment]
As @jthielen said, the typical usage is creating a registry and having a handle to it. That is why we never need to expose `_REGISTRY`, there was no need and in general I rather keep things *private*. (it is easier to expose something than de-exposing).

As also mentioned by @jthielen the application registry is the suggested way to do interoperate (but I agree that the usability is still klunky and needs to be better explained).

**Comment by TomNicholas** [comment]
I did not see that you can use `get/set_application_registry()`, I think that does what I need. Closing in favour of specific discussion on `pint-xarray` [here](https://github.com/TomNicholas/pint-xarray/issues/7).
