### ISSUE TITLE
dir() mixes units with methods - implement __iter__ instead?

### ISSUE THREAD

**Issue by TomNicholas** [hgrecco/pint#1072]
If I explore the directory the `UnitRegistry` with `dir(unit_registry)`, the result displays methods and attributes mixed in with actual choices of units - for example `parse_units` appears right next to `parsec`.

`__dir__` is conventionally used for methods and attributes: might it make for a cleaner interface to separate theses two distinct features of the class? 

I see that you need a way to list all the units easily, but I also notice `UnitRegistry` doesn't define an `__iter__` method. If `__iter__` returned the unit keys then you could instead list all the units with `list(unit_registry)`, which IMO would be a very intuitive syntax. You could of course then loop over units too for free. That would leave `__dir__` available to list just the actual class methods and attributes, which would make interactive exploration of the class structure easier.

Just a thought anyway.

**Comment by keewis** [comment]
That's something that bothered me, sometimes. On the other hand, it's great that autocompleters can complete the units, so I'm a bit torn.

Using `__dir__` is the [recommended way](https://docs.python.org/3/library/functions.html#dir) to tell users (and the autocompleters of `IPython` and `python`) about the attributes accepted by `__getattr__` and `__getattribute__`, so using it this way is legitimate. On the other hand, it definitely makes finding the actual attributes harder.

To work around that, we can use `object.__dir__(ureg)` and both `python` and `IPython` mark methods with parentheses.

Related to that: `ureg` defines `_dir`, which in theory is intended to list all public attributes, but it is seriously out-of-date. I'd propose to replace `_dir` with `object.__dir__(self)`:
```python
def __dir__(self):
    return list(self._units.keys()) + list(object.__dir__(self))
```

**Comment by hgrecco** [comment]
The original reason was autocomplete, indeed.

**Comment by TomNicholas** [comment]
Thanks for the suggestion @keewis, so when I change `BaseRegistry` by deleting `_dir`, and defining the dunder methods as
```python
class BaseRegistry:
    def __dir__(self):
        #: Calling dir(registry) gives all units, methods, and attributes.
        #: Also used for autocompletion in IPython.
        return list(self._units.keys()) + list(object.__dir__(self))

    def __iter__(self):
        """Allows for listing all units in registry with `list(ureg)`.

        Returns
        -------
        Iterator over names of all units in registry, ordered alphabetically.
        """
        return iter(sorted(self._units.keys()))
```
then
```python
from pint import UnitRegistry
ureg = UnitRegistry()
dir(ureg)
```
gives a list of all units, methods and attributes, and autocomplete seems to show them all in `IPython`, and `list(ureg)` gives a list of all names of just units. So that should be the best of both worlds?

(It seems `dir()` sorts by default, so doesn't need the `sorted()` call.)

With that change all the tests pass, so I've opened #1074 .
