### ISSUE TITLE
Compound units like pressure and torque?

### ISSUE THREAD

**Issue by sderose** [hgrecco/pint#1073]
I've spent a couple hours reading the doc, experimenting, and dumping the ureg data, and I still haven't been able to figure this out. Can someone tell if if/how this is even possible?

My goal is basically like the *nix "units" command: user types in a float and a unit name. Let's say it's pressure. I want to convert that value to *all* the available pressure units, and print a list of those equivalents.

The ureg.name convention is nice for some things, and I found check([domain]), but I couldn't find:
    * a way to ask for the domain of a unit given the unit name as a string
    * a way to find out what domains exist and are called

I tried using ureg.\__attr\__(unitname) but that doesn't work. And I can't figure out how to deal with compound units in general, other than constructing the by arithmetic. If the user tells me "1.2 newton*meters" (whatever the syntax!), I can't seem to get off the ground. What am I missing, or is it basically impossible to deal with units whose names are in *strings*, not in literal Python code?

**Comment by Amaretto-Coke** [comment]
As long as there is a clear seperator in between your numerical value and your unit of measurement you can easily split the two to create a quantity from them. 

```
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

user_input = '1.2 newton*meters'

sep = ' '

quantity = Q_(user_input.split(sep)[0], 
              user_input.split(sep)[1])

print(quantity)
```

Output:
`1.2 meter * newton`

**Comment by Amaretto-Coke** [comment]
With regards to wanting to list the quantity in all compound units, as in pressure, you might want to rethink your approach. For example pressure could be defined in nN/km² (which is perfectly acceptable in Pint, but not really a useful unit). I'd instead construct a list of all the pressure units that you want values for and then convert to only those.

```
pressure = Q_(101.325, 'kPa')

pressure_units = ['bar', 'psi', 'MPa', 'kpsi', 'mPa']

print(pressure)

for p_unit in pressure_units:
    mag = pressure.to(p_unit).magnitude
    unit = pressure.to(p_unit).units
    print('{:.4}'.format(mag), unit)
```

Output:
```
101.325 kilopascal
1.013 bar
14.7 pound_force_per_square_inch
0.1013 megapascal
0.0147 kilopound_force_per_square_inch
1.013e+08 millipascal
```

**Comment by keewis** [comment]
you don't really have to do the string manipulation, just pass it to `Quantity` and it should work:
```python
In [2]: ureg.Quantity("1.2 newton*meters")
Out[2]: 1.2 <Unit('meter * newton')>
```
(same result for `ureg("1.2newton*meters")`)

also, if you already have the unit in a separate string, you can use:
```python
unit_name = "newton * meters"
unit = ureg(unit_name) # option 1
unit = getattr(ureg, unit_name)  # option 2
unit = ureg.Unit(unit_name)  # option 3
```
---
to get all units with a certain dimensionality use:
```python
compatible_units = ureg.get_compatible_units(unit)
```
keep in mind, though, that there are a lot of units in the default unit definition file, so not all of them make sense in every context and it might be better to manually enumerate those you want to support (as suggested in https://github.com/hgrecco/pint/issues/1073#issuecomment-614307446)

**Comment by danielsreis** [comment]
I have the same issue

When I set Force in Newton:

```
force = 1000 *ureg('N')
force
```

> 1000 newton

The dimensionality should give Force, but:

`force.dimensionality`

> <UnitsContainer({'[length]': 1, '[mass]': 1, '[time]': -2})>

This error propagate to pressure:

```
pressure = force * 4 / (np.pi * diameter.to('m')**2)
pressure
```

> 1414710.605261292 newton/meter2

`pressure.dimensionality`

> <UnitsContainer({'[length]': -1, '[mass]': 1, '[time]': -2})>

**Comment by danielsreis** [comment]
I comprehend that you are apprehensive to indicate other dimensionality that is not what user expect.
But as an engineer this is useful to indicate, problems using different units, can be an indication of scale or unit error.
An suggestion to "change" dimensionality is , if are possible, creation an function to_dimensionality().
Of course that speak is easy of doing, isn't my intention to offend you, I think as said in [https://github.com/hgrecco/pint/issues/676] this kind of thing is common in Mathcad and Wolfran.

**Comment by hgrecco** [comment]
I am closing this until a good implementation is proposed.
