### ISSUE TITLE
Comparison (equality operator) gives different results depending on the order

### ISSUE THREAD

**Issue by avaucher** [hgrecco/pint#1079]
Basically, I get different results if I check "1 day == 86400 seconds" or the other way around, "86400 seconds == 1 day".

In Python:
```python
import pint

ureg = pint.UnitRegistry()

print(86400 * ureg.second == 1 * ureg.day)  # prints "False"
print(1 * ureg.day == 86400 * ureg.second)  # prints "True"
```

Why is this the case?? Is there a workaround to make sure that I always get `True`?

I am using Python 3.6.10 and Pint 0.11

**Comment by keewis** [comment]
in this case it's helpful to examine how the quantities convert to different units:
```python
In [2]: days = 1 * ureg.day 
   ...: hours = 24 * ureg.hour 
   ...: minutes = 24 * 60 * ureg.minute 
   ...: seconds = 24 * 60 * 60 * ureg.second 
   ...: days.to(ureg.day), hours.to(ureg.day), minutes.to(ureg.day), seconds.to(ureg.day)
Out[2]: 
(1 <Unit('day')>,
 1.0 <Unit('day')>,
 0.9999999999999999 <Unit('day')>,
 0.9999999999999998 <Unit('day')>)

In [3]: round(seconds.to(ureg.day)) == days, days == seconds
Out[3]: (True, True)
```
which means this is a floating point issue.

Manually converting to base units (using `q.to_base_units()`) works, but maybe we should make sure the comparison is commutative.

You could also try to switch to `Decimal` or `Fraction` (`numpy` has the same issue).
