### ISSUE TITLE
pkg_resources performance issues

### ISSUE THREAD

**Issue by tgbugs** [hgrecco/pint#1080]
https://github.com/pypa/setuptools/issues/510

The patch I used to resolve the issue against `pint-0.11` is [here](https://github.com/tgbugs/tgbugs-overlay/blob/801d7ba294e6244990f3595e84633b923b304688/dev-python/pint/files/setuptools-510-fix.patch). `'PACKAGE_VERSION'` could be replaced with importlib.metadata or importlib.resources as mentioned in https://github.com/hgrecco/pint/issues/1008#issuecomment-610451542.

**Comment by keewis** [comment]
While your changes do work, they are not backwards-compatible (and hard-code the version which is not an option). We currently support `python>=3.6` and `numpy>=1.14`, so any changes must be compatible with that. #1077 dropped the reference to `setuptools` and uses `packaging` directly, though, so no need to worry about the version check. That leaves us with the version and the `resource_stream`.

We could use `importlib.metadata.version` and `importlib.resources.read_binary`, but `importlib.resources` was introduced in `python==3.7` and `importlib.metadata` in `python==3.8`, so we still need to fall back to `pkg_resources` where these modules are not available (`python==3.6`, especially). The easiest way would be to use to the `pkg_resources` version if the import of the standard library version failed.

Discussing a patch file on another repository is hard, though, so please open a PR.

**Comment by hgrecco** [comment]
I agree with @keewis and I would also suggest to limit the PR to a single change. This changes two or three distinct things

**Comment by jules-ch** [comment]
We can use the backport like so adding this in `setup.cfg` at the `install_requires` section

```
importlib-metadata; python_version < '3.8'
importlib-resources; python_version < '3.7'
```

It should be pretty straight forward.
As @keewis said in #1008, we still need packaging for version comparison for np.matmul.

I can submit a PR if needed.
