### ISSUE TITLE
Replace pkg_resources.version with importlib.metadata.version

### ISSUE THREAD

**Issue by jules-ch** [hgrecco/pint#1083]
Replace setuptools `pkg_resources.version` with importlib.metadata.version from the standard library introduced in Python 3.8.

For Python < 3.8, we can rely on the backport imprtlib-metadata, which can be removed when we will move forward.

**Comment by jules-ch** [comment]
@hgrecco  prob a mistake, I don't think bors is working on the issue thread can you make the command on the PR #1084

**Comment by hgrecco** [comment]
Thanks. I read the PR, then went back to the issue and wrote it there. Thanks ... and thanks for the PR

**Comment by jules-ch** [comment]
Np, they had the same title. Thx for the quick review
