### ISSUE TITLE
How can find if a unit is in the Registry?

### ISSUE THREAD

**Issue by matteopulega** [hgrecco/pint#1086]
Hi,
when i make:
`ureg.Quantity(value,unit).to_base_units()`
i get the error:
`xyz is not defined in the unit registry`

Is there any function that allows me first to see if my unit exists in pint? I prefer not to use a "try except" operation

**Comment by keewis** [comment]
not sure if there is anything cleaner right now, but
```python
"xyz" in dir(ureg)
```
works (unless you try to have units like `to_base_units`)

In `master` (and thus in the next release), `__iter__` returns all unit names so this would be more reliable:
```python
"xyz" in ureg
```

**Comment by hgrecco** [comment]
Please bear in mind that `unit in dir(ureg)` might not work if unit is a prefixed unit as prefixed units are dinamically created as required.

**Comment by mgrau** [comment]
Why not use a "try/except pint.errors.UndefinedUnitError" block? It will be faster than testing 'xyz in dir(ureg)'.
