### ISSUE TITLE
Can't add alias to the unit definition file

### ISSUE THREAD

**Issue by esprit1995** [hgrecco/pint#1091]
Hello,
While I try to add an alias to the unit definition file, i get an error: 
"While opening pint_units.txt, in line None: Unknown directive @alias dos = ds"
The file is loaded using the code:
`import pint 
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.load_definitions("pint_units.txt")`
apart from alias, the file contains a bunch of unit definitions. Works fine without adding alias.
I know I can add it programmatically, but it is better for me to use a file. Am I doing something wrong?

**Comment by hgrecco** [comment]
Do you actually have a unit named `dos` in your file?

If true, please try the following and let me know
```
import pint from pint import UnitRegistry 
ureg = UnitRegistry(filename="my_units.txt")
```

(where `my_units.txt` is the new defintions fils)

**Comment by esprit1995** [comment]
Yes, I do have that unit. I also tried aliasing existing unit - gram. 
Got same error: "Unknown directive @alias gram = weight = gms". 
Tried loading a registry your way, still the same error.

**Comment by hgrecco** [comment]
Can you provide the pint version?
```
>>> import pint
>>> pint.__version__
```

**Comment by esprit1995** [comment]
0.9

**Comment by hgrecco** [comment]
That explains a lot! :-D The `@alias` syntax was added in 0.10 See [here](https://github.com/hgrecco/pint/blob/master/CHANGES#L209)

**Comment by hgrecco** [comment]
I am closing. Feel free to reopen if the problem persists.
