### ISSUE TITLE
How does scipy.optimize.fsolve works with pint?

### ISSUE THREAD

**Issue by hustquick** [hgrecco/pint#1092]
I was trying to solve a simple problem with fsolve.
```Python
from scipy.optimize import fsolve


h_1 = 47622     # J/kg
h_2 = 135000    # J/kg
h_3 = 167000    # J/kg
h_4 = 100000    # J/kg

m_3 = 50        # kg/s

d_1 = 0.011
d_2 = 0.038

def f(x):
    m_a, m_4 = x
    err0 = m_a * h_1 + m_3 * h_3 - m_a * h_2 - m_4 * h_4
    err1 = m_a * d_1 + m_3 - m_a * d_2 - m_4
    return err0, err1

x0 = [1, 49]
m_a, m_4 = fsolve(f, x0)
```
Then I want to add units for the variable with pint.
```Python
from scipy.optimize import fsolve
from pint import UnitRegistry

u = UnitRegistry()
Q_ = u.Quantity

h_1 = 47622 * (u.J/u.kg)
h_2 = 135000 * (u.J/u.kg)
h_3 = 167000 * (u.J/u.kg)
h_4 = 100000 * (u.J/u.kg)

m_3 = 50 * (u.kg / u.s)

d_1 = 0.011
d_2 = 0.038

def f(x):
    m_a, m_4 = x
    err0 = m_a * h_1 + m_3 * h_3 - m_a * h_2 - m_4 * h_4
    err1 = m_a * d_1 + m_3 - m_a * d_2 - m_4
    return err0, err1

x0 = [1 * (u.kg/u.s), 49 * (u.kg/u.s)]
m_a, m_4 = fsolve(f, x0)
```
However, it doesn't work. I also tried the wrapping functions ```@u.wraps```. But I dont know how to get the right result. How does scipy.optimize.fsolve works with pint?

**Comment by hgrecco** [comment]
you can wrap the whole thing

```python
from scipy.optimize import fsolve
from pint import UnitRegistry

u = UnitRegistry()
Q_ = u.Quantity


h_u = (u.J/u.kg) # units of h_X
m_u = u.kg / u.s
d_u = u.dimensionless

@u.wraps((m_u, m_u), (m_u, m_u, h_u, h_u, h_u, h_u, m_u, d_u, d_u))
def solve(x0_0, x0_1, h_1, h_2, h_3, h_4, m_3, d_1, d_2):
    def f(x):
        m_a, m_4 = x
        err0 = m_a * h_1 + m_3 * h_3 - m_a * h_2 - m_4 * h_4
        err1 = m_a * d_1 + m_3 - m_a * d_2 - m_4
        return err0, err1

    return fsolve(f, (x0_0, x0_1))


h_1 = 47622 * (u.J/u.kg)
h_2 = 135000 * (u.J/u.kg)
h_3 = 167000 * (u.J/u.kg)
h_4 = 100000 * (u.J/u.kg)

m_3 = 50 * (u.kg / u.s)

d_1 = 0.011 * u.dimensionless
d_2 = 0.038 * u.dimensionless


x0 = [1 * (u.kg/u.s), 49 * (u.kg/u.s)]

m_a, m_4 = solve(x0[0], x0[1], h_1, h_2, h_3, h_4, m_3, d_1, d_2)

print(m_a, m_4)
```

If creating `f` is expensive or you are calling fsolve a **lot** of times with the same parameters (but different starting points), you can split defining and solving

**Comment by hustquick** [comment]
Thanks a lot! You solved my problem.

I found that the problem was caused by ```numpy.asarray(x0)```. ```fslove``` tries to call the function ```numpy.asarray``` before it enters the function ```f```. If ```x0``` is an array of quantities, I get a ValueError. 
I tried to change the codes as
```Python
from scipy.optimize import fsolve
from pint import UnitRegistry

u = UnitRegistry()
h_1 = 47622 * (u.J/u.kg)
h_2 = 135000 * (u.J/u.kg)
h_3 = 167000 * (u.J/u.kg)
h_4 = 100000 * (u.J/u.kg)

m_3 = 50 * (u.kg / u.s)

d_1 = 0.011
d_2 = 0.038


def f(x):
    m_a, m_4 = x * u.kg/u.s
    err0 = m_a * h_1 + m_3 * h_3 - m_a * h_2 - m_4 * h_4
    err1 = m_a * d_1 + m_3 - m_a * d_2 - m_4
    return err0.magnitude, err1.magnitude


m_a = Q_(1,  'kg/s')
m_4 = Q_(49, 'kg/s')
x0 = [m_a.magnitude, m_4.magnitude]
m_a._magnitude, m_4._magnitude = fsolve(f, x0)
```
The code is not elegant. Are there any methods to pass the quantities into the function ```f``` without the loss of units? So that it may check the units of equations in the function ```f```.

**Comment by hgrecco** [comment]
Yes `asarray` does that and some other numpy functions do that as well. I raised this issue a long time ago in the numpy forum. Some of the latests numpy improvements like NEP-18 came to address this issue partially but are not here yet.

While your new solution works, it would be a lot slower that mine as you are allways operating with units. My solution should be as fast as the one without units (except for loading pint).

**Comment by hustquick** [comment]
Yes. Your solution is much better and it can check the units if I specified ```h_u```, ```m_u``` and ```d_u``` correctly.
Thanks again.
