### ISSUE TITLE
Comparing NaN in an array results in a RuntimeWarning

### ISSUE THREAD

**Issue by Hugovdberg** [hgrecco/pint#1100]
When comparing pint `Quantity` objects with an array containing a NaN this raises a `RuntimeWarning`.

This works fine:
```python
import numpy as np
import pint
ureg = pint.UnitRegistry()

ureg.Quantity(0, 'ug/L') <= ureg.Quantity(np.NaN, 'ug/L')
```

This raises a warning:
```python
ureg.Quantity(0, 'ug/L') <= ureg.Quantity([np.NaN], 'ug/L')
```

Warning raised:
```
RuntimeWarning: invalid value encountered in greater_equal
  return op(self._magnitude, other._magnitude)
```

Since comparison of NaN objects is well defined, and the correct result is returned, I don't expect this warning.

**Comment by jules-ch** [comment]
Can you tell us which version of pint & numpy you are using ?

**Comment by Hugovdberg** [comment]
Not anymore after several reinstalls and upgrades, apparently the stars are no longer in the correct alignment for this warning to occur. Will close it for now.
