### ISSUE TITLE
Comparison to non-quantity scalar of quasi-dimensionless quantity changes magnitude

### ISSUE THREAD

**Issue by jthielen** [hgrecco/pint#1102]
While I haven't gotten the chance to find a fix for this, I still wanted to get this bug report out there.

In general, it appears that, when evaluating `==` against a non-quantity scalar, the magnitude of a quantity with "dimensionless" dimensionality, but not "dimensionless" units (e.g., "degree", "g/kg") will be incorrectly converted in-place. For example:

```python
from pint import UnitRegistry
ureg = UnitRegistry()
val = [30., 45., 60.] * ureg.degree
check = val == 1
print(val)
```
outputs
```
array([0.52359878, 0.78539816, 1.04719755]) <Unit('degree')>
```
rather than the correct, unmodified
```
array([30., 45., 60.]) <Unit('degree')>
```

**Comment by jthielen** [comment]
> Is this related to #1144 ?

I believe so. They both appear to be due to misuse of `self._convert_magnitude`, which converts in place, instead of `self._convert_magnitude_not_inplace`, but are encountered in different locations in the code (so would need independent tests to make sure they are fixed).

**Comment by knightofni-i** [comment]
I tracked down my issue (1144), this issue (1102), and a third use of `Quantity._convert_magnitude()` that should have been `Quantity._convert_magnitude_not_inplace()`. I'll make a pull request with the modified code.
