### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1103]
It has been quite some time since the last release and there are a few bug fixes I really need.

@hgrecco, what would it take to get a new release (`0.11.1` or `0.12`) out? If you can make a list (or update the milestone) I think I can help with getting there.

**Comment by hgrecco** [comment]
Is a good time to release. I will make a release on friday.

**Comment by hgrecco** [comment]
Done! 0.12 is out!

**Comment by keewis** [comment]
could you change the default version on https://pint.readthedocs.io? Right now, that is `0.10.1`

**Comment by hgrecco** [comment]
done!

**Comment by keewis** [comment]
I just noticed you tagged the merge of #1000, which was 3 months ago. Was that intentional?

**Comment by keewis** [comment]
gentle ping, @hgrecco

**Comment by hgrecco** [comment]
@keewis Thank for the pointer. I will fix it!

**Comment by crusaderky** [comment]
@hgrecco I see that the 0.12 release tag was forked away from master a long time ago; I don't think that's intentional? It looks like you used an out-of-sync local master to make it?

**Comment by hgrecco** [comment]
I just released version 0.13 with your fix to the relase. Thanks a lot
