### ISSUE TITLE
synchronize Quantity.prod with np.prod(q)

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1118]
Continuing from #867: #1087 fixed the calculated units for `prod` when the `axis` or `where` (not both) parameters are passed, but only for the ufunc and not for the method (also, right now this will calculate the units using input and output sizes, but instead we could just use `q.shape[axis]`).

I looked into implementing this but it seems this is somewhat complicated: the way it works right now, `__getattr__` will get the method from the magnitude and wrap it using `_numpy_method_wrap` which in turn will call `get_op_output_unit`. To make this work I think we'd need to move the units calculation of `_prod` into a new function that accepts the shape and the args (`axis` and `where`) and try to modify `get_op_output_unit` to accept functions in addition to names. @jthielen, thoughts?

**Comment by jthielen** [comment]
In looking back on it now, I think the simplest way forward on this is to implement `Quantity.prod()` analogously to `Quantity.dot()`, where it just defers to the NumPy implementation:

https://github.com/hgrecco/pint/blob/0.13/pint/quantity.py#L1691-L1697

Would there be any objections to doing it this way?
