### ISSUE TITLE
Implementation of CO2eq (GWP)

### ISSUE THREAD

**Issue by lfaucheux** [hgrecco/pint#1121]
Pint is really amazing. 3 Questions:

I am not physicist and I would like to implement (static) [***G***lobal ***W***arming ***P***otentials](https://en.wikipedia.org/wiki/Global_warming_potential). It all starts with [radiative forcings](https://en.wikipedia.org/wiki/Radiative_forcing), dimensionalized as *W/m²*, i.e. an intensity, which already exists in the default registry,

```
# Intensity
[intensity] = [power] / [area]
```

#### Question 1
Does `[intensity]` have a given name when it is precisely instantiated as `watt / meter ** 2` ?
<hr>

Then it looks like we first have to imply the notion of ***absolute GWP*** (***AGWP***). Note that there is a **time-horizon non-linear** determinant behind any ***AGWP*** value.
I made a [python package](https://github.com/lfaucheux/PyGWP) some years ago to compute those things continuously. Yet, it seems that dealing with precomputed constants is the rule when dealing with ***GWP***s, mainly for the sake of convenience. Let's thus adopt the culture: the most common used *i)* time horizons in the litterature are 5, 10, 20, 30, 50, 100 years and *ii)* ghgs are CO<sub>2</sub> (of course), CH<sub>4</sub> and N<sub>2</sub>O. The point is that the following constants are very likely -- I am not physicist --  to be true only for `kilogram`s since the idea behind warming potential is precisely about timing of emissions *<=>* clearly not a linear-in-mass phenomenon.

#### Question 2
Does `[intensity] / kg` have a given name ?
<hr>

In conjunction with of the notion of timing/temporality, `[temporality]`, let's call it `[absolute_global_warming_potential]` for now. And only specify things for 100- and 50-year horizons for the sake of clarity,

```
#### Absolute Global Warming Potentials ####
agwp = [absolute_global_warming_potential] = [temporality] * [intensity] / kg

# 100-year horizon
agwp100 = nan agwp
co2_agwp100 = 8.69e-14 * agwp100
ch4_agwp100 = 2.1725e-12 * agwp100
n2o_agwp100 = 2.58962e-11 * agwp100

# 50-year horizon
agwp50 = nan agwp
co2_agwp50 = 5.100128578061494e-14 * agwp50
ch4_agwp50 = 2.1393321081948863e-12 * agwp50
n2o_agwp50 = 1.5742935781808625e-11 * agwp50
```

Finally, our (relative-to-CO<sub>2</sub>) ***GWP***s
```
#### Relative-to-CO2 Global Warming Potentials ####
co2eq = [global_warming_potential]

# 100-year horizon
co2_gwp100 = 1.0 * co2eq
ch4_gwp100 = 25.0 * co2_gwp100 = ch4_agwp100 / co2_agwp100
n2o_gwp100 = 298.0 * co2_gwp100 = n2o_agwp100 / co2_agwp100

# 50-year horizon
co2_gwp50 = nan co2eq
ch4_gwp50 = 41.94663086333451 * co2_gwp50 = ch4_agwp50 / co2_agwp50
n2o_gwp50 = 308.6772331491366 * co2_gwp50 = n2o_agwp50 / co2_agwp50
```
#### Question 3
Any suggestion that makes more sense *i)* regarding Pint's conventions as such and *ii)* ontologically speaking ?

**Comment by znicholls** [comment]
hi @lfaucheux, this will probably save you a few headaches https://github.com/openscm/openscm-units (the notebook is a good starting point https://github.com/openscm/openscm-units/blob/master/notebooks/introduction.ipynb). Not all the GWPs are included but you should be able to add new ones without too much trouble in https://github.com/openscm/openscm-units/blob/master/src/openscm_units/data/metric_conversions.csv

We simply define everything in terms of CO2, and then use contexts to control how the conversion works. It means you don't have the timescale in the name (i.e. the units are 'Mt CO2/yr', not 'Mt CO2 GWP50 / yr') but it seems to do the trick and avoids requiring all these new units and conversions (and Pint makes sure you can't accidentally convert between e.g. CO2 and N2O if you haven't explicitly specified the unit context to use).

**Comment by znicholls** [comment]
@lfaucheux can we close this issue?

**Comment by lfaucheux** [comment]
@znicholls I'll be back to you in a few days about that. Thanks for your attention.

**Comment by lfaucheux** [comment]
@znicholls you can close it if you like. Thx again for taking time.

**Comment by tfardet** [comment]
Sorry for necroposting, but I was also looking for this and I suspect people that are not familiar with GitHub or development in general may miss this.
Would you be OK with adding a ref to openscm-units somewhere in the doc? Maybe in the [Defining units](https://pint.readthedocs.io/en/stable/defining.html) section or in the FAQ?
(maybe tagging @hgrecco about that)

If it's fine with you, I can make a PR

**Comment by hgrecco** [comment]
@jules-ch was working on the new docs. Maybe we can put all packages using Pint in the same place.
