### ISSUE TITLE
Quantity wrapped Dask Arrays need deterministic hashing

### ISSUE THREAD

**Issue by rpmanser** [hgrecco/pint#1135]
Based on [xarray/#4208 (comment)](https://github.com/pydata/xarray/issues/4208#issuecomment-663117842), Pint should implement deterministic hashing for Quantity wrapped Dask Arrays. This is a recommended step in implementing the Dask collection interface that I skipped in #1129. 

This can be done in [one of two ways](https://docs.dask.org/en/latest/custom-collections.html#deterministic-hashing): either implementing `__dask_tokenize__` in the Quantity class, or registering a function with `dask.base.normalize_token`. The return value is the same. I'm wondering if there is a preference, since it seems that Pint tokenizes unit operations and I don't know if this would interfere with that. If there is no interference, I think `__dask_tokenize__` would be better since it is cleaner.

I can follow up with a PR following any discussion.

**Comment by jthielen** [comment]
Given no other feedback, I'd say go ahead and try it with `__dask_tokenize__`. I agree with you that it is cleaner.

**Comment by rpmanser** [comment]
I'll put in a PR early next week
