### ISSUE TITLE
DimensionalityError when raising float or int to array of dimensionless values

### ISSUE THREAD

**Issue by rob5ives** [hgrecco/pint#1136]
This works:
```python
a = Q_(2, '')
print(2 ** a)
```

However this gives the error: pint.errors.DimensionalityError: Cannot convert from 'dimensionless' to 'dimensionless'

```python
a = Q_([2, 3], '')
print(2 ** a)
```

**Comment by jules-ch** [comment]
It seems we have to remove this part

```python
         if is_duck_array_type(type(self._magnitude)): 
             if np.size(self._magnitude) > 1: 
                 raise DimensionalityError(self._units, "dimensionless") 
```
from
https://github.com/hgrecco/pint/blob/03be0544b749ee55fbd1253d18e2a84151dce716/pint/quantity.py#L1459-L1474

We need to get the same value as this : 
```python
2 ** np.array([2, 3])
```
and keep raising an error for any quantity with units.
