### ISSUE TITLE
Programmatically set a default prefix

### ISSUE THREAD

**Issue by dcnadler** [hgrecco/pint#1139]
I see that default prefixes can be modified using `default_en.txt`, but is there a way to modify programmatically?

Specifically, I would like to change the output of
```python
'{:~}'.format(ureg.parse_units('micromolar'))
```
from 'µM' to 'uM'

**Comment by hgrecco** [comment]
There is no defined API. You could hack into the prefix dictionary of the registry.

**Comment by dcnadler** [comment]
Thanks @hgrecco!!
