### ISSUE TITLE
Add the FFF System to Pints

### ISSUE THREAD

**Issue by bnice5000** [hgrecco/pint#1140]
Maybe I should have saved this one for the 1st of April, but I was wondering if there had been any thought to defining the [FFF System](https://en.wikipedia.org/wiki/FFF_system) in pint. It's base units consist of the [furlong](https://en.wikipedia.org/wiki/Furlong), [firkin](https://en.wikipedia.org/wiki/English_brewery_cask_units#Firkin), and [fortnight](https://en.wikipedia.org/wiki/Fortnight).

It appears that the furlong and fortnight have been defined. The firkin has not. I am relatively new to using Pint, but if there is no objection, I would be willing to work on it. It could also be used for other obscure base measurements such as Réaumur for temperature.

Please let me know if this is something the community might have an interest.

**Comment by jules-ch** [comment]
Feel free to add it in your custom registry. :)

I don't think we will add it to the default registry though as it is another system we need to maintain and I dont think it is widely used, but you can proove me wrong 😄.
