### ISSUE TITLE
Add case (in)senstive option to registry and extend to Unit and Quantity parsing

### ISSUE THREAD

**Issue by jthielen** [hgrecco/pint#1145]
[In our quest to handle CF compliant/UDUNITS style units in MetPy](https://github.com/Unidata/MetPy/issues/1362), we have come across a couple issues regarding case sensitivity. For example, we need to be able to parse `Meter` as `meter` and [`Celcius` as an alias of `degrees_Celcius`](https://github.com/hgrecco/pint/issues/1081). To enable this within Pint (as an option of course and not the default [to maintain standards](https://github.com/hgrecco/pint/issues/1081#issuecomment-615238512)), I would like to propose the following to extend the case insensitive handling already existing in Pint:

1) Add a `case_sensitive` option to `BaseRegistry` which defaults to `True`
2) Modify the existing `case_sensitive` options on `get_name`, `parse_unit_name`, `parse_pattern`, and `parse_expression` to default to `None` instead of `True`, and have `None` be replaced within the methods with the registry's `case_sensitive` option
3) Add analogous `case_sensitive` kwarg to `parse_units`
4) Optional: add analogous `case_sensitive` kwarg to any other public registry method that ends up using `parse_unit_name` (or something that uses it, recursively) so that it can be appropriately passed along.

This would allow something like the following to become valid, so that a greater extent of CF unit compliance can be achieved:

```python
import pint

ureg = pint.UnitRegistry(case_sensitive=False)

q = ureg("1 Meter")

print(q)
```

```
1 meter
```

@hgrecco Is this compatible enough with your philosophy for Pint in https://github.com/hgrecco/pint/issues/1081#issuecomment-618681303 and seem like a reasonable enough way forward in implementation?

**Comment by hgrecco** [comment]
Thanks @jthielen for the comprehensive and clear proposal. I think that your solution covers all major points and the suggetsted defaults are good not only to adhere to pint philosophy but also to maintain backwards compatibility. I also agree with point 4.

I will be happy to review and merge this PR when ready.

**Comment by jthielen** [comment]
> Thanks @jthielen for the comprehensive and clear proposal. I think that your solution covers all major points and the suggetsted defaults are good not only to adhere to pint philosophy but also to maintain backwards compatibility. I also agree with point 4.
> 
> I will be happy to review and merge this PR when ready.

Sounds great, thanks! I'll add this to my queue of PR's to work on across projects the next couple days.
