### ISSUE TITLE
siunitx_format_unit formats units with underscores incorrectly

### ISSUE THREAD

**Issue by jf2718** [hgrecco/pint#1149]
Units that contain underscores are not converted correctly. 

- For `electron_volt` it returns `\electron_volt`, whereas it should be `\electronvolt`
- For `degree_celsius` it returns `\degree_celsius`, whereas it should be `\degreeCelsius`

There are probably more examples.

Also, for some units, like `delta_degC`, there is no equivalent in siunitx. So maybe there should be a way to customize the unit-names that siunitx_format_unit is using.

Here is the function I'm talking about:

https://github.com/hgrecco/pint/blob/dea623a7a135670ffb0c725ccbac64a65645b315/pint/formatting.py#L278-L280

**Comment by jf2718** [comment]
The underscores also cause issues in matplotlib if latex rendering is enabled.

https://github.com/hgrecco/pint/blob/a70be489c46c03ca15c2832a308a56a556270461/pint/matplotlib.py#L22

**Comment by hartelt** [comment]
I encountered this bug recently and looked into it a bit. 
As far as I understand the pint implementation of siunitx, the tex output is made up of the appropriate combinations of formatting commands around the unit string as defined in pint, prefixed with `\`:

https://github.com/hgrecco/pint/blob/a70be489c46c03ca15c2832a308a56a556270461/pint/formatting.py#L321

So the underlying problem is that the definitions of unit strings can generally differ between pint and siunitx. For example the correct result for `degC` would be `\degreeCelsius`.
As far as I can judge from the [docs of siunitx](http://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/macros/latex/contrib/siunitx/siunitx.pdf), there is no dedicated concept of delta-units there. But some quick testing shows that `\si{\Delta \degreeCelsius}` compiles fine.

I guess a full mapping between the unit definitions of pint and siunitx would be necessary for a proper fix? Or would you prefer a replacement scheme for the breaking cases?

**Comment by hartelt** [comment]
I drafted a fix on my fork: https://github.com/hartelt/pint/blob/1149_siunitx_format_units_with_underscores/pint/formatting.py
It fixes all faulty units with underscores or differently defined names and uses the `\Delta ` command for delta-units.
The replacement for the delta units is still a bit ugly, but it should work.

There is still a case i found where it doesn't work: `millimeter_Hg`, for which the milli is interpreted as a prefix, so only `meter_Hg` is input to my mapping function and the correct siunitx command `\mmHg` cannot be generated there. I don't have an idea how to fix this, yet.

Have a look please if you're interested. Shall I submit a pull request?

**Comment by jf2718** [comment]
I think it's a good idea to fix the most common units, but the problem can't be fixed in a general way because many units and constants don't exist in siunitx. Maybe there should be way to hook into siunitx_format_unit formats and add your own conversions, this is especially for user defined units because both siunitx and pint allow you to define custom units. 

Ideally, pint should also throw an error in case it doesn't know how to convert a unit, but this is secondary I guess.

**Comment by CD3** [comment]
I wrote the first implementation of the `siunitx` formatter, and you are correct, it does not do any name mapping. It just takes the string that pint calls the name and adds a slash. I wanted to keep it simple, and there is a simple workaround.

In Python, define non-underscored versions of the units you want to use
```
ureg = pint.UnitRegistry()
ureg.define("electronvolt = electron_volt")
```
and then use this name to create quantities
```
energy = ureg.Quantity(5,'electronvolt')
```
Now `"{:Lx}".format(energy)` will generate `\SI[]{5}{\electronvolt}`

Some units are named differently in Pint and siunitx, and there are several units in Pint that are not in `siunitx`. In LaTeX define a new siunitx unit to add these. I have this list of defines in almost all of my LaTeX document (some of these require units to be added to Pint)
```
\DeclareSIUnit \degF {\degree F}
\DeclareSIUnit \degC {\degree C}
\DeclareSIUnit \degK {K}
\DeclareSIUnit \mile {mi}
\DeclareSIUnit \inch {in}
\DeclareSIUnit \foot {ft}
\DeclareSIUnit \yard {yd}
\DeclareSIUnit \acre {acre}
\DeclareSIUnit \lightyear {ly}
\DeclareSIUnit \year {yr}
\DeclareSIUnit \parcec {pc}
\DeclareSIUnit \teaspoon {tsp.}
\DeclareSIUnit \tablespoon {tbsp.}
\DeclareSIUnit \gallon {gal}
\DeclareSIUnit \quart {qt}
\DeclareSIUnit \pallet {pallet}
\DeclareSIUnit \dollar {{\$}}
\DeclareSIUnit \poundmass {lbm}     " ureg.define('poundmass = pound')
\DeclareSIUnit \poundforce {lbf}       " ureg.define('poundforce = pound_force')
\DeclareSIUnit \gravity {g}
\DeclareSIUnit \revolutionsperminute{rpm}  " ureg.define('revolutionsperminute = revolutions_per_minute')
\DeclareSIUnit \mph{mph}
\DeclareSIUnit \fluidounce{floz}      " ureg.define('fluidounce = fluid_ounce')
\DeclareSIUnit \turn {rev}

```

**Comment by hgrecco** [comment]
Linking to #1757
