### ISSUE TITLE
Pint 0.15 is out

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1155]
Now that Pint 0.15, we will prepare for the next version and the majore feature will be Logarithmic units. This long awaited featured is implemented in #1027 and it looks very good. So I think is time to accept it as provisional. I will merge it so we can all play longer with it until next pint version (Around september 10).

ping: @5igno @scasagrande @clarkgwillison @terikin

Thanks for all the amazing code you have contributed.

**Comment by scasagrande** [comment]
Awesome, I will be looking into using this code asap to start testing.

**Comment by hgrecco** [comment]
I would like to do release a new version next weekend. How are we doing with the log support?

**Comment by scasagrande** [comment]
In a branch, I've updated InstrumentKit to make use of the new functionality. So far I've been able to get everything running and passing. I need to experiment a little bit around converting between different prefixed Bels, eg converting from `dBm` to `cBm`. This is a niche case as no one in their right mind uses centibel milliwatts, except for this one instrument.

**Comment by hgrecco** [comment]
Pint 0.16 is out with provisional log units support. Congratulations to everyone who was involved.
