### ISSUE TITLE
Support parsing dimensionless engineering notation

### ISSUE THREAD

**Issue by clarkgwillison** [hgrecco/pint#1156]
Tried reaching for Pint to parse some dimensionless numbers with engineering notation

Was hoping for something like this to work:
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg('100k').magnitude
100000.0
```
Instead, got:
```python
>>> ureg('100k')
<Quantity(100, 'boltzmann_constant')>
```
Fine, was a little ambiguous, let's try something else. Hoping for something like:
```python
>>> Q_ = ureg.Quantity
>>> Q_('100k', ureg.dimensionless).magnitude
100000.0
```
But instead got:
```python
>>> Q_('100k', ureg.dimensionless).magnitude
'100k'
```
Could be a good to support this. If well documented, it could even become the default solution for "how do you read strings in engineering notation in python". Come for the parsing, stay for the units (or vice versa)

**Comment by hgrecco** [comment]
I use this notation a lot, but I do not see how to implement this without breaking other things.
