### ISSUE TITLE
Check and cast to float before stripping units

### ISSUE THREAD

**Issue by knightofni-i** [hgrecco/pint#1158]
For dimensionless units where m_as("") changes the magnitude (particularly degrees), there is an error trap when units are stripped if the Quantity was (possibly unintentionally) type int. It'd be potentially safer to cast to float if conversion to dimensionless changes the magnitude.

    >>> test = pint.Quantity(30,"degree")  
    >>> np.concatenate(([test], [2]))     
    array([0, 2])
    >>> test = pint.Quantity(30.0,"degree")
    >>> np.concatenate(([test], [2]))       
    array([0.52359878, 2.        ])

**Comment by hgrecco** [comment]
I forgot to write here. I am not sure you can cast here automatically. If you find a way, let us know.
