### ISSUE TITLE
Units added using load_definitions are not in compatible_units results.

### ISSUE THREAD

**Issue by stevecj** [hgrecco/pint#1163]
Units are successfully loaded into a registry from a file using `<registry>.load_definitions(<filename>)`, but units loaded this way do not appear in results of subsequent `<unit>.compatible_units()` calls where the units are actually compatible.

Let's say that we create a `UnitRegistry` instance (`ureg = UnitRegistry()`) and then load a file containing the following entry using its `load_definitions` method:
```
foobar = 5 * second = fobr
```

If we then invoke `ureg['second'].compatible_units()`, we get a set of units including _planck_time_, _shake_, _second_, _minute_, etc., but the _foobar_ unit is not in the set. If we invoke `ureg['foobar'].compatible_units()`, then we get the exact same set. The _foobar_ unit is not in its own set of compatible units.

**Comment by hgrecco** [comment]
This has been fixed, it will be included in 0.21 release.
