### ISSUE TITLE
Quantity class and tug war between magic methods

### ISSUE THREAD

**Issue by ArendVerboomEC** [hgrecco/pint#1167]
Hi, 

First of all thank you all for your time and effort to create such a very nice project. I am impressed.

I have a question.

I am trying to integrate pint into my own project, but I ran into an issue with the magic methods of the Quantity class. My own project is about creating a kind CAS system, a bit like sympy, but then focussed especially on mechanical engineering.

Basically, Quantity accepts objects of my own class Expression for arithmetic operations as `__mul__`, while it should, in my case, return NotImplemented. So that my class can take care of handling the multiplication, or other arithmetic operations.

Here is a working example.
```
from pint import UnitRegistry, Quantity
import operator as op

class Expression(object):
    
    def __init__(self, a1, *args):
        
        args = list(args)
        
        if len(args) == 0:
            # I only want to have instances of Quantity here
            assert isinstance(a1, Quantity) 
        else:
            for n, a in enumerate(args):
                if not isinstance(a, Expression):
                    args[n] = Expression(a)
            
    def __mul__(self, other):
        return Expression(op.mul, self, other)
    
    __rmul__ = __mul__
    
class Variable(Expression):
    
    def __init__(self):
        pass

if __name__ == "__main__":
    
    ureg = UnitRegistry()
    
    c = Quantity(1, ureg.m)
    
    x = Variable()
    
    # this one works because __mul__ of my class is called first
    c * x
    
    # this one does not, raises AssertionError in line 19
    # __mul__ of Quantity class is called first
    x * c 

```
The problem arises when the `_mul_div` treats Expression as a magnitude, at line [1216](https://github.com/hgrecco/pint/blob/5d4e9154885d7e7a0d9c43c0459b237c7a87ad01/pint/quantity.py#L1216)

Now a solution I found is appending my class to this list:

```
from pint import compat
compat.upcast_types.append(Expression)
```
which returns a NotImplemented through the `check_implemented` decorator defined in quantity.py. This ensures only my implementation of `__mul__` is used as defined in Expression, and not the `__mul__` of Quantity.

But I wonder whether it is intended for this use, and more importantly, I have a lot of derived class from Expression. Since the check_implemented method compares the types and does not use `isinstance` I will have to add all the subclasses as well and I don't think that it is a pretty solution.

Any directions towards a solution would be appreciated.

Thanks in advance!

**Comment by jthielen** [comment]
@ArendVerboomEC You may find this section of the Pint docs helpful: https://pint.readthedocs.io/en/0.11/numpy.html#Technical-Commentary. In short, appending to the `compat.upcast_types` list exactly the intended way to register an new upcast type of Pint (one that wraps `Quantity` like your `Expression` class).

In regards to your related issue of subclasses, perhaps it would be best to update the current upcast type check function to also check for subclasses. So instead of:

https://github.com/hgrecco/pint/blob/5d4e9154885d7e7a0d9c43c0459b237c7a87ad01/pint/compat.py#L178-L189

it could be changed to

```python
other in upcast_types or issubclass(other, tuple(upcast_types))
```

**Comment by ArendVerboomEC** [comment]
Thank you!

If the change you mention in your reply is helpful to the project then I would not mind to make a small contribution.
I suppose there is some logic in treating classes that are derived from the upcast_types the same as their super classes.

**Comment by rpmanser** [comment]
I am also interested in seeing this changed. Do you still plan on making this contribution @ArendVerboomEC?

**Comment by hgrecco** [comment]
I am closing this for now. Feel free to open a new issue if necessary.
