### ISSUE TITLE
How to detect the presence of dimensionless units ?

### ISSUE THREAD

**Issue by huard** [hgrecco/pint#1171]
I'm trying to catch user input errors and would need to be able to identify units that mistakenly include angles in them. For example, if instead of specifying `degC`, someone writes:

```python
In [1]: units.parse_expression("1 degree celsius")
Out[1]: 274.15 <Unit('degree * kelvin')>
```
they'll get a non-sensical answer when converting to another unit:
```python
In [2]: units.parse_expression("1 degree celsius").to("kelvin")
Out[2]: 4.784820144342454 <Unit('kelvin')>
```
How would I check that the dimension of the inputs are a temperature, and not an angle times a temperature ? 

I'm currently checking the *dimensionality*, but since angles are dimensionless, I'm not catching this particular error.

**Comment by dalito** [comment]
Would it be an option for you to use a custom unit definition file without the angle units "deg" and "degree"?

**Comment by hgrecco** [comment]
The parser does not actually recognizes spaces within unit names and I think it will make things really hard.  Removing degree from the unit list is a way to at least ensure that you have an error message.

**Comment by huard** [comment]
Thanks for the suggestion. We're also dealing with wind directions, so removing degree entirely might not be an option, but we'll see how far we can go with this idea.
