### ISSUE TITLE
Error when using function numpy.sign

### ISSUE THREAD

**Issue by rtesse** [hgrecco/pint#1174]
I have a TypeError when I execute this portion of code:

import pint
import numpy as np

ureg = pint.UnitRegistry()
a = -2*ureg.m
np.sign(a)

TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'sign'>, '__call__', <Quantity(-2, 'meter')>): 'Quantity'

I use version 1.19.2 of numpy and 1.16 of Pint. 

Do I miss something ? 

Regards,

Robin Tesse

**Comment by jthielen** [comment]
Nope, you did not missing anything, `np.sign` is simply not yet implemented for Pint Quantities. Adding an implementation for this ufunc should be easy to add to [the appropriate list in `pint/numpy_func.py`](https://github.com/hgrecco/pint/blob/master/pint/numpy_func.py#L324-L431). To verify, would the expected result of `np.sign(-2 * ureg.m)` be `-1` (no units on result)?
