### ISSUE TITLE
chemistry extensions

### ISSUE THREAD

**Issue by twindus** [hgrecco/pint#1177]
I am part of a project, Molecular Sciences Software Institute (MolSSI, https://molssi.org/), and quite a few of our projects use pint as a base for conversions.  However, we have been customizing the unit registries for several other units and includes the NIST CODATA.  Is this something you would be interested in having added to Pint?  If so, are there any restrictions to additions that you have?

**Comment by hgrecco** [comment]
Very nice projects, congratulations on your work.

While we do not have a written policy (yet), over the years we have followed a few guidelines that proven useful:
- Always adhere to standards regarding naming, definitions, etc
- Document sources for definitions.
- Enforce correctness in calculations.
- Do not guess user intention.
- Allow interoperability with other packages.
- Include everything that might be useful for a wide scientific community, leave specifics for related packages.

It is difficult for me to answer your questions in detail but I would say that if the units/constants that you want to add are standard in a wide field, well defined and do not collide with other; feel free to add them.

**Comment by twindus** [comment]
Thanks for the quick response!  We are gathering our extensions together and will evaluate them based on your guidelines.  Hopefully, we will send you something in the not too distant future.

**Comment by hgrecco** [comment]
Once that you have a more concrete idea, feel free to write it up here so we can discuss it. I would also be interested to know if any particular missing feature you might find useful.
