### ISSUE TITLE
Formatting with SI prefixes

### ISSUE THREAD

**Issue by adamgreg** [hgrecco/pint#1199]
I'm a big fan of Pint - excellent work, thanks!

I think it would be useful if there was a format specifier that could be used to scale the number for readability and add an appropriate prefix from the unit registry. Plotly/D3 includes something similar for SI prefixes with the format specifier "s". It would allow code like:

```
>>> format(1e-6 * ureg.V, '~s')
'1µV'
```

Would you be interested in a feature like this? I'd be happy to work on a pull request.

**Comment by jules-ch** [comment]
You can do this with `to_compact`:

```python

>>> format(1e-6 * ureg.V).to_compact(), "~")
'1.0µV'

**Comment by adamgreg** [comment]
Oh that's fantastic, thanks! I don't know how I missed that, sorry.

**Comment by jules-ch** [comment]
No problem we can see if more ppl are asking for this feature. We can improve documentation for this maybe
