### ISSUE TITLE
Add Sverdrup to default._en.txt

### ISSUE THREAD

**Issue by uliw** [hgrecco/pint#1202]
Sverdrup is a volumetric flow unit used in Oceanography. The definition is as follows

```
Sverdrup = 1e6 * meters **3 / second = Sv = Sverdrups
```
the shorthand conflicts however with the Sievert
https://en.wikipedia.org/wiki/Sverdrup

Can this be added to default._en.txt?

Thanks

**Comment by uliw** [comment]
jut noticed I can do local definnitions

**Comment by rabernat** [comment]
I would love to see Sverdrup added to the default unit registry. Would a PR for this be considered?

**Comment by keewis** [comment]
I think this should be fine (the default registry already has a lot of other domain specific units), but if not you can always add it to `cf-xarray`
