### ISSUE TITLE
ValueError: Integers to negative integer powers are not allowed when used with force_ndarray

### ISSUE THREAD

**Issue by prataffel** [hgrecco/pint#1203]
Hey,

First of all: thanks for pint, it's a really useful tool.

I have an issue (that might be a corner case) when using ``to_base_units()`` with ``force_ndarray`` or ``force_ndarray_like`` equals ``True``. If I run

``` python
import pint

ureg = pint.UnitRegistry()
ureg.force_ndarray = True

a = ureg('1 / farad ** 2')
a.to_base_units()
```

the script raises a ValueError:
``` bash
  File "/usr/lib/python3.8/site-packages/pint/quantity.py", line 697, in to_base_units
    _, other = self._REGISTRY._get_base_units(self._units)
  File "/usr/lib/python3.8/site-packages/pint/registry.py", line 2059, in _get_base_units
    factor, units = self.get_root_units(input_units, check_nonmult)
  File "/usr/lib/python3.8/site-packages/pint/registry.py", line 794, in get_root_units
    f, units = self._get_root_units(input_units, check_nonmult)
  File "/usr/lib/python3.8/site-packages/pint/registry.py", line 829, in _get_root_units
    self._get_root_units_recurse(input_units, 1, accumulators)
  File "/usr/lib/python3.8/site-packages/pint/registry.py", line 880, in _get_root_units_recurse
    self._get_root_units_recurse(reg.reference, exp2, accumulators)
  File "/usr/lib/python3.8/site-packages/pint/registry.py", line 878, in _get_root_units_recurse
    accumulators[0] *= reg._converter.scale ** exp2
ValueError: Integers to negative integer powers are not allowed.
```

Note, that the minimal example runs smoothly, if ``a = 1 / ureg.farad ** 2`` is used to define ``a``. 

I am using python 3.8.6 on a linux machine, pint version 0.16.1.

**Comment by lukelbd** [comment]
I also encountered this error trying to initialize a unit registry for pint-xarray (they [recommend](https://pint-xarray.readthedocs.io/en/stable/creation.html#attaching-units) `force_ndarray_like=True`).

**Comment by keewis** [comment]
what version of `pint` are you using? I remember working on this error some time ago (see #1328), so upgrading `pint` should fix this.

**Comment by hgrecco** [comment]
Closing now. Feel free to reopen.
