### ISSUE TITLE
Weird dtype change

### ISSUE THREAD

**Issue by dopplershift** [hgrecco/pint#1210]
I ran into some really weird behavior with a resulting dtype from operations on 32-bit floats:
```python
p = np.array([1.5, 2.5], dtype=np.float32) * units.hPa

# Prints "float32"
print(p.dtype)

# Prints "float32"
print(np.nanmax(p).dtype)

# Prints "float32"
print(np.nanmax(p.m).dtype)

# Prints "float64" HUH?
print((np.nanmax(p.m) * units.hPa).dtype)
```

I can't think of any logical reason why that last one results in a type conversion.

**Comment by dopplershift** [comment]
Ok now what in the world:
```python
p = np.array([1.5, 2.5], dtype=np.float32) * units.hPa

# Prints "float32"
print((p / (1.0 * units.hPa)).dtype)

# Prints "float64"
print((p[0] / (1.0 * units.hPa)).dtype)
```

**Comment by jthielen** [comment]
I think this is just upstream behavior with combining `float32` and `int` in ufuncs, as the following replicates it without Pint involved at all?

```python
p = np.array([1.5, 2.5], dtype=np.float32)

# Prints "float32"
print(p.dtype)

# Prints "float64"
print((p[1] * 1).dtype)
```

**Comment by dopplershift** [comment]
Ok, the second one might be. Not so sure about `nanmax` above though.

**Comment by jthielen** [comment]
They *should* be the same, as both `p[1]` from my example and `np.nanmax(p.m)` above are `numpy.float32` instances. I think it is just NumPy behavior to cast `float32 * int` to `float64`, unless I'm mistaken?

**Comment by dopplershift** [comment]
Well, you keep saying `int` but I'm working with Python `float` (but that *is* a NumPy issue). However, unless I'm missing something under the hood, this:
```
np.nanmax(p.m) * units.hPa
```
involves neither `int` nor `float`, just the original `float32` scalar.

**Comment by dopplershift** [comment]
And the answer about NumPy's casting is that it doesn't seem to depend on `int` vs. `float`, but *does* depend on scalar vs. array:
```python
# float32
np.find_common_type([np.float32], [int])

# float64
np.find_common_type([], [np.float32, int])

# float32
np.find_common_type([np.float32], [float])

# float64
np.find_common_type([], [np.float32, float])
```

We'll see what discussion comes about that from numpy/numpy#17816.

**Comment by jthielen** [comment]
> Well, you keep saying `int` but I'm working with Python `float` (but that _is_ a NumPy issue). However, unless I'm missing something under the hood, this:
> 
> ```
> np.nanmax(p.m) * units.hPa
> ```
> 
> involves neither `int` nor `float`, just the original `float32` scalar.

Sorry if I wasn't being clear earlier...this indeed goes to something under the hood. `int` becomes involves because this operation goes to [`Unit.__mul__` where `units.hPa` becomes `units.Quantity(1, 'hPa')`](https://github.com/hgrecco/pint/blob/5e59f373ea237a95f22960a2b169c3a756a264c9/pint/unit.py#L177-L188), and then `Quantity`'s `_mul_div` performs the multiplication of magnitudes (`1 * np.nanmax(p.m)`, where the possibly unexpected casting occurs) and wraps as Quantity again.

**Comment by dopplershift** [comment]
Alright, apparently they *are* all the same. I'll close this in favor of the numpy issue. Thanks for the clarification.
