### ISSUE TITLE
Does converting metric tons to kilo gram fail?

### ISSUE THREAD

**Issue by TaskeHAMANO** [hgrecco/pint#1215]
Thank you for developing a cool package!
I am trying to write a very simple script that will calculate the price per weight. Here is my code.

```
from pint import UnitRegistry

unit_registry = UnitRegistry()
unit_registry.define("USD = []")
(1000 * unit_registry.USD / unit_registry.kg).to("USD/metric_tons")
```

The result of this script is `1000000.0 USD/metric_ton`, but I think it is supposed to be `1 USD/metric_ton`. I feel that I'm getting inappropriate answers because I'm using weight as a divisor. What should I do in this case?

Environment:
* OS: windows10
* python: 3.7.9 (with Anaconda 3)
* pint: 0.15

**Comment by jules-ch** [comment]
I don't get your issue.
If you have something whose price is 1000$/kg then for a metric ton which is 1000 times more weight then it will cost you 1 000 000$ per ton.

1kg -> 1 000$
1000kg -> 1 000 000 $

**Comment by TaskeHAMANO** [comment]
@jules-ch 

Thank you for your comment!
I have understood how to use `pint` from your example. It turns out that I used the library wrong.

I am trying to do dimensional analysis. For example, please look at the following script.
```
from pint import UnitRegistry

ur  = UnitRegistry(filename=None)
ur.define("KG = []")
ur.define("MT = 1000 * KG")
ur.define("USD = []")

X = ur.USD / ur.MT
FORMULA = "X / 1000"
eval(FORMULA )
```

What I want to know is the unit of FORMULA. I have tried to adopt a unit that converts FORMULA value to 1. In this example, the unit I want to get is [USD/KG], as shown in the following example.
```
FORMULA  = X / 1000
         = [USD/MT] / 1000
         = 10^-3 [USD/MT].
         = 1 [USD/KG].
```
It seems that `.to` performs the conversion. In this case, `to` may not be appropriate because **the conversion itself has already been built into the formula.**
Do you know any good way to find out the dimension of this FORMULA?

**Comment by cpascual** [comment]
Hi @TaskeHAMANO ,  if you want to work with dimensionality, have a look at 
https://pint.readthedocs.io/en/stable/wrapping.html#checking-dimensionality

Maybe this example makes it clearer:

```python
import pint
ur = pint.UnitRegistry()
ur.define("usd = [currency]")
dollars_per_ton = ur.usd / ur.metric_ton
print(dollars_per_ton.dimensionality)     # -->  [currency] / [mass]
a = ur.Quantity("1 usd/kg")
b = a.to(dollars_per_ton)
c = a.to("usd/ounce")
print(a)                                                    # --> 1.0 usd / kilogram
print(b)                                                    # --> 1000.0 usd / kilogram
print(c)                                                    # -->  0.028349523125 usd / ounce
print(a.dimensionality)                            # -->  [currency] / [mass]
print(b.dimensionality)                            # -->  [currency] / [mass]
print(b.dimensionality)                            # -->  [currency] / [mass]
```

**Comment by TaskeHAMANO** [comment]
Hi @cpascual ,
Thanks for sharing your knowledge. Now I understand what the rectangle bracket meaning!
