### ISSUE TITLE
Unable to calculate units for moment of inertia

### ISSUE THREAD

**Issue by chrisspen** [hgrecco/pint#1217]
I'm attempting to calculate the moment of inertia for an inverted pendulum, which is `I = m*g*l*sin(theta)`, but Pint returns an error when asked to return the value in the correct units of `kg*m^2`.

Running:

    import pint

    from pint import UnitRegistry
    ureg = UnitRegistry()
    Q = ureg.Quantity

    mass = Q(213, 'gram')

    gravity = Q(9.8, 'm/s^2')

    L = Q(70, 'mm')

    I1 = (mass * gravity * L).to('kg*m^2')

gives me the error:

    pint.errors.DimensionalityError: Cannot convert from 'gram * meter * millimeter / second ** 2' ([length] ** 2 * [mass] / [time] ** 2) to 'kilogram * meter ** 2' ([length] ** 2 * [mass])

Do you know why this is?

**Comment by dalito** [comment]
Your equation for the [moment of inertia](https://en.wikipedia.org/wiki/Moment_of_inertia) is not correct.

This is a good example how pint helps to reveal bugs early on.

**Comment by chrisspen** [comment]
I believe it is correct. I'm using the equation for the moment of inertia for an [inverted pendulum.](https://en.wikipedia.org/wiki/Inverted_pendulum#Equations_of_motion) How is it incorrect?

**Comment by chrisspen** [comment]
Oh, I see. I think I'm using the equation for torque, not inertia. Thanks.
