### ISSUE TITLE
Output of UnitRegistry.get_compatible_units depends on cache state

### ISSUE THREAD

**Issue by fuglede** [hgrecco/pint#1218]
Consider the following example (taken from [here](https://stackoverflow.com/a/65593102/5085211)):

```python
import io
import pint

ureg = pint.UnitRegistry()
ctx_def = io.StringIO("""\
EUR = [currency]
DKK = 0.14 EUR
""")
ureg.load_definitions(ctx_def)
```
With this, the result of `ureg.get_compatible_units('EUR')` depends on the state of `ureg._cache` and will only run without errors once the cache has been explicitly modified (e.g. through `ureg._build_cache()`):

```python
In [26]: ureg.get_compatible_units('EUR')  # Fails
KeyError: <UnitsContainer({'[currency]': 1})>

In [27]: ureg._build_cache()

In [28]: ureg.get_compatible_units('EUR')  # No longer fails
Out[28]: frozenset()
```

Maybe this is working as intended, but I assume this is a bug, and that there's a cache check missing somewhere, as the user shouldn't have to worry about implementation details surrounding the cache.

This is using pint 0.16.1.

**Comment by hgrecco** [comment]
This has been fixed. Will be included in 0.21 release.
