### ISSUE TITLE
Adding dimensionless to degree is implicitly converted to radians instead of degree.

### ISSUE THREAD

**Issue by theRealSuperMario** [hgrecco/pint#1230]
See below

```python
>>>np.rad2deg(np.arctan2(np.sin(np.pi / 2) * UNIT_REGISTRY.dimensionless, np.cos(np.pi / 2) * UNIT_REGISTRY.dimensionless)) + 90
<Quantity(91.5707963, 'dimensionless')>
>>>np.rad2deg(np.arctan2(np.sin(np.pi / 2), np.cos(np.pi / 2))) + 90
180.0
```

Interestingly, the expression on the left of the `+` operator works fine

```python
>>>np.rad2deg(np.arctan2(np.sin(np.pi / 2) * UNIT_REGISTRY.dimensionless, np.cos(np.pi / 2) * UNIT_REGISTRY.dimensionless))
<Quantity(90.0, 'degree')>
np.rad2deg(np.arctan2(np.sin(np.pi / 2), np.cos(np.pi / 2)))
90.0
```

So it seems like the + operator implicitly casts dimensionless quantities to radians, which are then converted to degree.

I am a little bit confused by this behaviour. Is this intended? I think adding dimensionless (`float`) to degree should keep the float value in degrees.

What do you guys think?

**Comment by jthielen** [comment]
Yes, this is intended behavior, because dimensionless and radians are in-effect the same unit. To make your first example dimensionally consistent, the 90 needs to have units of degrees and not be unitless, so,

```
>>>np.rad2deg(np.arctan2(np.sin(np.pi / 2) * UNIT_REGISTRY.dimensionless, np.cos(np.pi / 2) * UNIT_REGISTRY.dimensionless)) + 90 * UNIT_REGISTRY.degree
<Quantity(180.0, 'degree')>
```

Also, it is probably better to rely on Pint's unit handling than `np.rad2deg` and `np.deg2rad` for the best results. You can achieve the same results as the above with

```
>>>90 * UNIT_REGISTRY.degree + np.arctan2(np.sin(np.pi / 2) * UNIT_REGISTRY.dimensionless, np.cos(np.pi / 2) * UNIT_REGISTRY.dimensionless)
<Quantity(180.0, 'degree')>
```

or


```
>>>np.arctan2(np.sin(np.pi / 2) * UNIT_REGISTRY.dimensionless, np.cos(np.pi / 2) * UNIT_REGISTRY.dimensionless).to('degree') + 90 * UNIT_REGISTRY.degree
<Quantity(180.0, 'degree')>
```

Hopefully that helps clear things up!

**Comment by theRealSuperMario** [comment]
Thanks for the explanation. I have some thoughts on the design choice.

Adding anything to a quantity throws `DimensionalityError`
```python
>>>30 * UNIT_REGISTRY.kilometer + 90
pint.errors.DimensionalityError: Cannot convert from 'kilometer' to 'dimensionless'
```

But adding anything to to an angle works fine
```python
30 * UNIT_REGISTRY.radians + 90
<Quantity(120, 'dimensionless')>
30 * UNIT_REGISTRY.degree + 90
<Quantity(90.5235988, 'dimensionless')>
```

I think this is very inconsistent and a quick way to introduce programming error. 
- have look at the lines of code. The only thing that differs is which unit you take from the registry
- The result could not be more different
- Case 1: exception
- Case 2: casting to dimensionless, then correctly adding the values
- Case 3: implicit casting to radians, dimensionless, then correctly adding the values.


Don't get me wrong, I totally get **why** you chose to implement it this way. But to me it feels like it breaks the consistency with how package behaves with all other units, and I would prefer a different behaviour.

What do you think?

If you want, I can give it a try to make a PR that changes this.

**Comment by fschuetz04** [comment]
As you said, it is understandable why it is implemented the way it is: Both degrees and radians are dimensionless units. Changing the behavior by default would break many programs, so I would strongly recommend against doing so. However, you can create custom unit definitions in which degrees and radians are independent and not dimensionless. See https://pint.readthedocs.io/en/stable/defining.html.

**Comment by theRealSuperMario** [comment]
Thats a good idea. Thanks.
