### ISSUE TITLE
inconsistent byte conversions

### ISSUE THREAD

**Issue by fogx** [hgrecco/pint#1232]
I've done some testing, as i need to use pint to convert byte-units and i have to agree with the poster in #874 that the parsing is very inconsistent.
While i do understand the need to remain SI-compliant in the "default settings", there should be a way to properly and simply parse these *very common* byte units. And sadly, most data sources do not respect SI-formatting such as `kB`.

As you can see in the following tests, the case_sensitive option does not help (it makes it worse in some cases).

```
--- B ---
ureg(B, case_sensitive=True): 1 byte
ureg(B, case_sensitive=False): 1 byte
ureg(b, case_sensitive=True): 1 barn
ureg(b, case_sensitive=False): 1 barn
--- KB ---
ureg(KB, case_sensitive=True): 'KB' is not defined in the unit registry
ureg(KB, case_sensitive=False): 'KB' is not defined in the unit registry
ureg(kb, case_sensitive=True): 1 kilobarn
ureg(kb, case_sensitive=False): 1 kilobarn
ureg(Kb, case_sensitive=True): 'Kb' is not defined in the unit registry
ureg(Kb, case_sensitive=False): 'Kb' is not defined in the unit registry
ureg(kB, case_sensitive=True): 1 kilobyte
ureg(kB, case_sensitive=False): 1 kilobarn
--- MB ---
ureg(MB, case_sensitive=True): 1 megabyte
ureg(MB, case_sensitive=False): 1 megabarn
ureg(mb, case_sensitive=True): 1 millibarn
ureg(mb, case_sensitive=False): 1 millibarn
ureg(Mb, case_sensitive=True): 1 megabarn
ureg(Mb, case_sensitive=False): 1 megabarn
ureg(mB, case_sensitive=True): 1 millibyte
ureg(mB, case_sensitive=False): 1 millibarn
--- GB ---
ureg(GB, case_sensitive=True): 1 gigabyte
ureg(GB, case_sensitive=False): 1 gilbert
ureg(gb, case_sensitive=True): 'gb' is not defined in the unit registry
ureg(gb, case_sensitive=False): 1 gilbert
ureg(Gb, case_sensitive=True): 1 gilbert
ureg(Gb, case_sensitive=False): 1 gilbert
ureg(gB, case_sensitive=True): 'gB' is not defined in the unit registry
ureg(gB, case_sensitive=False): 1 gilbert
--- TB ---
ureg(TB, case_sensitive=True): 1 terabyte
ureg(TB, case_sensitive=False): 1 terabarn
ureg(tb, case_sensitive=True): 'tb' is not defined in the unit registry
ureg(tb, case_sensitive=False): 'tb' is not defined in the unit registry
ureg(Tb, case_sensitive=True): 1 terabarn
ureg(Tb, case_sensitive=False): 1 terabarn
ureg(tB, case_sensitive=True): 'tB' is not defined in the unit registry
ureg(tB, case_sensitive=False): 'tB' is not defined in the unit registry

expected implementation, such as with hertz:
--- HZ ---
ureg(HZ, case_sensitive=True): 'HZ' is not defined in the unit registry
ureg(HZ, case_sensitive=False): 1 hertz
ureg(hz, case_sensitive=True): 'hz' is not defined in the unit registry
ureg(hz, case_sensitive=False): 1 hertz
ureg(Hz, case_sensitive=True): 1 hertz
ureg(Hz, case_sensitive=False): 1 hertz
ureg(hZ, case_sensitive=True): 'hZ' is not defined in the unit registry
ureg(hZ, case_sensitive=False): 1 hertz
```

so the questions that arise for me are:
1. Are these inconsistencies intended? I would expect case_insensitive to return the same values for `tb`, `Tb`, `tB` and `TB`. Also, i would expect all units that return a value in their non-capitalized versions to return something when case_insensitive is set (like kb and KB).
This works properly with other units, such as hertz (see examples)
2. how do i configure my pint-commands to properly comprehend (casefold) byte-conversions?
`ureg(x, case_sensitive=False)` is not an option, since it returns multiple incorrect values (gilbert, barn and not defined)
Do i edit the entries for barn and gilbert, and add the missing units (gb, tb,...?)  to the unit registry?
Is there a unit_registry.txt that i can pull from somewhere to do this?

**Comment by hgrecco** [comment]
We stick to SI-compliance because is the right thing and there is no way to guess user intention. I would argue that is tha datasource that is wrong, not pint. Having said that, Pint is completely configurable. You can copy and modify `default_en.txt` and then use the new file as your unit registry. So you can delete all units that are giving you trouble and add everything you need. Importantly: DO NOT ADD PREFIXED units. Pint does this for you.

**Comment by fogx** [comment]
As i have stated, i understand that SI-compliance is mandatory. Nevertheless, i don't understand the purpose of having a nebulous `case_sensitive` parameter that doesn't act in a sensible way. If i specify the function to be case insensitive, and SI-compliance dictates that `kb` = kilobarn then that is fine. Ignoring the parameter and sometimes outputting kilobarn sometimes failing is definitely not fine imo (see the example).
Especially since this seems to work with some units, Hz and Gb, and doesn't with others, such as B and KB.

It doesn't matter if the datasource is "wrong", it is how it is. The question is how do we use pint to properly deal with such a datasource. 

> DO NOT ADD PREFIXED units. Pint does this for you.
Can you elaborate? It seems like i have to change some of the prefixes. mb will output millibyte after overwriting b = byte, which does not exist.

Is there a way to remove entries in the default definitions file? Gb will always ignore the prefix and use gilbert, even when overwriting it in the definitions extension file (`gilbert = 1 / (4 * π) * biot_turn = XXXX`)

**Comment by hgrecco** [comment]
I agree that the parser should be deterministic and currently is not. There a few reasons for this, but it boils down to the fact there is cache that my preempt the parser for keep looking. However, we do provide a warning the first time you parse such a case. If you look at pint logs you will see:
```
2021-01-12 14:33:55,123 - pint.util - WARNING - Parsing kb yield multiple results. Options are: (('kilo', 'barn', ''), ('kilo', 'byte', ''))
```
Regarding prefixes and casing, only units are treated either case-sensitive or insensitive. Prefixes are always case-sensitive. You can add an alias to the prefix if you want.

There is no public API to remove units programmatically as most people that were interested in this preferred just creating a specific file with their interest (which they need to do only once).

If the datasource is wrong in a very specific way, the easiest way is using a preprocessor rule which is a still undocumented but now stable feature in Pint. Briefly is a list of callables (str -> str) which are sequentially applied on any input expression or unit string.

**Comment by fogx** [comment]
Alright. Thanks for your answers!
in case anyone else has this issue and is looking for a solution, i have solved my issue by creating the following definitions file. It's not very clean but it works for me without overwriting the entire defaults.txt
```
byte = [] = B = b
megabyte = byte * 1e6 = mb = Mb = mB
kilobyte = byte * 1e3 = kb
gigabyte = byte * 1e9 = gb = gB
terabyte = byte * 1e12 = tb = gB
```
