### ISSUE TITLE
module 'pandas.core.ops' has no attribute '_get_op_name'

### ISSUE THREAD

**Issue by BerneStober** [hgrecco/pint#1233]
This occurs while running Pint_test_pandas.py from your pint_pandas\testsuite at the "import pint" statement.  Windows 10, Python 3.8.5, Pandas (1.2.0), Pint-Pandas (0.1), Pint (0.16.1).

I am somewhat of a novice python programmer, building weather station software using Dash/Plotly with a MySQL database storing the weather station data and simply want to use pint_pandas to unitize my dataframe and do unit slate conversions.  My initial error occured running the code at https://pint.readthedocs.io/en/0.16.1/pint-pandas.html was data type 'pint[lbf ft]' as others documented at https://github.com/hgrecco/pint/issues/972 . But then realized I hadn't installed pint-pandas. After successfully installing pint-pandas I now get this error.

**Comment by andrewgsavage** [comment]
this was fixed in a newer verison of pint-pandas
