### ISSUE TITLE
Moving out of travis

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1236]
Recently I started getting notificactions in the travis-ci.org website announcing that it will close soon and prompting migration to travis-ci.com. This is a commercial website with some free plans. I subscribed but the amount of free credits in the free plan is too little and requesting OSS credits is not convenient.

I am considering moving to another CI service, maybe AppVeyor, but I would like to hear your thoughts.

**Comment by jthielen** [comment]
I would highly recommend GitHub Actions! We've been using it successfully over at MetPy, and I believe xarray just switched over recently as well.

**Comment by jules-ch** [comment]
Just like @jthielen I'd say Github Actions.

**Comment by hgrecco** [comment]
Looks really good. Would you mind sending a PR with the workflows? Also, I was thinking about using the Discussions feature as well to clean up the tracker from things like: "How do I?" What is your experience with that?

**Comment by cpascual** [comment]
Github Actions is the easy path if you do not want to leave github, but in the [Tango collaboration](https://www.tango-controls.org/) (a collaboration of several large scientific infrastructures), we opted to move everything to [gitlab-ci](https://gitlab.com) instead. Here are [the arguments in favour of gitlab](https://github.com/tango-controls/cppTango/issues/812#issuecomment-732154412), and here the [announcement of the final decision to move all of our ~70 repos](https://github.com/tango-controls/TangoTickets/issues/47)

**Comment by hgrecco** [comment]
@cpascual Thanks for the information. While I agree with multiple of the points discussed in the link, I think that is too much of a change for now.
