### ISSUE TITLE
Overly hasty conversion of `int` to `float` causes precision loss

### ISSUE THREAD

**Issue by Kodiologist** [hgrecco/pint#1238]
```
>>> Q_(1, "ag") + Q_(1, "Mg")
<Quantity(1e+24, 'attogram')>
```

Python 3 integers are arbitrary-precision, so if there were not an internal conversion to `float`, the result could be `<Quantity(1000000000000000000000001, 'attogram')>`.

**Comment by andreacortis** [comment]
yeah, I am not sure that this is only an integer to float conversion issue 

```
>>  ipython
Python 3.9.0 (default, Dec 14 2020, 14:39:25)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pint

In [2]: pint.__version__
Out[2]: '0.16.1'

In [3]: from pint import UnitRegistry
    ...: ureg = UnitRegistry()
    ...: Q_=ureg.Quantity

In [4]: x = Q_('3.0 m^3')

In [5]: x.m_as('cm^3')
Out[5]: 2999999.9999999995

In [6]: x.m_as('km^3')
Out[6]: 3.0000000000000004e-09

```

This is actually, quite troubling.

**Comment by hgrecco** [comment]
> Python 3 integers are arbitrary-precision, so if there were not an internal conversion to float, the result could be 

Yes, but this would require to store all scaling factors as ints, and rewriting all divisions to multiplications to make sure that all operations are `+-*` among ints. If you want to avoid float rounding errors you can use another `non_int_type`.

```python
>>> ureg = pint.UnitRegistry(non_int_type=decimal.Decimal)
>>> ureg("1 ag") + ureg("1 Mg")
<Quantity(1000000000000000000000001, 'attogram')>
```

But bear in mind that then you then all non decimal numbers must be decimals.

**Comment by Kodiologist** [comment]
> Yes, but this would require to store all scaling factors as ints, and rewriting all divisions to multiplications to make sure that all operations are `+-*` among ints.

Is this not desirable? Given, it can't be done for some pairs of units, but wouldn't you want this when you can get it?

**Comment by hgrecco** [comment]
> This is actually quite troubling.

Same as above. floats are troubling. These are my favourite two examples for this:

```python
>>> 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1
0.9999999999999999
```

and 

```python
>>> 1 + 1e-17 - 1
0.0
>>> 1 - 1 + 1e-17
1e-17
```

Then, in your case:

```python
>>> x = ureg('3.0 m^3')
<Quantity(3.0, 'meter ** 3')>
>>> x.m_as('cm^3')
Decimal('3.0E+6')
>>> x.m_as('km^3')
Decimal('3.0E-9')
```

**Comment by hgrecco** [comment]
> Is this not desirable? Given, it can't be done for some pairs of units, but wouldn't you want this when you can get it?

I do not see any way of doing this without a big performance hit.

**Comment by Kodiologist** [comment]
Ah, shame. I thought such a change would actually improve performance, but I'm not familiar with the implementation. I might as well just use `fraction` when performance isn't an issue.

**Comment by hgrecco** [comment]
no type beats float in speed, that is why is the default non int type. 

But you can use fraction as well as `non_int_type`. Pint is fully customizable

```python
>>> import fractions
>>> ureg = pint.UnitRegistry(non_int_type=fractions.Fraction)
>>> ureg("1 ag") + ureg("1 Mg")
<Quantity(1000000000000000000000001, 'attogram')>
>>> x = ureg('3.0 m^3')
>>> x.m_as('cm^3')
Fraction(3000000, 1)
>>> x.m_as('km^3')
Fraction(3, 1000000000)
```

**Comment by Kodiologist** [comment]
That's what I meant. Sorry if I was unclear.

**Comment by andreacortis** [comment]
OK, this makes (sort of) sense now ... not knowing the internals of `pint`, I was expecting that the units conversions would be taken care by means of multipying factors, something like 

```
In [9]: from pint import UnitRegistry
   ...: ureg = UnitRegistry()
   ...: Q_=ureg.Quantity
   ...: x = Q_('3.0 m^3')
   ...: print(f"x = {x}")
   ...: m3_to_cm3 = lambda x: Q_(x.m*(100.**3),'cm^3')
   ...: y = m3_to_cm3(x)
   ...: print(f"y = {y}")
   ...: cm3_to_m3 = lambda x: Q_(x.m/(100.**3),'cm^3')
   ...: z = cm3_to_m3(x)
   ...: print(f"z = {z}")
x = 3.0 meter ** 3
y = 3000000.0 centimeter ** 3
z = 3e-06 centimeter ** 3

In [25]: print((z.m/y.m / y.m*x.m))
1e-18
```

Maybe I am still missing something?

**Comment by andreacortis** [comment]
Not knowing the internals of `pint`, I was expecting it to work something like this

```
In [27]: from pint import UnitRegistry
    ...: ureg = UnitRegistry()
    ...: Q_=ureg.Quantity
    ...: x = Q_('3.0 m^3')
    ...: print(f"x = {x}")
    ...: m3_to_cm3 = lambda x: Q_(x.m*(100.**3),'cm^3')
    ...: y = m3_to_cm3(x)
    ...: print(f"y = {y}")
    ...: cm3_to_m3 = lambda x: Q_(x.m/(100.**3),'m^3')
    ...: z = cm3_to_m3(y)
    ...: print(f"z = {z}")
x = 3.0 meter ** 3
y = 3000000.0 centimeter ** 3
z = 3.0 meter ** 3
```

**Comment by hgrecco** [comment]
@andreacortis I see a lot of problems with that idea

what currently is just multiplying the magnitude by a scaling factor will require:
- requires rewriting all conversions depending if the factor is larger or small than one (as described above)
- requires handling exponentiation.
- will only work for units conected by decimal systems (inch to cm will still need a float)
- will only work if the magnitude is an int (if it is a float, casting will happen)
- will scale very badly for compound units (`kg m/s^2` -> ` 1 g cm/s^2`)

I do not see a way to do it.

**Comment by andreacortis** [comment]
I understand all the problems with the scaling, and I am completely satisfied with the `decimal` solution ... I was just startled by the result. 
Would it make sense to default to `decimal` instead of float then?

**Comment by hgrecco** [comment]
>  Would it make sense to default to decimal instead of float then?

No, for two reasons:
1. decimal is slower than float
2. Python repl and interpreter parses non int numbers as float and they do not interoperate with Decimals

```python
>>> Decimal("1.") + 1.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float'
```

**Comment by andreacortis** [comment]
@hgrecco ok, got it

**Comment by hgrecco** [comment]
I am closing this issue, feel free to reopen.
