### ISSUE TITLE
resistance, mega/milliohms unit error

### ISSUE THREAD

**Issue by raveslave** [hgrecco/pint#1241]
`pint.errors.UndefinedUnitError: 'mOhms' is not defined in the unit registry  ` 

Both digikey.com and mouser.com return Resistance values like below (`1 mOhms` and `1 MOhms`)

<img width="225" alt="image" src="https://user-images.githubusercontent.com/1734770/105876340-2d862f80-5fff-11eb-85e0-6308da5d75b3.png">   

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1734770/105876426-4262c300-5fff-11eb-94bb-34936649e8d3.png">   

thoughts?

**Comment by dalito** [comment]
One of the [general rules in the SI system](https://en.wikipedia.org/wiki/International_System_of_Units#General_rules) is: "Symbols do not have a plural form." - If you want to accept "ohms" nevertheless, you can create your own copy of the unit registry with "ohms" added as a synonym for ohm.

**Comment by raveslave** [comment]
thx, makes sense. I wonder why the big chip distros mix like this. total mayhem
