### ISSUE TITLE
Cannot alias dimensionless unit

### ISSUE THREAD

**Issue by rfrowe** [hgrecco/pint#1242]
As we all know, there's an implicit unit named `dimensionless`. I use these units a lot in a config file and would rather use `none`.

I first tried creating an alias with `@alias dimensionless = none` but this fails with a KeyError. I then tried a new definition `none = dimensionless`. This succeeds, but then the following fails, also with a KeyError: `(1 * reg.none).to(reg.dimensionless)`

The only way I've been able to do this is to redefine the dimensionless unit with:
```
none = [] = dimensionless
```

This is not ideal as the following is false:
```
reg.dimensionless == reg.none
```

**Comment by jules-ch** [comment]
I think this is a use case for preprocessors here :

```python

import pint
ureg = pint.UnitRegistry(
    preprocessors=[lambda s: s.replace('none', 'dimensionless')]
)
```

Although documentation is missing, see https://github.com/hgrecco/pint/issues/1211
