### ISSUE TITLE
Method numpy.ndarray.clip min applied as max

### ISSUE THREAD

**Issue by knightofni-i** [hgrecco/pint#1244]
When the method `numpy.ndarray.clip` is used to apply only a minimum as a positional argument (without specifying kwarg `min=...`), the minimum is applied as a maximum.

Incorrect behavior
```
>> Quantity([3, 5, 4, 5], "mm").clip(Quantity([3.5, 6, 2, 2], "mm"), None)
<Quantity([3. 5. 2. 2.], 'millimeter')>
```
Correct behavior:
```
>> np.array([3, 5, 4, 5]).clip(np.array([3.5, 6, 2, 2]), None)
array([3.5, 6. , 4. , 5. ])

>> Quantity([3, 5, 4, 5], "mm").clip(min=Quantity([3.5, 6, 2, 2], "mm"), max=None)
<Quantity([3.5 6.  4.  5. ], 'millimeter')>
```
Environment versions:
python v3.8.1
numpy  v1.18.1
Pint v0.16.1

**Comment by ishigoya** [comment]
Hello, first-time contributor here, would it be alright if I had a go at resolving this?

**Comment by jules-ch** [comment]
@ishigoya 

Sure, give it a shot. SUbmit a PR & we will help you during review. :)
