### ISSUE TITLE
Use of seemingly equal units as dictionary keys

### ISSUE THREAD

**Issue by mrwizard82d1** [hgrecco/pint#1245]
Using pint 0.16.1 on Windows from Python 3.8.7.

I see "surprising" (at least to me) results in `ipython` when using seemingly equal units as dictionary keys:
```
[ins] In [1]: import pint

[ins] In [2]: ureg = pint.UnitRegistry()

[ins] In [3]: d = {(ureg.lb / ureg.cu_ft): 'lb-per-cu-ft'}

[ins] In [4]: d[ureg.lb / ureg.cu_ft]
Out[4]: 'lb-per-cu-ft'

[ins] In [5]: d[ureg.lb / ureg.ft ** 3]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-2141a796fcf3> in <module>
----> 1 d[ureg.lb / ureg.ft ** 3]

KeyError: <Unit('pound / foot ** 3')>
```

I understand that `Quantity` instances are mutable; however, it seems that `Unit` instances are not. (I have not yet checked the source code.)

What do I not understand about `Unit` instances and dictionaries?

**Comment by cpascual** [comment]
I guess it all boils down to the fact that:

```python
In [1]: from pint import UnitRegistry
In [2]: ureg = UnitRegistry()
In [3]: ureg.ft**3 is ureg.cu_ft
Out[3]: False
In [4]: ureg.ft**3 == ureg.cu_ft
Out[4]: False
```

**Comment by cpascual** [comment]
It depends on what you have in mind for that dictionary, but if all you care about from the keys is the dimensionality, you can do:

```python
In [1]: import pint
In [2]: ureg = pint.UnitRegistry()
In [3]: d = {(ureg.lb / ureg.cu_ft).dimensionality: 'mass-per-volume'}
In [4]: d[(ureg.lb / ureg.cu_ft).dimensionality]
Out[4]: 'mass-per-volume'
In [5]: d[(ureg.lb / ureg.ft**3).dimensionality]
Out[5]: 'mass-per-volume'
```

**Comment by keewis** [comment]
just note that instead of `id` (compared using `is`) the important property is `hash(obj)`:
```python
In [2]: class wrapper:
   ...:     def __init__(self, obj):
   ...:         self.obj = obj
   ...: 
   ...:     def __hash__(self):
   ...:         return hash(obj)
   ...: 
   ...:     def __eq__(self, other):
   ...:         return self.obj == other
   ...: 
   ...: 
   ...: obj = ("abc", 0)
   ...: display(obj is wrapper(obj))
   ...: display({wrapper(obj): "a"}[obj])
False
'a'
```
this also means that in theory you could write a `__hash__` that will return `hash(self.obj.dimensionality)` and have `__eq__` take units and compare quantities:
```python
In [10]: ureg.ft ** 3 == ureg.cu_ft
Out[10]: False

In [11]: 1 * ureg.ft ** 3 == 1 * ureg.cu_ft
Out[11]: True
```
It's probably better to use the dimensionality directly, though.

**Comment by mrwizard82d1** [comment]
In my use case, I need more than dimensionality since I typically have both metric measurements (kg / m ** 3) and (lb / ft ** 3) in the same dictionary. 

I can understand `is()` returning false for `cu_ft` and for `ft ** 3`; I had expected that these two "synonyms" would have the same value returned by `hash()`. I know I'm thinking of the problem from the "human/engineer/scientist" point of view, but I understand that providing the illusion that these units are "the same" is not at all easy for a computer.

**Comment by hgrecco** [comment]
@cpascual and @keewis explained quite clearly. You need a specialized dict for this. My suggestion would be to do something like this: https://stackoverflow.com/questions/2082152/case-insensitive-dictionary

but storing everything as root units.
