### ISSUE TITLE
Kitchen calculations

### ISSUE THREAD

**Issue by cabiad** [hgrecco/pint#1249]
Hi!

`pint` is one of the things I love most about Python. It's there when you need it, has a simple and beautiful API, and it works reliably. Thank you for it!

Lately, I've been using `pint` for kitchen calculations and noticed that its kitchen units make the default assumption that you want [USCS / "US customary" volumes for these units](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L561).

```python
In: (1 * ureg.cup).to("ml")
Out: 236.58823649999994 <Unit('milliliter')>
```

This might be the most common case (?), but where I live and in many other situations, common unit names like "teaspoons", "tablespoons", and "cups" have different commonly-accepted values.

For example, a "cup" may mean:

1. US customary - 236.5882365 millilitres (what pint uses)
2. US "legal" - 240 millilitres (req'd def'n for nutrition labelling in the US)
3. "metric" in UK, Australia, Canada, New Zealand, etc - 250 millilitres
4. in Japan - 200 millilitres

You can see these and more in the super-exciting Wikipedia article for [Cup (unit)](https://en.wikipedia.org/wiki/Cup_(unit)). Don't even get me started on Australian tablespoons! 😜

I certainly recognize that `pint` offers several great ways to set up my own context with measurements just the way I want them. That said, the default assumption that "cup" means "US customary cup" might not be obvious and cause incorrect results for the `pint`'s users (as it did me).

Would there be any interest in fleshing out the kitchen measurements in `pint` itself with the metric and other versions, and possibly removing the default assumption about these units being US customary volumes? If so, how can I help?

**Comment by hgrecco** [comment]
Wow! This is the first time that I hear about this. I would be in favor of changing this and making metric the default one with the following comments:
1.- For the next release, we create distinct contexts for each of these definitions (including US customary) but keep US customary as default one
2.- In the subsequent release we shift the default to the metric

**Comment by hgrecco** [comment]
I am closing this for the time being. Feel free to reopen if needed.

**Comment by cabiad** [comment]
Understood. Entirely reasonable. I will gladly re-visit should the opportunity arise again.
