### ISSUE TITLE
Extract SI prefix from a unit

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1256]
Is it possible to separate a unit into its Si prefix and its "base" unit (for example separate "millivolt" into "milli" and "volt"). I can't see a way to do this in any of the standard functiions. I thought to_reduced_units() might do the trick, but it appears not. I don't want to change to base SI units, just to change into the non-prefixed unit.

**Comment by jules-ch** [comment]
The api you're looking for is `ureg.parse_units()`

**Comment by edmundsj** [comment]
Yup! That appears to do it. Thanks! Is there also a function that takes the string 'milli' and converts it into a magnitude (I'm looking for a floating-point value). Is iterating through the ureg._prefixes dict the best way to do it?

**Comment by jules-ch** [comment]
If you want to change your magnitude, Quantities do that out of the box:

```python
from pint import UnitRegistry

ureg = UnitRegistry()

electric_tension = 1 * ureg.V
electric_tension.to("millivolt")
1000.0 millivolt
electric_tension.m_as("millivolt")
1000.0
electric_tension.to("millivolt").magintude
1000.0
```

Maybe those does not cover your use case.
Can you explain what you want to achieve?

**Comment by edmundsj** [comment]
I believe this does not quite cover my use case, which I will explain briefly:

I have a bunch of saved data with a bunch of _different_ units (mA, mV, uV, kOhm, etc). I want to generate some power spectral density plots of these data in a programmatic way in terms of standard units (dBA, dBV, dBOhm). I don't know for any given file whether the unit will be mA, kOhm, nV, or whatever, and I want this to work for all possible cases. So I want to take a unit, split it into its prefix and 'base' unit (kOhm -> 1000 * Ohm, or mV -> 1e-3 * Volt) and then convert that quantity into its logarithmic unit (1000 dBOhm -> 60dBOhm, 1e-3 * Volt -> -60dBV). So I need a way of converting an arbitrary SI unit into one with magnitude 1, and a way of extracting what the magnitude of the original prefix was.

**Comment by jules-ch** [comment]
```python
logarithmic_units = {
    "ampere": "dBA",
    "volt": "dBV",
    "ohm": "dBohm",
}

ureg.define("decibelvolt = 1 volt; logbase: 10; logfactor: 20 = dBV")
ureg.define("decibelampere = 1 ampere; logbase: 10; logfactor: 20 = dBA")
ureg.define("decibelohm = 1 ohm; logbase: 10; logfactor: 20 = dBohm")


def get_logarithmic_quantity(unit: str):
    """convert to logarithmic unit mapping base unit to dB counterpart"""

    (prefix, base_unit, _) = ureg.parse_unit_name(unit, case_sensitive=False)[0]
    quantity = ureg.Quantity(1, unit).to(base_unit)
    log_base_quantity = quantity.to(logarithmic_units[base_unit])

    return log_base_quantity


>>> get_logarithmic_quantity('mV'):~.2f}"
'-60.00 dBV'

>>> get_logarithmic_quantity('kohm'):~.2f}"
'60.00 dBohm'
```

Something like this will work for you.

**Comment by edmundsj** [comment]
Absolutely gorgeous. Thanks!
