### ISSUE TITLE
Define Personal Set of base units

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1257]
Is it possible to set a different set of base units than the ones provided by default? I'm an electrical engineer, and in my world, the base units are the Volt, second, Ampere, and some other less-important ones. Is it possible to do something like:

```
ureg.setBaseUnits(ureg.V, ureg.s, ureg.A, ureg.IDontCareWhatTheOthersAreFigureThemOutPls)
```

**Comment by hgrecco** [comment]
Not like that, but you can rewrite your definition file as will! It is fully flexible.
