### ISSUE TITLE
Pickle error with Spyder

### ISSUE THREAD

**Issue by puastro** [hgrecco/pint#1262]
I'm having some trouble with pint in Spyder when I try to open a class in the variable explorer.  I've posted on the spyder project and talked with one of the developers. (See here https://github.com/spyder-ide/spyder/issues/14900).  It seems my issue isn't with spyder, but with python itself and how it handles weakref.

There are no errors at runtime, but I get this error in iPython if I try to open the class in the variable explorer window, "TypeError: cannot pickle 'weakref' object".

I'm attaching a MWE showing 4 test classes where I'm running into trouble.  The only way I can not have the pickling error is if I pass ureg into the class and not save it to self.ureg.  That is demonstrated in TestClass1 and it allows me to look into tc1 after running the code.

is this something I have set up or done incorrectly?

[MWE.txt](https://github.com/hgrecco/pint/files/6118656/MWE.txt)

**Comment by hgrecco** [comment]
I think this is solved.
