### ISSUE TITLE
np.testing.assert_equal does not work with quantity lists

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1272]
When creating a list of quantities from a numpy array, numpy's built-in test methods for array comparison no longer work. This is breaking a lot of my test suite now that I am trying to incorporate pint's unit capabilities into my packages. Is there an easy way around this, or am I just going to have to write a wrapper function and swap it out for numpy's?

```
import pint
import numpy as np


ureg = pint.UnitRegistry()
data = ureg.mV * np.array([1, 2, 3])
np.testing.assert_equal(data, data) # This fails

```

**Comment by andrewgsavage** [comment]
There's some helper functions in the testsuite
```
from pint.testsuite import helpers
helpers.assert_quantity_equal(x, y)
```

**Comment by hgrecco** [comment]
I was also starting to look into this. Any idea what triggered this?

**Comment by edmundsj** [comment]
It looks like numpy fails to recognize the item as a list, and so doesn't invoke all() appropriately. I see there has been discussion of this for a while (https://github.com/hgrecco/pint/issues/1128)

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by hgrecco** [comment]
Yes, but you mentioned that is working before. That is what surprised me.

**Comment by keewis** [comment]
looking at the code of `assert_equal` it seems that there is a special case for `ndarray`, in which case `assert_array_equal` is used. If we directly use `numpy.testing.assert_array_equal` that casts to `numpy` using `asarray`.

I think for testing it would be good to expose `pint.testsuite.helpers.assert_quantity_equal` as `pint.testing.assert_equal`.

**Comment by edmundsj** [comment]
> Yes, but you mentioned that is working before. That is what surprised me.

Ah! Apologies, not working with pint, but working with regular arrays of dimensionless numbers.

**Comment by hgrecco** [comment]
Ahh, ok. Then as mentioned by @andrewgsavage and @keewis  mentions we should expose and document `assert_quantity_equal` (and `assert_quantity_almost_equal`) which work like the corresponding numpy counterparts but deal with unit conversions.

**Comment by keewis** [comment]
following `numpy.testing`, `assert_quantity_almost_equal` should be exposed as `pint.testing.assert_allclose`

**Comment by hgrecco** [comment]
True (see https://github.com/numpy/numpy/blob/v1.20.0/numpy/testing/_private/utils.py#L936 )

My recomendation is tha we double check  the implementation of `assert_quantity_almost_equal` so tha it follows the semantics of `assert_allclose`.
If yes, then we expose `assert_quantity_almost_equal` as `assert_allclose` 
If no, then we define `assert_allclose` to match the semantics of numpy.
