### ISSUE TITLE
Remove "The unit of the quantity is stripped when downcasting to ndarray." warning when quantity is dimensionless

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1276]
Much of my time over the last day has been spent tracking down and eliminating these annoying warnings. I regularly use numpy, pandas, and pint, and often switch back and forth between using quantities and regular numpy arrays. Usually, this is something like:

```
numpy_array *= np.sin(time * frequency)
```
When ``time*frequency`` has the wrong units, I get a REALLY helpful error which has helped me track down several bugs now. However, when the quantity involved (time * frequency) is unitless, I still get a UnitStripped warning, because a Quantity (``np.sin(time*frequency)``) is being downcasted to an ``np.ndarray`` to perform the multiplication. It seems to me if the unit is dimensionless this warning should be suppressed. There's no unit being stripped - the quantity is dimensionless.

**Comment by hgrecco** [comment]
Can you show a full example?

**Comment by edmundsj** [comment]
```
import pint
import numpy as np
q = pint.Quantity(1)
np.array([q])
```

Gives the following warning:
```
__main__:1: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
array([1])
```
While technically (I imagine) the correct behavior, it seems unnecessary when the quantity is dimensionless (although if dimensionless units are implemented, probably less so).
