### ISSUE TITLE
Measurements supports arrays

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#128]
Both of the following fail:

```
x = ([3,3]*ureg.m).plus_minus([1,1])
x = ([3,3]*ureg.m).plus_minus(1)
```

**Comment by knly** [comment]
How do you work with arrays of data and their associated errors in the current implementation of Pint (v0.7.2)?

I would like to do something like this:

```python
data = np.loadtxt('data.txt')
t = (data[:,0] * units.seconds).plus_minus(data[:,1])
```

Is something of this sort possible already, or are there plans to implement this?

**Comment by hgrecco** [comment]
0.7 was focus in getting support for systems. I would be very much like to make 0.8 about uncertainties and logarithmic units. I think we need to come up with good semantics that are also able to deal with #348

**Comment by knly** [comment]
@hgrecco Since `Quantity.magnitude` can hold an `uncertainties.unumpy.uarray`, this worked surprisingly well:

```python
import uncertainties.unumpy as unp
t = Q_(unp.uarray(data[:,0], data[:,1]), units.seconds)
```

There are no `Measurement` objects involved, though, so would you recommend to _not_ use this code in my code?

FYI: I am working on a university course where I want to show some _best practice_ code for working with uncertainties and units. Would you advise to wait for the 0.8 release for this?

**Comment by hgrecco** [comment]
@knly That is indeed correct and might be path we choose at the end so as an internal representation. In other words
```python
x = ([3,3]*ureg.m).plus_minus([1,1])
```
might be internally treated as:
```python
x = Q_(unp.uarray([3, 3], [1, 1]), units.meter)
```

But we need to make sure this idea is compatible with all other features of Pint


But I think there are a few things to iron out regarding and I cannot tell you that this is the final solution

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if neeeded.

**Comment by crusaderky** [comment]
@hgrecco why has this been closed?

**Comment by hgrecco** [comment]
I think that the whole Measurements experience requires a discussion in one place. In particular, we need a redesign.
