### ISSUE TITLE
How to avoid expression evaluation?

### ISSUE THREAD

**Issue by XtremeGood** [hgrecco/pint#1281]
I want to use pint for automatic doc creation. I want to show sample calculations, and thus I also need to show intermediary steps. How to avoid evaluation of expression after parsing? In the second step I need the computed value.So the output in the image is desired to be the third one. I need the unevaluated expression in latex form first. Also how to shorten liter to l, meter^3 to m^3

```
expr = ureg("35 l / (56 m**3)" )
            
md(f"Volume of sample taken at each time interval ($V_2$) =  ${expr:L}$"  )
```
![image](https://user-images.githubusercontent.com/40588378/113281183-d81e1580-9302-11eb-857b-d2374e8d1806.png)

**Comment by hgrecco** [comment]
We do not have a way to do this. The easier way would be to use Fraction as magnitude or to create two separate quantities
