### ISSUE TITLE
Get ureg.wraps to work with np.vectorize

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1283]
I am trying to use np.vectorize to vectorize a function I use. However, when I try to wrap that with ureg.wraps, I get the following error: 

```
*** AttributeError: 'vectorize' object has no attribute '__name__'
```

What I want is for pint to return a function which is vectorized and gives me a list of quantities

(non)-working example:
```
import pint
import numpy

ureg = pint.UnitRegistry()

def my_func(x):
    return x * x

my_func_vectorized = np.vectorize(my_func)
my_func_wrapped = ureg.wraps(ureg.s, ureg.s ** 2, False)(my_func_vectorized)

```

(non)-working test:
```
input_vals = 1 * ureg.s * np.array([1, 2])
desired_vals = 1 * ureg.s ** 2 * np.array([1, 4])
actual_vals = my_func_wrapped(input_vals)

assert_equal(actual_vals, desired_vals)
```

When the followi

**Comment by lnmaurer** [comment]
I'm running into the same issue. I don't think that the AttributeError is the fundamental issue; it seems to be an error in creating an error message:

> /usr/lib/python3/dist-packages/pint/registry_helpers.py in decorator(func)
>     260             raise TypeError(
>     261                 "%s takes %i parameters, but %i units were passed"
> --> 262                 % (func.__name__, count_params, len(args))
>     263             )
>     264 

So, the fundamental error is a TypeError due to some type of mismatch in the number of parameters and units. I'm not sure why there's a mismatch, but maybe that gives someone an idea for what's going on.

**Comment by lnmaurer** [comment]
Oh, I think that I understand the issue. vectorize returns an object with a `__call__` method (i.e. a functor), and the first argument to `__call__` is `self`. This extra argument probably throws off pint. A hacky solution is to give a lambda to `ureg.wraps` like so:

```import pint
import numpy as np

ureg = pint.UnitRegistry()

def my_func(x):
    return x * x

my_func_vectorized = np.vectorize(my_func)
my_func_wrapped = ureg.wraps(ureg.s, ureg.s ** 2, False)(lambda x: my_func_vectorized(x))```

Kind of hacky, but it seems to work.

pint developers, is there some way to make ureg.wraps play nice with functors?

**Comment by hgrecco** [comment]
Linking this to #1753
