### ISSUE TITLE
Where is the pint API? Please add link on main documentation page

### ISSUE THREAD

**Issue by edmundsj** [hgrecco/pint#1284]
Every time I search the pint docs, I cannot for the life of me find a complete API reference. For example, right now I am looking for the testing functions available via pint and cannot find them. I found it once, and I really should bookmark it. EDIT: I have since found it [here](https://pint.readthedocs.io/en/stable/developers_reference.html).

What I expect, as a developer, is on the left-hand side under the "About Pint" section to see something along the lines of "Developer Reference" or "API". I don't see any such link, and it was incredibly frustrating to find the one time I managed to find it. I expect to see it regardless of the page I am on in the documentation. For example, on [numpy's documentation](https://numpy.org/devdocs/) there is a nice big juicy "API Reference" prominently displayed at the top of the page near the menu. Same with [pandas](https://pandas.pydata.org/pandas-docs/stable/) and [matplotlib](https://matplotlib.org/stable/contents.html) Please add this :) Thanks!

**Comment by TomNicholas** [comment]
+1 to this - I also find it really frustrating when trying to do development work that involves pint. Developer documentation should also ideally include textual sections aimed at a more advanced audience, describing things like the class hierarchy, for example.

**Comment by jthielen** [comment]
This would be a critical component to include with the doc updates of https://github.com/hgrecco/pint/issues/972, though, would there be an easy way to have a stop-gap fix in the current theme configuration now?

**Comment by jules-ch** [comment]
I'll see what I can do.
We're gonna have to work on the new documentation.

**Comment by TomNicholas** [comment]
Thanks @jthielen - even just making a developers page with links to other pages with things like the class heirarchy would be helpful for now!

**Comment by andrewgsavage** [comment]
this exists now
