### ISSUE TITLE
How to use pint with scipy?

### ISSUE THREAD

**Issue by Teut2711** [hgrecco/pint#1286]
I want to use scipy's ode integration technique (`scipy.integrate.RK45`) . So the initial value vector `y0` uses a numpy  array with different units.  But during this operation the units gets stripped.  Code:  https://dpaste.org/bfDv

**Comment by dalito** [comment]
The linked code is no longer available. 

You should be able to use [wrapping](https://pint.readthedocs.io/en/stable/wrapping.html) to make scipy functions unit aware.

**Comment by XtremeGood** [comment]
yes , this was the solution I was looking for.  Thanks @dalito
