### ISSUE TITLE
Language format error

### ISSUE THREAD

**Issue by juandadamo** [hgrecco/pint#1296]
When defining a variable with temperature units in its denominator (ie Kelvin**-1) there is an error due to language format . I test this in spanish and in french with the same output.

`import pint
ureg = pint.UnitRegistry(fmt_locale='es_ES')
h = 400 * ureg.watt/ureg.K/ureg.m**2
print(h)`

the output is
`TypeError                                 Traceback (most recent call last)
<ipython-input-7-13694e348097> in <module>
      1 h = 400 * ureg.watt/ureg.K/ureg.m**2
----> 2 print(h)

~/.local/lib/python3.8/site-packages/pint/quantity.py in __str__(self)
    284     def __str__(self):
    285         if self._REGISTRY.fmt_locale is not None:
--> 286             return self.format_babel()
    287 
    288         return format(self)

~/.local/lib/python3.8/site-packages/pint/quantity.py in format_babel(self, spec, **kwspec)
    429         return "{} {}".format(
    430             format(obj.magnitude, remove_custom_flags(spec)),
--> 431             obj.units.format_babel(spec, **kwspec),
    432         ).replace("\n", "")
    433 

~/.local/lib/python3.8/site-packages/pint/unit.py in format_babel(self, spec, **kwspec)
    110             units = self._units
    111 
--> 112         return "%s" % (units.format_babel(spec, **kwspec))
    113 
    114     @property

~/.local/lib/python3.8/site-packages/pint/util.py in format_babel(self, spec, **kwspec)
    454 
    455     def format_babel(self, spec, **kwspec):
--> 456         return format_unit(self, spec, **kwspec)
    457 
    458     def __copy__(self):

~/.local/lib/python3.8/site-packages/pint/formatting.py in format_unit(unit, spec, **kwspec)
    278     else:
    279         # HTML and Text
--> 280         return formatter(unit.items(), **fmt)
    281 
    282 

~/.local/lib/python3.8/site-packages/pint/formatting.py in formatter(items, as_ratio, single_denominator, product_fmt, division_fmt, power_fmt, parentheses_fmt, exp_call, locale, babel_length, babel_plural_form, sort)
    231             neg_ret = parentheses_fmt.format(neg_ret)
    232     else:
--> 233         neg_ret = _join(division_fmt, neg_terms)
    234 
    235     return _join(division_fmt, [pos_ret, neg_ret])

~/.local/lib/python3.8/site-packages/pint/formatting.py in _join(fmt, iterable)
     38     if not iterable:
     39         return ""
---> 40     if not __JOIN_REG_EXP.search(fmt):
     41         return fmt.join(iterable)
     42     miter = iter(iterable)

TypeError: expected string or bytes-like object`

**Comment by jules-ch** [comment]
The current version of pint does not handle Babel >= 2.9

There is a regression on the babel side, we can lock babel version < 2.9 in the meantime

**Comment by keewis** [comment]
as an aside, in `xarray` we've been running a scheduled CI using development versions of upstream libraries, and have it open a new issue for failed runs. Since I think this would have been caught by such a CI: should we add something like that here, too?

**Comment by jules-ch** [comment]
I'll close in favour of #1219
