### ISSUE TITLE
make UnitRegistry.__call__ call parse_units

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1297]
From #1295: right now, `ureg("m / s ** 2")` returns a `Quantity` because `UnitRegistry.__call__` is a alias of `parse_expression`. I would argue that it should actually call `parse_units` and return a `Unit` object.

Since this is a breaking change: what do you think about deprecating the current behavior in favor of making it call `parse_units`?

**Comment by hgrecco** [comment]
This is a large breaking change. I am principle against this without a very good reason.

**Comment by keewis** [comment]
fair enough. I still think that we should require explicit use of `parse_expression` to parse expressions, but #1295 has been fixed since then so I can just avoid the use of `__call__`.

**Comment by keewis** [comment]
fair enough. I still think that we should require explicit use of `parse_expression` to parse expressions, but #1295 has been fixed since then so I can just avoid the use of `__call__`.
