### ISSUE TITLE
"Redefining" warning raised when @alias being added

### ISSUE THREAD

**Issue by stringfellow** [hgrecco/pint#1304]
When trying to add `@alias` definitions for particular units (see `degree_Celsius` example below), the registry warns of redefinition when it is just adding a new alias. This doesn't happen for all units, but not sure why (see `volt` example below).

## `degree_Celsius` example
```pycon
In [1]: import logging; logging.basicConfig(level=logging.DEBUG)

In [2]: from pint import UnitRegistry; ureg = UnitRegistry()

In [3]: ureg.parse_expression('degC')
Out[3]: 1 <Unit('degree_Celsius')>

In [4]: ureg.define('@alias degree_Celsius = Deg_C')
WARNING:pint.util:Redefining 'degree_Celsius' (<class 'pint.definitions.UnitDefinition'>)
WARNING:pint.util:Redefining '°C' (<class 'pint.definitions.UnitDefinition'>)
WARNING:pint.util:Redefining 'celsius' (<class 'pint.definitions.UnitDefinition'>)
WARNING:pint.util:Redefining 'degC' (<class 'pint.definitions.UnitDefinition'>)
WARNING:pint.util:Redefining 'degreeC' (<class 'pint.definitions.UnitDefinition'>)
WARNING:pint.util:Redefining 'Deg_C' (<class 'pint.definitions.UnitDefinition'>)

In [5]: ureg.parse_expression('Deg_C')
Out[5]: 1 <Unit('degree_Celsius')>
```

## `volt` example
```pycon
In [1]: import logging; logging.basicConfig(level=logging.DEBUG)

In [2]: from pint import UnitRegistry; ureg = UnitRegistry()

...

In [20]: ureg.parse_expression('volt')
Out[20]: 1 <Unit('volt')>

In [21]: ureg.define('@alias volt = Volt = vlt = Vlt = v')

In [22]: ureg.parse_expression('Vlt')
Out[22]: 1 <Unit('volt')>
```

**Comment by lukelbd** [comment]
Also encountered this error. Looks like `UnitRegistry(on_redefinition='ignore')` is another possible workaround (although warnings due to legitimately redefined variables are then also ignored).

**Comment by hgrecco** [comment]
Can you tell me the pint version?

**Comment by lukelbd** [comment]
It's the most recent version: 0.19.2

Also this issue doesn't happen out of the box -- it only happens if `logging.basicConfig()` is called first (don't really understand why though). In my case another module I was importing was doing this.

**Comment by hgrecco** [comment]
In the current master branch this does not happen any more ... but there is also no warning when you redefine an existing alias. I am marking this as a bug

**Comment by hgrecco** [comment]
I just pushed a commit to the develop branch that should do the trick. The only open question is if what we should do if we redefine something as the same unit. For example:

```python
ureg.parse_expression('Vlt')
ureg.parse_expression('Vlt')
```

What should happen in the second call? Options and rationale
- do nothing: we are not really redefining, so do nothing.
- warn/raise: we are not really redefining, but there is something fishy in the definition file.
- warn (same or different) but never raise: we are not really redefining, but there is something fishy in the definition file.

**Comment by lukelbd** [comment]
Thanks for the quick fix! Options 1 and 2 both make sense to me. Initially would lean toward option 2 since it seems simpler / more consistent (if the definition exists, follow the `on_redefinition` behavior, period). One caveat is that if someone wants to repeatedly run the same definition script while they are amending it (e.g., manually, or with ipython [`%autoreload`](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) magic) then option 2 will emit lots of warnings. But that's probably a bit of an edge case. Anyway your call of course.

**Comment by hgrecco** [comment]
Let's stick with 2 now that is the current behavior and let's see if in the future there are more reasons to change it (or not!). I would be great if you can install and test the current master (that I have just merged develop into it)
