### ISSUE TITLE
UnitRegistry.check and UnitRegistry.wraps decorators hide function type annotations from type checker

### ISSUE THREAD

**Issue by RobbinDG** [hgrecco/pint#1307]
If this request/issue has already been posted previously, my apologies. I have been unable to find a similar issue, but I may have simply missed it.

Hey everyone, 

While writing code in PyCharm, I noticed that PyCharms type checker is unable to verify types when a function is decorated with `UnitRegistry.check` or `wraps`. That is, if I have a function
```python
def test_func(variable: Q_):
    pass

test_func(Q_(10.0, ureg.kg))
test_func(10)
```
PyCharm warns me that, in the second call, the type provided is incorrect and should be `Q_` (`Quantity`). However, if I decorate `test_func` with `@ureg.check('[mass]')` to ensure the parameter has the correct quantity, I lose this warning. This likely is an issue with forwarding parameter specifications from the inner function to the decorator function. Although I am unsure if this can be fixed in python 3.9, python 3.10 (currently in beta) brings PEP 612 which introduces `ParamSpec`s which may introduce this useful functionality. 
I would personally love to see this feature, as I have become increasingly reliant on type verification and annotate effectively all my code with type hints.

**Comment by hgrecco** [comment]
Linking to #1753
