### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [hgrecco/pint#1308]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine pint/unit.py and observe `quanities`, however expect to see `quantities`.
- Examine pint/registry_helpers.py and observe `writen`, however expect to see `written`.
- Examine pint/testsuite/test_quantity.py and observe `resuls`, however expect to see `results`.
- Examine pint/measurement.py and observe `implimentation`, however expect to see `implementation`.
- Examine README.rst and observe `entusiasts`, however expect to see `enthusiasts`.
- Examine pint/registry.py and observe `dimenstions`, however expect to see `dimensions`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/pint/pull/new/bugfix_typos

Thanks.

**Comment by keewis** [comment]
thanks, @timgates42, that does look like a welcome improvement. Feel free to open a PR.

Note that CI should not be a concern for first-time contributors as the maintainers (i.e. @hgrecco) will have to review *before* any CI is run.

**Comment by timgates42** [comment]
Thanks @keewis have added a PR
