### ISSUE TITLE
Announcing Jules Cheron (@jules-ch) as Release Manager for Pint 0.18

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1312]
Congratulations @jules-ch and thanks for taking this role.

**Comment by hgrecco** [comment]
Already in the AUTHORS: cdf0a50f49c6ad55a77b312166d3803f17d3e618 Cannot be more official than that 😄

**Comment by hgrecco** [comment]
@jules-ch I have created the 0.18 milestone. Maybe you can start labeling some issues/PR with it so we can choose were to focus.

**Comment by jules-ch** [comment]
Hi, thanks @hgrecco. Can you give me permission to label issues, I don't think I can.
I'll do a quick clean up also, a lot of issues has been fixed over the past months / years.
