### ISSUE TITLE
Wrong Image

### ISSUE THREAD

**Issue by fbordignon** [hgrecco/pint#1320]
Every time I open the pint homepage I got annoyed by the image not resembling a proper pint :joy:
I know that the actual volume of the glass pictured can be of a pint, but the proportions are just wrong.
I propose a virtual toast :beers: with the beverage of choice to decide if it is proper to change the image.

**Comment by hgrecco** [comment]
I can stop laughing about this. If you find a nice image that we can use, I will be happy to use it.
