### ISSUE TITLE
Use pint with pytest.approx

### ISSUE THREAD

**Issue by mmarras** [hgrecco/pint#1323]
I was curious to know what the approach is to use pint in testing scripts?

I use pytest and often the `pytest.approx` function of the latter. Any recommendations on how to set tests up? Consider the simple case: I have a function which calculates a length, where I know that the expected length is `L=(114.4 +-0.1) cm`. 

Then I would do the following to test that my function which uses pint for unit representation checks out properly, where `type(calcualtedvalue) is pint.quantity.build_quantity_class.<locals>.Quantity`: 
```python
import pytest
import pint
...
def test_myfunc():
    assert calulatedvalue.to('cm').magnitude == pytest.approx(114.4,0.1)
```

Is this a good way? Most straight forward would be something like `assert calculatedvalue = pytest.approx(114.4,0.1) * ureg.cm` but `pint` does not work with `ApproxScalar`.

Any opinions or previous guidance on testing and pint - not testing pint?

**Comment by andrewgsavage** [comment]
Take a look at
https://github.com/hgrecco/pint/blob/master/pint/testsuite/helpers.py#L133

**Comment by mmarras** [comment]
Just for completeness, this is how I use @andrewgsavage's answer. Answers my question.
```python
from pint.testsuite.helpers import assert_quantity_almost_equal as assert_approx


def test_myfunc(calc_val_with_units, truth_val_with_units, relerror):
    #  use with rtol or atol for errors given in percent or absolute.
    assert_approx(calc_val_with_units, truth_val_with_units, rtol=relerror)
```
