### ISSUE TITLE
[question] making a unitless `Quantity` 

### ISSUE THREAD

**Issue by teauxfu** [hgrecco/pint#1333]
how does one define or use a unitless instance of `Quantity`?
as distinct from a `Quantity` of unit 'dimensionless' which is returned when no unit is specified
```py
assert Q_('1').units == Q_(1, None).units == ureg.dimensionless
```
the docs don't seem to mention their existence

I see that `Quantity` objects have a `unitless` property
https://github.com/hgrecco/pint/blob/9fc752c8e0720aa265a19490a9378e40ab096b0e/pint/quantity.py#L461-L464

but it seems only to be used within `Quantity` here in `to_compact`
https://github.com/hgrecco/pint/blob/9fc752c8e0720aa265a19490a9378e40ab096b0e/pint/quantity.py#L760-L766
and here
https://github.com/hgrecco/pint/blob/9fc752c8e0720aa265a19490a9378e40ab096b0e/pint/quantity.py#L1789-L1791

but after glancing about it's not apparent (to me) how one would even instantiate a unitless quantity, or otherwise what they'd be used for internally

I haven't yet fully inspected the `UnitsContainer` and its usage/references;
is the `unitless` property used when working with those?

possibly related #1277 regarding adding unitless dimensions

**Comment by keewis** [comment]
Could you explain what exactly you're seeing? `ureg("1")` returns a standard python `int` of value `1` for me, causing your `assert` line to fail with an `AttributeError`.

**Comment by teauxfu** [comment]
> Could you explain what exactly you're seeing? `ureg("1")` returns a standard python `int` of value `1` for me, causing your `assert` line to fail with an `AttributeError`.

you're right! my bad -- I'm getting used to the differences between using `Q_` vs `ureg` when making `Quantities`

what I meant to comment was 

```py
assert Q_('1').units == ureg.dimensionless
```

**Comment by hgrecco** [comment]
I do not follow. `Q_('1').units == Q_(1, None).units`. If you want somehing without a units fields, then you want a numeric object not a Quantity.

**Comment by coxipi** [comment]
I ran across a similar problem I think, I was expecting `pint.Quantity` as an output, but got an `int`.

```python
pint.__version__
type(pint.registry.UnitRegistry()("1")) # what I did
type(pint.registry.UnitRegistry()("1 dimensionless")) # what would work with the current way pint functions
>>> 0.24.3
>>> <class 'int'>
>>> <class 'pint.Quantity'>
```
I get your point about not using units fields if you know you have a numeric value, but it can be useful to treat numeric values as a Quantity with dimensionless units. It allows to have general functions where you don't need to know if the input is a numeric value, or some number with units. I am not so familiar with the inner workings of `pint`, and whether this might cause problems. But I just wanted to point out that I was also surprised by the way `pint` works in this instance.
