### ISSUE TITLE
Parsing of `√`

### ISSUE THREAD

**Issue by NicoWeio** [hgrecco/pint#1334]
I noticed that using the `√` character when creating a `ufloat` neither raises an error (or a warning), nor does what it should.

### Example

```python
print(f"{ureg('√s')=}")
print(f"{ureg('√(s)')=}")
print(f"{ureg('s^.5')=}")
```
gives
```
ureg('√s')=<Quantity(1, 'second')>
ureg('√(s)')=<Quantity(1, 'second')>
ureg('s^.5')=<Quantity(1.0, 'second ** 0.5')>
```

**Comment by ishigoya** [comment]
I'm still very new to the codebase, but it looks like `tokenize` is being used to parse the unit text.

I used the code below to compare the output of pint and `tokenize`:

```python
import pint
import tokenize
from io import BytesIO

u = pint.UnitRegistry()

def check_first_token(x):
    try:
        unit = u(x)
    except:
        unit = "failed to create unit"
    tokens = list(tokenize.tokenize(BytesIO(x.encode("utf-8")).readline))
    first_token_type = tokenize.tok_name[tokens[1].type]
    return (unit, first_token_type)

var1 = 'ﻰs'
var2 = '猫s'
var3 = "√s"
var4 = "'s"
var5 = "!s"
```

Testing each string gives:

```python
Ꮲ > check_first_token(var1)
('failed to create unit', 'NAME')
Ꮲ > check_first_token(var2)
('failed to create unit', 'NAME')
Ꮲ > check_first_token(var3)
(<Quantity(1, 'second')>, 'ERRORTOKEN')
Ꮲ > check_first_token(var4)
(<Quantity(1, 'second')>, 'ERRORTOKEN')
Ꮲ > check_first_token(var5)
(<Quantity(1, 'second')>, 'ERRORTOKEN')
```

It seems to me that all of the strings should fail by default, so the issue may be in the handling of these `ERRORTOKEN`s.

**Comment by hgrecco** [comment]
I think that the problem is how far should the `√` cover. I guess it should be 1 character unless it is a `(` and in that case until the next `)` 

In any case, you can use the `preprocessors` argument. See this [test](https://github.com/hgrecco/pint/blob/fe3e8f7f1ea3b27d6beeb52d44919c9cf6108bb0/pint/testsuite/test_unit.py#L354). This could  be also provided as a flag.
