### ISSUE TITLE
Quantity is Iterable but should not.

### ISSUE THREAD

**Issue by mmarras** [hgrecco/pint#1337]
pint: 0.17
numpy: 1.20.3
python: 3.9.1
________

I observe some inconsistency when testing for `Iterable`  on a `Quantity`.

```python
mylength = (4 * ureg.m)
iter(mylength)
```
\>>> TypeError: 'int' object is not iterable

BUT

```python
from collections.abc import Iterable
isinstance(mylength, Iterable)
```
\>>> True

**Comment by jules-ch** [comment]
There is no inconstitency there, `isinstance` is just checking if `__iter__` is implemented.

Since quantity is handling both iterable & non iterable this is excpeted

**Comment by jules-ch** [comment]
https://docs.python.org/3/library/collections.abc.html?highlight=iterable#collections.abc.Iterable

**Comment by mmarras** [comment]
Ok, now I understand. Thanks also for the link!
