### ISSUE TITLE
Suggestion for pint

### ISSUE THREAD

**Issue by cmcconomyfwig** [hgrecco/pint#1339]
Before officially submitting code, I wanted to get your impression of whether this would be compatible with your vision for Pint.

In your performance tuning section you mention wrapping, I have a similar concept that is a bit more global;
If you are the type of person that stores Dicts of constants, Dicts of value sets to pass around etc, you could instead optionally apply Pint to the dictionary while you're "working things out", then disable for your production code (and deal only with vanilla Magnitudes):

``` python
class OptionalPintDict:
    """
    Base class for creating dictionary of quantities. Use of Quantities is optional and can be turned off for performance.
    To use:
        * Create a subclass of OptionalPintDict [eg. "class MyClass(OptionalPintDict)"]
        * Declare member variables in your Dict definition, optionally with defaults
        * Populate '_unit_map' with a Dict with entries of {varname, unit}
        * If the instantiation parameter 'use_pint' is set to True (it is False by default), all units named in '_unit_map' will become quantities.
    """

    _unit_map: Dict[str, Unit]
    """Static map of member to Unit"""

    def _apply_units(self):
        for var, unit in self._unit_map.items():
            self.__setattr__(var, self.__getattribute__(var) * unit)

    def __init__(self, use_pint: bool = False, **kwargs):
        self._use_pint = use_pint

        my_public_keys = list(filter(lambda n: n[0] != '_', dir(self)))
        # Sets variables that are passed in
        for key in kwargs:
            if key in my_public_keys:
                self.__setattr__(key, kwargs[key])

        if use_pint:
            self._apply_units()
```

This could be used as follows:

``` python
class GlobalParams(OptionalPintDict):
    """
    Contains parameters that remain constant over the life of the run.
    """
    AMBIENT_TEMP: float = 305  # = 32C
    """(deg K)."""
    WIND_SPEED: float = 8.333  # 30 km/h 
    """(m/s)."""
    HEAT_COEFF: float = 11e6
    """(J/kg). Amount of heat per kg"""

    _unit_map: Dict[str, Unit] = {
        'AMBIENT_TEMP': _ureg.kelvin,
        'WIND_SPEED': _ureg.meters / _ureg.seconds,
        'HEAT_COEFF': _ureg.joules / _ureg.kilograms
    }
```
(where _ureg is defined at the top of the python file, `_ureg = pint.get_application_registry()`)

You get a "Pint Dict" by calling `gp = GlobalParams(use_pint=True)`, and you get a magnitude-only vanilla Dict with `gv = GlobalParams()`

Would you be interested in a PR?

**Comment by hgrecco** [comment]
I do not understand completely the code.  Can you show how you will use `GlobalParams` ?

**Comment by burnpanck** [comment]
IMHO, that seems relatively far off from Pint's scope.

**Comment by jules-ch** [comment]
As @hgrecco & @burnpanck said, it seems outside of Pint scope.
Thanks for asking feedback on this, but we won't implement this in Pint.
Do not hesitate to keep submitting new ideas though, thats how pint is evolving & going forward. :)
