### ISSUE TITLE
default_format for omitting units

### ISSUE THREAD

**Issue by JonesKenzie** [hgrecco/pint#1343]
Hello, 

I'm using pint for an automating reporting tool and most of the units printed there should be omitted because they are referenced on the tables. I tried using default_format but couldn't figure out which one to use to omit .

Does this exists or need to be implemented?

**Comment by jules-ch** [comment]
Can you show us an example of what you expect?

**Comment by JonesKenzie** [comment]
Yes sure:

** INPUT **
```
ureg = pint.UnitRegistry()
ureg.default_format = "magnitude" # I don't know it could be other stuff

print(ureg.Quantity(1,"m"))

```

 **OUTPUT** 
```
>>>   raise ValueError("Unknown conversion specified " + ch)
ValueError: Unknown conversion specified t
```

**Expected**
```
>>> 1
```

**Comment by jules-ch** [comment]
If you just want the magnitude you can use the magnitude property :
```python
ureg = pint.UnitRegistry()
quantity = ureg.Quantity(1,"m")
print(quantity.magnitude)

>>> 1

print("{:.4f}".format(quantity.magnitude))

>>> 1.0000

**Comment by jules-ch** [comment]
default format is used only to change formatting of the units, if you only want the magnitude, just use the magnitude property.

**Comment by JonesKenzie** [comment]
The idea is to add this functionality to Jinja2. What I did is a custom filter, but to omit the units I need to use this filter.

```
def convert_to(quantity, unit=None, uformat = ":"):

    if unit is not None:
        result = quantity.to(unit)
    else:
        result = quantity
    if ("~" not in uformat) and ("P" not in uformat):

        s = "{"+"0.magnitude{0}".format(uformat)+"}"
    else:
        s = "{"+"{0}".format(uformat)+"}"
    return s.format(result)
```

**Comment by hgrecco** [comment]
Formatting is used to configure the way the complete quantity (and its parts) are printed. Take a look at the string formatting operations https://pint.readthedocs.io/en/stable/tutorial.html#string-formatting.

**Comment by JonesKenzie** [comment]
Hello @hgrecco , I understand how you designed the formatting strings to show all the parts. I just think it would be a nice feature to have to be able to hide by default the units. In some cases, when showing tables for example, it would be cool to hide units, because there are no need to repeat them all over again. Am I missing something?

**Comment by hgrecco** [comment]
I would something like this:
```jinja
<table>
<tr>Height [m]</tr>
{% for q in qs %}
<tr>
   <td>{{ q.m_as("meter") }}</td>
</tr>
{% endfor %}
</table>

```

**Comment by jules-ch** [comment]
Closing this, feel free to reopen if this is still unclear.
