### ISSUE TITLE
Pint does not play well with dark mode

### ISSUE THREAD

**Issue by igurin-invn** [hgrecco/pint#1346]
I'm using Spyder 5.0.5 with a dark theme. Pint's prettyprinted output displays as black on dark, which is hard to read. Can we get a global variable or something to invert the display color?

**Comment by jules-ch** [comment]
Are you talking about HTML or LATEX representation ?

**Comment by igurin-invn** [comment]
You know, I'm not sure. How do I find out?

**Comment by jules-ch** [comment]
Well give us some infos, because just like that we can not help you.

Do you have steps to reproduce ?

**Comment by igurin-invn** [comment]
I don't know about HTML and LaTeX representations. (This is something I've found about the online documentation: it's good as a tutorial, but it's not comprehensive.) But here's what I did.

1) Open Spyder
2) Set a dark theme (any dark theme seems to give the same results)
3) Create a Quantity, such as:
```
import pint
ureg = pint.UnitRegistry()
ureg('3 m')
```

![image](https://user-images.githubusercontent.com/53919701/125985530-9020c6d6-ac7c-49d6-b613-618850def8ca.png)

**Comment by charliefortner** [comment]
I'm having the same issue. I can't see the units in a dark theme and I can't figure out how to change the behavior of pint.

Here's how 3 m looks in a dark theme:
![pint_dark](https://user-images.githubusercontent.com/52753034/131228993-88050c1f-0337-467f-b2d5-b508922bb64d.png)

Here's the same but in a light theme:
![pint_light](https://user-images.githubusercontent.com/52753034/131228946-635644e8-6ec9-4be3-9895-d3530cae1da6.png)
