### ISSUE TITLE
How to get base numbers from quantities consistently, efficiently and safely?

### ISSUE THREAD

**Issue by burnpanck** [hgrecco/pint#1348]
People use `.magnitude` when they need a number e.g. for an external function or an inherently dimensionless argument (e.g. to an exponential function). Unfortunately, I see too much code where the unit information is silently discarded rather than ensured, defeating the purpose of using a units package (making things worse, as the use of units suggests units awareness, while the implementation in fact isn't).

I am aware of [wrapping](https://pint.readthedocs.io/en/stable/wrapping.html) as a good method to avoid the need to remove units in the first place, but in some case, that is not easily possible, e.g. because the source is out of the users control.

In that case, a safe and consistent way to get a number in a specific unit is to do `quantity.to(some_unit).magnitude`. This is explicit in the unit of the returned number - unfortunately, people sometimes tend leave out the call to `.to` ("it _works_ without `.to`"). I'm therefore looking for a method like `quantity.magnitude_in(some_unit)`, so we can teach a rule to avoid bare `.magnitude` except for very specific cases.

There is a common special case for when `some_unit` is `u.dimensionless`. In that case, for a scalar, `float(dimensionless_quantity)` is safe and efficient (it will properly convert to base units and raise an error if it is not dimensionless). However, it doesn't work for numpy arrays, and the equivalent of `np.array(dimensionless_quantity)` is not safe (it will not convert to base units, but simply strip). Therefore, a method like `.to_dimless_number()` or similar that works for both scalars and arrays would be great.

Is an equivalent of either of these already available? If yes, the documentation should probably be improved to point to them (I couldn't find them). If not, would you agree in having such methods? While the difference in typing compared with `.to(some_unit).magnitude` is minimal, I believe there is value in a direct method for teaching purposes - combined with the right documentation. Either way, I'm willing to contribute a PR to that effect.

**Comment by dopplershift** [comment]
`Quantity.m_as()` I think is what you're looking for.

**Comment by burnpanck** [comment]
Indeed, I didn't know that one, thanks for pointing out! Is there also a convenience shortcut for `dimensionless` by chance?

**Comment by burnpanck** [comment]
I wasn't aware of that either. Thanks a lot!
