### ISSUE TITLE
numpy_func.implements question

### ISSUE THREAD

**Issue by marouane-miftah** [hgrecco/pint#1355]
Versions:

- Python 3.9.6
- pint       0.17 
- numpy  1.21.1

the following piece of code

```
import numpy
import pint


def func(a, increment):
    return numpy.floor(a + increment)


@pint.numpy_func.implements("func", "ufunc")
def _pint_func(a: pint.Quantity, increment):
    return a._REGISTRY.Quantity(func(a.magnitude, increment), a.units)


ureg = pint.UnitRegistry(["foo = [d]"])
out = func(ureg.Quantity(512.34, "foo"), 3)
```

is throwing the following stack trace:

```
Traceback (most recent call last):
  File "/miniconda3/envs/x/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ea7fe97e3cb8>", line 1, in <module>
    runfile('/Library/Preferences/PyCharm/scratches/scratch2.py', wdir='/Library/Preferences/PyCharm/scratches')
  File "/Applications/PyCharm Pro.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm Pro.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Library/Preferences/PyCharm/scratches/scratch2.py", line 17, in <module>
    out = func(ureg.Quantity(512.34, "foo"), 3)
  File "/Library/Preferences/PyCharm/scratches/scratch2.py", line 7, in func
    return numpy.floor(a + increment)
  File "/miniconda3/envs/x/lib/python3.9/site-packages/pint/quantity.py", line 1078, in __add__
    return self._add_sub(other, operator.add)
  File "/miniconda3/envs/x/lib/python3.9/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/miniconda3/envs/x/lib/python3.9/site-packages/pint/quantity.py", line 984, in _add_sub
    raise DimensionalityError(self._units, "dimensionless")
pint.errors.DimensionalityError: Cannot convert from 'foo' to 'dimensionless'
```

Does anyone see where I am going wrong here.

Thank you.

**Comment by crusaderky** [comment]
You should use ``@pint.numpy_func.implements(<name>, "ufunc")`` only for actual numpy ufuncs, such as those you create with ``@numba.vectorize`` and ``@numba.guvectorize``.
For everything else, such as your pure-python function, just use an if statement:

```python
def func(a, increment):
    if isinstance(a, pint.Quantity):
        return a._REGISTRY.Quantity(func(a.magnitude, increment), a.units)
    return numpy.floor(a + increment)
```

**Comment by crusaderky** [comment]
P.S. I would seriously question on why you want to circumvent pints dimensionality check and you're adding a pure number to a quantity. If you KNOW that increment can be added to a without conversion, then you also know its units and you should wrap it into a Quantity. If you can't be certain of increment's dimensionality, then you're adding apples and oranges.

**Comment by marouane-miftah** [comment]
> P.S. I would seriously question why you want to circumvent pint's dimensionality check and add a pure number to a Quantity. If you _know_ that `increment` can be added to `a` without conversion, then you also know its units and you should wrap it into a Quantity. If you can't be certain of `increment`'s dimensionality, then you're adding apples and oranges.

@crusaderky Thank you for your answers.
This was just for the minimum reproducible example, the actual function does a bit more than just increment.
