### ISSUE TITLE
formats, documentation and custom formats

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1357]
I think there are several issues with unit formatting right now:

Related to xarray-contrib/pint-xarray#121: whenever I need to format units, rather than the documentation I tend to look through the source code of `pint.formatting`, especially `_FORMATS` is useful. This, I think, is because the documentation of the format values is hidden pretty well (the only mention I can find is in the tutorial which is incomplete, i.e. some of the formats and the quantity modifer `"#"` are never mentioned).

I also think the default format (`""` in `_FORMATS`) should get a actual name: if I set `UnitRegistry.default_format = "P"`, the "default format" as defined in `_FORMATS` is not accessible anymore until I set the registry's default back to `""`.

Finally, it would be great to have some kind of mechanism to register custom formats (we already can modify `pint.formatting._FORMATS`, but that's a implementation detail, right?). The syntax could be
```python
@pint.register_unit_format("xyz")
def format_units_xyz(units, modifier):
    ...
```
where the register function should make sure it does not overwrite already existing formats.

Not sure if it would be better to open separate issues for each of these, but I though it might make sense to consider them together.

**Comment by hgrecco** [comment]
I like this proposal. I was wondering for a time if there should provide some kind of templating engine but it way to broad, I think. So I then thought about allowing `default_format` to be a method but I like your idea better because it  allows you combine with the existing formats. I only think that we might consider having a `register_unit_format` and `register_quantity_format`.

**Comment by keewis** [comment]
great, I'll look into implementing `register_unit_format`, then (`register_quantity_format` would be a later PR, although I'm not sure what I would use it for). Should we also allow adding `dict`s like the existing ones in `_FORMATS`, or do we want to require `callable`s?

**Comment by hgrecco** [comment]
Regarding `register_quantity_format`, I think it could be useful for those wanting to modify the magnitude and its location relative to units.

Right now those dicts are the kw of `formatter`.  My guess is that "the right way" would be to reimplement the current formatters with your proposal (i.e. make any user defined format first class just as the pint ones).

So I think we could do something like this

```python
@pint.register_unit_format("P")
def format_units_pretty(units, modifier):
    ### SOME CODE 
    return formatter(units.items(), 
         as_ratio=True,
        single_denominator=False,
        product_fmt= "·",
        division_fmt= "/",
        power_fmt= "{}{}",
        parentheses_fmt= "({})",
        exp_call= _pretty_fmt_exponent,
    )
```

(I am not puting here the modifier for simplicity)
