### ISSUE TITLE
Error when trying to convert from byte to kilobyte

### ISSUE THREAD

**Issue by pr-ravi** [hgrecco/pint#1362]
I'm getting an error, 
"can't multiply sequence by non-int of type 'float' "

Code: 
` result = result.to(query['output_unit'])`

Here, 
`result = <Quantity(143610, 'byte')>`
and 
`query['output_unit'] = "kilobytes"`

The way I construct this quantity is by, 
`result = result * ureg(query['source_unit'])`
where 
`query['source_unit'] = "bytes"`

I've tried this outside of my script in a python shell, and it seems to be working fine.
Any idea on what could cause an error in this specific circumstance ?

**Comment by jules-ch** [comment]
This error comes when you are trying to multiply a sequence (tuple or list) by a float.

Do you have a minimal example to reproduce?

**Comment by pr-ravi** [comment]
This was a mistake on my part, the magnitude was of type string, rather than float. 
Closing the issue.
