### ISSUE TITLE
Feature request: option to disable units canceling?

### ISSUE THREAD

**Issue by emlys** [hgrecco/pint#1364]
Hello,
In some situations, units should not cancel out in division. For example, soil erodibility is measured in `t * ha * hr / (ha * MJ * mm)`. By convention the hectares are left on the top and bottom, to emphasize that it measures soil loss (in `t`) per unit area (in `ha`) per unit of storm erosivity (in `MJ * mm / (ha * hr)`).

The option to instantiate a `pint.Unit` that evaluates without canceling would be useful in this situation. Something like: 
```
>>> non_canceling_unit = pint.Unit('t * ha * hr / (ha * MJ * mm)', cancel=False)
>>> print(non_canceling_unit)
hectare * hour * metric_ton / hectare / megajoule / millimeter
```

**Comment by hgrecco** [comment]
Please take a look at #551 I would love to merge something in this direction, if someone wants to generate a PR
