### ISSUE TITLE
Format without space between magnitude and unit

### ISSUE THREAD

**Issue by rosscosack** [hgrecco/pint#1370]
```
>>> f'{meter:~P}'
'1 m²'
```
Is it possible to exclude the space between the `1` and the `m`?

**Comment by rosscosack** [comment]
And,  could the superscript 2 be just a standard 2
I would like `1m2`

**Comment by hgrecco** [comment]
That is currently not possible pint. formats are hardcoded and not templated. While I do not think we should implement this format because it will fail in multiple cases, I would like to see a way to specify in an easy manner a custom format

**Comment by keewis** [comment]
see also #1357 for some ideas about the custom formats, although I'm not sure whether the custom format should be a callable, a `dict` like the existing ones, or both.
