### ISSUE TITLE
Wrong calculation when using temperature prefixes 

### ISSUE THREAD

**Issue by Christian-Mueller** [hgrecco/pint#1381]
I'm doing following conversion:

```
from pint import UnitRegistry

ureg = UnitRegistry()
t = ureg.Quantity(20, ureg.degC)
print(t.to(ureg.millidegC))
```

output:
`293150.0 millidegree_Celsius`

It seems like prefixes for degree Celsius are not handled correctly. The result should be 20000 millidegree_Celsius.
Looks like it changes the unit to Kelvin internally.
It this a known issue? Is there a workaround for my use case?

**Comment by jules-ch** [comment]
It seems millidegree_Celsius is not identified as offset units in the convert stage hence the value does not make sense afterwards.

I'll investigate

**Comment by Christian-Mueller** [comment]
Any progress so far on this bug?

**Comment by jules-ch** [comment]
The issue has been identified but the implementation is tricky with the current implementation:

https://github.com/hgrecco/pint/blob/c99ed1f537dea91af36c756dccef49e26d4f6447/pint/registry.py#L1529-L1550

Here the conversion for offset untis is handled like so:

- Value is converted to the reference unit of the source unit which is Kelvin for all temperature unit
- Conversion for remaining unit is done for non offset dimensions
- Value is converted to destination unit from reference unit of destination unit which is Kelvin for all temperature unit


In the case of prefixed units:
for DegC to mDegC

- Value is converted to the reference unit which is kelvin
- Conversion for remaining unit is done for non offset dimensions
- Value is converted from reference unit which is DegC for mDegC

calculation does output the wrong value, for those step

- 20 -> 293.15
- 293.15 -> 293.15
- 293.15 -> 293150.0

I'll probably end up with a fix for only those prefixed temperature units.

Thoughts @hgrecco.

I find it difficult to work with UnitDefinition, UnitsContainer there

**Comment by dalito** [comment]
I also thought a bit about this: mDegC is the same as 1e-3 * degC which is a multiplication that is forbidden by default. So to be consistent pint should in my opinion raise errors for 

1. any kind of conversion to an SI-prefixed offset unit and
2. creation of quantities with an SI-prefix (`ureg.Quantity(20, ureg.milli_degC)`).

**Comment by hgrecco** [comment]
Moving this to #1754
