### ISSUE TITLE
feature request: bare-bones unit-to-unit conversions

### ISSUE THREAD

**Issue by hjalmarlucius** [hgrecco/pint#1383]
I'm building an integrated IOT (internet of things) library and would love to use pint for units on every element. However, performance is very poor when using it.

Most methods are available only on Quantities despite the same logic applies to Units (but without the added complexity of having a magnitude. Conversion from Q to U is trivial but extra overhead is incurred. Hence, my request is to implement and document a user-facing unit-to-unit conversion. Currently `BaseRegistry.convert` seems to be the best fit but it also is magnitude-oriented.

**Comment by keewis** [comment]
what would you expect such a function to do when converting units? I might be missing something, but I think the only thing it *can* do is check whether the original unit is compatible with the new unit, which you can do manually using `{UnitRegistry,Unit,Quantity}.is_compatible_with`.

**Comment by hjalmarlucius** [comment]
Thanks for the prompt response and a very well written and pythonic library!

The core issue I'm trying to resolve is that pint approximately doubles the time it takes to run a simulation in my application.

I would expect it to return the ratio between the two units as well as the residual units, if any.

It looks like `BaseRegistry.get_root_units` applied to the unit ratio does what I want (even caching) so I will test this.

**Comment by hgrecco** [comment]
You can actually use convert to obtain the conversion factor (in multiplicative units)
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.convert(1, "meter", "micrometer")
1000000.0
```
