### ISSUE TITLE
Error when plus temperature parameters in degrees celsius

### ISSUE THREAD

**Issue by C2oWisComing** [hgrecco/pint#1387]
I found the problem when calculate total totals index based on this formula: TT = (T850 + Td850) - (2 * T500). 
Ref : http://tornado.sfsu.edu/geosciences/classes/m201/buoyancy/SkewTMastery/mesoprim/skewt/tt.htm

In terms of T850 + Td850, mean plus temperature with dew point temperature at 850 hPa, both parameters are temperature in degrees celsius.

For example:
(18.8 * units.degC) + (16.5 * units.degC)

Error message:
`---------------------------------------------------------------------------
OffsetUnitCalculusError                   Traceback (most recent call last)
<ipython-input-32-182b05d5549c> in <module>()
----> 1 (18.8 * units.degC) + (16.5 * units.degC)

2 frames
/usr/local/lib/python3.7/dist-packages/pint/quantity.py in __add__(self, other)
   1076             return self.to_timedelta() + other
   1077         else:
-> 1078             return self._add_sub(other, operator.add)
   1079 
   1080     __radd__ = __add__

/usr/local/lib/python3.7/dist-packages/pint/quantity.py in wrapped(self, *args, **kwargs)
    113         elif isinstance(other, list) and other and isinstance(other[0], type(self)):
    114             return NotImplemented
--> 115         return f(self, *args, **kwargs)
    116 
    117     return wrapped

/usr/local/lib/python3.7/dist-packages/pint/quantity.py in _add_sub(self, other, op)
   1060             units = other._units
   1061         else:
-> 1062             raise OffsetUnitCalculusError(self._units, other._units)
   1063 
   1064         return self.__class__(magnitude, units)

OffsetUnitCalculusError: Ambiguous operation with offset unit (degree_Celsius, degree_Celsius). See https://pint.readthedocs.io/en/latest/nonmult.html for guidance.`

**Comment by dalito** [comment]
The problem is the term `(2 * T500)` which should be "(2 * TD500)" since multiplication of offset quantities is not allowed. Your example is different from the case where you found the problem since it tests addition (which is forbidden) not subtraction (which gives a delta_degC quantity). This works:

```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> Q_ = ureg.Quantity
>>> t850 = Q_(850., ureg.degC)
>>> td850 = Q_(850., ureg.delta_degC)
>>> td500 = Q_(500., ureg.delta_degC)
>>> (t850 + td850) - (2 * td500)
<Quantity(700.0, 'degree_Celsius')>
```

**Comment by C2oWisComing** [comment]
Thank you for your answer but t and td unit is degC (https://drive.google.com/file/d/1aojC8E8rvNk3y526n-GdBibfb_N6Vv5v/view?usp=sharing) and 2*t500 is fine (https://drive.google.com/file/d/1PvEa-Hyz5zd1uLi5zRSjYS7hCGRic7_M/view?usp=sharing).

I try to solve by:
`((t850.m + td850.m) * units.degC)`
or
`t850 + td850.m * units.delta_degC`
both result is 35.3 degree_Celsius but I don't know it make sense?

**Comment by dalito** [comment]
There is probably a bug in the library if it is not using `units.delta_degC` for a temperature interpolation calculation but `units.degC`.

**Comment by dalito** [comment]
In your last comment, in the first example you rely on the special behavior allowed by `autoconvert_offset_to_baseunit = true`.
The second example is written as it should be for pint. It will also work with `autoconvert_offset_to_baseunit = false`.

**Comment by C2oWisComing** [comment]
It's mean the second example is better choice. Thank you very much for your help.

**Comment by dopplershift** [comment]
Just for the record, this is coming from MetPy where we do set `autoconvert_offset_to_baseunit = true` in order to make it much easier to work with temperatures like anything else (e.g. `mytemp = 5 * units.degC`)

The easier way to fix this up is to refactor the calculation (to better match what it's trying to do anyway):
```python
TT = (T850 - T500) + (Td850 - T500)
```
That will give you addition of two temperature differences, which is fine and really what the calculation is doing anyway.
