### ISSUE TITLE
parsing of `Δ`

### ISSUE THREAD

**Issue by CagtayFabry** [hgrecco/pint#1390]
I am having trouble parsing delta temperature values where the unit is stored as a string in short notation.
Basically I cannot recreate a unit from a string notation that contains `Δ`

```python
import pint

ureg = pint.UnitRegistry()
u = ureg.Unit('delta_degree_Fahrenheit')
ureg.Unit(u)
#> <Unit('delta_degree_Fahrenheit')>
ureg.Unit(f"{u:.}")
#> <Unit('delta_degree_Fahrenheit')>
ureg.Unit(f"{u:~}")
#> pint.errors.UndefinedUnitError: 'Δ' is not defined in the unit registry
```

Is there a way to enable this without explicitly adding `Δ°C`, `Δ°F` etc. as shortcuts to the unit dictionary?

**Comment by hgrecco** [comment]
You can use preprocessors, which are basically callables that are applied sequentially to any text input. Just pass a list with a callable when instantantiating the registry to the `preprocessors` keyword argument.

**Comment by CagtayFabry** [comment]
thank you for the quick reply, using `lambda s: s.replace("Δ°", "delta_deg")` as a preprocessor works nicely for each  `Δ°C`, `Δ°F` and `Δ°Re`

I thought there might be a more generic way to capture other offset units with `Δ` but this approach is enough for my use-case
