### ISSUE TITLE
Example of setting up and using a formatter

### ISSUE THREAD

**Issue by carowjp** [hgrecco/pint#1391]
I am trying to match unit formats from pint to unit formats in another software tool. I'd appreciate an example of setting up and using a formatter, or other suggestions on how to accomplish this. 

Here are some examples of desired unit formats:

| Unit   | Formatted |
|--------|-----------|
| J/K/kg | J/(kg K)  |
| W/K/m  | W/(m K)  |
| W/m**2 | W/m^2    |

**Comment by keewis** [comment]
currently, there's just the [tutorial](https://pint.readthedocs.io/en/latest/tutorial.html#string-formatting). However, #1375 sums up my understanding of the formatters (here's a [preview](https://pint--1375.org.readthedocs.build/en/1375/formatting.html)). If you find anything that needs clarification feel free to ask on that PR.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
