### ISSUE TITLE
Support for units that are not named according to prefix + base unit

### ISSUE THREAD

**Issue by matthuszagh** [hgrecco/pint#1398]
In electrical engineering and machining (as well as probably some other disciplines) a 'milliinch' is commonly referred to by its abbreviation, 'mil' (thou is also used for this). It would be nice to be able to print it this way in abbreviated unit names.

Currently, pint gives me 'milliinch' or 'min':

```python
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

x = Q_(1, "mm")
print(f"size: {x.to('inch').to_compact():.4~P}")
print(f"size: {x.to('inch').to_compact():.4P}")
```
```
size: 39.37 milliinch
size: 39.37 min
```

Unfortunately, this seems to be a bit of an unusual case, as 'mil' is a scaling prefix. For example, attempting `ureg.define('mil = 1e-3 * inch = mil')` doesn't work. Similarly, `ureg.define("@alias mil = milliinch")` also failed when setting 'mil' as the destination of a conversion. Is there any way to override the abbreviated form of milliinch to this?

'thou', which is supported by pint is also a bit of an unusual case. For example,

```python
x = Q_(1e4, "thou")
print(f"size: {x.to_compact():.4P}")
```
```
size: 10.0 kilothou
```

It seems unusual to think of something as a kilothou rather than just an inch.

Is it possible (or is it intended to be possible) to have pint give me 'mil' and 'inch' in these cases?

This does raise the additional question of how you might choose between 'thou' and 'mil' since they're both aliases for the same unit.

**Comment by hgrecco** [comment]
Maybe with the new `to_preferred`?

**Comment by hgrecco** [comment]
Feel free to reopen if needed
