### ISSUE TITLE
Creating a dimensional value in pandas triggers weird conditional logic error message

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [hgrecco/pint#1405]
Consider the following DataFrame:

`x = pd.DataFrame(data=[[1, 'Mt']], columns=['Value', 'Unit'])`

I can use the apply function to multiple my value by unity (not very exciting):

`x.assign(Value=lambda x: x['Value'] * 1)`

I can try to use pint to convert from Megametric Tons to Tons:

`x.assign(Value=lambda x: x['Value'] * ureg(x['Unit']).to(ureg('t')))`

Whereupon all hell breaks loose:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-75-e17efbd70698> in <module>
----> 1 x.assign(Value=lambda x: x['Value'] * ureg(x['Unit']).to(ureg('t')))

/opt/app-root/lib64/python3.8/site-packages/pandas/core/frame.py in assign(self, **kwargs)
   4484 
   4485         for k, v in kwargs.items():
-> 4486             data[k] = com.apply_if_callable(v, data)
   4487         return data
   4488 

/opt/app-root/lib64/python3.8/site-packages/pandas/core/common.py in apply_if_callable(maybe_callable, obj, **kwargs)
    356     """
    357     if callable(maybe_callable):
--> 358         return maybe_callable(obj, **kwargs)
    359 
    360     return maybe_callable

<ipython-input-75-e17efbd70698> in <lambda>(x)
----> 1 x.assign(Value=lambda x: x['Value'] * ureg(x['Unit']).to(ureg('t')))

/opt/app-root/lib64/python3.8/site-packages/pint/registry.py in parse_expression(self, input_string, case_sensitive, use_decimal, **values)
   1253             )
   1254 
-> 1255         if not input_string:
   1256             return self.Quantity(1)
   1257 

/opt/app-root/lib64/python3.8/site-packages/pandas/core/generic.py in __nonzero__(self)
   1535     @final
   1536     def __nonzero__(self):
-> 1537         raise ValueError(
   1538             f"The truth value of a {type(self).__name__} is ambiguous. "
   1539             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

What is causing the pint conversions to head into the use of conditional logic so unfavored by Pandas?

**Comment by keewis** [comment]
The issue is `ureg(x["Unit"])`, which means you're trying to construct a unit from a `Series` object (even if that only has a single row). Units are always scalars, so `pint` uses boolean operators (`not`) to check the value (hence the `ValueError`).

In any case, did you see the [pint-pandas](https://github.com/hgrecco/pint-pandas) package already? It should make working with `pandas` a lot easier.

**Comment by MichaelTiemannOSC** [comment]
Thanks for the explanation.  I have seen pint-pandas but thought that when working with single rows of DataFrames it did not apply.  Now I see that such are still series, albeit very short Series.
