### ISSUE TITLE
pint.UndefinedUnitError not raised after upgrade to pint=0.18

### ISSUE THREAD

**Issue by marouane-miftah** [hgrecco/pint#1408]
MacOS Big Sur 11.5.2
The following tests pass with pint=0.17

```import pytest
import pint


@pytest.fixture
def ureg():
    try:
        return pint.application_registry
    except AttributeError:
        return pint._APP_REGISTRY


@pytest.fixture
def custom_ureg():
    ureg = pint.UnitRegistry()
    ureg.define("test_unit = 123 kg")
    return ureg


@pytest.fixture
def custom_ureg_global():
    ureg = pint.UnitRegistry()
    ureg.define("test_unit = 123 kg")
    prev = pint.get_application_registry()
    pint.set_application_registry(ureg)
    yield ureg
    pint.set_application_registry(prev)


def test_ureg_global(custom_ureg_global):
    assert "test_unit" in custom_ureg_global


def test_custom_units(ureg, custom_ureg):
    a = custom_ureg.Quantity([1], "test_unit")
    assert str(a.units) == "test_unit"

    with pytest.raises(pint.UndefinedUnitError):
        ureg.Quantity([1], "test_unit")
```

After upgrading to pint=0.18

I am getting this error:

```
========================================================================== FAILURES ===========================================================================
______________________________________________________________________ test_custom_units ______________________________________________________________________

ureg = <pint.registry.ApplicationRegistry object at 0x7ff7d859ea60>, custom_ureg = <pint.registry.UnitRegistry object at 0x7ff7d88744f0>

    def test_custom_units(ureg, custom_ureg):
        a = custom_ureg.Quantity([1], "test_unit")
        assert str(a.units) == "test_unit"
    
        with pytest.raises(pint.UndefinedUnitError):
>           ureg.Quantity([1], "test_unit")
E           Failed: DID NOT RAISE <class 'pint.errors.UndefinedUnitError'>

```

Please let me know if I am doing something wrong here.

Thank you.

**Comment by keewis** [comment]
the issue is that `pint.get_application_registry()` returns the global `ApplicationRegistry` object, so your isolation mechanism doesn't work. Try this instead:
```python
@pytest.fixture
def custom_ureg_global():
    ureg = pint.UnitRegistry()
    ureg.define("test_unit = 123 kg")

    prev = pint.get_application_registry()
    try:
        prev = prev.get()
    except AttributeError:
        pass

    pint.set_application_registry(ureg)
    yield ureg
    pint.set_application_registry(prev)
```
@hgrecco, @jules-ch, should we switch `get_application_registry` to use `.get()` and require the use of `pint.application_registry` to take advantage of the new wrapper class? That way the friction might be a little bit smaller...

**Comment by marouane-miftah** [comment]
@keewis thanks that worked but I have to admit it's a bit confusing as we are getting the wrapper class instead of the actual registry.

Thank you.

**Comment by keewis** [comment]
Right, it might probably make sense to convert `pint.set_application_registry` to a `contextmanager`. With that, you would be able to shorten your fixture to:
```python
@pytest.fixture
def custom_ureg_global():
    ureg = pint.UnitRegistry()
    ureg.define("test_unit = 123 kg")

    with pint.set_application_registry(ureg) as registry:
        yield registry
```

Even better, for full test isolation you might just replace your fixture with this:
```python
@pytest.fixture
def custom_ureg_global(monkeypatch):
    ureg = pint.UnitRegistry()
    ureg.define("test_unit = 123 kg")

    monkeypatch.setattr(pint, "application_registry", ureg)

    return ureg
```
and you'd just have to make sure you don't use `set_application_registry` (if you do you might have to wrap `ureg` in a new `ApplicationRegistry` instance)

**Comment by marouane-miftah** [comment]
> Right, it might probably make sense to convert `pint.set_application_registry` to a `contextmanager`. With that, you would be able to shorten your fixture to:
> 
> ```python
> @pytest.fixture
> def custom_ureg_global():
>     ureg = pint.UnitRegistry()
>     ureg.define("test_unit = 123 kg")
> 
>     with pint.set_application_registry(ureg) as registry:
>         yield registry
> ```
> 
> Even better, for full test isolation you might just replace your fixture with this:
> 
> ```python
> @pytest.fixture
> def custom_ureg_global(monkeypatch):
>     ureg = pint.UnitRegistry()
>     ureg.define("test_unit = 123 kg")
> 
>     monkeypatch.setattr(pint, "application_registry", ureg)
> 
>     return ureg
> ```
> 
> and you'd just have to make sure you don't use `set_application_registry` (if you do you might have to wrap `ureg` in a new `ApplicationRegistry` instance)

I prefer the `contextmanager` solution it looks cleaner

**Comment by hgrecco** [comment]
This has been fixed long ago.
