### ISSUE TITLE
flaky test

### ISSUE THREAD

**Issue by shenganzhang** [hgrecco/pint#1412]
`pint/testsuite/test_unit.py::TestRegistryWithDefaultRegistry::test_redefinition` will fail when executing `pytest --flake-finder --flake-runs=2`;
`pint/testsuite/test_quantity.py::TestOffsetUnitMath::test_multiplication_with_scalar` and `pint/testsuite/test_issues.py::TestIssues::test_issues86b` will fail when executing `pytest --randomly-seed=1234`.

**Comment by dalito** [comment]
I can reproduce this. For the first `pytest-flakefinder` must be installed. 

The second needs `pytest-randomly`. Once this is installed running the test suite by the standard `pytest` commend already gives one of the failures: `pint/testsuite/test_quantity.py::TestOffsetUnitMath::test_multiplication_with_scalar`.

All errors seem to be related to whether the unit registry is in the right offset-unit-calculation mode. Probably, the tests are not fully isolated with respect to the value of `ureg.autoconvert_offset_to_baseunit`.

**Comment by hgrecco** [comment]
Creating completely isolated registries while safer is also a performance burden. We need to take a look test by test and decide when isolation is needed and when is not. Some time ago I stared migrating everything to pytest and creating a few fixture. Maybe we can continue this migration effort.

**Comment by jules-ch** [comment]
I'm not sure about the worsened performance.
We can at least use a unit_registry fixture for those flaky test where unit registry of the Test class is mutated & overall behavious is not guaranteed.
