### ISSUE TITLE
Version number: install from git archive

### ISSUE THREAD

**Issue by dgoeries** [hgrecco/pint#1423]
Hi,

we did try to install by source and noticed that the version is not set correctly (0.0.0). It also appeared that we did not get the corresponding code. Without further checking, our unit tests act differently when installing from source and not via pip or conda.

**Comment by keewis** [comment]
where did you get the source from?

Installing from a clone of the repository definitely works, but it is known that `github`'s source tarballs do not – they're essentially the output of `git archive` which breaks `setuptools_scm`. We could fix that using `setuptools_scm_git_archive`, though.

**Comment by dgoeries** [comment]
Thanks a lot, yes the pypi seems to work now. Looks like we had a conflict. Would be great to have a number indicator what is installed :-).

**Comment by keewis** [comment]
> Would be great to have a number indicator what is installed

I'm not sure I understand ... can you elaborate?

**Comment by dgoeries** [comment]
Sorry, I mean the version number

**Comment by keewis** [comment]
oh, okay. The version number can be fixed using `setuptools_scm_git_archive`. Can you reopen this issue and rename it to something like "install from git archive"? That would make tracking this a bit easier.

**Comment by dgoeries** [comment]
yes of course, thanks again!

**Comment by keewis** [comment]
great, thanks
