### ISSUE TITLE
Type checking problem using function wrapping

### ISSUE THREAD

**Issue by Suseko** [hgrecco/pint#1431]
Hello,

using pint 0.18, I found that writing a wrapper with mulitple arguments and ignoring some of them (following section "Ignoring an argument or return value" in [https://pint.readthedocs.io/en/stable/wrapping.html](url)),
```
from typing import Tuple
import numpy as np
from pint import UnitRegistry, Unit

ureg = UnitRegistry()

@ureg.wraps((None, Unit(ureg.mm)), (None, Unit(ureg.mm)))
def f(x: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    return x + y, x * y
```
static code checking via `mypy` for both arguments of the wrapper raises an error:
> Argument has incompatible type "Tuple[None, Unit]"; expected "Union[str, Unit, Iterable[str], Iterable[Unit], None]"

I think the type definition should maybe look like
`Union[str, Unit, None, Iterable[Union[str, Unit, None]]]`
to match the documentation's example.

**Note:** Actually, when setting up the wrapper *exactly* as illustrated in the examples without an additional `Unit()` around the `ureg.mm`, `@ureg.wraps((None, ureg.mm), (None, ureg.mm))`, the error would be
> Argument has incompatible type "Tuple[None, **Any**]"; expected "Union[str, Unit, Iterable[str], Iterable[Unit], None]".

However, using e.g. `@ureg.wraps((ureg.mm, ureg.mm), (ureg.mm, ureg.mm))` does not raise a `mypy` error. Just included that to make sure, the `None` was the source of the error raised, not the `Any` instead of a `Unit`.

**Comment by jules-ch** [comment]
Yes that's true. Can you submit PR ? :heart:

**Comment by Suseko** [comment]
Ok, I tried my best :) (this is my first attempt on contributing to open source and creating a PR on GitHub).
I did not have any good idea about how to write a test. The example I posted above worked with the change, i.e. not throwing an error when running `mypy`on it. However, running `mypy`in the command line on a file was insanely slow, when I did it, so that does not qualify as a test in my opinion.
Let me know any problems or if anything else is required.

**Comment by jules-ch** [comment]
It's ok, we don't have test for type hinting yet.
It requires a mypy plugin for that.
You can see an example in numpy repo https://github.com/numpy/numpy/blob/main/numpy/typing/tests/test_typing.py

It's a bit early for that for pint.

Glad to see you submitted a PR :)
I'll check that
