### ISSUE TITLE
Unit object gives wrong unit when mixing aliases

### ISSUE THREAD

**Issue by kvanderwijst** [hgrecco/pint#1441]
When creating a unit object with mixed aliases (`ureg.Unit('hour/hr')`), it returns a wrong unit. It seems like part of it gets ignored. This does not happen when creating a quantity as `ureg.Quantity('1 hour/hr')`.

Replicating code:
```
import pint
ureg = pint.UnitRegistry()
print(ureg.Unit('hour/hr'))       # prints "<Unit('1 / hour')>"

print(ureg.Quantity('1 hour/hr')) # prints "<Quantity(1.0, 'dimensionless')>"
```

In my model, the user sometimes uses units like "Gt CO2/yr" and "trillion USD/year". Costs per gigaton of CO2 become messed up because the "yr/year" doesn't disappear. I cannot switch to `Quantity`, since I use pint through the optimisation package Pyomo, which uses `Unit`.

**Comment by jules-ch** [comment]
Good catch, investigated a bit, not too complicated to fix.
The parser is updating value based on canonical name but both of them have the same.

**Comment by hgrecco** [comment]
I think this is the same problem that was raised in #1433 we need to make this homogeneous and always use the canonical name. What do you think @jules-ch ?
