### ISSUE TITLE
Check decorator and class definition

### ISSUE THREAD

**Issue by srgkoshelev** [hgrecco/pint#1442]
I have encountered an interesting behavior when `u.check` decorator is used on a class. The dimensionality check itself works perfectly but the class is getting turned into a function, thus removing the ability to check `isinstance()`, for example.
```
  from pint import UnitRegistry
  u = UnitRegistry()

  class CheckingOnInit:
      @u.check(None, '[time]')
      def __init__(self, t):
          self.t = t

  test = CheckingOnInit(1*u.s)
  print('Works: ', isinstance(test, CheckingOnInit))

  @u.check('[time]')
  class CheckingOnClass:
      def __init__(self, t):
          self.t = t

  test2 = CheckingOnClass(1*u.s)

  from pint import errors
  try:
      test3 = CheckingOnClass(1*u.m)
  except errors.DimensionalityError:
      print('Fails as expected')

  try:
      print(isinstance(test2, CheckingOnClass))
  except TypeError as e:
      print('Fails on checking instance because type is')
      print(type(CheckingOnClass))
      print(e)
```

This is most relevant when dataclasses are used as they don't have `__init__` method. Is this the expected behavior of the decorator? Is there a way to make it work for the dataclass?

**Comment by jules-ch** [comment]
`ureg.checks` & `ureg.wraps` are function decorator meant to decorate a function.
They are not meant to be used on classes.
Those decorator takes a function as argument.

See class decorator, to decorate a class.

**Comment by srgkoshelev** [comment]
I tried to find info on class decorators in the pint documentation and was unsuccessful. Is it there? All I see is the function wrapper that I have (improperly) used.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hgrecco** [comment]
Linking this to #1753
