### ISSUE TITLE
The order that units appear matters

### ISSUE THREAD

**Issue by shaharkadmiel** [hgrecco/pint#1443]
For some reason:

```python
str(ureg['(m/s**2)**2/Hz'].units)
```

outputs:
```
'm²/Hz/s⁴'
```

Now, although mathematically correct, there should be some mechanism to keep meaningful dimensions together. I've defined a new derived dimension as `[acceleration]**2/[frequency]`, which is how I would like the units formatted.

I would be okay with `'(m/s²)²/Hz'`, or `'m²/s⁴/Hz'`, but `'m²/Hz/s⁴'` is funky.

Is there a way to get this done?

**Comment by hgrecco** [comment]
I am not sure how would you do it. Because "meaningful" in this case (I think) depends on user intention, and we need to communicate that to pint. Maybe you can try to invent an API (independently if this is then doable) to see how it feels.

**Comment by shaharkadmiel** [comment]
Meaningful in this context can be existing dimensions in the unit registry. If we match the units against dimensions in the unit registry, perhaps we can use the definition to recompose the units?

**Comment by keewis** [comment]
just for reference, it *is* possible to customize this since 0.18 if built-in formatters don't work for you. See #1422 for a example, although there might still be a bit more documentation necessary.

As a hint, `str` uses `ureg.default_format`/`unit.default_format` as the format.

**Comment by hgrecco** [comment]
Closing for the time now. Feel free to reopen.
