### ISSUE TITLE
pint-pandas notebook duplication

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint#1444]
I wanted to make an change to pint-pandas and update the notebook, but the most up to date notebook is in pint so would need a separate PR in pint. I think the notebook should be stored in pint-pandas, and pint links to it like is done for uncertainties. 

Pint's docs link to two notebooks, one in pint-pandas (which is outdated)

> For full details, see the pint-pandas Jupyter notebook. https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pandas_support.ipynb

and one in pint

> User Guide
> ...
> Pandas support https://pint.readthedocs.io/en/stable/pint-pandas.html

**Comment by jules-ch** [comment]
+1 for this linking to pint-pandas docs

**Comment by andrewgsavage** [comment]
OK copied it over, the link is https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pint-pandas.ipynb

**Comment by hgrecco** [comment]
+1
