### ISSUE TITLE
Implementing parts/mL

### ISSUE THREAD

**Issue by ForeverWintr** [hgrecco/pint#145]
I'm trying to implement unit conversions for 'parts per measurement', but am getting an exception.  

Here's what I'm trying:

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.define('parts = [parts]')
>>> a = ureg.parse_expression('parts/ml')
>>> b = ureg.parse_expression('parts/100ml')
>>> a.to(b)
    pint.unit.DimensionalityError: Cannot convert from 'parts / milliliter' ([parts] / [length] ** 3) to 'milliliter * parts' ([length] ** 3 * [parts])
```

It seems like these two quantities should be convertible. Am I doing something wrong here, or is this conversion outside of the scope of Pint?

This is on pint 0.5

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen or open a new issue if needed.
