### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1450]
Since the last release in October we had quite a few bugfixes:
- [x] #1417
- [x] #1420
- [x] #1403
- [x] #1399
- [x] #1426
- [x] #1435 
- [x] #1419
- [x] #1427 / #1449
- [x] #1409
- [x] #1478
- [x] #1476
- [x] #1481

some new features:
- [x] #1404
- [x] #1484
- [x] #1421 
- [x] ~#1448~: needs more time to review
- [x] #1369
- [x] #1454

and some docs updates (including the redesign):
- [x] #1422
- [x] #1483
- [x] ~#1474~: pushed back to the next release

and I'm sure I missed a few PRs (if so, feel free to edit the post)

We were originally planning to make a bugfix release, but I think we could just as well make a full release. What do you think, @hgrecco, @jules-ch?

**Comment by dalito** [comment]
What about merging #1409, too? It fixes a bug for offset units of higher dimension.

**Comment by jules-ch** [comment]
I'll check those PRs.

We can also change minimum Version support according to NEP29.

Python 3.8+
Numpy 1.19+

**Comment by hgrecco** [comment]
Agreed on doing a release, maybe also a pint-pandas one just after that. Let's put a deadline. @jules-ch when do you think is reasoable?

**Comment by jules-ch** [comment]
I've reviewed @keewis PRs.
I think we can say end of this month.
I'l try to fix some bugs in the meantime

**Comment by jules-ch** [comment]
@keewis can you make the appropriate changes after my review on https://github.com/hgrecco/pint/pull/1419 https://github.com/hgrecco/pint/pull/1421 https://github.com/hgrecco/pint/pull/1422
So I can merge them.

**Comment by keewis** [comment]
sure, can you tell me what exactly I should change?

**Comment by keewis** [comment]
@jules-ch, what do we need to make this happen?

**Comment by jules-ch** [comment]
Ok we should be good to go for a release, just waiting for #1454 to be merged.

@keewis I'm gonna wait for #1448, I haven't had time to review it, and I'm not sure delegating to registered formatter is making things simpler for the end user.
Can we delay this PR to the next release ?

**Comment by keewis** [comment]
it's not really urgent, but I was hoping to make use of this in a unit format that changes significantly once `~` is passed. I guess that means we can push it back for now?

What do you think about merging #1404?

**Comment by hgrecco** [comment]
I was looking at the PRs which are still open (and not included here):
- #1275 we could merge a version of this
- #946 As stated [here](https://github.com/hgrecco/pint/issues/943#issuecomment-1046318394) I think this works as expected and can be closed
- #1022 I think we can merge this and add it as breaking change referencing #1021
-  #1191 Not sure

**Comment by hgrecco** [comment]
Shall we release this weekend?

**Comment by keewis** [comment]
that would be great. What would be needed get there?

**Comment by jules-ch** [comment]
@keewis @hgrecco If you guys can review #1476 & # 1481. After that I think we are ready to do a release.
Next release, we can push the new version of the documentation.

**Comment by keewis** [comment]
with both of those merged that only leaves us with the remaining PRs that add units (#1404, and I guess #1484) and the PR removing the `pint-pandas` notebook (#1444).

I think #1444 is uncontroversial and can be merged right now, while the new units need a decision (personally, I think we can merge those too)

**Comment by hgrecco** [comment]
I agree with merging all three

**Comment by jules-ch** [comment]
Agreed, I think we need to provide guidelines on units that can be added to the default registry.
That will provide us checks that have to be fullfilled in order to add those units.

I'll add an issue for this.

**Comment by jules-ch** [comment]
@hgrecco Does the activation of Github Discussions is also on the menu, that can reduce the noise on Issues.
Ideas & day to day maintenance can be moved there also.

**Comment by jules-ch** [comment]
@hgrecco just merged the 3 PRs mentionned by @keewis

**Comment by OrangeChannel** [comment]
Should the new units be documented in the changelog? They weren't on the individual PRs.

**Comment by jules-ch** [comment]
True I'll had those.

**Comment by jules-ch** [comment]
Ok this time I think we are ready for that release :)

**Comment by hgrecco** [comment]
I have just release Pint 0.19 Thanks for all the awesome work. I will do a few tests and then tweet about it!
