### ISSUE TITLE
Byte conversion not done properly

### ISSUE THREAD

**Issue by samwaseda** [hgrecco/pint#1452]
The following code
```python
from pint import UnitRegistry
ureg = UnitRegistry()
(1000 * ureg.byte).to_compact()
```
return `1.0 kilobyte`, and `(1024 * ureg.byte).to_compact()` returns (not so surprisingly) `1.024 kilobyte`, while I had expected 0.975 kilobyte for the first case and 1 kilobyte for the second. I'm using version 0.18.

**Comment by keewis** [comment]
`10³` is the only SI-conform way to define the prefix `kilo` so this is expected. Instead, `2¹⁰ byte` are `1 kilobibyte` / `1 KiB` ([reference](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units)).

`bibyte` are tricky to support, as we'd need to either define new prefixes (`kilobi` / `Ki`, `megabi` / `Mi`, etc.) or overload the standard SI prefixes to be non-linear and define a new `bibyte` unit. Neither option sounds great, but I guess the latter is worse.

**Comment by samwaseda** [comment]
Ok that means there's currently no way to use `(xxx * ureg.byte).to_compact()` in a meaningful way, correct?

**Comment by keewis** [comment]
There might be a way to use contexts to override the prefixes (i.e. have `kilo` mean `2^10` temporarily), but I'm not sure.

**Comment by jules-ch** [comment]
Well we could see if it is possible to use binary prefixes.
It would be an argument in to_compact to use those prefixes instead of SI ones.

**Comment by jules-ch** [comment]
My 2 cents for you, use a function to transform to byte.
Then process to map to the suitable binary prefixes  to use.
It will be easier to use this custom function for now and you can customize it to your needs.

**Comment by jules-ch** [comment]
Here is a quick one


```python

from pint import UnitRegistry, Quantity
from math import log2, floor

ureg = UnitRegistry()

BINARY_PREFIXES = {
    10: "Ki",
    20: "Mi",
    30: "Gi",
    40: "Ti",
    50: "Pi",
    60: "Ei",
    70: "Zi",
    80: "Yi",
}

ureg.default_format = "~P"


def get_compact_size(size: int) -> Quantity[float]:
    binary_power = floor(log2(size) / 10) * 10
    binary_prefixes_power = BINARY_PREFIXES.keys()

    if binary_power > max(binary_prefixes_power):
        prefix = BINARY_PREFIXES[-1]
    elif binary_power < min(binary_prefixes_power):
        return ureg.Quantity(size, "byte")
    else:
        prefix = BINARY_PREFIXES[binary_power]
    size = ureg.Quantity(size, "byte")
    return size.to(f"{prefix}byte")

**Comment by samwaseda** [comment]
ok I guess for now I'll go for a conversion outside of `pint`. Anyway thanks for your help and I'll look forward to seeing byte convention integrated at some point :)

**Comment by jules-ch** [comment]
We can open an issue to support a kwarg binary to support this see if it can be implemented easily.

In any case Base 10 is widely adopted for disk size now, by OS & disk manufacturer.

See: 
- https://wiki.ubuntu.com/UnitsPolicy
- https://support.apple.com/en-ca/HT201402


Only Microsoft resists to this change, not for long probably.
So I'd advise to use base 10 today.
