### ISSUE TITLE
Human friendly formatting based on significant figures

### ISSUE THREAD

**Issue by mmarras** [hgrecco/pint#1459]
Hi, 

I know about  `ureg.default_format`.  However, from what I see, for the formatting it is not desired to format magnitude and quantity independently. After all the power of pint is to have a quantity which has both info at once! 

I'm thinking of something like significant figures. And this has nothing to do with numbers after the comma, as can be set by the standard float formatter, e.g., `.3f`. 

Here is what I have in mind: using units to give the best human readable result for a requested number of significant digits. I would argue this would be a small number (I propose at least one, but not more than 3 digits before the comma [3 because the standard intervals for unit prefixes are multiple of 1000s], imho non-zero digits before the comma are much easier to digest than zeros behind the comma). 

Eg. if you had 3 significant figures and a value of 
3.122 meters it would print 
3.12 meter. 
if you had 

0.3122 meters it would print 
3.12 decimeter
if you had 

0.000031222 meter it would print 
31.2 micrometer 

and so on
Is there something like this in pint already?

**Comment by keewis** [comment]
I might be wrong, but I think you're looking for [`Quantity.to_compact()`](https://pint.readthedocs.io/en/latest/tutorial.html#simplifying-units) (see also the [reference](https://pint.readthedocs.io/en/latest/developers_reference.html#pint.Quantity.to_compact)) and the [`#` quantity modifier](https://pint.readthedocs.io/en/latest/formatting.html#modifiers).

**Comment by mmarras** [comment]
It has the human friendly down (conversion to next 10^3 unit), the significant figures not. But works for my purpose for now.

**Comment by mportz** [comment]
I'd also see this as very helpful feature. Especially for units where a conversion to the next 10**3 unit does not make sense (e.g. seconds, minutes etc.).

There is already a package out there tackling the issue for times and file sizes (https://pypi.org/project/humanize/). However, it does not support any other units. For regular number it offers conversion to human readable versions though (e.g.: 123455913 to 123.5 million)

**Comment by hgrecco** [comment]
Also look at the new `to_preferred`.

**Comment by mmarras** [comment]
> Also look at the new `to_preferred`.

Not sure how this helps with time, is there some documentation? 

Now I needed this again so I came up with a proposal. I tried to stay with pint typical conversion so just give a magnitude and a unit, not 3 minutes 50 seconds etc like it may be more common for times. 

```python
import pint

def to_compact_time(self, min_time_unit:str='s', max_time_unit:str='year'):
    if self.check('[time]'):
        ureg = self._REGISTRY
        # this list may need expansion where needed 
        time_units_sm_to_lg = [ureg.millisecond, ureg.s, ureg.min, ureg.h, ureg.day, ureg.month, ureg.year]
        idx_low = time_units_sm_to_lg.index(ureg.parse_units(min_time_unit))
        idx_max = time_units_sm_to_lg.index(ureg.parse_units(max_time_unit))
        time_units_to_display = time_units_sm_to_lg[idx_low:idx_max+1]
        in_units = []
        characteristics_nonzero = []
        for unit in time_units_to_display:
            in_units.append(self.to(unit))
            characteristics_nonzero.append(int(str(in_units[-1].m).split('.')[0])>0)
        try:
            idx_time_with_smallest_nonzero_characteristics = characteristics_nonzero.index(False)-1
        except ValueError:
            # no characteristis_nonzero
            idx_time_with_smallest_nonzero_characteristics = len(characteristics_nonzero)-1
    else:
        return self.to_compact()
    return in_units[idx_time_with_smallest_nonzero_characteristics]
    
```

Then we can do

```python
pint.Quantity.to_compact_time = to_compact_time

i = 1 
while i<1000000000:
    print(pint.Quantity(i,'s').to_compact_time())
    i=+i*10
```

> 1 second
> 10 second
> 1.6666666666666667 minute
> 16.666666666666668 minute
> 2.7777777777777777 hour
> 1.1574074074074072 day
> 11.574074074074073 day
> 3.802570537683474 month
> 3.1688087814028947 year
