### ISSUE TITLE
Major refactoring of definition parsing and loading

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1465]
**Background**: A separate, text based definition file has been always one of Pint's strong points (and one of the reason it was created). But the definition file evolved from a very simple thing containing prefixes, multiplicative units and constants to a richer albeit more complex one. Extra code was added to the Registry to accommodate these new features. Recent discussions regarding speeding up registry instantiation sparked some discussions about caching to disk. But also, and more importantly, about how are we storing information in the registry. It is time to rethink how we do this and clean things up.

**Current situation**: Upon (default) registry instantiation, the following steps occur:
1. `default_en.txt` and `constants_en.txt` are *parsed*. (~ 70 ms)
2. Definitions are *loaded* into the registry. (~ 10 ms)
3. The *RegistryCache* is built. (~ 60 ms)

Steps (1) and (2) are actually intertwined, as definitions are loaded as they are read. Some definitions are parsed into a definition object (UnitDefinition, AliasDefinition, PrefixDefinition, DimensionDefinition) and then loaded into the Registry, while others (such as systems, groups and contexts) are handled by the final classes that will operate with the quantities. Finally, directives such as `@import` and `@defaults` are hacked into the registry.

In the definition file, there are three type of definitions (this is not explicit in the code)
- statements: units, prefix, constants, dimensions
- single line directives: alias, import (start with and `@`)
- block directive: defaults, systems, groups and contexts (start with and `@` and end with `@end`)

**Proposal**: 
- Separation of concerns: 
   - make a parser that parses into definition objects (like UnitDefinition) but for all type of things found on a definition file.
   - define loaders that take these definition objects and put them in the registry
- Definition object to communicate between parser and loader
   - immutable (as much as we can do this with Python)
   - avoid members that are registry objects (Quantity, Unit, Measurement)
   - avoid `<local> objects`
   - pickable
- Definition file object as a parsed version of a text definition file.
   - contains information about the original file
   - contains definition objects
   - contains line numbers for debugging
   - pickable
- Infrastructure to cache in disk.
   - can generate a filename from information about the source that is going to be cached.
   - invalidates the cache file if the source is newer

**What is done** in #1464:
- new `parser.py` module
   - ImportDefinition class: represents a parsed `@import` directive
   - DefinitionFile class
   - defines Parser class
      - parses and handles the `@import directive`
      - new single line and block directives can be registered
      - can load package resources and files
      - the `parse` method returns a tuple of DefinitionFile objects.
- SystemDefinition: represents a parsed `@system` directive.
  - a System object can be created from a  SystemDefinition object.
  - the loader puts the System object in the registry.
- GroupDefinition: represents a parsed `@group` directive
  - a Group object can be created from a  GroupDefinition object.
  - the loader puts the Group object in the registry.
- ContextDefinition: represents a parsed `@context` directive
  - a Context object can be created from a  ContextDefinition object.
  - the loader puts the Context object in the registry.
- DefaultsDefinition: represents a parsed `@defaults` directive
- reworked AliasDefinition: represents a parsed `@defaults` directive
- A separate loader for `@alias` so that is used as a directive, not a statement.
- Migrated PrefixDefinition, UnitDefinition, DimensionDefinition to frozen dataclasses.
- new `diskcache.py` module
   - defines DiskCache that can load and save data to disk
   - a unique cache name for a given content.
- Add caching capabilities to the Registry:
   - Added a `cache_folder` argument to configure or disable the DiskCache object.
   - Use the cache for steps (1.parsing files) and (3.-build cache)

A lot of the code is nicer now due to the separation of concerns.

**What I broke/change/fix in the way**:
- Definition.from_string cannot handle something like "@alias meter = metro". See 79fb2eecf740a1146ea5dd4d09920a363d15a79b
- symbol property became defined_symbol attribute in certain definitions. See 26461894df8958f91c52bea6ee9bf5efa5306492
- Group definitions no longer accept lines that cannot be parse by Definition.from_string. See d4c22477b8e79a5a271ac72886964e7fb8507895
- Pickling UnitsContainer does not save the hash value. See 19c9d326975e2255c2ea51aed8d1be2ae8f7d579

I do not think that any of these changes will affect real code as is used internally. The public API as not affected.

**What still needs to be done/decided**: 

The only missing functionality are:
- enable the cache without providing a specific folder, but rather let Python choose an appropriate one. My suggestion would be to incorporate [appdirs](https://pypi.org/project/appdirs/) as a dependence and use the `user_cache_dir` function to provide a folder when `cache_folder` argument is a special value (e.g. `:auto:`, or something like this) 
- add extra information to generate the caching name (e.g. the parsed files with `non_int_type=float` are different than those parsed with `non_int_type=Decimal`). Something similar might happen with other registry configuration and the cache.

**Roll out**
If these modifications are accepted, the proposal would be to 
1. Have a release with the code but with the cache disabled by default
2. Test this feature in real world situations
3. Enable the feature in the subsequent release

**With the version** in 0b62622:

 Upon (default) registry instantiation, the following steps occur:
1. `default_en.txt` and `constants_en.txt` are *parsed*. (~ 70 ms, ~ 9 ms if cached)
2. Definitions are *loaded* into the registry. (~ 10 ms)
3. The *RegistryCache* is built. (~ 60 ms, ~ 4 ms if cached)

Before: ~ 140 ms, after ~ 13 ms

**Future work**:
In terms of code, this refactoring enables future work that could improve readability:
- Allow registering definition statements as it happens for directives
- Better define how a definition objects classes should look like for statements, single line and block directives.
- Reorganize content to keep certain things together (i.e. everything context related).

Also, there is some room for improving performance:
- Make System, Group and Context wrap (instead of consume) their corresponding definition
- Cache the loading step.

ping @jules-ch @keewis @dalito @andrewgsavage

**Comment by jules-ch** [comment]
Hey @hgrecco,

I'm in favor of this change I always wondered why it was done like so.
Parsing splitting parsing & instantiation is a step in the good direction.

I'm curious what are the use cases for loading registry from disk with pickled version of the registry.
Do we have use cases where this is the bottleneck vs using a persisted `ureg` in memory ?

On further steps, I would like to move to a standard file format like `TOML`.
We'd be able to easily map `dataclasses` definitions to the parsed version.
Moreover, embeded validation with file standard, like no duplicate keys is nice to have, to enforce no duplication at the file level.

I have worked on a working version of this, a year ago but it was maybe a bit too early for that kind of change, so why not.

**Comment by jules-ch** [comment]
Also for further steps.

About group definitions, I think units definitions should live at the root level & group definitions should only be a list of units keys that defines membership, avoiding having unit definition at the group definition level.

System is basically mapping base dimensions to units.

**Comment by hgrecco** [comment]
Merged in #1464
