### ISSUE TITLE
Handling multi-dimensional units?

### ISSUE THREAD

**Issue by deeplook** [hgrecco/pint#1473]
I haven't seen this topic mentioned anywhere, but looking at the "printer units" in https://github.com/hgrecco/pint/issues/943#issuecomment-1046242294 I wonder if there is a recommended way or best practice to deal with multi-dimensional units like, in this context, say paper formats, e.g. Letter, A4, etc.?

**Comment by hgrecco** [comment]
Can you provide an specific example?

**Comment by deeplook** [comment]
A very simple example could be:

```python
from pint import UnitRegistry

ureg = UnitRegistry()
Q = ureg.Quantity

A4 = (Q("21 cm"), Q("29.7 cm"))
A3 = (Q("29.7 cm"), Q("42 cm"))

assert A3 == 2 * A4  # should be True
``` 

In this context the orientation _might_ also be of importance.

**Comment by deeplook** [comment]
Right. The tuple above is only one way to conceptualize it. Another would be `Q("21 cm", "29.7 cm")`.

**Comment by hgrecco** [comment]
If you have numpy installed, that is possible with arrays:
```python
>>> [21, 29.7] * ureg.cm
```

**Comment by deeplook** [comment]
Ok, I see how this is helpful. Allowing multiple values for `Q` above would then perhaps provide some more symmetry and make the following work, too: `Q(["21 cm", "29.7 cm"])`, although it would not be strictly needed.

**Comment by hgrecco** [comment]
That is not possible and would not be as array quantities are defined as array of quantities with the same units. Allowing a constructor like `Q(["21 cm", "29.7 cm"])` will encourage to do something like `Q(["3 m", "2 seconds"])`

**Comment by hgrecco** [comment]
I am closing, feel free to reopen if needed.

**Comment by deeplook** [comment]
Ok. Maybe this is a better example to explain what I think I ask for. ;) Here, it's the number of A4 sheets to cover a one square meter area. The last bit shows the result I'd like to get. For this there must be a concept of "area" which I can, of course, express in one dimension, but the question for me from the start was if this should be possible with "multi-dimensional" units, too (deriving an area from the fact of multiplying two lengths). I thought the term is not perfect, but I haven't found another one. 

```python
>>> A4 = [21, 29.7] * ureg.cm
>>> M = [100, 100] * ureg.cm
>>> print(M / A4)
[4.761904761904762 3.367003367003367] dimensionless

>>> A4 = [21, 29.7] * ureg.cm
>>> M = [1, 1] * ureg.m
>>> print(M / A4)
[0.047619047619047616 0.03367003367003367] meter / centimeter

>>> A4 = 21 * 29.7
>>> M = 100 * 100
>>> print(M / A4)
16.033349366682703
```
