### ISSUE TITLE
Dynamic redefinition of constants

### ISSUE THREAD

**Issue by ximtec** [hgrecco/pint#1482]
Hi,

I was wondering if there is any support for dynamically changing physical constants?
I am working with code where some of the physical constants are artificially changed such that certain properties changes that allow simulations to run.
Specifically, I work with code that changes the elementary charge. I am trying to get a python program running to keep track of how this affects other quantities. 

For this, I would like to change the "elementary_charge = 1.602176634e-19 C = e", without having to manually go in and change the txt-file.

I have tried to simply do:
`
u = pint.UnitRegistry()
u.elementary_charge =  1.602176634e-19 * u.C * 0.1
`
But, this does not change fx. the conversion of eV to J or the value of the vacuum_permittivity. It also doesn't change the value of "u.e".

Is there currently any way to achieve this or would I have to manually reset all constants/units that depend on u.e?

Thanks you,
Ximtec

**Comment by hgrecco** [comment]
No. There is no way to achieve this. If you need a new definition, you should create a new definition file.
