### ISSUE TITLE
Parentheses around isolated unit components seem to change implied multiplication and exponent operator precedence

### ISSUE THREAD

**Issue by jthielen** [hgrecco/pint#1485]
In the following, I would expect these to be equivalent:

```python
from pint import UnitRegistry
ureg = UnitRegistry()

assert ureg.parse_units("(m) (s)**-1") == ureg.parse_units("m s**-1")
```

However, this fails, as

```python
str(ureg.parse_units("(m) (s)**-1"))
```

```
'1 / meter / second'
```

and

```python
str(ureg.parse_units("m s**-1"))
```

```
'meter / second'
```

Note also that

```python
str(ureg.parse_units("(m)*(s)**-1"))
```

```
'meter / second'
```

so something weird is going on with implied multiplication.

Does anyone with a more detailed knowledge of Pint's parser know what's going on here? I'd consider this a bug, but perhaps there is a surprising reason why this is intended?

<details>

The above example may seem contrived on its own, but it is a minimum reproducible example of what arose with the following unit string: `"(J kg-1)(m s-1)-1"`, which after a preprocessor for UDUNITS-style exponents, becomes `"(J kg**-1)(m s**-1)**-1"`, which i'd expect to reduce to `"meter / second"`, but instead becomes `"second ** 3 / meter ** 3"`. `"(J kg**-1)*(m s**-1)**-1"` works fine.

</details>

**Comment by jules-ch** [comment]
I'd say it is a bug, the tokenizer is evaluating as `'((m s) ** (- 1))'`

**Comment by jules-ch** [comment]
I think this use case with implicit mutliplication with parentheses has not been covered

**Comment by hgrecco** [comment]
This snippet could be useful for debugging and fixing it:
```python
>>> from pint import pint_eval, compat
>>> gen = compat.tokenizer("(x) (y) ** -1")
>>> et = pint_eval.build_eval_tree(gen)
>>> print(et.to_string())
((x y) ** (- 1))
```

**Comment by mrclary** [comment]
I don't know if this is completely redundant to the previous comments, but I've also come across an issue with parsing.
```python
from pint import UnitRegistry

ureg = UnitRegistry()

print(ureg('1/(m^3) (m)^2'))  # '1 / meter ** 8' INCORRECT
print(ureg('1/(m^3) m^2'))    # '1 / meter'      CORRECT
print(ureg('1/m^3 (m)^2'))    # *** pint.errors.DimensionalityError: Cannot convert from 'meter ** 2' to 'dimensionless'
print(ureg('1/m^3 m^2'))      # '1 / meter'      CORRECT
print(ureg('(m^-3) (m)^2'))   # '1 / meter ** 4' INCORRECT
print(ureg('(m^-3) m^2'))     # '1 / meter'      CORRECT
print(ureg('m^-3 (m)^2'))     # *** pint.errors.DimensionalityError: Cannot convert from 'meter ** 2' to 'dimensionless'
print(ureg('m^-3 m^2'))       # '1 / meter'      CORRECT

```

**Comment by rcaneill** [comment]
Discussion from issue #1730:


> this seems like a bug in `pint.pint_eval.build_eval_tree`: since there's no token between the parens it will not check the operator priority (but treat it as multiplication anyways), and so the result is the same as `((m/s)*(m/s))^-1`.
>
> To fix that I think we could insert a token (`*`) if a closing paren is followed by a open paren. Something like
>```python
>...
>elif token_text == "(":
>    if index > 0 and tokens[index - 1].string == ")":
>        new_token = current_token._replace(string="*")
>        tokens.insert(index, new_token)
>        continue
>...
>```
>Not sure if there's less hacky solution, though

_Originally posted by @keewis in https://github.com/hgrecco/pint/issues/1730#issuecomment-1481319001_

**Comment by hgrecco** [comment]
I am pretty sured this has been fixed. Feel free to reopen if needed.
