### ISSUE TITLE
numeric formatting overriding `default_format ` in `0.19`

### ISSUE THREAD

**Issue by CagtayFabry** [hgrecco/pint#1501]
I noticed that the unit string formatting changed slightly with the new `0.19` release

specifically, when setting a custom `default_format` on the `UnitRegistry` the setting is now lost when printing with additional numeric formatting options (e.g. `.2f`) (see the code below)

is this intended or is there a different way to keep the default unit formatting style?

### 0.18
```python
import pint
print(f"{pint.__version__=}")
#> pint.__version__='0.18'
ureg = pint.UnitRegistry()
q = ureg.Quantity("1.2345 m")

print(f"{q}")
#> 1.2345 meter
print(f"{q:.2f}")
#> 1.23 meter
print(f"{q:~.2f}")
#> 1.23 m

ureg.default_format = "~"

print(f"{q}")
#> 1.2345 m
print(f"{q:.2f}")
#> 1.23 m <- keeps the unit formatting options
print(f"{q:~.2f}")
#> 1.23 m
```

### 0.19
```python
import pint
print(f"{pint.__version__=}")
#> pint.__version__='0.19'
ureg = pint.UnitRegistry()
q = ureg.Quantity("1.2345 m")

print(f"{q}")
#> 1.2345 meter
print(f"{q:.2f}")
#> 1.23 meter
print(f"{q:~.2f}")
#> 1.23 m

ureg.default_format = "~"

print(f"{q}")
#> 1.2345 m
print(f"{q:.2f}")
#> 1.23 meter <- ignores the unit formatting options
print(f"{q:~.2f}")
#> 1.23 m
```

**Comment by hgrecco** [comment]
@keewis I agree with the registry setting. If you think you can make it fast, we can include in 0.19.1 that will fix #1498

**Comment by hgrecco** [comment]
@keewis I am ready to release 0.19.1. Do you want to include your patch in this release or in 0.19.2?

**Comment by keewis** [comment]
not sure. I was planning to investigate this evening, but I can't promise anything. If it's not a lot of work for you to do the release I'd say doing two separate bugfix releases might be worth considering?

**Comment by hgrecco** [comment]
agreed!
