### ISSUE TITLE
Problems when converting values with offset and prefixes

### ISSUE THREAD

**Issue by khasrusn** [hgrecco/pint#1504]
I am happy to use your library, but I ran into problems when converting values with offset and prefix. Example:
```python
>>>from pint import UnitRegistry
>>>ureg = UnitRegistry(lines)
>>>ureg.Quantity(0, "kilodegC").to("degK")
<Quantity(0.0, 'kelvin')>
>>>ureg.Quantity(1, "kilodegC").to("degK")
<Quantity(1000.0, 'kelvin')>
```
After all, 0 * 1000 degrees Celsius is not equal to 0 Kelvin, just as 1000 degrees Celsius is not equal to 1000 degrees Kelvin. The same applies to user units used with offset. I hope the authors of the project will fix this problem.

**Comment by dalito** [comment]
see also #1381 which is basically the same problem.
