### ISSUE TITLE
Liter is a unit of volume but dimensionality is set to 'length'

### ISSUE THREAD

**Issue by TommyHanusa** [hgrecco/pint#1518]
I'm not sure why this is the case but liters is returning the dimensionality as 'length' instead of volume

When I run the following code:

```
from pint import UnitRegistry

ureg = UnitRegistry()

quant1 = "1 ml"
quant2 = "1 L"
quant1 = ureg(quant1)
quant2 = ureg(quant2)

print(quant1)
print(quant2)
print(quant1.dimensionality)
print(quant2.dimensionality)
```

I get the following output:
```
1 milliliter
1 liter
[length] ** 3
[length] ** 3
```

I expected this to be `[volume]` 

I'm using:
Python 3.10.2
Pint 0.19.2

**Comment by OrangeChannel** [comment]
Dimensionality is represented in terms of the base dimensions raised to mostly integer (sometimes rational) exponents. See https://en.wikipedia.org/wiki/Dimensional_analysis#Definition . Volume is not a base dimension, it is L^3, which is what your output is showing. `[length] ** 3` [_is_ volume](https://github.com/hgrecco/pint/blob/82e4fe30aa1890943068afd0610f34e2412d0206/pint/default_en.txt#L213).

**Comment by TommyHanusa** [comment]
ok, so this seems to be working as intended.
