### ISSUE TITLE
Convert list of quantities to quantity of list

### ISSUE THREAD

**Issue by bmoneke** [hgrecco/pint#1519]
Is there any method, which converts (efficiently) a list of quantities (e.g. [Q_(1, "m"), Q_(50, "cm")]) to a quantity of a list (e.g. Q_([1, .5], "m"))?

I'm collecting data over some time and want to plot that data, which requires just a single quantity (containing a list) instead of a list of quantities. If my measurement devices return Quantities, I have to store this information or drop the unit part, which is what I do not want.

Is there a method to return the magnitude of a Quantity in another unit without returning a whole new Quantities instance? Here the use case is to convert all incoming quantities into magnitudes of a specific unit for internal storage. For me it seems to be overkill to create a quantity, read its magnitude and drop it. Or is the creation of the instance no burden?

Thanks for the library and sorry if these are default questions. I'm trying to understand pint in order to organize my data acquisition programs.

**Comment by andreala** [comment]
If it is performance you are worried about, then pint is not helping performance.

But doing something like this:
`>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> distance = 24 * ureg.meter
>>> print(distance)
24 meter
>>> print(distance.to(ureg.feet))
78.74015748031496 foot
>>> print(distance.to(ureg.feet).magnitude)
78.74015748031496`

doesn't really give you a "whole new Quantities instance", depending on your perspective.

**Comment by jules-ch** [comment]
You can use `Quantity.from_list`: https://github.com/hgrecco/pint/blob/82e4fe30aa1890943068afd0610f34e2412d0206/pint/quantity.py#L552

**Comment by bmoneke** [comment]
Hey thanks, that is exactly what I was looking for. The code even showed me, that there is an Quantity.as_m method which gives the magnitude in another unit.

Performance is not my primary concern, but neither do I want to bog down my system.

Am 13. Mai 2022 13:40:10 MESZ schrieb "Jules Chéron" ***@***.***>:

**Comment by jules-ch** [comment]
Closing
