### ISSUE TITLE
Converting between units changes number of significant places of Decimal objects

### ISSUE THREAD

**Issue by noahsprent** [hgrecco/pint#1527]
When using Decimal objects, one expects that the precision in which one specified the original value is retained. However, when converting between units, I've noticed that precision is added:

```
import decimal

import pint

print(f"Pint version: {pint.__version__}")
print(f"Decimal version: {decimal.__version__}")

ureg = pint.UnitRegistry(non_int_type=decimal.Decimal)

x = ureg.parse_expression("2 microliter milligram/liter")
print(x.m)
print(x.to_compact().m)
print(x.to_base_units().m)
print(x.to("ng").m)

>>> Pint version: 0.19.2
>>> Decimal version: 1.70
>>> 2
>>> 2.000
>>> 2.000E-12
>>> 2.000
```

The expected behaviour should be that changing the units does not change the precision.  What I suspect might be happening is somewhere in the code the value is multiplied by another decimal object that has a higher precision, like in this example:

```
decimal.Decimal("2")*decimal.Decimal("1.000")
>>> Decimal('2.000')
```

I don't know enough about the codebase, but from a quick look maybe this behaviour might be caused from Line 1044 in `registry.py` in the `_convert` function. The comments for that bit of code seem to indicate that a factor that the value is being multiplied by is being converted to a Decimal, potentially with the level of precision that is a problem here:

```
# factor is type float and if our magnitude is type Decimal then
# must first convert to Decimal before we can '*' the values
if isinstance(value, Decimal):
    factor = Decimal(str(factor))
elif isinstance(value, Fraction):
    factor = Fraction(str(factor))

if inplace:
    value *= factor
else:
    value = value * factor
```

With some pointers I might be able to dig deeper and try to submit a pull request, but I'm a bit out of my depth right now. Any help appreciated!

**Comment by noahsprent** [comment]
Looking a bit deeper by cloning the repository and installing the package from source, it looks like _get_root_units_recurse returns a Decimal that is used in the _get_root_units function that contains a precision of three decimal places. In the case of the code above it returns `1.000`. I don't understand enough to go any deeper.

**Comment by hgrecco** [comment]
I am not sure if this is really a change in precision. Take a look at this:

```python
def test(val):
    print(val.next_minus(), val, val.next_plus())

test(decimal.Decimal("2"))
test(decimal.Decimal("2.000"))
test(decimal.Decimal("2.000000"))
```

that results in:

```
1.999999999999999999999999999 2 2.000000000000000000000000001
1.999999999999999999999999999 2.000 2.000000000000000000000000001
1.999999999999999999999999999 2.000000 2.000000000000000000000000001
```

So the precision is the same (e.g). This is because it is managed by the decimal context and this is not changed in Pint.

What does change is the significance, and as stated in the python docs: "The significance of a new Decimal is determined solely by the number of digits input. Context precision and rounding only come into play during arithmetic operations.". Therefore, the resulting significance will depend on the used multiplication factors that were used in between.

**Comment by noahsprent** [comment]
Thanks for that clarification, you are right that the precision is the same. I have updated the name of the issue.

However, it still seems to me that it is not the correct behaviour that the number of significant places changes. Do you have any pointers on what might need changing in the code to avoid this issue? I imagine it probably isn't as simple as just making sure that `_get_root_units` returns a decimal with 1 significant figure rather than the 4 that it currently returns?

**Comment by hgrecco** [comment]
I do not think this is (in general) possible as you do not control the number of significant digits' int the multiplier factor (i.e. they are obtained from the definition file). Maybe ther is a way to remove trailng zeros of the multiplication factors befor applying them to unit conversions (Take a look a this https://docs.python.org/3/library/decimal.html#decimal.Decimal.normalize)

But I cannot think of a way of putting this in pint in simple way

**Comment by noahsprent** [comment]
Thanks very much for the tip! Simply adding the line `factor = factor.normalize()` within the if statement of `_convert` solved the issue for me. I've opened a pull request, but as I say in the comment there I'm not very experienced, and suspect I might have missed something as you say that "you cannot think of a way of putting this in pint in a simple way".
