### ISSUE TITLE
`numpy.alen()` called by `numpy_func`, but `alen()` is deprecated

### ISSUE THREAD

**Issue by sharonzitara** [hgrecco/pint#1532]
https://github.com/hgrecco/pint/blob/37a61ede6fbd628c7dc160eb36278cf41c96484c/pint/facets/numpy/numpy_func.py#L897

In the latest pre-release of NumPy (https://github.com/numpy/numpy/releases/tag/v1.23.0rc2), `alen` has been removed due to its deprecation expiring. Pint's `numpy_func` is still calling `alen` [here](https://github.com/hgrecco/pint/blob/37a61ede6fbd628c7dc160eb36278cf41c96484c/pint/facets/numpy/numpy_func.py#L897).

NumPy [1.18.0 release notes](https://numpy.org/doc/stable/release/1.18.0-notes.html#deprecate-np-alen) indicate that `len` should be used instead.

**Comment by wenx-z** [comment]
Would definitely appreciate an update here! This is breaking our production pipelines.

**Comment by jules-ch** [comment]
@wenx-z can you describe the error you encounter ?
it should work even if the numpy version have removed it.

**Comment by wenx-z** [comment]
```AttributeError: module 'numpy' has no attribute 'alen'```

**Comment by keewis** [comment]
well, that makes sense to me: `__array_function__` registers by function object, not by name, so we need to access the attribute. This is a easy fix, though: remove a single line plus a test (if that exists).

Feel free to send in a PR, @wenx-z (no pressure, though).
