### ISSUE TITLE
wraps decorator, but preserve Quantity type

### ISSUE THREAD

**Issue by Geekly** [hgrecco/pint#1543]
I believe the wraps decorator will convert to the specified unit, then convert that argument to a standard type (float, int) stripping the units. Is there a way to use the conversion feature of wraps while preserving the Quantity type of the argument? Perhaps the only benefit would be to eliminate the explicit conversion of the return value to a preferred unit, but that would still be nice. 

I'm using a class with several methods that return values and I want to enforce consistent units for the return values with perhaps a single decorator on each method.

**Comment by Geekly** [comment]
I wanted to add some clarification about why this would be helpful. Within the class methods, I'm using attributes of the class that are Quantity types. I'm passing in Quantity arguments to the methods, but they're stripped of Quantity by wraps(). Now I have mixed variables - some as Quantity and some as standard types. Within that method, I can't leverage the benefits of the Quantity type.

**Comment by hgrecco** [comment]
There is also the [check](https://pint.readthedocs.io/en/stable/wrapping.html#checking-dimensionality) decorator that ensures that the input value has a given dimensionality. Will that be useful?
