### ISSUE TITLE
floating accuracy in `.m_as` 

### ISSUE THREAD

**Issue by ngam** [hgrecco/pint#1545]
I am wondering if this is expected or there should be some tightening on these floating decimals. Could we improve this?

```
~$ python3 -m pip list | grep Pint
Pint                          0.19.2
~$ python3 
Python 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pint import UnitRegistry 
>>> uu = UnitRegistry()
>>> a = 1*uu.m**3
>>> b = 1*uu.s
>>> c = a/b
>>> c 
<Quantity(1.0, 'meter ** 3 / second')>
>>> c.m
1.0
>>> c.m_as('cc/s')
999999.9999999999
>>> c.m_as('cc/ms')
999.9999999999999
>>> 
>>> 1e6*1.0/1.0
1000000.0
>>>
>>> c.m_as('km^3/s')
1e-09
>>> c.m_as('m^3/ms')
0.001
>>> c.m_as('cm^3/ms')
999.9999999999999
```

(edit: both 0.19.2 and 0.19.1)

**Comment by OrangeChannel** [comment]
Try the same example using Decimal or Fraction as the `non_int_type`. Is the floating point issue still there?

**Comment by jules-ch** [comment]
For reference conversion for m³/s to cm³/s is done like so:

centi prefix (1e-2)

1.0 / (1.0e-2 ** 3) -> 999999.9999999999

There is nothing we can do with floating point error, it is inherent on how computer is computing floats.
You can either rely on `is_close` function if you are making comparison or use `non_int_type` argument in `UnitRegistry` to use `Decimal` or `Fraction` types.

**Comment by jules-ch** [comment]
Yes you will have the same value using numpy or not.

The issue comes from the order & nature of operation see using numpy :

```python
>>> import numpy as np
>>> np.float64(1.0) / (np.float64(1.0e-2) ** 3) 
999999.9999999999
>>> np.float64(1.0) / (np.float64(1.0e-2) ** 3) 
999999.9999999999
>>> np.float64(1.0) * (np.float64(1.0e2) ** 3) 
1000000.0

**Comment by OrangeChannel** [comment]
With the amount of times this comes up I think it's worth adding a page to the docs called something like "dealing with floating point inaccuracies" at the top level under User Guide to explain the use of `non_int_type` and possible drawbacks. Besides performance, iirc there are limitations with some of the operations and conversions you can do with decimals etc but will need testing.
