### ISSUE TITLE
Fractions are parsed in a non-intuitive way

### ISSUE THREAD

**Issue by eliasmistler** [hgrecco/pint#1550]
I'm seeing the following issue, where units are not parsed as expected:

```python
import pint
ureg = pint.UnitRegistry()

fuel_usage_metric = 6.1 * ureg('l / 100km')
fuel_usage_metric
# 0.061 kilometer liter

fuel_usage_metric.dimensionality
# <UnitsContainer({'[length]': 4})>
```

The output makes sense in that `l / 100km` is interpreted the same as `l / 100 * km`, but it's not intuitive.

My expectation would be that `ureg('l / 100km')` gets parsed the same way as `6.1 * ureg('l / (100km)')`, as I believe it to be a widespread convention that quantities with unit take precedence over simple operators, just like parentheses do.

**Comment by dalito** [comment]
see https://pint.readthedocs.io/en/stable/defining.html#units-with-constants for how to define/use such a unit.

**Comment by eliasmistler** [comment]
Thanks -- that works, as well as the version with the parentheses. There are also other ways around it, like using mathematical operators in Python, which force you to make operators explicit, e.g.:

```python
fuel_usage_metric = 6.1 * ureg.l / (100 * ureg.km)
```

Independently of that, the way `ureg('l / 100km')` gets parsed still seems un-intuitive to me. I wonder if it might make sense to either:
- ensure expressions without operator have preference over explicit ones OR
- force the use of operators
to help avoid bugs.

Feel free to close the issue if you disagree!

**Comment by dalito** [comment]
Personally, I think what you propose (_"force the use of operators to help avoid bugs"_) could be an improvement.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if needed or create a new issue for parsing rules
