### ISSUE TITLE
Chemistry context conversion

### ISSUE THREAD

**Issue by oiao** [hgrecco/pint#1559]
When converting with the 'chem' context, the following works without without any trouble:
``` python
from pint import UnitRegistry
ureg = UnitRegistry()
ureg('mol/L').to('ug/mL', 'chem', mw=10*ureg('g/mol'))
```
however, when adding time, the conversion breaks with a `DimensionalityError`:
``` python
ureg('mol*h/L').to('ug*h/mL', 'chem', mw=10*ureg('g/mol'))
```
What would be the proper way to enable conversion for the above?

**Comment by jules-ch** [comment]
Looking on how context was implemented, it seems it can convert only when dimensionality match exactly what was defined in the context.
For a workaround you can either define a transformation with the dimension you want or either do it in 2 operation if you can.
I'll see if we can do it in a smarter way

**Comment by hgrecco** [comment]
That is correct, there is no way to achieve this at the moment. The algorithm works by transversing a graph that connects dimensions. Right now, it only connects dimensions explicitly defined. I would be nice to have a more generic algorithm. One way would be to ratio the dimensions  and use that ratio to find what is different in each quantity, and then fall back to the previous algorithm.

**Comment by oiao** [comment]
Thanks a lot, I got around it by defining a custom context.
