### ISSUE TITLE
is_compatible_with should not raise UndefinedUnitError

### ISSUE THREAD

**Issue by oiao** [hgrecco/pint#1566]
In my opinion, querying for compatibility should not raise an `UndefinedUnitError` for cases like the one below, but instead return _False_.
``` python
ureg('g').is_compatible_with('bananas')
```
If this is still desired, maybe there can be an optional kwarg to the error being raised?

**Comment by dalito** [comment]
```
>>> ureg('g').is_compatible_with('K')
False
```
If the unit is defined, you get true/false as reutrn value, which is as it should be or not?

**Comment by oiao** [comment]
Sorry, I meant specifically for a case where the unit is not defined

**Comment by dalito** [comment]
So `ureg('g').is_compatible_with('bananas', raises=False)` would be what you want?

**Comment by oiao** [comment]
Yes, exactly. Maybe this could even be considered the default behavior - this is just my opinion, but I would expect a boolean return even if a unit is not defined. I wouldn't mind creating a PR for this, if the devs are too busy.

**Comment by hgrecco** [comment]
I agree, we should raise an UndefinedUnitError. But we should be careful rolling this change to avoid breaking downstream libraries and I am not so happy about adding an extra parameter. Any ideas how to roll this in the best manner?

**Comment by oiao** [comment]
If adding an extra argument is not an option (why is that exactly?), the straightforward solution would be an additional method.
But that does not seem to make too much sense. I guess users should not have any trouble monkey-patching the functionality themselves with something like
``` python
@add_to_class(Quantity)
def iscompat(self,*a,**kw):
    try:
        return self.is_compatible_with(*a, **kw)
    except UndefinedUnitError:
        return False
```

**Comment by hgrecco** [comment]
I think that adding an extra parameter is unnecessary and will pollute the API.  I would be fine with the following: 
Next version: we emit a warning indicating that the unit is undefined and inform the upcoming change.
Next, next version: we change the behavior.

**Comment by OrangeChannel** [comment]
Just my opinion but catching the error should 100% be on the user's side. We are checking the dimensionality of an undefined unit (via parsing a string), why would we not raise the error? Should be raising same error as "ureg.g.dimensionality == ureg.bananas.dimensionality".

**Comment by hgrecco** [comment]
@OrangeChannel I do agree we have to raise an Exception, but not in the next version because is a breaking change.

So my proposal would be:
Next version: same behavior as the current one, but issue a warning when the unit is undefined and let the user know about the upcoming change of behavior.
Next, Next version: we raise an exception if the unit is undefined and only return True/False if the unit exist.

**Comment by OrangeChannel** [comment]
Can't test right now but I believe it should already raise an exception on strings not found in the registry. I thought the issue was suggesting that this current behavior is wrong? (L131 on unit.py)

**Comment by hgrecco** [comment]
@OrangeChannel You are right! 🤦 I completely misread the original issue.

I stand by the current behavior (as said in my original response that suggest raising an Exception, which is the current behavior 🤦). 

The rationale is as follows: if somebody mistyped a unit (e.g. "mililiter") or parse a text file in which this is written in a non-standard way, the bug will be very difficult to find if `is_compatible` always returns a boolean.

**Comment by oiao** [comment]
Thanks for the explanations. Having the exception as a precaution for typos makes sense to me. I'll close this issue then.
