### ISSUE TITLE
get_application_registry/set_application_registry broke in 0.18

### ISSUE THREAD

**Issue by cslominski** [hgrecco/pint#1568]
Hi,

The follow code succeeds in 0.17 but fails in 0.18:

import pint
ur = pint.UnitRegistry()
pint.set_application_registry(ur)
assert ur is pint.get_application_registry()

This appears to be a serious issue. Could you please help?

Thanks,
Charlie

**Comment by keewis** [comment]
this is a side-effect of making the application registry a instance of `ApplicationRegistry`, which solves a lot of inter-library compatibility issues.

This still holds:
```python
assert ur is pint.get_application_registry().get()
```

**Comment by cslominski** [comment]
This fix worked for me, thank you so much. Is there a way I could have determined that from the documentation?
