### ISSUE TITLE
UnitRegistry with non-float non_int_type creates float NaN magnitudes.

### ISSUE THREAD

**Issue by cgevans** [hgrecco/pint#1570]
When using a UnitRegistry with a non_int_type other than float, normal values are created correctly, but NaN values are not:

```python
import pint
from decimal import Decimal
ureg = pint.UnitRegistry(non_int_type=Decimal)
a = ureg("5.0 m")
type(a.m)
#[Out]# decimal.Decimal
b = ureg("NaN m")
type(b.m)
#[Out]# float
c = ureg.Quantity(Decimal("NaN"), "m")
type(c.m)
#[Out]# decimal.Decimal
```

**Comment by hgrecco** [comment]
This is the offending line:

https://github.com/hgrecco/pint/blob/37a61ede6fbd628c7dc160eb36278cf41c96484c/pint/util.py#L644

A patch would be appreciated.
