### ISSUE TITLE
adding packets and Gbps units to the default

### ISSUE THREAD

**Issue by manatbay** [hgrecco/pint#1585]
I have added non-default 'packets' unit and 'gbps' (gigabits/sec) to the units, it it appropriate to add these to default_en.txt?

unit_registry = pint.UnitRegistry()
unit_registry.define('packets = count')
unit_registry.define('Gpbs = bit * giga')

**Comment by OrangeChannel** [comment]
bits per second is already defined. https://github.com/hgrecco/pint/blob/208d36a5bb051465296dad846296bb19628e2307/pint/default_en.txt#L141
Pint can parse prefixes. Try `unit_registry('4 Gbps')` or `4 * unit_registry.Gbps`.
