### ISSUE TITLE
Missing wheels for 0.19.x releases

### ISSUE THREAD

**Issue by gverm** [hgrecco/pint#1586]
When installing Pint I noticed that a wheel wasn't used, but looking on PyPi I saw that the 0.18 release did have one. Would it be possible to have them for these releases and/or future releases?

**Comment by jules-ch** [comment]
@hgrecco, can you fix this with uploading a wheel for this version ?

**Comment by hgrecco** [comment]
Did this a while ago. Forgot to close.
