### ISSUE TITLE
Make physical constants more easily accessible

### ISSUE THREAD

**Issue by rkingsbury** [hgrecco/pint#159]
It may be helpful to have a more direct way to access the value of a physical constant from pint. As it stands, one has to convert a constant before being able to see its actual value.

For example, with speed_of_light:

```
In [53]:   ureg.speed_of_light
Out[53]: 1 speed_of_light           # I would expect this to return 299... meter/second

ureg.speed_of_light.magnitude
Out[54]: 1                                   # I would expect this to return 299...

ureg.speed_of_light.dimensionality
Out[55]: <UnitsContainer({'[length]': 1.0, '[time]': -1.0})>
```

In order to actually retrieve the value of speed_of_light, I have to convert it:

```
ureg.speed_of_light.to('meter / second')
Out[56]: 299792458.0 meter/second 
```

Please consider changing this behavior, if it can be done without breaking other things.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if neeeded.
