### ISSUE TITLE
Precision representation problem after adding when using non_int_type=decimal.Decimal

### ISSUE THREAD

**Issue by darwintree** [hgrecco/pint#1590]
Hello, I'm using pint to deal with cryptocurrency uint conversions.
Here is my definition txt

```
Wei = [value]
ETH = 10**18 * Wei
```

As you can see, it defines `10^18 Wei = 1 ETH`. And here is my code

```py
import pint
import decimal
ureg = pint.UnitRegistry(non_int_type=decimal.Decimal)
ureg.load_definitions("./def.txt")

print(1 * ureg.Wei + 2 * ureg.Eth)
# 2000000000000000001.0 Wei
```

No value minor to 1 is specified, but the representation of the result is `2000000000000000001.0 Wei` rather than `2000000000000000001 Wei`. Is there any method to fix the problem? Thank you

**Comment by OrangeChannel** [comment]
Can't take a deeper look at this at the moment but I can tell you that exponentiation of ints results in a float in python. Try representing 10^18 as 100000... etc.

**Comment by darwintree** [comment]
> Can't take a deeper look at this at the moment but I can tell you that exponentiation of ints results in a float in python. Try representing 10^18 as 100000... etc.

The result doesn't change after changing the definition to 
```
Wei = [value]
ETH = 1000000000000000000 * Wei
```

Besides, the result is similar even I change the definition to 

```
Wei = [value]
ETH = 10 * Wei
```

whose result is `21.0 Wei`

**Comment by hgrecco** [comment]
Because numbers were casting into floats and therefore their default representation includes decimal numbers.

Take a look at this to learn how to select the string format: https://pint.readthedocs.io/en/stable/tutorial.html#string-formatting
