### ISSUE TITLE
Magnitude is a confusing name

### ISSUE THREAD

**Issue by vankessel** [hgrecco/pint#1598]
I see this was discussed (#525), but to add, I think using magnitude to refer to the raw quantity is only appropriate when talking about physical quantities in a general sense (like a wikipedia summary, or designing this framework), but not when actually using this framework to crunch numbers.

Quantities in this framework have both real and imaginary components. If I have a quantity of 1-i of some unit, I would expect magnitude to return sqrt(2) not 1-i, especially when my ide is suggesting `.real` and `.imag` alongside `.magnitude`.

Magnitude should always be positive. If you allow vectors to have a negative magnitude you get a double cover. And scalars are just vectors in disguise (both are tensors). Scalars just have a binary direction. This may seem arbitrary, but it's really just the same thing how the equator of a sphere is a circle, but the equator of a circle is just two discrete points.

Thanks for listening, do what you like not super invested just think it's a silly name over something like value.

**Comment by hgrecco** [comment]
The current [NIST guideline](https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-7-rules-and-style-conventions-expressing-values) state:

> The value of a quantity is its magnitude expressed as the product of a number and a unit, and the number multiplying the unit is the numerical value of the quantity expressed in that unit.

So in that sense you are (partly) right. The NIST name for Pint's magnitude would be `numerical_value` but not just `value`. But I would also mention that NIST use the word magnitude things that can be negative, complex, etc.
