### ISSUE TITLE
Pint-Pandas support

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint#1599]
Since pandas 1.4 https://github.com/pandas-dev/pandas/pull/44626, the ndim attribute of a object is used to identify the object as a scalar. (thanks @burnpanck!) 

Adding an ndim attribute that defaults to 0 for scalars with magitudes that don't have an ndim attribute defined, along with adding DataFrame to pint's upcast types allows pint-pandas to pass all pandas' extension tests! https://github.com/hgrecco/pint-pandas/pull/133

I've added these changes here https://github.com/hgrecco/pint/pull/1596. It would be great to also have a new pint version for pint-pandas to require once these changes are merged.

**Comment by MichaelTiemannOSC** [comment]
That's great news!  I certainly spent a lot of time chasing my tail on this issue...
