### ISSUE TITLE
UnitsContainer print

### ISSUE THREAD

**Issue by romarro** [hgrecco/pint#160]
Hi I want to print only the units of a quantity (for a label in a plot). But it doesn't print the abbreviated units  even if I am formatting it with ~
here is the code:
>>> from __init__ import um,Q_
>>> x=125.3*um['l/s']
>>> print x
125.3 l/s
>>> x.units
<UnitsContainer({'liter': 1.0, 'second': -1.0})>
>>> print x.units
liter / second
>>> print '{:~}'.format(x.units)
liter / second
>>> print '{:~L}'.format(x.units)
\frac{liter}{second}

But with latex formatting works
is there a workaround?

Thanks for help

**Comment by hgrecco** [comment]
I think the current is fixed in develop. Please reopen if you find any problem.
