### ISSUE TITLE
Rate of change of temperature to be done manually?

### ISSUE THREAD

**Issue by defencedog** [hgrecco/pint#1612]
As per the [documentation](https://pint.readthedocs.io/en/0.7.2/nonmult.html)  

> The parser knows about delta units and uses them when a temperature unit is found in a multiplicative context. 

But I am not getting deired effect

```
ureg = pint.UnitRegistry(autoconvert_offset_to_baseunit = True)
Teasy=25.4 * ureg.degC
Teasy/(5*ureg.m)  # 59.709999999999994 kelvin/meter
rate=Teasy/(5*ureg.m); rate.to(ureg.delta_degC/ureg.m)  # 59.709999999999994 delta_degree_Celsius/meter
```
Now I have to convert (the last line) to get desired unit output?

**Comment by dalito** [comment]
Shouldn't `Teasy` be defined with a delta unit? For example, a heat expansion coefficient has the dimension length/delta_temperature.

**Comment by defencedog** [comment]
@dalito Not necessarily,  `Teasy` is a `source` (constant) temperature that for instance is to be spread across a unit `length`

**Comment by dalito** [comment]
Out of interest: What is the physical problem?

I think what you cite from the docs is not relevant.  In your example you don't use the parser.

**Comment by defencedog** [comment]
@dalito say a steam source is available at said temperature (its constant) ...Heat is transferred from this source to  a metal bar of said length.
Of course I will add certain equations but I just want to know beforehand if pint will provide results in deg_change or not

**Comment by dalito** [comment]
This is still a bit vague. Just 2 examples:

You may have absolute start (or end) temperature but the temperature change resulting from heat-transfer coefficient (or heat capacity) will be a delta_temperature that is added (or subtracted) from the absolute start temperature. Of course heat_transfer coefficient or heat-capacity have to be defined with delta units.

In another scenario, you may have both the start and the end temperature given. If you subtract the two absolute temperatures, pint will give you a delta_temperature which you can use to e.g. calculate a heat transfer coefficient of the insulation.

**Comment by defencedog** [comment]
@dalito thanks for the input. But still I be very careful what i input in this pint especially with temperature dimension. One typo & results become erroneous.

I come from the background of using `SMATH STUDIO` they got these temperature stuff & I recall it was very buggy
