### ISSUE TITLE
Base Units aren't automatically recasted to Compounded Units & Vice Versa

### ISSUE THREAD

**Issue by defencedog** [hgrecco/pint#1613]
```
import pint
unt = pint.UnitRegistry(autoconvert_offset_to_baseunit = True)
Q_ = unt.Quantity
import numpy as np
multimass=np.array([ [10,100,1000] ])*unt('kg')
accel= 5*unt('N') / multimass
```
Now `accel` is returned in `newton/kilogram` I have to convert it to `m/s**2` using `.to` or `.ito` 
Also `accel.to_base_units` doesn't convert it to `m/s**2`

**Comment by jules-ch** [comment]
I don't have any problem with your code :

```python
>>> import pint
>>> ureg = pint.UnitRegistry(autoconvert_offset_to_baseunit=True)
>>> Q_ = ureg.Quantity
>>> import numpy as np
>>> multimass = np.array([[10, 100, 1000]]) * ureg("kg")
>>> accel = 5 * ureg("N") / multimass
>>> accel
<Quantity([[0.5   0.05  0.005]], 'newton / kilogram')>
>>> accel.to_base_units()
<Quantity([[0.5   0.05  0.005]], 'meter / second ** 2')>
```

To base units, returns m.s**-2 as expected

**Comment by defencedog** [comment]
@jules-ch  How one determines what is a `base unit`
```
In [10]: Charge= 10*unt('C')

In [11]: Dur= 5*unt('s')
                                                                                                                                                                                      In [12]: Amp=Charge/Dur; Amp
Out[12]: 2.0 <Unit('coulomb / second')>

In [13]: Amp.ito(unt('A'))

In [14]: Amp.to_base_units()
Out[15]: 2.0 <Unit('ampere')>
```

**Comment by jules-ch** [comment]
By default, pint uses the SI (International System of Units), it is defined by 7 base units & dimensions.
Any physical quantities can be defined by those 7 dimensions & units.

See [https://en.wikipedia.org/wiki/International_System_of_Units & ](https://www.bipm.org/en/measurement-units) if you want to know more about how those units are defined.


If you want to use other systems, you can. Some are already defined or if you want to use yours you need to map those seven dimensions with your own units.

https://pint.readthedocs.io/en/stable/systems.html

**Comment by jules-ch** [comment]
About the Ampere, it is the base unit of current in the International system.
