### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by Alexxxyy** [hgrecco/pint#1620]
'__version__': '0.19.2'

from pint import  Quantity

Quantity("3.6*10**04 mg/L")
Out[40]: 
14.4 <Unit('milligram / liter')>

**Comment by hgrecco** [comment]
The problem here is the leading `0` in the exponent.

```python
>>> ureg.Quantity("3.6*10**4 mg/L")
<Quantity(36000.0, 'milligram / liter')>
```

It is a problem with pint_eval module, which can be reduced to this example:
```python
>>> from pint.pint_eval import build_eval_tree
>>> from pint.compat import tokenizer
>>> f = lambda s: build_eval_tree(tokenizer(s)).to_string()
>>> f("10**4")
'(10 ** 4)'
>>> f("10**04")
'((10 ** 0) 4)'
```


By the way, Pint is allowing something that Python does not.
```python
>>> 10**04
  File "<stdin>", line 1
    10**04
         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by hgrecco** [comment]
We follow Python's ways here. Feel free to reopen if another problem is found
