### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint#1623]
I'd like to release a new version of pint-pandas. This will need a new release of pint to use as a requirement so it has the changes from #1596. Could a new version of pint be released?

**Comment by hgrecco** [comment]
Hi my plan is to wait until tomorrow, when Python 3.11 is [released](https://peps.python.org/pep-0664/). Make sure that all tests run properly against 3.11 in github and then make a release. What do you think? 

cc: @jules-ch

**Comment by andrewgsavage** [comment]
sounds great

**Comment by hgrecco** [comment]
I recently [added](https://github.com/hgrecco/pint/commit/6425ee08b8b453ee84847f0849847c4d198bcd54) "3.11-dev" to ci. Maybe you can do the same for pint-pandas just to get ahead. I am working on the hypothesis that if it works with 3.11-dev (which now corresponds to 3.11-rc2), it should work with 3.11.

**Comment by hgrecco** [comment]
Done (including the wheel). Please test it and let me know.

**Comment by jules-ch** [comment]
Closing
