### ISSUE TITLE
Contributor instructions can be improved (babel-2.8 and pytest-subtests)

### ISSUE THREAD

**Issue by tovrstra** [hgrecco/pint#1624]
I believe the following should be added to [`contributing.rst`](https://github.com/hgrecco/pint/blob/master/docs/dev/contributing.rst)

- Some mention of the babel version (2.8).
- Install instruction for `pytest-subtests` (but recommend using `pytest.mark.parametrize` instead).

I'm not sure how a newer version of babel got installed in my venv, probably through some dependency. (That would be good to understand). It could also be helpful to just refer to [`.github/workflows`](https://github.com/hgrecco/pint/tree/master/.github/workflows), but these are not as easy to follow for everyone, and probably too detailed. With the above two, I got the tests to work.

I also got the impression that the docs instructed to go into `pint/pint`, but this didn't turn out to be needed. Maybe remove this?

The `contributing.rst` page also mentions travis-ci, but I assume that is historical.

**Comment by hgrecco** [comment]
Pint does not install any dependencies in its standard version. If you follow the [contributing.rst](https://github.com/hgrecco/pint/blob/master/docs/dev/contributing.rst) everything listed under test extra requires will be installed. [This](https://github.com/hgrecco/pint/blob/bb7fcb6ce9ec1eea5bb1029f3f6c728cbfdd91d1/setup.cfg#L36) includes pytest-subtests.

In relation to optional packages, it might be a good idea to list them or reference them here. I think it would be better to reference (setup.cfg) to avoid having multiple places.

By the way, babel is not listed as extras in setup. I will open another issue.

Indeed, travis reference should be removed.

**Comment by tovrstra** [comment]
Thanks for pointing out the extras. I followed the instructions in [contributing.html](https://pint.readthedocs.io/en/stable/contributing.html) on readthedocs, but I should have followed the [`conctributing.rst`](https://github.com/hgrecco/pint/blob/master/docs/dev/contributing.rst) on GitHub instead.

**Comment by jules-ch** [comment]
Reference to travis has been removed in the latest version of the docs.
We will make a release soon.
I'm going to close this issue, we can follow this in #1627

**Comment by tovrstra** [comment]
Ok. Thanks!
