### ISSUE TITLE
Different Output of pi_theorem method for Pressure Loss in Pipe compared to Docs

### ISSUE THREAD

**Issue by edibotopic** [hgrecco/pint#1626]
The small problem I am having relates to implementing the [second documented example](https://pint.readthedocs.io/en/stable/pitheorem.html#pressure-loss-in-a-pipe) of the `pi_theorem` method.
Below is the example taken directly from the *stable* version of the docs:

```python
import pint

ureg = pint.UnitRegistry()
ureg.pi_theorem({'p': '[pressure]',
                 'L': '[length]',
                 'D': '[length]',
                 'd': '[mass]/[volume]',
                 'm': '[viscosity]',
                 'v': '[speed]'
                 })
```

This outputs the following when run in my text editor:

```
[{'p': 1.0, 'L': 2.0, 'd': 1.0, 'm': -2.0},
 {'p': -1.0, 'd': 1.0, 'v': 2.0},
 {'L': -1.0, 'D': 1.0}]
```

The second and third quantities seem to correspond to the [head loss parameter and ratio of pipe length to diameter](https://projects.exeter.ac.uk/fluidflow/Courses/FluidDynamics3211-2/DimensionalAnalysis/dimensionalLecturese4.html).
However, in the [relevant section of the docs](https://pint.readthedocs.io/en/stable/pitheorem.html#pressure-loss-in-a-pipe) the output also includes the Reynold's number in its typical form (the second quantity):

```
[{'p': 1.0, 'm': -2.0, 'd': 1.0, 'L': 2.0},
{'v': 1.0, 'm': -1.0, 'd': 1.0, 'L': 1.0},
{'L': -1.0, 'D': 1.0}]
```

Why is my output different to the docs? I hope I haven't missed something obvious.
Perhaps this is just a documentation issue, and the output in the example should reflect more closely what will be output for the user?

I do not have this issue when applied to the more simple example of [the pendulum](https://pint.readthedocs.io/en/stable/pitheorem.html#application-to-the-pendulum).

---

I am using Python 3.8.10 and Pip-installed Pint 0.19.2 in a virtual environment.

Otherwise, much thanks to the creator and contributors for developing such a useful library :+1:

**Comment by hgrecco** [comment]
I am not able to test this right now, but I can tell you that Pi Theorem solutions are not unique

If I remember correctly, Pint just finds one. The solution that it obtains when resolving the linear system depends on how you walk through it. While iteration order now only depends on the insertion order, before Python 3.6 (2016) this was not guaranteed.

This code is 10 years ago, and I guess the docs are well. So my best guess is that this change in the iteration order is the reason.

**Comment by edibotopic** [comment]
Got it. After some follow-up testing I see that different sets of dimensionless terms are outputted depending on the order in which the quantities are entered into the `pi_theorem` method, with a problem that has multiple solutions (pressure loss in a pipe).

I assume Pint is designed to output *a* solution rather than *all* solutions, and I know there are some alternative implementations that do the latter.

Thanks for your help.

**Comment by hgrecco** [comment]
I would love to have a way to output all non-trivial solutions. If you want to add it, feel free to open a PR.
