### ISSUE TITLE
Listing extra requirements in setup.cfg

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#1627]
I have noticed that our extra requirements is inconsistent. It currently looks like this.

```
numpy = numpy >= 1.19.5
uncertainties = uncertainties >= 3.1.6
test =
    pytest
    pytest-mpl
    pytest-cov
    pytest-subtests
```

Pint interacts with more projects (if available), not just numpy and uncertainties. My suggestion would be to include as independent lines everything that is optional: babel, pandas (which should install pint-pandas), xarray, dask.

**Comment by hgrecco** [comment]
Which versions should we specify for each package. The minimal would be:
```
[options.extras_require]
numpy = numpy >= 1.19.5
uncertainties = uncertainties >= 3.1.6
babel = babel >= 2.8
pandas = pint-pandas
xarray = xarray
dask = dask
test =
    pytest
    pytest-mpl
    pytest-cov
    pytest-subtests
```
but maybe we should be more strict?

**Comment by andrewgsavage** [comment]
pint-pandas >= 0.3

**Comment by jules-ch** [comment]
babel <= 2.8 for now
