### ISSUE TITLE
Intersphinx issue

### ISSUE THREAD

**Issue by dopplershift** [hgrecco/pint#1637]
With the release of 0.20, `pint.Quantity` and `pint.Unit` no longer appear in the intersphinx catalog (`objects.inv`) and can't be linked in other sphinx docs any more. I get errors like:
```
 WARNING: py:obj reference target not found: pint.Quantity
```

**Comment by dcamron** [comment]
Coming from the same discovery, #1474 removed the top-level `pint` automodule, removing those references and any documentation of those classes in the [API docs](https://pint.readthedocs.io/en/stable/api.html).

**Comment by marscher** [comment]
Actually the top-level pint module aliases Quantity and Unit, but since Sphinx inspects the `__module__` attribute, both objects will not be contained in the documentation, right?

The docs still contains the automodule instruction though:

```===================
Developer reference
===================

All Modules
===========

.. automodule:: pint
    :members:
```

But as a I said before, both objects of interest won't be collected for the members list.

**Comment by marscher** [comment]
Mhm, I just saw, that #1638 will introduce lots of changes. Will there be a new release soon after this has been merged?

**Comment by hgrecco** [comment]
Ok. This has been fixed now
```
$  python -m sphinx.ext.intersphinx ~/Downloads/objects.inv | grep pint.Quantity
	pint.Quantity                            api/base.html#pint.Quantity
```

I will release a new version as soon as tests are done.

**Comment by marscher** [comment]
really fast roll-out! Thank you so much!!

**Comment by hgrecco** [comment]
You are welcome 0.20.1 is out.

I have started a section in the docs to explain how to test continuously against upstream pint. The goal is to catch as many issues as possible before the release.

https://pint.readthedocs.io/en/stable/getting/pint-in-your-projects.html#keeping-up-to-date-with-pint-development

**Comment by dopplershift** [comment]
@hgrecco Just FYI, `pint` itself is not listed as a module in `objects.inv`. We'll work around it in MetPy's docs, so no worries, but wanted you to be aware.
