### ISSUE TITLE
Breaking change not mentioned in changes, is there an easy way to support both Pint0.19 and 0.20?

### ISSUE THREAD

**Issue by MauriceHendrix** [hgrecco/pint#1641]
The latest release  (0.20) caused a breaking change Is there an easy way for our project to support both pint 0.19 and 0.20?
It seems to do with a few things not mentioned in the change log. 

Errors we have seen:
`from pint.converters import ScaleConverter` class not found, it seems this was relocated to `pint.facets.plain.definitions.ScaleConverter`?
`from pint.definitions import UnitDefinition` class not found, it seems this was relocated to `from pint.facets.plain.definitions.UnitDefinition`?

'''
definition = UnitDefinition(qname, '', (), ScaleConverter(quantity.to(self._registry.dimensionless)))
E           TypeError: __init__() missing 1 required positional argument: 'reference'
'''
Reference used to be optional, before I beleive?

**Comment by hgrecco** [comment]
The API to programmatically define units, dimensions, etc has not been really stabilized yet. But now that the parser has been split, I think we are ready to do this.

My idea would be:
1. import all relevant things into a module or modules (i.e. converters and definitions, or just definitions)
2. point people to call `ureg.define(obj)` where obj is an instance of any of the definition classes.

For the time being you can just do:
 definition = UnitDefinition(qname, '', (), ScaleConverter(quantity.to(self._registry.dimensionless)))

**Comment by MauriceHendrix** [comment]
@hgrecco yes that's what I figured, but what imports would I use? Is there a correct set of imports that will work for both pint 0.19 and 0.20?

**Comment by hgrecco** [comment]
I was sure that the facets change was going to bring some trouble, that is why we stalled the release. But it was worth it as we can now hack the code much easier. How about trying to release a 0.20.2 that brings this back?

**Comment by MauriceHendrix** [comment]
It would be really nice tbh not to have to do the following if possible
```
try:
    from pint.converters import ScaleConverter
except ImportError:
    from pint.facets.plain.definitions import ScaleConverter
```

I would just move to requiring Ping 0.20+ but unfortunately the powers that be require us to still support Python 3.6 & 3.7 
https://chaste.cs.ox.ac.uk/trac/wiki/InstallGuides/DependencyVersions

**Comment by jules-ch** [comment]
@hgrecco do you want to bring back definitions & converters back with all of the dataclasses with it to fix this issue ?

**Comment by hgrecco** [comment]
Feel free to reopen if another problem is found
