### ISSUE TITLE
pint.readthedocs.io "Getting Started" Link

### ISSUE THREAD

**Issue by DanKremer** [hgrecco/pint#1649]
Apolgies if this shouldnt go here. The "Getting Started" square button links to:
[https://docs.scipy.org/doc/scipy/getting_started.html](https://docs.scipy.org/doc/scipy/getting_started.html)
instead of:
[https://pint.readthedocs.io/en/stable/getting/index.html](https://pint.readthedocs.io/en/stable/getting/index.html)

Dan

**Comment by jules-ch** [comment]
Yes it has been fixed but we need to make a release to get it fixed in the
stable page

**Comment by jules-ch** [comment]
See #1639

**Comment by jules-ch** [comment]
One way to do it is to create a tag as a post release according to PEP440 https://docs.readthedocs.io/en/stable/versions.html @hgrecco. Readthedocs will build it as stable even if we do not make a release on PyPI.
That's an option.

Or we wait the next release which will fix those links

**Comment by jules-ch** [comment]
I'm closing this, we will make a release soon to patch this.
We just need to make a new read the docs build
