### ISSUE TITLE
Compass direction (discrete  unit)

### ISSUE THREAD

**Issue by stustd** [hgrecco/pint#1650]
How would I go about specifying a unit in `pint` for compass_direction, i.e. mapping string_codes to a discrete set of (float) degrees:
```
compass_direction2degrees = dict(
       N=0.0, NNE=22.5, NE=45.0, ENE=67.5, E=90.0, ESE=112.5, SE=135.0, SSE=157.5,
        S=180.0, SSW=202.5, SW=225.0, WSW=247.5, W=270.0, WNW=292.5, NW=315.0, NNW=337.5,  # N=360
    )
```

**Comment by jules-ch** [comment]
Direction units are already implemented (radians & degrees).
I'd advise to work with those.

If you need to get direction as string, you can use a function that will take input in degrees (azimuth conventions, 0 is north, 180 South, Est 90°) and ouput the string you need.

**Comment by jules-ch** [comment]
Search for `degrees to cardinal` there are plenty of function already implementing this.

**Comment by stustd** [comment]
> Search for `degrees to cardinal` there are plenty of function already implementing this.
But what, if for readability reasons, I also want to store compass direction ('N', 'NW', etc) as a column in a csv file? I can't assign a [radians] or [degrees] unit to it... A custom [compdir] unit convertible to a discrete set of [radians] or [degrees] would be the solution. Is that possible with pint?

**Comment by jules-ch** [comment]
I'd argue, these are not units. Units by definition is used to quantify something.
Directions or any other kind of warm/cold like you said are there to categorize your data.

You can store them in your csv, just do not assign a unit to it.

**Comment by stustd** [comment]
> I'd argue, these are not units. Units by definition is used to quantify something. Directions or any other kind of warm/cold like you said are there to categorize your data.
> 
> You can store them in your csv, just do not assign a unit to it.

See your point, thanks!
