### ISSUE TITLE
dead link to pint-pandas

### ISSUE THREAD

**Issue by RobbesU** [hgrecco/pint#1651]
The link in pint-pandas jupyter notebook under Pandas Integration in the docs, going to `https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pandas_support.ipynb` via the results in a '404 page not found'. Might be looking for `https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pint-pandas.ipynb` ?

**Comment by jules-ch** [comment]
Are you on the last version of the documentation I can't find any dead links ?
Can you point to the URL where you found the deadlink

**Comment by RobbesU** [comment]
Apologies. Link is at the bottom of the https://github.com/hgrecco/pint/blob/master/README.rst  
>Pandas integration: Thanks to [Pandas Extension Types](https://pandas.pydata.org/pandas-docs/stable/extending.html#extension-types) it is now possible to use Pint with Pandas. Operations on DataFrames and between columns are units aware, providing even more convenience for users of Pandas DataFrames. For full details, see the [pint-pandas Jupyter notebook](https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pandas_support.ipynb).

**Comment by jules-ch** [comment]
Thanks, do you want to make a PR to fix this ? :)

**Comment by RobbesU** [comment]
Never done one, but can try.  😉

Regards,
Rob Urselmann
________________________________
