### ISSUE TITLE
Quantity module import not found in 0.20

### ISSUE THREAD

**Issue by James-Wickenden** [hgrecco/pint#1656]
Hi,

In Pint 0.20 and pint-pandas 0.3 the pint.quantity module has been removed, causing our tests to fail.
I'm working around it for the moment by importing pint==0.19.2.

Is there an intended alternative in the pint API going forward? I understand this issue is similar in scope to #1641, so apologies if I'm asking something thats already been asked.

Thanks!

**Comment by hgrecco** [comment]
Feel free to reopen if another problem is found
