### ISSUE TITLE
Change frequency to angular frequency in the docs

### ISSUE THREAD

**Issue by jules-ch** [hgrecco/pint#1659]
We should change `frequency` to `angular_frequency` in the code snippet since we are stating to use `angular frenquency` for quantities in `rad/s` or `rpm`

https://pint.readthedocs.io/en/stable/user/angular_frequency.html

**Comment by rsk2** [comment]
Hi @jules-ch, can I work on this issue?

**Comment by jules-ch** [comment]
Of course :)
