### ISSUE TITLE
Release 0.20.x breaks generics on Quantity

### ISSUE THREAD

**Issue by gerbenoostra** [hgrecco/pint#1662]
Since 0.18, and up to 0.19.*, one could use generics to ensure the magnitude is the right type, and could also including numpy's typing mechanism.

For example:
```
from pint import Quantity
import numpy as np
import numpy.typing as npt

def method(measure1: Quantity[int], measure2: Quantity[npt.NDArray[np.float_]]):
    pass
```
But with 0.20.1 one gets a `TypeError: <class 'pint.util.Quantity'> is not a generic class`

In 0.20.1 I see the following facets:
```
from pint.facets.plain.quantity import PlainQuantity
from pint.facets.numpy.quantity import NumpyQuantity
```
But only `PlainQuantity` is generic, so I don't know how to migrate the `numpy` quantities while preserving the `numpy` arrray type annotations.

Probably related to https://github.com/hgrecco/pint/issues/1641

**Comment by jules-ch** [comment]
I think inheriting NumpyQuantities from PlainQuantity will fix this issue

**Comment by gerbenoostra** [comment]
How is the type hierarchy designed? Should `Quantity` be a descendent of every facet, merging their functionality. Or should each facet inherit from a base `Quantity` that provides the common interface.
Either way, providing a generic version for each to ensure the right measurement type would help in type safety.

**Comment by hgrecco** [comment]
The default `Quantity` inherits from every facet, but is constructed dynamically according to the registries. Maybe we should provide a more static typing friendly version.

**Comment by hgrecco** [comment]
Feel free to reopen if needed
