### ISSUE TITLE
Defining units under ```auto_reduce_units=True``` generates strange units after multiplication

### ISSUE THREAD

**Issue by JosePauloSavioli** [hgrecco/pint#1666]
I generally use 'm3' for cubic meters as this is how it is stored in most data I use. Due to that, I usually define it in pint's UnitRegistry using `up.define('m3 = 1 * m**3')`. Lately, I have come across a strange unit generated by a multiplication, the basic case being:
```python
import pint

# happens only with the option to auto_reduce_dimensions
up = pint.UnitRegistry(auto_reduce_dimensions=True)
up.define('m3 = 1 * m**3')

z = up.Quantity(1, 'ha') * up.Quantity(1, 'kg/m3')
print(z)
```
Which yields `10000.0 kilogram / m3 ** 0.333333` as result. I get the unit is technically correct (it is a cubic root of a cubic meter, which is a meter), but is there a way to make 'm3' behave as 'm**3'?

Side note 1: The number '3' at 'm3' doesn't seem to make any difference since renaming the new unit to 'mmmm' would yield the same result.

Side note 2: Changing the side of multiplication and doing:
```python
import pint

# only with option to auto_reduce_dimensions
up = pint.UnitRegistry(auto_reduce_dimensions=True)
up.define('m3 = 1 * m**3')

z = up.Quantity(1, 'kg/m3') * up.Quantity(1, 'ha')
print(z)
```
Yields `1000000.0 kilogram / hectare ** 0.5`, which continues with the strange units.

**Comment by keewis** [comment]
`metpy` and `cf-xarray` contain a unit preprocessor that changes all units of format `m3` (unit followed by a number without a space) to `m ** 3` (put `import cf_xarray.units` if you wish to use that, but if all you need is the preprocessor I guess you can just copy that?)
```python
preprocessors=[
        functools.partial(
            re.compile(
                r"(?<=[A-Za-z])(?![A-Za-z])(?<![0-9\-][eE])(?<![0-9\-])(?=[0-9\-])"
            ).sub,
            "**",
        ),
    ],
```

Otherwise, you might be able to explicitly call `.to_base_units()` on the result?

**Comment by JosePauloSavioli** [comment]
The ```preprocessor``` worked great for me and avoids the multiple ```define``` for this kind of aliases. ```to_base_units()``` worked as well but only after the multiplication is done, so I think for several calculations ```preprocessor``` works better.

The result in Side note 2 seems to be the expected for reduced units, but the ```m3 **0.333333``` was converted as expected to ```meter```. 

Thanks!
