### ISSUE TITLE
.to_reduced_units() doesn't reduce as expected

### ISSUE THREAD

**Issue by UncleOwen** [hgrecco/pint#1675]
Given the following code
```python
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity

a = Q_(1, 'watthours')
b = Q_(1, 'watt')
c = a/b

print(c.to_reduced_units())
```
I'd expect an output of `1.0 watt`. However, pint-0.20.1 outputs `1.0 watt_hour / watt`, which, while technically correct, is quite comical.

If I define a as
```python
a = 1 * ureg.watt * ureg.hour
```
instead, it works as expected.

**Comment by hgrecco** [comment]
Finding the best representation is not straight forward. I would love to have a better way, and open to suggestions.
