### ISSUE TITLE
Modulo fails on negative numbers

### ISSUE THREAD

**Issue by bededict-cumberbach** [hgrecco/pint#1689]
### Problem:
pint returns a wrong value for modulo of a negative number.

### Minimal Example:
```
from pint import UnitRegistry
u = UnitRegistry()

foo = -180 % 360
print(foo)
>> 180
bar = -180 * u.deg % 360
print(bar)
>> 20446.480624709635 degree
```

### Versions:
python = 3.9.0
pint = 0.20.1

**Comment by jules-ch** [comment]
You should use :

```python

bar = -180 * u.deg % 360 * u.deg
```

Or use the magnitude for your operation, pint assume dimensionless as `radians` so it will basically be equivalent to :

-180 degree % 360 radians
