### ISSUE TITLE
Controlling the format of axis label with matplotlib

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [hgrecco/pint#1702]
It'd be nice if users were able to control the format of the units in the axis.

For instance, instead of `bequerel/hour` one may want `Bq/h`.

I believe the format here would need to be exposed.
https://github.com/hgrecco/pint/blob/521dc80fabdacae20d57d9e3dce95e04633894ca/pint/matplotlib.py#L19-L24

What do people think?

**Comment by dopplershift** [comment]
I'm not sure the best way to expose it, but I think making it controllable is a good enhancement.

**Comment by RemDelaporteMathurin** [comment]
I am happy contributing to solve this.

How about something like this?
```python
import pint

ureg = pint.UnitRegistry()
ureg.setup_matplotlib()

ureg.format_matplotlib = "{:P}"
```

**Comment by hgrecco** [comment]
Wouldn't be better if Matplotlib pint extension directly honors the registry selected format?

In a slightly related note, Something I have been playing around after deploying facets, was moving certain features to delegates. It actually started from a suggestion by @maurosilber when talking about the increase of keyword arguments in the Registry. Discussing possible alternatives (attributes that are modified after instantiation), he suggested to move to "composition over inheritance" for this purpose.

```python
class BaseRegistry:

     formatter: DefaultFormatter
```

The registry then will instantiate this class if necessary (or use the object), and formatting configuration will be encapsulated there.

**Comment by RemDelaporteMathurin** [comment]
@hgrecco Maybe I didn't understand your point completely but the idea would be to let users decide on the matplotlib unit formatter. If the `BaseRegistry.formatter` attribute can be modified by users then I suppose that should do the trick!

Then we'd have to somehow pass `formatter` to `PintAxisInfo`.

**Comment by RemDelaporteMathurin** [comment]
Maybe:

```python
class PintAxisInfo(matplotlib.units.AxisInfo):
    """Support default axis and tick labeling and default limits."""

    def __init__(self, units, formatter):
        """Set the default label to the pretty-print of the unit."""
        super().__init__(label=formatter.format(units))
```

**Comment by hgrecco** [comment]
Indeed, I am thinking something along those lines. For the time being, we can deploy now a solution where `PintAxisInfo` is instantiated not only with the units but also with the current registry format.

**Comment by RemDelaporteMathurin** [comment]
I'm afraid because `axisinfo` is a static method we can't access the registry object `PintConverter` was instatiated with and therefore can't instantiate `PintAxisInfo` with a formatter.
For the same reason, we also can't pass a registry object to `PintAxisInfo` which means storing the formatter as a registry attribute wouldn't work either.

Any thoughts?

**Comment by keewis** [comment]
`Unit` objects are always associated with a registry, so you can pull the registry from the `Unit` object: `unit._REGISTRY`

**Comment by hgrecco** [comment]
@keewis exactly

**Comment by RemDelaporteMathurin** [comment]
Good shout. I think I got it to work, will open a PR soon

**Comment by RemDelaporteMathurin** [comment]
Hi all, #1703 is an attempt at closing this.

**Comment by RemDelaporteMathurin** [comment]
Anyone having time to have a gander at #1703?
