### ISSUE TITLE
list of Quantities not supported in matplotlib 

### ISSUE THREAD

**Issue by fthorey** [hgrecco/pint#1706]
Trying to plot the following:

```
a = Q_(1, 'Pa')
b = Q_(2, 'Pa')
c = Q_(3, 'Pa')

ax.plot([a, b, c], [a, b, c])
```

raise the following exception:

```
DimensionalityError: Cannot convert from 'pascal' to 'dimensionless'
```

It would be nice to add support of lists

**Comment by dopplershift** [comment]
That's really difficult because that's going to get passed to numpy with `np.array([a, b, c])`, which ends up (I think) creating an array with an object type.

Is there any reason you can't do:

```python
a = 1
b = 2
c = 3

x = y = Q_([a, b, c], 'Pa')

ax.plot(x, y)
```
?

**Comment by fthorey** [comment]
Thanks for the quick answer ! and sorry for the late feedback, I just came across it :(

For x I sure can do what you suggest, but what if I use list comprehension to generate y as f(x) ?

```
x = Q_([a, b, c], 'Pa')
y = [f(s) for s in x]
```

I get a list of Quantities instead of a Quantity array for y.

in my case f is wrapped using the decorator @ureg.wraps because I'm making call to external libraries (and in particular using scipy.optimize module) which doesn't support Pint so I don't really see another way to generate y.

**Comment by dopplershift** [comment]
If that's the intended use for the output of `f()`, I'd avoid using `wraps`. If there's need to use that elsewhere with units, then I'd just do something like:
```
y = Q_[f(s).m_as('meters') for s in x], 'meters')
```

**Comment by fthorey** [comment]
I didn't know of the function ````m_as(unit)```` and always used ```.to(unit).magnitude```` when in need to use the magnitude. That does the trick indeed although a bit redundant (getting magnitude from values that are already Quantities to convert back to an array Quantity).
