### ISSUE TITLE
Issue with exponential to the exponential. Ex: (m**3)**2

### ISSUE THREAD

**Issue by antopemo** [hgrecco/pint#1707]
Hi there! 

I was playing around with the units and I have come across something weird.
If have a unit elevated to a certain power and I exponentiate it again to another number the result seems wrong.

For example:
`UnitRegistry.Unit('m ** 3') ** 2` gives me `m ** 6` while I would expect it to be `m ** 9`

Am I doing something wrong or this is not working properly?

**Comment by keewis** [comment]
I would actually expect the current behavior: `python` computes `(10 ** 3) ** 2` as `10 ** 6` and `10 ** (3 ** 2)` as `10 ** 9`.
