### ISSUE TITLE
Index of detected units

### ISSUE THREAD

**Issue by DhruvAwasthi** [hgrecco/pint#1709]
The package is awesome. 

Just want to add to the functionality, it would be nice if we can somehow get the index of the detected units. 

What do you think?

**Comment by OrangeChannel** [comment]
https://github.com/hgrecco/pint/issues/1587#issuecomment-1263038564 ? Possible duplicate if I understand right. Maybe we could add a simple ureg property to accomplish this cleaner.

**Comment by DhruvAwasthi** [comment]
#1587 gives the list of all available units but it's not the same.
Yes, maybe we should add a property to accomplish this.

**Comment by dalito** [comment]
Why would you need an index? ...and would you expect that one unit has the same index forever?

**Comment by hgrecco** [comment]
See https://github.com/hgrecco/pint/discussions/1752
