### ISSUE TITLE
Help: for parsing a pattern

### ISSUE THREAD

**Issue by DhruvAwasthi** [hgrecco/pint#1710]
I am trying  to extract the unit out of this string:

`serving size 100 g`

The following regex pattern do just fine for accomplishing above:
`ureg.parse_pattern("serving size 100 g", re.compile("{g} *g"))`

However, when I slightly change the string to:
`serving size 100 100 g`

I get the following error:
`ValueError: could not convert string to float: '100 100'`

Can you please tell me how to capture the second scenario too.

Thanks and best!

**Comment by dalito** [comment]
What would you expect? Should pint multiply 100*100 or just parse the number that is closest to the unit?

**Comment by DhruvAwasthi** [comment]
Parse the number closest to the unit please.
Thank you!

**Comment by dalito** [comment]
It may be helpful for others to change the issue title to reflect that.

**Comment by Tejash-Shah** [comment]
How about just using regex to extract ```100 g``` from ```serving size 100 100 g```

```
import re

sentence = "serving size 100 100 g"
pattern = r"\b(\d+)\s+g\b"
match = re.search(pattern, sentence)
if match:
    serving_size = match.group(0)
    print(serving_size)
else:
    print("No match found.")
```

**Comment by DhruvAwasthi** [comment]
Thank you @Tejash-Shah for the solution. This works.
In the meanwhile, I worked around the solution. But thanks for the help!
