### ISSUE TITLE
Pint does not know the relation between Joule and Watt

### ISSUE THREAD

**Issue by oliviermarti** [hgrecco/pint#1714]
`pint.Quantity ( 1, 'J') / pint.Quantity ('watt')` gives `J/W` and should gives `s`

`pint.Quantity ( 1, 'J') / pint.Quantity ('second')` gives `J/s` and should give `Watt`

`pint.Quantity ( 1, 'W') * pint.Quantity ('second')` gives `1 W/s`and should give `J`

Tested with pint 0.20.1 in python 3.10.8

Would be very nice if this could be improved. 

Is there a way to obtain the desired result in the present version ?

Olivier

**Comment by hgrecco** [comment]
By default Pint does not simplify units. Check out the docs [here](https://pint.readthedocs.io/en/stable/getting/tutorial.html?highlight=auto_reduce_dimensions#simplifying-units)

**Comment by dec8tt8** [comment]
Hello, 
I was running into the same issue.
The documentation is well written.
Here is a piece of code which should help the next pal:

```
import pint

ureg = pint.UnitRegistry()
ureg.default_format = "P"
ureg.auto_reduce_dimensions = True

Q_ = ureg.Quantity

power = Q_(10, "W")
energy = Q_(10, "J")

x = energy / power
print(x)
print(x.to_reduced_units()) # it does not simplify the units, because watt and joule do not share exactly the same dimensionality
print(x.to_base_units())
print(x.to("s")) # does work

print()

latent_heat = Q_(10, "J/kg")
mass_flow_rate = power / latent_heat
print(mass_flow_rate)
print(mass_flow_rate.to_reduced_units()) # it does not simplify the units, because watt and joule do not share exactly the same dimensionality
print(mass_flow_rate.to_base_units())
print(mass_flow_rate.to("kg/s"))
```
