### ISSUE TITLE
Check dimension validity

### ISSUE THREAD

**Issue by sebakahn** [hgrecco/pint#1715]
## Description

I would like to associate a given dimension to a abstract variable, and a unit associated to its value.

The idea is to have a repository of defined variables a given model could use. But not to specify any value/units.

It is quite easy to check if a unit is supported or to get the list of supported units from a dimension.

Is it possible to have a way to check if a given dimension is supported by pint such as

Let's imagine the function `check_dimension` the would implement the functionality

`check_dimension("[length]")`      
returns `True`

`check_dimension("[power]/[length]")`    
returns `True`

`check_dimension("meter")`        
returns `False` as a the input is a unit, not a dimension

`check_dimension("[chewbaka]")`         
returns `False` as chewie is not yet a unit 

As a lot of operation are done based on dimensionality, I imagine there is already a way to get that. But it is hard to find to find from a quick search.

Best regards
Sebastien Kahn

### Update
I found a workaround using `get_dimensionality()`, it however does not error out if units are used instead of a dimension.

I could use some regular expression to remove the text in `[]` keeping `*` and `/` and to see if anything remains, but surely there is better ways if you have access to the unit system.

@shimwell

**Comment by sebakahn** [comment]
If I can don anything to help enabling this, please let me know!

**Comment by sebakahn** [comment]
Dear @hgrecco 

I found a very circumvented, and hence fragile way to get the functionality I wanted defining the following function

``` python
def is_equivalement_dimension(dimension_1: str, dimension_2: str) -> bool: 
    """Check if dimension_1 is equivalent to dimension_2
    
    TODO: TO BE TESTED, especially as it enables a functionality that
        is not explicitly supported by pint (can break with a pint update).

    Parameters
    ----------
    dimension_1: str
        First pint dimension to be tested
    dimension_2: str
        Second pint dimension to be tested

    Returns
    is_equivalent: bool
        True if the dimensions are equivalent (ex: [speed] and [length]/[time])
        False if the dimension are incompatible (ex: [mass] and [speed])
    """
    # Circumventing pint errors for dimensionless quantities
    if dimension_1 == "dimensionless":
        dimension_1 = "[]"
    if dimension_2 == "dimensionless":
        dimension_2 = "[]"

    # Create a dummy quanitity from the dimension used in the check
    dummy_unit, *_ = ureg.get_compatible_units(dimension_1)
    dummy_unit = str(dummy_unit)
    dummy_quantity = ureg.Quantity(1.0, dummy_unit)

    # Check the dimension of the dummy quantity
    is_equivalent = dummy_quantity.check(dimension_2)

    return is_equivalent
```

**Comment by hgrecco** [comment]
Sorry for the late reply. I think it would be better to use `pint.util.ParseHelper`, and `is_dim` and then `get_dimensionality`

**Comment by hgrecco** [comment]
I am closing this, feel free to open.
