### ISSUE TITLE
Defining miligram per cent (mg%)

### ISSUE THREAD

**Issue by mac93pl** [hgrecco/pint#1717]
Hi! Great package 💪

I'm currently exploring Pint possibilities in medical field and stumbled upond a problem with adding support for "mg%" measure. 
It's rather depricated, but in some cases still in use ( [https://en.wikipedia.org/wiki/Milligram_per_cent] )
The problem is that I can't simply register "mg%" unit symbol, due to definition error `DefinitionSyntaxError('missing unary operator "%s"' % op_text)`.

I tried different approaches (#1402, #379, #429) but non of them works in my case and in most cases it somehow ends up with the error above.

One thing that worked in some cases was to append the definition to default_en.txt as:
`miligrampercent = mg/dL = mg%`
But even then ureg checkup or `.to(ureg['mg%'])`doesn't work (same error).

I use the packeage to convert quantities based on provided string and in almost all cases it works perfectly except this one. Seem like I can simply replace string from "mg%" to eg "miligrampercent" before defining it in Pint and again, after obtaining the result, replace "miligrampercent" to "mg%" in some caseses, but it doesn't looks like the most elegent solution.

**Comment by lafrech** [comment]
Not sure but this might have been solved in master already while introducing % and ppm (not released yet). Would you like to try master branch to confirm?

**Comment by mac93pl** [comment]
Thanks @lafrech - it looks like the new version supports useage of "%" in such definitions!
