### ISSUE TITLE
Possibility to check for Quantity (regardless of dimension) in decorator

### ISSUE THREAD

**Issue by tirolerstefan** [hgrecco/pint#1723]
Currently, I use the decorator `@ureg.check` for checking dimensionalities, which works very well.
Now, I have a use case where I want to accept *any* pint quantities to my function, regardless of the dimension. I'd like to display the object's magnitude (`obj.m_as`), separated from the unit (`obj.u`) in separate widgets on a GUI.

Is there a possibility using the existing decorators, to perform this check - maybe something like:

```py
@ureg.check(Quantity)
def display_quantity(q):
    # do something with q
```

If not currently possible, would this be a use case for other users, too, worth to implement?

**Comment by hgrecco** [comment]
Is not possible now, but might be something to think about.

See #1753
