### ISSUE TITLE
Parsing with powers: bug of feature?

### ISSUE THREAD

**Issue by rcaneill** [hgrecco/pint#1730]
Hello,

I ran into a case where I use pint to parse a unit with exponents, and I don't know if the result is a bug or a feature.

Example:

```python
from pint import UnitRegistry
ureg = UnitRegistry()
```

```python
ureg('(m/s)(m/s)^-1')
```
outputs
```
1.0 second2/meter2
```
I would have expected the power to be applied to the right parenthesis (as exponents usually have the bigger precedence), and not to the whole result.

I can get it work the way I thought with:
```python
ureg('(m/s)*(m/s)^-1') # add a multiplication between parenthesis
# or
ureg('(m/s)((m/s)^-1)')
```

pint version is 0.20.1.

PS. I am aware of the treating of units with the same precedence as number as described in the doc https://pint.readthedocs.io/en/stable/user/defining-quantities.html
PPS. I get the same result if I use `**` instead of `^` for exponent

**Comment by rcaneill** [comment]
PPS. `ureg('m m^-1')` works well and returns dimensionless number, as expected

**Comment by keewis** [comment]
this seems like a bug in `pint.pint_eval.build_eval_tree`: since there's no token between the parens it will not check the operator priority (but treat it as multiplication anyways), and so the result is the same as `((m/s)*(m/s))^-1`.

To fix that I think what could insert a token (`*`) if a closing paren is followed by a open paren. Something like
```python
...
elif token_text == "(":
    if index > 0 and tokens[index - 1].string == ")":
        new_token = current_token._replace(string="*")
        tokens.insert(index, new_token)
        continue
...
```
Not sure if there's less hacky solution, though

**Comment by jthielen** [comment]
This looks like the same issue as https://github.com/hgrecco/pint/issues/1485? Perhaps we could consolidate the bug reports.

**Comment by rcaneill** [comment]
> This looks like the same issue as #1485? Perhaps we could consolidate the bug reports.

Yes you are right, my bad. I searched on the issues but it was hard to find the proper keywords...
I close this issue as duplicate
