### ISSUE TITLE
Make a release of the docs?

### ISSUE THREAD

**Issue by kenahoo** [hgrecco/pint#1731]
As reported on #1681 and #1708 (both closed), the links for the big buttons on https://pint.readthedocs.io/en/stable/ are wrong, and have been for a few months.  Can someone make a release so that the links get fixed?

**Comment by lafrech** [comment]
No pressure intended but there are features in master I'd like to use (% symbol) and I'd be happy if a release came out. Since there is no open milestone (except outdated 0.18), I figured I'd chime in here to +1 and get an ETA.

Thanks for the work on this lib.

**Comment by hgrecco** [comment]
Stay tuned for May 1st #1751
