### ISSUE TITLE
Wraps cannot handle "dimensionless" being passed in args.

### ISSUE THREAD

**Issue by rob5ives** [hgrecco/pint#1732]
Passing in the string "dimensionless" for a return argument with wraps throws an AssertionError in the _is_multiplicative function (assert len(names) == 1). It appears that the parse_unit_name method cannot handle "dimensionless".

```
def pint_error():
    from pint import UnitRegistry
    ureg = UnitRegistry()
    Q_ = ureg.Quantity

    @ureg.wraps("dimensionless", ("dimensionless", "dimensionless"))
    def func(x, y):
        return x + y
    
    a = Q_(3, "dimensionless")
    b = Q_(4, "dimensionless")
    c = func(a, b)
    print(c)
```

**Comment by OrangeChannel** [comment]
Not a fix but try `''` if it's urgent.

**Comment by hgrecco** [comment]
We need to urgently improve `wraps` and `check`!

**Comment by hgrecco** [comment]
See #1753
