### ISSUE TITLE
UnitRegistry is slow

### ISSUE THREAD

**Issue by bje-** [hgrecco/pint#1742]
`UnitRegistry()` is quite slow esp. for modules that initialise these in their `__init__.py`:

```
In [1]: %timeit pint.UnitRegistry()
640 ms ± 6.23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

0.6 seconds is pretty sluggish. It would be good to profile this code and speed it up.

**Comment by bje-** [comment]
I see that if I call `UnitRegistry(filename=None)`, it's quick. Obviously the default definition file is large, and I assume I could speed it up with a pruned down set of units. Sorry!

**Comment by hgrecco** [comment]
Exactly. We have implemented a cache that will be activated by default as soon as we feel confortable with its inner working

**Comment by hgrecco** [comment]
You can try it:
```python
In [1]: import pint
In [2]: %timeit pint.UnitRegistry()
203 ms ± 889 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
vs
```python
In [1]: import pint
In [2]: %timeit pint.UnitRegistry(cache_folder=":auto:")
4.85 ms ± 89.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by bje-** [comment]
Is there a reason the newer versions of Pint have dropped Python 3.7 support? It's not yet EOL.

**Comment by hgrecco** [comment]
We actually follow NumPy version policy as it is common for a large part of the Python science ecosystem

https://numpy.org/neps/nep-0029-deprecation_policy.html
