### ISSUE TITLE
Unexpected conversion to unit unit

### ISSUE THREAD

**Issue by jonnymaserati** [hgrecco/pint#1743]
Hi there!

First of all, great library... thank you!

I'm getting some unexpected behavior.

```console
>>> Q_('2/30 deg / m')
<Quantity(0.0666666667, 'degree / meter')>
```

The above is what I expect. But if I do this:

```console
>>> Q_('2 deg/30m')
<Quantity(0.0666666667, 'degree * meter')>
```

The unit is now degrees * meters which is not as expected and then doesn't work when I multiply by say Q_('30m') to oget back to the original number.

```console
>>> Q_('2 deg/30m') * Q_('30m')
<Quantity(2.0, 'degree * meter ** 2')>
```

I now get degrees * meters ** 2 instead of degrees like below.

```console
>>> Q_('2/30 deg/m') * Q_('30m')
<Quantity(2.0, 'degree')>
```

Any idea why this happens and how I can get the first outcome when I have the second input string?

Thank you!

**Comment by MichaelTiemannOSC** [comment]
It's a fairly standard problem due to equal precedence of multiplication and division.  Pint treats `2 deg` as `2 * deg` and `30m` as `30 * meter`.  If we write it all out `2 deg/30m` is `2 * deg / 30 * meter`, which is `((2 * deg) / 30) * meter`.  Use parentheses to express your intentions more clearly: `(2 deg) / (30 m)` will work as expected.

**Comment by jonnymaserati** [comment]
Thanks @MichaelTiemannOSC.

I see... I didn't realize this, I just assumed BODMAS like I was taught at school! :-)

In that case, for a `Quantity` and assuming no spaces in the unit part of the string, this works:

```python
def manage_unitized_unit(string):
    scalar, unit = string.split(" ")
    try:
        numerator, denominator = unit.split('/')
    except ValueError:
        numerator = unit
        denominator = 1

    new_string = f"({scalar} {numerator}) / ({denominator})"
    
    return new_string
```

**Comment by hgrecco** [comment]
This discussion can be summarized as. Does `30meter` equals `Quantity(30, "meter")` or `30 * Unit("meter")` While this might look the same it is not as in the example given above and others like `30degC`. 

This was discussed sometime ago, and it was decided not to change the current behavior until a comprehensive and easy to implement change to the parser was proposed.

**Comment by hgrecco** [comment]
See #555 and #1550

**Comment by cohearn-16** [comment]
Hello, I'm new to Pint and have reviewed some of the issues here, but I am still having a similar issue to the one described here.

z = 1/ (jwC) <- capacitance, impedance relation
`z = 1/( 1j*omega*C)` , where omega is a quantity consisting of a pint array with unit rps (I'm treating revolutions per second as radians per second to easier track angular frequency) and C quantity pint array with unit farads.
While trouble shooting I have also tried testing with single quantities such as
```
zdtest = 1j*(62*ureg.rps)*(10*ureg.farad)
ztest = 1/(zdtest)
```
The resulting units should be 1/(rps*F), however the units of the resulting z and ztest are always 1 / farad / revolutions_per_second i.e.
`-0.0016129032258064516j / farad / revolutions_per_second`

**Comment by keewis** [comment]
`1 / x / y` is the same as `1 * x**-1 * y**-1`, which can be transformed to `1 * (x * y)**-1` and thus `1 / (x * y)`
