### ISSUE TITLE
`pint.Unit`/`pint.Quantity` not valid as a type

### ISSUE THREAD

**Issue by fostermaier** [hgrecco/pint#1767]
This might be me misunderstanding the typing system or recent changes to the latter. I have a few typed methods like

    def foo() -> pint.Unit:
        pass
    
    
    def bar() -> pint.Quantity:
        pass

in my code. This was totally fine with `Pint==0.20`

    $ mypy
    Success: no issues found in 1 source file

Upgrading to `Pint==0.21` broke my pipeline. `mypy` yields

    $ mypy
    error: Variable "pint.Unit" is not valid as a type  [valid-type]
    note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
    error: Variable "pint.Quantity" is not valid as a type  [valid-type]
    note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases

**Comment by glatterf42** [comment]
We have the same issue with our code, you might be able to see some logs [here](https://github.com/iiasa/message-ix-models/actions/runs/4859696673/jobs/8662636335?pr=97). There are other errors, too, but we still have to check if they are not more our responsibility.

**Comment by fostermaier** [comment]
@glatterf42 it is indeed the very same message. Thanks for the insights @hgrecco. I'll perform a bisect right away.

**Comment by glatterf42** [comment]
After running `pip install git+https://github.com/hgrecco/pint.git@master`, I now receive locally (where before I had the same errors as in the logs linked above):
```
python -m mypy --show-error-codes --ignore-missing-imports .
message_ix_models/util/scenarioinfo.py:138: error: Variable "pint.Unit" is not valid as a type  [valid-type]
message_ix_models/util/scenarioinfo.py:138: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
message_ix_models/util/scenarioinfo.py:170: error: Variable "pint.Unit" is not valid as a type  [valid-type]
message_ix_models/util/scenarioinfo.py:170: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
message_ix_models/util/scenarioinfo.py:187: error: Unsupported left operand type for / (pint.Unit?)  [operator]
message_ix_models/util/__init__.py:366: error: Variable "pint.Quantity" is not valid as a type  [valid-type]
message_ix_models/util/__init__.py:366: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 4 errors in 2 files (checked 67 source files)
```

**Comment by glatterf42** [comment]
Thanks for your research. Most of the lines from that commit seem to be deletions of empty lines. Without knowing too much about dask, I'd guess the problem was introduced [here](https://github.com/hgrecco/pint/commit/6b115f68a53083c3188cb62f175b17b0403a9a2c#diff-a0caefd88b333de52e7dbb9da294c84ebb413469fa994c377deb4bad4997ffeaR45).

**Comment by glatterf42** [comment]
Agreed, but does that mean we should not type hint `pint.Unit` and `pint.Quantity` anymore? 
FYI: with the [current state of the master branch](https://github.com/hgrecco/pint/commit/5643c32f7f2c886015df459f26b4d72adaee1207), I'm still seeing the same error messages as above.

**Comment by fostermaier** [comment]
This might be a naive and oversimplified approach.

To my understanding, though, a hotfix could be provided by populating `UnitLike` from `_types.py` via the package `__init__.py` so that the user function can be annotated by `pint.UnitLike`.

**Comment by CagtayFabry** [comment]
Thank you for opening this @fostermaier , I am running into the same issues

A reliable way to ensure basic type hinting compatibility (without magnitude type or dimensionality) like mentioned above would be great.

In addition, this simple example also fails in `mypy` with `pint=0.21.0` without any type hints:

```python
# pint_typing.py
import pint
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

def a(b: float):
    return Q_(b, "m")

```

```
mamba create -n pint_mypy python=3.11 pint=0.21 mypy=1.2.0
conda activate pint_mypy
mypy pint_typing.py

>>> pint_typing.py:9: error: "PlainQuantity[Any]" not callable  [operator]
>>> Found 1 error in 1 file (checked 1 source file)
```

**Comment by hgrecco** [comment]
Can you please test against the latest master. It has a lot of additions in relation to typing.

**Comment by glatterf42** [comment]
Sorry, even with `Successfully installed Pint-0.22.dev22+g8426b39`, I see
```shell
message_ix_models/util/scenarioinfo.py:138: error: Variable "pint.Unit" is not valid as a type  [valid-type]
message_ix_models/util/scenarioinfo.py:138: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
message_ix_models/util/scenarioinfo.py:170: error: Variable "pint.Unit" is not valid as a type  [valid-type]
message_ix_models/util/scenarioinfo.py:170: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
message_ix_models/util/scenarioinfo.py:187: error: Unsupported left operand type for / (pint.Unit?)  [operator]
message_ix_models/util/__init__.py:366: error: Variable "pint.Quantity" is not valid as a type  [valid-type]
message_ix_models/util/__init__.py:366: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 4 errors in 2 files (checked 67 source files)
```

**Comment by hgrecco** [comment]
Cannot reproduce one part.
```python
$ pip freeze
mypy==1.3.0
mypy-extensions==1.0.0
typing_extensions==4.5.0
```
and using Python 3.11.3 and Pint-0.22.dev22+g8426b39.

When analyzing the following code
```python
import pint
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

def a(b: float):
    return Q_(b, "m")
```

using `mypy --show-error-codes --ignore-missing-imports .` returns 
```
y.py:8: error: No overload variant matches argument types "float", "str"  [call-overload]
y.py:8: note: Possible overload variants:
y.py:8: note:     def __new__(cls, value: str, units: Union[str, Dict[str, Union[float, int, Decimal, Fraction, Any]], UnitsContainer, PlainUnit, None] = ...) -> Quantity
y.py:8: note:     def __new__(cls, value: Sequence[Any], units: Union[str, Dict[str, Union[float, int, Decimal, Fraction, Any]], UnitsContainer, PlainUnit, None] = ...) -> Quantity
```

which is just that we need to teach the overload a new trick.

**Comment by glatterf42** [comment]
How was this done in pint 0.20? The issue did not exist with that version, so maybe a similar approach can be taken here?

**Comment by hgrecco** [comment]
Actually there has not been any real change in relation to that. My guess is that mypy inteprets differently the code (even though is mostly the same).

**Comment by hgrecco** [comment]
Can you try again? I just pushed some new commits

**Comment by hgrecco** [comment]
There is one test that is failing in a very specific situation with Python 3.9. As soon as I can address that I will make a release candidate and then a release.

Also, please take a look at this:

https://github.com/hgrecco/pint/blob/master/downstream_status.md
