### ISSUE TITLE
Unable to override an existing unit definition programmatically

### ISSUE THREAD

**Issue by aidenprice** [hgrecco/pint#1773]
Hi,

Thank you for the awesome work here. I'm really looking forward to bringing more scientific rigour into our app.

I need to build a custom unit, `bag`. We're tracking industrial sized bags of ammonium nitrate, each somewhere between 1 - 1.3 tonnes. It's part of our app's domain so I can't change the word.

The `bag` unit already exists in `default_en.txt` in the `Avoirdupois` group

```
bag = 94 * pound
```

For the sake of faster dev speed I've been trying to override `bag` in Python code;

```python
from decimal import Decimal

import pint

ureg = pint.UnitRegistry(
    case_sensitive=False,
    non_int_type=Decimal,
    on_redefinition="ignore",
)

ureg.define("each = [stock]")
ureg.define("bag = 1 * each")

y = 5 * ureg.bag
y.dimensionality
```

`[stock]` is a custom dimension I'm experimenting with for tracking physical counts of items later to be multiplied by their weight. Unfortunately the code above results in `<UnitsContainer({'[mass]': 1})>` not `<UnitsContainer({'[stock]': 1})>` like I would expect.

If I delete the `bag` line from "default_en.txt" in my local virtualenv then my code works. But when I update Pint then obviously it reverts to the default file. Similarly, other devs in my team would need to manage their config files. I can make a new default file when I deploy the app in Kubernetes but then it's not possible to use the same file for local dev work.

According to the docs we can redefine a unit through a context, but further reading leads me to understand that a context is for transforming a unit from one dimension to another. I'd want to completely redefine bag in all situations, especially for creating new Quantities from strings.

Any help to override the default definition would would be much appreciated.

Thank you again everyone.

Using Python 3.10 with Pint 0.21.0

**Comment by hgrecco** [comment]
This is a cache problem. You need to call `ureg._build_cache()` after redefine. I am opening an issue to discuss the idea that I have in mind for 0.23

**Comment by aidenprice** [comment]
Thank you, that worked. 🙏
