### ISSUE TITLE
simple conversion between cups and ounces not working

### ISSUE THREAD

**Issue by greenersharp** [hgrecco/pint#1784]
Hi,

I was excited to find Pint and thought it could help with some basic unit conversions.
I tried a basic example that fails and was wondering if I was doing something wrong.

`import pint`
`ureg = pint.UnitRegistry()`
`res = ureg("2 cups").to("ounces")`
`print(res)`

this results in an error:

`pint.errors.DimensionalityError: Cannot convert from 'cup' ([length] ** 3) to 'ounce' ([mass])`

I went over the docs and saw there are some contexts included in the code, like **energy** and **chemistry**, neither of which work for basic conversions like I attempted above.

Are there any contexts available that are capable of converting simple food/ingredient measurements like I attempted above ?

Thank you

**Comment by dopplershift** [comment]
You need to use "fluid_ounces" for volume, since "ounces" is a unit of mass. So this should work:
```python
import pint
ureg = pint.UnitRegistry()
res = ureg("2 cups").to("fluid_ounces")
print(res)
```

**Comment by greenersharp** [comment]
Thanks, that works.   Is there a way to get the string parser to identify these kinds of variations?: 

`ureg("fluid ounces")`
or
`ureg("fl ounces")`

**Comment by hgrecco** [comment]
@greenersharp Sadly, there is no way to do this without guessing the user intention. If you have this appearing in your datasets a lot, you should add a preprocessor rule. Take a look at this test: https://github.com/hgrecco/pint/blob/5f5fff1f7f8291b4d2a6cccfd33bde2dfa6c88ce/pint/testsuite/test_quantity.py#L721
