### ISSUE TITLE
Issue with unit simplification

### ISSUE THREAD

**Issue by DerMilchschnittenmann** [hgrecco/pint#1788]
I'm facing an issue with unit simplification in the Pint Python library. I have a unit_definitions.txt file containing the following definitions:
`MMBTU = [energy] = 293071 * [watt_hour]`

I'm trying to perform a division operation and expecting the units to cancel out, resulting in a dimensionless value. However, the units are not simplifying as expected. Here's the code I'm using:
```
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.load_definitions('unit_definitions.txt')
Q_ = ureg.Quantity
a = Q_(12000, 'watt_hour')
b = Q_(2, 'MMBTU')
result = a / b
print(result)  # -->  6000 'watt_hour' / 'MMBTU'
```

Instead of getting a dimensionless value, the result still contains units: 6000 watt_hour / MMBTU. I expected the result to be 0.020 dimensionless because 1 MMBTU is equal to 293297 watt_hour.

.to_root/base_unit() doesn't do the job...

I would appreciate any help or guidance in resolving this issue. Thank you!

**Comment by MichaelTiemannOSC** [comment]
Two things.  First, it's best to create a self-contained example, like this:

```
import pint
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.define("MMBTU = [energy] = 293071 * [watt_hour]")
Q_ = ureg.Quantity
a = Q_(12000, 'watt_hour')
b = Q_(2, 'MMBTU')
result = a / b
print(result)  # -->  6000 'watt_hour' / 'MMBTU'
```

Second, if you know the reduced units you want, you can get them with `.to()`:

```
print(result.to('dimensionless'))
# 21600000000.0 dimensionless
```
