### ISSUE TITLE
reduce_dimensions function is not used anywhere

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint#1807]
`reduce_dimensions `function is not used anywhere - should it be deleted?

**Comment by hgrecco** [comment]
I think it has been replaced by `ireduce_dimensions` to reduce the amount of code. I would like to double-check that we are not making a logical mistake by doing this.

**Comment by andrewgsavage** [comment]
That's what I saw looking at history too where `@ireduce_dimensions` is used.
