### ISSUE TITLE
Support for polars?

### ISSUE THREAD

**Issue by kszlim** [hgrecco/pint#1811]
I was wondering if you see polars support ever coming? [Polars](https://github.com/pola-rs/polars/) is an up and coming DataFrame library written in rust with very nice Python bindings. Imo it's going to rival pandas in popularity in the future. Would be great if pint could integrate (though it might be tricky due to laziness in Polar's design).

**Comment by hgrecco** [comment]
It would be very nice! Take a look at pint pandas.
