### ISSUE TITLE
Problem with bbl/day conversion

### ISSUE THREAD

**Issue by huangkai31** [hgrecco/pint#1812]
Pint                  0.21.1

```
from pint import UnitRegistry
ureg = UnitRegistry(fmt_locale='en_US')
test = 1 * ureg('L/min')
test.to('bbl/d') 
```
The result is: <Quantity(12.0764367, 'barrel / day')>
It shoud be 9.06 bbl/d

**Comment by hgrecco** [comment]
I think you are mixing up "barrel" with oil 

```python
>>> (1 * ureg.liter / ureg.min).to(ureg.barrel / ureg.day)
<Quantity(12.0764367, 'barrel / day')>
>>> (1 * ureg.liter / ureg.min).to(ureg.oil_barrel / ureg.day)
<Quantity(9.05732751, 'oil_barrel / day')>
```

Like many other imperial units, for barrel there are multiple definitions for the same name. https://en.wikipedia.org/wiki/Barrel_(unit)
