### ISSUE TITLE
Question about dimensionless units conversion

### ISSUE THREAD

**Issue by lennart0901** [hgrecco/pint#182]
This is not exactly a bug report or feature request, but I'd like to note something important in my humble opinion.

I was quite surprised that:

```
Q_(1., '1/s').to('rpm')
```

is not 60 rpm but 9.55 rpm ( 60./(2_pi) ).
I believe there is a reason for that. But defining some dimensionless unit as a "base" unit seems not appropriate to me. For example Hz is also defined as "cycles per second" but having "1/s_1s=2*pi" is also strange.

Would it be possible to do dimensionless unit conversion only if units appear on both sides of the conversion and otherwise ignore them completely. Or might there be another solution.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if neeeded.
