### ISSUE TITLE
bug: default_preferred_units not working

### ISSUE THREAD

**Issue by fgvieira** [hgrecco/pint#1823]
I am trying to set some `default_preferred_units`:
```
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.default_preferred_units = [ureg.minute, ureg.mebibyte]
ureg.autoconvert_to_preferred = True
unit = ureg.Quantity
```

But they do not seem to work:
```
In [141]: unit("2 GiB")
Out[141]: 2 <Unit('gibibyte')>

In [142]: unit("2 GiB").to_preferred([ureg.minute, ureg.mebibyte])
Out[142]: 2 <Unit('gibibyte')>

In [143]: unit("2 h")
Out[143]: 2 <Unit('hour')>
```

at least sometimes: :smile: 
```
In [144]: unit("2 h").to_preferred([ureg.minute, ureg.mebibyte])
Out[144]: 120.0 <Unit('minute')>

```

But they all work fine if I specify the unit:
```
In [145]: unit("2 GiB").to(ureg.mebibyte)
Out[145]: 2048.0 <Unit('mebibyte')>

In [146]: unit("2 h").to(ureg.minute)
Out[146]: 120.0 <Unit('minute')>
```

**Comment by andrewgsavage** [comment]
`default_preferred_units` was added after the last released version, so you'll need to install from github to use it before the next release.
With the master branch, I get 
```
unit("2 GiB")
2 gibibyte

unit("2 hour")
120.0 minute
```

So for me `default_preferred_units` is working, but `to_preferred` is not working for GiB to MiB.

**Comment by fgvieira** [comment]
Yes, it seems only the `GiB` to `MiB` is not working on current `master`:
```
In [2]: from pint import UnitRegistry
   ...: ureg = UnitRegistry()
   ...: ureg.default_preferred_units = [ureg.minute, ureg.mebibyte]
   ...: ureg.autoconvert_to_preferred = True
   ...: unit = ureg.Quantity

In [3]: unit("2 GiB")
Out[3]: 2 <Unit('gibibyte')>

In [4]: unit("2 GiB").to_preferred([ureg.minute, ureg.mebibyte])
Out[4]: 2 <Unit('gibibyte')>

In [5]: unit("2 GiB").to(ureg.mebibyte)
Out[5]: 2048.0 <Unit('mebibyte')>
```

thanks @andrewgsavage for double-checking it!

**Comment by andrewgsavage** [comment]
GiB can't become MiB because they're both dimensionless. if you were to change its definition in default_en.txt so the base information unit (byte?) is defined with [information] instead of [] it will work
