### ISSUE TITLE
Typing of Quantity.to() raises mypy error

### ISSUE THREAD

**Issue by hassec** [hgrecco/pint#1827]
When type checking the below snippet with mypy (v.1.4.1), it raises an error. 
Pint version is 0.22.

```py
import pint

def foo(a: pint.Quantity, b: pint.Unit) -> pint.Quantity:
    return a.to(b)
```

Error: 
```
type.py:4: error: Incompatible return value type (got "PlainQuantity[Any]", expected "Quantity")  [return-value]
```

**Comment by vallsv** [comment]
Got the same with `isinstance(foo, pint.Quantity)`.

Is anybodu know if there is actually a "right" way to use pint and mypy?

**Comment by nup002** [comment]
Came here because I'm running into the same problem.
At runtime, `a.to(b)` correctly returns a `Quantity` instance, but according to the Pint type hints, it can only return a `PlainQuantity`, hence why mypy complains.

**Comment by jules-ch** [comment]
duplicates of #2088
