### ISSUE TITLE
Use defined unit in another define unit as dimensionless value

### ISSUE THREAD

**Issue by decepol** [hgrecco/pint#1829]
hello.
I have a problem with defining custom units. and how to use it in other definitions:

there are my units:
```
unit1 = gram / liter = g/L
unit2 = unit1 * 10 = degree_P
unit3 = 259 / (259-unit2) = _  -> TypeError: No loader function defined for UnhandledParsingError
```

how to use only value without dimension in unit3 ? 

```
ureg.Quantity(35,'unit1').to('unit2')
> <Quantity(3.5, 'unit2')>
```

it should be:
```
ureg.Quantity(35,'unit1').to('unit3')
> <Quantity(1.0136986, 'unit3')>

as 259 / (259 - 3.5) == 1.0136986
```

any hints how to deal with that ?

**Comment by hgrecco** [comment]
> unit3 = 259 / (259-unit2) = _

This is not a valid unit definition. Checkout how offset units like Celsius are defined:

https://github.com/hgrecco/pint/blob/6c2dda9541e7f83f5b1cd263a7f3427585353931/pint/default_en.txt#L208

**Comment by decepol** [comment]
any doc for this `offset` and `define` feature?

**Comment by hgrecco** [comment]
Sorry, I misunderstood the question. There is a reciprocal relation between `unit2` and `unit3` and this is not supported by current converters. Only multiplicative (i.e. inches to meters), additive (i.e. Celsius to Fahrenheit) and logarithmic (i.e. db) are supported. 

Do you really need a conversion of units, or you need to operate between quantities with a specific relation? Can you describe your use case?
