### ISSUE TITLE
Override units display order (1 kW·h displayed as 1 h·kW)

### ISSUE THREAD

**Issue by scanzy** [hgrecco/pint#1841]
Let's consider this code

```python
import pint as pt

# sets compact display mode
u = pt.UnitRegistry()
u.default_format = '~P'

# creates quantity
q = u.Quantity("1 kW * 1 h")

# this prints "1 h·kW", not "1 kW·h" as expected
print(q)
```

During the string conversion I believe the units are sorted alphabetically, in fact `hour` comes before `kilowatt`.

How can I override this behaviour to have it printed correctly as `1 kW·h`?
For now I am doing `str(q).replace("h·kW", "kW·h")` but I am looking for a better solution, that may act globally and before string conversion.

Any suggestions?
Thank you!

**Comment by andrewgsavage** [comment]
With latest version you may be able to with a custom format that sorts the units in unit as desired.
https://pint.readthedocs.io/en/latest/user/formatting.html?highlight=format#custom-unit-format-types

It may be worth adding custom sorting as an example there.

**Comment by scanzy** [comment]
Thank you!
I have some ideas about how to do it. I will try

However, do you think it would be possible to use this to change only the
order but not the format?

In other words: How to apply my custom order to all the existing possible
formatting options? Compact, latex, etc.

I may find all the format specifiers and (programmatically) create a new
updated format (with custom) for each one.

What do you think?

Il giorno mar 12 set 2023 alle 22:17 andrewgsavage ***@***.***>
ha scritto:

**Comment by MichaelTiemannOSC** [comment]
I do think it's pretty common to place time dimensions after all other dimensions (i.e., acceleration as `m/s**2` or power as `kW * h`), so just doing that one thing might solve most of the problems.

**Comment by scanzy** [comment]
This is a very interesting point, however do you have any ideaabout how to implement this in pint?

Or maybe the library requires some sort of unit order customization functionality?

**Comment by MichaelTiemannOSC** [comment]
Xref: https://www.iso.org/obp/ui/#iso:std:iso:80000:-1:ed-1:v1:en

**Comment by hgrecco** [comment]
There is a long standing plan to move the formatting to Delegate (like the Parser) which is composed (not inherited). In this way, string formatting would be more decoupled and therefore easy to change..
