### ISSUE TITLE
Error when unit has a scaling factor

### ISSUE THREAD

**Issue by 3mrrrx** [hgrecco/pint#1846]
for 
`
Q_ = ureg.Quantity
`
while 

```
Q_(1, 'mg/100mL')
#results in ValueError: Unit expression cannot have a scaling factor.
```

the work around results in an error:
```

1 * ureg('mg/100mL') == Q_(1, ureg('mg/100mL'))
# is false!

```

**Comment by hgrecco** [comment]
The result of `ureg('mg/100mL')` is a quantity from which only the unit is used to when building the quantity in `Q_(1, ureg('mg/100mL'))`
