### ISSUE TITLE
Installation on macos with poetry

### ISSUE THREAD

**Issue by ChauhanT** [hgrecco/pint#1859]
Hi,

I am trying to install pint on macos with `poetry add pint` in a python 3.10.10 virtual environment. I get an error saying `Installing pyqt5-qt5 (5.15.2): Failed`. Any tips/tricks that might help resolve this ? Sorry, this is not an issue with the library itself, but I was not able to find a forum for my question. Happy to take it down if the maintainers don't want this here!

Cheers

**Comment by hgrecco** [comment]
Not sure what is the reason, but pint does not require nor refers to pyqt. So I guess is something in your installation.

**Comment by clintonroy** [comment]
@ChauhanT poetry has a discourse server, github issues. Please follow the bug templates.
