### ISSUE TITLE
Quantity intervals

### ISSUE THREAD

**Issue by gsakkis** [hgrecco/pint#1888]
I'm trying to use `pint` with [portion](https://github.com/AlexandreDecan/portion) for quantity intervals. Portion defines its own singletons for positive and negative infinity that can compare to any type. However pint quantities can be compared only with other quantities:
```py
In [1]: import pint, portion

In [2]: portion.inf > pint.Quantity("3 mg")
Out[2]: True

In [3]: -portion.inf > pint.Quantity("3 mg")
Out[3]: False

In [4]: pint.Quantity("3 mg") < portion.inf
ValueError: Cannot compare PlainQuantity and <class 'portion.const._PInf'>

In [5]: pint.Quantity("3 mg") < -portion.inf
ValueError: Cannot compare PlainQuantity and <class 'portion.const._NInf'>
```

Now pint can parse `inf` as native float but this is not exactly equivalent to `portion.inf`, for example you can create a closed interval with infinite bounds:
```py
In [6]: portion.closed(pint.Quantity("-inf mg"), pint.Quantity("inf mg"))
Out[6]: [<Quantity(-inf, 'milligram')>,<Quantity(inf, 'milligram')>]
```

I think this can be fixed on the pint side by returning `NotImplemented` instead of raising `ValueError` for unhandled comparisons. 

cc @AlexandreDecan in case this can be somehow handled on the `portion` side.

**Comment by AlexandreDecan** [comment]
Hello, 

Thanks for your interest in portion (and pint)! As you mention, the easiest (and probably most appropriate) way to fix this "issue" is to return `NotImplemented` instead of raising `ValueError`, as suggested by Python https://docs.python.org/3.8/reference/datamodel.html#object.__ge__ This should be made in `pint`, however...

**Comment by andrewgsavage** [comment]
Add the types that should return not implemented to pint.compat.upcast_types

https://pint.readthedocs.io/en/stable/user/numpy.html#Technical-Commentary

**Comment by gsakkis** [comment]
Thanks for pointing me to the right direction! Btw there's no `upcast_types`, there is an `upcast_type_map` which is annotated as `Mapping[str, Optional[type]]` so I needed to add a `# type: ignore` to update it without mypy complaining.

**Comment by andrewgsavage** [comment]
That's what adding the type to upcast_types does. pint returns NotImplemented for any types in pint.compat.upcast_types

**Comment by andrewgsavage** [comment]
You could make a PR adding the types required to here https://github.com/hgrecco/pint/blob/master/pint/compat.py#L216
