### ISSUE TITLE
magnitude and casting

### ISSUE THREAD

**Issue by vishnubob** [hgrecco/pint#189]
Thanks for Pint!  It's a great library, very easy to use, well thought out, and cleanly written.  I was up and running with it in a matter of no time.  I have one hangup, however, and that's with accessing the magnitude value.  For the most part, I find that I can just drop Pint into my projects without having to disturb the way they accomplish arithmetic--except when I need a final value.  I am constantly tripping a ```DimensionalityError``` like so:

    In [1]: import pint
    In [2]: units = pint.UnitRegistry()
    In [3]: float(units.parse_expression("3mm") * 2.2)
    ---------------------------------------------------------------------------
    DimensionalityError                       Traceback (most recent call last)
    <ipython-input-4-6779a77df576> in <module>()
    ----> 1 float(units.parse_expression("3mm") * 2.2)

    /Users/ghall/.current/pyenv/lib/python2.7/site-packages/pint/quantity.pyc in __float__(self)
        290         if self.dimensionless:
        291             return float(self._convert_magnitude_not_inplace(UnitsContainer()))
    --> 292         raise DimensionalityError(self.units, 'dimensionless')
        293
        294     def __complex__(self):

    DimensionalityError: Cannot convert from 'millimeter' to 'dimensionless'

I believe this is what the API wants me to use:

    In [4]: (units.parse_expression("3mm") * 2.2).magnitude
    Out[4]: 6.6000000000000005 

I've read the docs, and I think I understand why this dimensionality safe-guard exists, but I also find this part of the API to be pythonicly counter-intuitive.  I would assume that casting a ```Quantity``` to a float (or an int) would always return the magnitude, no questions asked.  When is this the wrong thing to do?  Why is it important to be so stringent about casting?

Thanks for your time and your hard work!

**Comment by hgrecco** [comment]
We implemented `m` (a short form for `magnitude`) and `m_as` (to return the magnitude in other units).

Feel free to reopen if needed.
