### ISSUE TITLE
Copy 'units' from a Quantity to another variable

### ISSUE THREAD

**Issue by jgostick** [hgrecco/pint#190]
This issue was brought up in #103, but Hernan closed it while "awaiting more use cases or a better syntax".  I would like 'reopen' this issue.  

I want to include *pint* support in a larger package (*OpenPNM*), but I don't want to have to import *pint* into all of my modules.  I'd rather have users import and apply *pint* if they so choose, then I merely provide "support" for *pint* from within my package.  To do this, I need the ``Quantity`` object to possess an additional attribute that I can use for applying the ``units`` of one array onto another.  My specific use case is that I want to "interleave" two arrays (not concatenate):

> import pint
> p = pint.UnitRegistry()
> a = sp.array([1,2,3]) * p.m
> b = sp.array([4,5,6]) * p.cm

So deep inside my package I want to do this:
> ai = [0,3,5]
> bi = [1,2,4]
> c = sp.zeros(6)  # This array does not have units!
> c[ai] = a
> c[bi] = b
> print(c)
> array([1,4,5,2,6,3])  # No units here

I'm OK with doing a ``to_base_units`` on *a* and *b* first, but I need some way to apply the units of *a* (or *b*) to *c* without having *pint* in the local scope.  

My proposed syntax is to copy how *quantities* package does it:

> c = sp.zeros(6) * a.units

I realize that the ``units`` attribute is already committed to some other functionality, but perhaps a new attribute can be added to a during the ``a * p.m`` step that somehow stores ``p.m``?  For instance the following works:

> a = sp.array([1,2,3]) * p.m
> a.\__setattr\__('foo', p.m)
> b = sp.array([4,5,6]) * a.foo
> print(b)
> \<\<Quantity([1 2 3], 'meter')\>\>

I propose this attribute be called ``iunits`` to mirror the ``ito`` naming...as in "apply units in-place".

Or perhaps there is some other way to access this capability from the ``Quantity`` object?

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.
