### ISSUE TITLE
Cannot convert from `kcal/mol` to `meV`

### ISSUE THREAD

**Issue by Roy-Kid** [hgrecco/pint#1900]
It is very common to convert these two energy units.
It is ok if use command-line:
```
$ pint-convert kcal/mol meV                                                                                               
1.0 kilocalorie / mole = 43.3641042418 meV
``` 
but error raise when:
```
1 * ureg('kilocalorie / mole').to('meV')
```
or 
```
1 * ureg('meV').to('kcal/mol')
```
error:
```
Cannot convert from 'kilocalorie / mole' ([length] ** 2 * [mass] / [substance] / [time] ** 2) to 'millielectron_volt' ([length] ** 2 * [mass] / [time] ** 2)
```
How should I deal with `mole` properly?

**Comment by mskblackbelt** [comment]
You need to remove the quantity component… from a dimensional analysis point of view, your meV should (probably) be an energy per molecule or particle, so you need to either specify that unit in pint or get rid of the molar portion of the energy measurement. I can't suggest why the conversion works at the command-line, it's my belief that the conversion should fail there as well.

**Comment by Roy-Kid** [comment]
Thanks for your help! How to separate those basic units from the combined unit? Using `to_base_units` and then check if a `mole` exists? More generally, If I define a set of basic units, such as lengths, energy, mass, how can I reduce any combined unit to a reduced unit?

**Comment by jules-ch** [comment]
It's because the nergy context is activated by default in the pint-convert script.

**Comment by jules-ch** [comment]
It basically gives you the energy per entity here for 1 kcal per mole of a substance, you get 43.3 meV of energy per entity.

To have this behaviour you need to enable the context energy, in the docs: https://pint.readthedocs.io/en/stable/user/contexts.html

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> q = 1 * ureg.kilocalorie / ureg.mole
>>> q.to("meV")
pint.errors.DimensionalityError: Cannot convert from 'kilocalorie / mole' ([mass] * [length] ** 2 / [time] ** 2 / [substance]) to 'millielectron_volt' ([mass] * [length] ** 2 / [time] ** 2)
>>> q.to("meV", "energy")
<Quantity(43.3641042, 'millielectron_volt')>

**Comment by jules-ch** [comment]
Going to close this, feel free to reopen if something is not clear :)

**Comment by Roy-Kid** [comment]
Dear Jules,

I’m refactoring my code and wanted to thank you for your previous response (and sorry for forgetting to appreciate it earlier!). I’m now working on integrating unit conversion internally, and here’s my new approach:

```
import pint


class Unit(pint.UnitRegistry):
    
    UNIT_STYLES = {
        "real": {
            "length": "angstrom",
            "energy": "kcal/N_A",
            "mass": "gram/mole",
            "time": "femtosecond"
        },
        "lj": {  # define when initializing
            "length": "2.5 angstrom",
            "energy": "1.0 kcal/N_A",
            "mass": "12.011 gram/mole",
            "time": "1 nanosecond"
        }
    }

    def __init__(self, style="real", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.style = style

    def _after_init(self):
        super()._after_init()

        style = self.UNIT_STYLES[self.style]
        for dim, unit in style.items():
            self.define(f"{dim} = {unit}")

class TestUnit:

    def test_unit(self):
        unit = mp.Unit()
        assert "angstrom" in unit
        unit.define("@alias angstrom = length")
        assert "length" in unit
        np.testing.assert_allclose((1 * unit.length).to("nanometer").magnitude , 0.1)

    def test_lj_unit(self):
        unit = mp.Unit(style="lj")
        assert "length" in unit

        np.testing.assert_allclose((1 * unit.nanometer).to(unit.length), 4.0)
```
I have a couple of questions regarding this implementation:

How can I define energy or mass with the correct context programmatically? Right now, I can only use `N_A` instead of `mol`.
What’s the difference between defining a unit alias with `@alias` versus directly defining it as a unit?
Do you think this approach follows good practices? I’d appreciate any advice you have!

Best,
Jichen
