### ISSUE TITLE
surprising behavior when Quantity called on value from a foreign registry

### ISSUE THREAD

**Issue by Ricyteach** [hgrecco/pint#1914]
Hi, thanks for pint. It rules.

I find the behavior shown below- where a `Quantity` `u` from registry `U` is attmpted to be "converted" to a different registry, `V`- to be somewhat weird. I think I understand what is happening: it is just taking the `Quantity` object and using it as the quantity magnitude, and the units are dimensionless.

Since Quantity objects from different registries aren't supposed to be valid to each other, I would expect one of two things to happen:

1. An error on line 6
2. For the `v` quantity object- which is registered with registry `V`- to be properly "converted" to the registry, `U`.

```
In [1]: from pint import UnitRegistry

In [2]: U=UnitRegistry()

In [3]: V=UnitRegistry()

In [4]: u=1*U.m

In [5]: U.Quantity(u)
Out[5]: 1 <Unit('meter')>

In [6]: V.Quantity(u)
Out[6]: 1 <Unit('meter')> <Unit('dimensionless')>
```

EDIT: since `Unit` objects can be "converted" between registries in this manner, it seems to me that option 2 would be the expected behavior and that `Quantity` objects should therefore also be "converted".

```
In [7]: U.Unit(V.m)._REGISTRY is U
Out[7]: True
```

**Comment by hgrecco** [comment]
I am glad that you enjoyed pint. 

First, we discuss some time ago that `Quantity(x)` where `x` is a quantity should raise an exception (maybe except when the magnitude is 1, like here). In relation to your specific question, I think everything that mixes Registries should raise an exception and conversion should be done explicitly through strings.

**Comment by Ricyteach** [comment]
Gotcha. Sounds like this needs to be on the list of things to be addressed, then.

I'll try to write my code with this in mind. Thanks!
