### ISSUE TITLE
Parsing unit yield multiple results

### ISSUE THREAD

**Issue by rufuswilson** [hgrecco/pint#1916]
I am using pint 0.23 and I faced the following problem.

I have a unit in short format (`dat`). It can refer to `deci-technical_atmosphere` or `deca-metric_ton`. Here is what I do at the moment

```
>> import pint
>> ureg = pint.UnitRegistry()
>> d = "[denisty]"
>> ureg.Unit("dat")
<Unit('decitechnical_atmosphere')>
```

How can I force it to give me the `deca-metric_ton` as it should be a `[density]`?

**Comment by hgrecco** [comment]
There is no way to force it that way. You can either use the full name or create a new definition file (it is super easy) in which the "other unit" in this case "technical_atmosphere"

**Comment by rufuswilson** [comment]
OK. Thanks for the answer.
