### ISSUE TITLE
Error while using to_preferred() 

### ISSUE THREAD

**Issue by erielias** [hgrecco/pint#1929]
I'm trying to use the to_preferred() method with a megawatts Quantity object with no success.
The code below shows that Unit("watt") is a compatible unit. However when we try to run .to_preferred(preferred_units) it throws an error message.

env:
python 3.11.5
pint 0.23

`
```python
from pint import Quantity, Unit

a = Quantity(1, "MW")
print(a.compatible_units())
preferred_units = [Unit("watt")]

b = a.to_preferred(preferred_units)
print(b)

``` 

Error message:
```text
.../lib/python3.11/site-packages/mip/cbc.py", line 603, in <module>
    Osi_getNumCols = cbclib.Osi_getNumCols
                     ^^^^^^
NameError: name 'cbclib' is not defined
```

Anything you may know of? Am I using it incorrectly?

**Comment by andrewgsavage** [comment]
do you have mip installed?
