### ISSUE TITLE
 floating point arithmetic errors 

### ISSUE THREAD

**Issue by transfluxus** [hgrecco/pint#1945]
Hi,
is there a pint internal way to avoid   floating point arithmetic errors 

simple example

ureg("Ml").to("l")
Out[4]: 1000000.0000000001 <Unit('liter')>

thanks!

**Comment by hgrecco** [comment]
Yes, you can use decimal

```python
>>> import pint
>>> from decimal import Decimal
>>> ureg = pint.UnitRegistry(non_int_type=Decimal)
>>> ureg("Ml").to("l")
<Quantity(1E+6, 'liter')>
```

**Comment by transfluxus** [comment]
works nice, except that it leads to crashes when trying to do floating point numbers as well
`ureg.parse_expression("kg") * 1.2

**Comment by hgrecco** [comment]
That is not a Pint thing, but a Python thing:
```python
>>> from decimal import Decimal
>>> Decimal("1000") * 1.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
```
