### ISSUE TITLE
Suggestion: Add permille ratio

### ISSUE THREAD

**Issue by Musaefendic** [hgrecco/pint#1963]
Following the suggestion/issue https://github.com/hgrecco/pint/issues/1277

Adding the `permille` unit `‰` would be interesting for applications like combustion. It's common to define the `Fuel-Air-Ratio` variable, with an order of magnitude around `0.01`, often written as `10‰`.

Is there a particular reason why this ratio hasn't been added in the pull request https://github.com/hgrecco/pint/pull/1661? 
Would you be open to a new pull request that includes the permille ratio and the `‰` preprocessor ?

#### Workaround
```python
from pint import UnitRegistry, set_application_registry

ureg = UnitRegistry()
ureg.define("permille = 0.001")

set_application_registry(ureg)
```

**Comment by andrewgsavage** [comment]
> Is there a particular reason why this ratio hasn't been added in the pull request #1661? Would you be open to a new pull request that includes the permille ratio and the `‰` preprocessor ?

It looks like it wasnt added as it permille wasn't really discussed (and keewis' post reads as if it was already defined)

I don't see any issues with adding "permille = 0.001 = ppthousand" to the registry or a ‰ preprocessor

**Comment by andrewgsavage** [comment]
A PR implementing this is welcomed
