### ISSUE TITLE
How to convert kNm to custom unit Nmm?

### ISSUE THREAD

**Issue by nelbs** [hgrecco/pint#1965]
Hi,

I want to create a unit "Nmm" (newton * millimeter) and convert other units to it. For example kNm to Nmm. I tried everything but I cannot get it to work. 

I tried the following:

```
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.default_format = "~P"
Nmm = ureg.N * ureg.mm
print((5*kNm).to(Nmm))
```

Which results in

`pint.errors.DimensionalityError: Cannot convert from 'kilonumber_meter' ([length] / [mass]) to 'millimeter * newton' ([length] ** 2 * [mass] / [time] ** 2)`

I also tried this:
```
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.default_format = "~P"
kNm = ureg.kNm
Nm = ureg.Nm
Nmm = kNm * 10**6
print((5*kNm).to(Nmm))
```
but that did not work either as it should give 5e06 Nmm instead of 5 kNm

`5 kNm`

What am I doing wrong??

**Comment by andrewgsavage** [comment]
Use `ureg.Quantity`

```
>>> Q_ = ureg.Quantity
>>> Q_(5, "kN m").to("N mm")
55000000.0 mm N
```

note that Nm for torque is not defined in the unit definition file so you must leave a space between N and mm

**Comment by nelbs** [comment]
Thanks, but is it not possible to add some custom units? 

Let me explain what I want to achieve.

I have some classes with arguments for forces, lengths etc and I want to make the input value independent by using units. So I want the user can input for example 5*kNm, 5000*Nm or 5e6*Nmm. The input is then converted to Nmm and then stored as a float because all the calculations are based on newton and millimeters. Is this possible with the use of a Quantity?

**Comment by andrewgsavage** [comment]
Please go through the tutorial as it answers your questions 
https://pint.readthedocs.io/en/stable/getting/tutorial.html
https://pint.readthedocs.io/en/stable/user/defining-quantities.html

You can define units;
https://pint.readthedocs.io/en/stable/advanced/defining.html
`Nm` has a conflict in the unit definition file, default_en.txt. I suggest editing your version:

Change line 601
`    number_meter = kilometer / kilogram = Nm`
to 
`    number_meter = kilometer / kilogram`

And to define torques, at line 333 add
```
newton_meter = newton * meter = Nm
newton_millimeter = newton * millimeter = Nmm
```
Pint will recognise prefixes at the start of a unit. Usually for compound units a space is used to seperate the units allowing pint to detect "N mm" as (N) * (1e-3*m). To write the unit without the space you'll need to define the unit as I did for Nmm above.

**Comment by nelbs** [comment]
This did the trick 👍 
```
ureg.define('Nmm = kNm / 1e6')
Nmm = ureg.Nmm
```

**Comment by andrewgsavage** [comment]
careful, you haven't changed the definition of Nm so it's still using the number_meter definiton. That may be ok if you're only converting and then taking the magnitude, not using pint to do any calcs on it.

**Comment by nelbs** [comment]
Good point but manually adjusting the code is not desirable for me as there are multiple users.
