### ISSUE TITLE
Default format of dimensionless Unit: undocumented change in 0.24

### ISSUE THREAD

**Issue by khaeru** [hgrecco/pint#2007]
Consider the following:
```py
import pint

q = pint.Quantity(1.0, "")
print(f"{q.units}")
```

With pint 0.23:
- The output is `'dimensionless'`.
- With instead `f"{q.units:D}"`, the output is `'dimensionless'`.
- With instead `f"{q.units:~}"`, the output is `''`.

With pint 0.24:
- The output is `''`.
- It seems none of the format specifiers described on the [String formatting specifications](https://pint.readthedocs.io/en/stable/user/formatting.html) can be used to get `'dimensionless'` as output.

This change is not mentioned in the change log, and there was not a PendingDeprecationWarning or FutureWarning to indicate this behaviour would change with 0.24.

**Comment by andrewgsavage** [comment]
@hgrecco would it be worth releasing a 0.24.1 formats dimensionless as dimensionless for these format specs?

**Comment by hgrecco** [comment]
Yes! And also to address #2009
