### ISSUE TITLE
Another package for ecosystem.rst

### ISSUE THREAD

**Issue by bje-** [hgrecco/pint#2008]
NEMO (https://github.com/bje-/nemo) is another package using Pint.

**Comment by hgrecco** [comment]
Awesome. You can help Pint help your project by submitting a PR to include it in downstream_status.md

https://github.com/hgrecco/pint/blob/master/downstream_status.md

**Comment by bje-** [comment]
Is there a reason Pint 0.24 not longer supports Python 3.8 and 3.9? Neither of these have reached end-of-life.

**Comment by andrewgsavage** [comment]
closed by #2010
