### ISSUE TITLE
What does `registry=None` mean in custom formatter ?

### ISSUE THREAD

**Issue by aulemahal** [hgrecco/pint#2009]
Hi!

With pint 0.24, the internal workings of `register_unit_format` have changed and the `registry` argument of the wrapped function can now be "None". I do not see in the doc the meaning of that new possible value. Wouldn't a `Unit` object always be related to a registry, even if it's the default one ?

This is causing issues in `cf-xarray` (and downstream) for example (xarray-contrib/cf-xarray#507) where we used `registry` to convert the `UnitContainer` back to a `Unit` (see https://github.com/xarray-contrib/cf-xarray/blob/24dd81b2748db59c3ede68735a200b63b8a3d2d2/cf_xarray/units.py#L17-L38)

EDIT: Also, the way  `register_unit_format` is written, wouldn't `registry` _always_ be None ?

**Comment by hgrecco** [comment]
First, sorry for breaking things. The move to the new Formatter delegate allows more flexibility so I think this annoyance will pay off. Let me answer each of your questions:

> Wouldn't a Unit object always be related to a registry, even if it's the default one ?
The formatter also format unit like objects (i.e. dicts mapping names to exponents) which do not necesesary require a registry.

> Also, the way register_unit_format is written, wouldn't registry always be None 
Yes. I was planning to try a solution but there was no need until now. 

The idea would be to make [this function](https://github.com/hgrecco/pint/blob/a472c2634622622b51e96d174b811e5b86d2aa1a/pint/delegates/formatter/full.py#L98
) look and instantiate the registered formatters.

```python
    def get_formatter(self, spec: str):
        if spec == "":
            return self._formatters["D"]
        for k, v in self._formatters.items():
            if k in spec:
                return v

        try:
            orphan_fmt = REGISTERED_FORMATTERS[spec]
        except KeyError:
            return self._formatters["D"]

        try:
            fmt = orphan_fmt.__class__(self._registry)
            spec = get_attr(fmt, "spec", spec)
            self._formatters[spec] = fmt
            return fmt
        except:
            return orphan_fmt
```

**Comment by hgrecco** [comment]
and then also add the spec attribute to `NewFormatter` [here](https://github.com/hgrecco/pint/blob/a472c2634622622b51e96d174b811e5b86d2aa1a/pint/delegates/formatter/_to_register.py#L63)

**Comment by hgrecco** [comment]
On a second thought
`spec = get_attr(fmt, "spec", spec)` and adding the spec attribut might not be necessary.

**Comment by aulemahal** [comment]
I think I understand. I think I can try to suggest these changes in a PR if that helps.

**Comment by hgrecco** [comment]
That would be great. I have review the code, it is necessary to add `spec = get_attr(fmt, "spec", spec)` and adding the spec attribute to NewFormatter. Let me know if you need help.
