### ISSUE TITLE
Conversions for quantities with Decimal units yield imprecise results

### ISSUE THREAD

**Issue by mulkieran** [hgrecco/pint#201]
Probably because float operations are being used.

Below is an example showing the problem:

[mulhern@localhost pint]$ PYTHONPATH=/home/mulhern/reference/pint python
Python 2.7.5 (default, Jun 19 2014, 12:16:30) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
! >>> import pint
! >>> help(pint)

! >>> from decimal import Decimal
! >>> ureg = pint.UnitRegistry()
! >>> z = Decimal(1835008)
! >>> p  = z * ureg.bytes
! >>> p.to(ureg.mebibytes)
 result: Quantity(1.749999999999541248, 'mebibyte')   #imprecise value for mebibytes
! >>> z / 1024**2
 result: Decimal('1.75')                                                    # precise value for mebibytes

Occurs in current HEAD in master.

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.

**Comment by mulkieran** [comment]
You were right to close this. And it is correct to continue to support bytes. It is just inappropriate to use pint when you are using bytes to calculate memory layouts. It is fine to use pint when bytes represent memory consumption, e.g., of an executing process or are using in KiB/sec as bandwidth. Thanks for all the work!
