### ISSUE TITLE
Euro symbol cannot be parsed by the UnitRegistry

### ISSUE THREAD

**Issue by Emenemer** [hgrecco/pint#2018]
Im on v0.23

I am attempting to use pint with some redefinitions, but running into error with special characters, most notably the '€' and '$' characters
I introduce a money dimension and define the Euro unit with a redefinition, then try to call it, but it results in an Assertionerror

I use the following code in python:

```from pint import UnitRegistry

UNIT_OVERWRITE_DEFINITIONS = (
    "euro = 1 [money] = € = EUR = EURO = Euro",
)
ureg = UnitRegistry(autoconvert_offset_to_baseunit=True)
ureg.load_definitions(UNIT_OVERWRITE_DEFINITIONS)
euro_quantity = ureg('€')
```

NB: this does work when i call on `ureg('EUR')`

Note that this is also the case for '$' and '-' symbols, from what I have found. It seems like the eval tree cannot handle these somehow?
I would expect these symbols to be parseable, especially when I define them explicitly.

**Comment by andrewgsavage** [comment]
those characters can't be used. see the solution in https://github.com/hgrecco/pint/issues/2015
