### ISSUE TITLE
How to use pint and odeint?

### ISSUE THREAD

**Issue by dreyeslastiri** [hgrecco/pint#203]
I am new to Python and I'm trying to use pint when solving systems of differential equations using pint and odeint.
How can use both packages?
The problem I face seems related to the usage of an array with elements of different units.
For instance, the following error is returned by the code below.
    ValueError: setting an array element with a sequence.
When defining the initial conditions as yinit = np.array([s0,v0],dtype=object), diff(yinit,t[0]) yields the correct units but the error
    TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'
So far I am working around the problem by obtaining the magnitudes of the variables before integrating. I would like to know if there is a more direct way.

from scipy.integrate import odeint
from pint import UnitRegistry as ureg
Qty = ureg.Quantity
import numpy as np

a = Qty(-2.0,'s**-2')
b = Qty(-0.1,'s**-1')
def diff(y,t):
    self = [ y[1], (a*y[0]+b*y[1]) ]
    return self
t=linspace(0.0,10.0,101)
t=Qty(t,'s')
s0 = Qty(0.05,'m')
v0 = Qty(0.2,'m/s')
yinit = np.array([s0,v0])
y = odeint(diff,yinit,t)

**Comment by dreyeslastiri** [comment]
Thank you very much!
This has been helping me a lot.

**Comment by hgrecco** [comment]
Glad to help. I am closing this. Feel free to reopen or open a new one.
