### ISSUE TITLE
reduce_units? 

### ISSUE THREAD

**Issue by rwijtvliet** [hgrecco/pint#2076]
Using these definitions:

```text
#unitdefinitions.txt

mega- = 1e6 = M-

### Base dimensions and their units. Base unit without prefix. ###

# Dimensionless
fraction = []

# Duration (Time)
hour = [time] = h = hr

# Energy
watthour = [energy] = Wh

# Revenue (Currency)
euro = [currency] = Eur = €

### Derived dimensions and their units. ###

# Power
[power] = [energy] / [time]
watt = watthour / hour = W

# Price
[price] = [currency] / [energy]
euro_per_MWh = euro / (1_000_000 * watthour)  = Eur/MWh
```

I often get into a situation where a quantity has redundant units, even though `auto_reduce_dimensions` is set to `True`. For example:

```python
 import pint
 ureg = pint.UnitRegistry(str(path), auto_reduce_dimensions=True)
 
power = ureg.Quantity(5, 'MW')
duration = ureg.Quantity(2, 'h')
price = ureg.Quantity(1, 'Eur/MWh')
revenue = power * duration * price # in euros

revenue
<Quantity(10, 'megawatt * hour * euro / megawatthour')>   # wat

revenue.dimensionality
<UnitsContainer({'[currency]': 1})> # as expected
```

Is there an issue with my config?

I know I can do `revenue.to('Eur')`, but I'd like to avoid having to do this.

**Comment by andrewgsavage** [comment]
https://pint.readthedocs.io/en/stable/getting/tutorial.html#simplifying-units

> There are also methods to_reduced_units() and ito_reduced_units() which perform a simplified dimensional reduction, combining units with the same dimensionality but otherwise keeping your unit definitions intact.

it'll reduce m and mm. megawatt * hour are treated as MW and hour, which have different dimensionality to megawatthour so won't reduce

try using to_base_units or to_preffered

**Comment by rwijtvliet** [comment]
Thanks for that fast reply. I think `to_preferred` is actually what I want.

One follow-up question if I may, as I cannot find it in the docs. 

If I set `autoconvert_to_preferred=True` when initialising a unit registry - where do I specify, what those prefererred units are?

**Comment by andrewgsavage** [comment]
It's in the docs, ureg.default_preferred_units
