### ISSUE TITLE
`round` doesn't convert the magnitude of a quantity to `int`

### ISSUE THREAD

**Issue by Kodiologist** [hgrecco/pint#2081]
```py
>>> import pint; U = pint.UnitRegistry()
>>> round(1.1), type(round(1.1))
(1, <class 'int'>)
>>> round(1.1 * U.kg), type(round(1.1 * U.kg).magnitude)
(<Quantity(1.0, 'kilogram')>, <class 'float'>)
```

I'm not sure if this is a bug, but it certainly surprised me.

**Comment by jules-ch** [comment]
Seems to come from this line https://github.com/hgrecco/pint/blob/c70c0765f5c81c54a680045f872efe50a5c83425/pint/facets/plain/quantity.py#L1291

Want to open a PR for this ?

**Comment by jules-ch** [comment]
Might be more complicated than just type hinting haha, I will try to see whats going on

**Comment by Kodiologist** [comment]
I haven't used type hints much myself. That code sure looks like it should produce an `int`, if the built-in `round` is being called.

**Comment by jules-ch** [comment]
Those lines should be like this:

```python
    def __round__(self, ndigits: int | None = None) -> PlainQuantity[int]:
        return self.__class__(round(self._magnitude, ndigits), self._units)
```

**Comment by jules-ch** [comment]
Per the docs : 

round(number[, ndigits])
Return number rounded to ndigits precision after the decimal point. If ndigits is omitted or is None, it returns the nearest integer to its input.


It defaulted to 0 here
