### ISSUE TITLE
Typing: to method returns a PlainQuantity

### ISSUE THREAD

**Issue by denialhaag** [hgrecco/pint#2088]
Running `mypy` on the file below results in the following error: `Incompatible return value type (got "PlainQuantity[Any]", expected "Quantity")`

```py
from pint import Quantity, UnitRegistry

ureg = UnitRegistry()

def quantity_to_mm(quantity: Quantity) -> Quantity:
    return quantity.to(ureg.mm)
```

**Comment by jules-ch** [comment]
Hey there I probably have a fix for this.
Need to use `Self` in PlainQuantity

**Comment by denialhaag** [comment]
@jules-ch, thanks for the hint! Your proposed fix seems to work for me. I created a PR.

**Comment by jules-ch** [comment]
I'm gonna tackle this soon to work on fixing type hints that have been broken after introducing facets. @hgrecco has worked on improving things to use static classes & keep runtime checks that was built into pint.
Should not be too hard, I hope for now it works only on mypy I struggle with pyright sometimes.

Will introduce a PR soon
