### ISSUE TITLE
Cannot pass list using @ureg.wraps and np.array is hard to construct

### ISSUE THREAD

**Issue by mj8w** [hgrecco/pint#210]
I'm very new to this library, but I am impressed with much of it's capabilities. 

I have the following code which illustrates my dilemma. I need to pass a list [Q_,...] into a wrapped function. Although I can pass a np.array() into scalePts(), it takes a lot of work to construct it from other components, because np.array won't directly accept a list of quantities, without at least losing the units, so I would need to re-specify the units, as shown below.

Please also see the proposed solution; where the list is allowed in the wrap decorator. If there is a better way, I'm way open to hearing it.

############ EXAMPLE ###########
import numpy as np

from pint import UnitRegistry
ureg = UnitRegistry()

@ureg.wraps(None, (ureg.mil, None)) 
def scalePts(pts, scale = 1):
    """ write points to a file; pts = [[x,y],...] """
    points = np.array(pts) * scale
    print points

if __name__ == '__main__':
    # requirement for these two structures to be created and acted on separately
    i1 = [3., 4.] * ureg.mil
    i2 = [400., 300.] * ureg.millimeter
    print ("i1,i2 = %s, %s\n\n" % (i1,i2))

    # this doesn't currently work...
    scalePts([i1,i2], (ureg.mil / ureg.meter))

    # > np.array([i1,i2]) 
    # ValueError: setting an array element with a sequence.

    # a way to allow a build up of np array
    outer = np.array([np.array(i1.to(ureg.mil)),np.array(i2.to(ureg.mil))]) *ureg.mil
    print ("outer = %s\n\n" % (outer))
    
    scalePts(outer, (ureg.mil / ureg.meter))
   

############  unit.py, around line 1308 ###########
            def wrapper(*values, **kw):
                new_args = []
               
                for unit, value in zip(units, values):
                    if unit is None:
                        new_args.append(value)
                    elif isinstance(value, Q_):
                        new_args.append(self.convert(value.magnitude, value.units, unit))
*                   elif isinstance(value, type([])) and len(value) and isinstance(value[0], Q_):
*                       c = [self.convert(v.magnitude, v.units, unit) for v in value]
*                       new_args.append(c)
                    elif not strict:
                        new_args.append(value)

**Comment by hgrecco** [comment]
http://pint.readthedocs.org/en/0.6/defining.html
