### ISSUE TITLE
Tips for Improving Performance in pint calculations

### ISSUE THREAD

**Issue by rkingsbury** [hgrecco/pint#212]
This is less of an issue and more of a "best practices" in how to minimize the performance impact of using pint in a computationally-intensive project. I know that there is work underway to continue improving pint's performance (See #193 ), but I think it's also worth discussing coding techniques that make most efficient use of what we have now.

Here's what I've found so far. Please add other ideas!

#### Do arithmetic with magnitudes whenever possible.
If you need to do a simple comparison or difference, it's significantly faster to operate on the magnitudes (even though your'e still using pint to retrieve them)
```
from pint import UnitRegistry
ureg = UnitRegistry()

In [4]: q1 =ureg('1m')

In [5]: q2=ureg('2m')

In [6]: %timeit (q1-q2)
100000 loops, best of 3: 7.9 µs per loop

In [7]: %timeit (q1.magnitude-q2.magnitude)
1000000 loops, best of 3: 356 ns per loop

```
#### Avoid iteration + unit conversion
Calling a numerical solver (such as brentq from the scipy package) on a function that involves unit-aware computations seems to be quite expensive. If possible, recast the function to use magnitudes.
```
from scipy.optimize import brentq

def foobar_with_quantity(x):
    # find the value of x that equals q2

    # assign x the same units as q2
    qx = ureg(str(x)+str(q2.units))
    
    # compare the two quantities, then take their magnitude because
    # brentq requires a dimensionless return type
    return (qx - q2).magnitude

def foobar_with_magnitude(x):
    # find the value of x that equals q2

    # don't bother converting x to a quantity, just compare it with q2's magnitude
    return x - q2.magnitude
    
In [1]: %timeit brentq(foobar_with_quantity,0,q2.magnitude)
1000 loops, best of 3: 310 µs per loop

In [2]: %timeit brentq(foobar_with_magnitude,0,q2.magnitude)
1000000 loops, best of 3: 1.63 µs per loop
```
Some of this may be obvious, but I thought I'd post here to be helpful and to see what experience others have had with this. If we develop enough of a consensus, perhaps I'll add something to the documentation.

**Comment by rsking84** [comment]
Thanks for pointing out wraps! I had compeltely overlooked it in the documentation. I've been trying to make use of it on my project but am finding it difficult to use with complex functions that have either 1) optional arguments with default Quantity values or 2) call other functions that return Quantities.

See Issue #225

**Comment by hgrecco** [comment]
@rsking84 See also #195 and #196
