### ISSUE TITLE
Better document unintuitive aspects of pint

### ISSUE THREAD

**Issue by ryanpdwyer** [hgrecco/pint#214]
Some unintuitive aspects of pint:

1. ``to_base_units`` converts to units without prefixes, not MKS units (See #209)
2. Unlike many other units implementations, dividing two quantities with the same dimensionality does not cancel the units, or produce a unitless / dimensionless output

This is documented, but included here for completeness.
3. Units from different unit registries can't be compared.

These type of issues could be a separate gotchas section of the tutorial, or in the FAQ.

**Comment by bgamari** [comment]
@hgrecco if I'm not mistaken `float` will not work if the `Quantity` is an `ndarray`.

**Comment by hgrecco** [comment]
@bgamari  True.

**Comment by bgamari** [comment]
@hgrecco I would love to see a function added to `Quantity` like the following to address this,

```python
def as(self, unit):
    return (self / unit).to('').magnitude
```

**Comment by hgrecco** [comment]
I like the idea. Let's bikeshed the name and add it.

**Comment by hgrecco** [comment]
I am closing this right now. Feel free to reopen.
