### ISSUE TITLE
found another units library

### ISSUE THREAD

**Issue by rebcabin** [hgrecco/pint#216]
In your docs, you asked us to let you know if we know of another units library in python: 

sympy has one, here http://docs.sympy.org/dev/modules/physics/units.html

not sure if this is the same as https://bitbucket.org/adonohue/units/, which has a similar name

**Comment by endolith** [comment]
(I made this to compare them all http://socialcompare.com/en/comparison/python-units-quantities-packages-383avix4  it's unfinished, but can be edited by anyone)
