### ISSUE TITLE
Remove _freeze if not longer needed

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#218]
After #202, _freeze might not be needed any longer.

**Comment by MatthieuDartiailh** [comment]
Also true I should have removed it.

**Comment by hgrecco** [comment]
Don't hit yourself :-D The PR was perfect, it does what it described. But it also leaves room for further optimization!

**Comment by hgrecco** [comment]
Let's keep this open until we see your PR in action and then we fix this.
