### ISSUE TITLE
Remove TransformDict if not longer needed

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#219]
After #202 TransformDict might not be needed any more

**Comment by MatthieuDartiailh** [comment]
I think this is true. I can do it later this week if you want.

**Comment by hgrecco** [comment]
Don't hit yourself :-D The PR was perfect, it does what it described. But it also leaves room for further optimization! Let's leave this for now, until we see your PR in action. If everything works out, we fix this later.
