### ISSUE TITLE
Improving Unit speed and memory consumption by using namedutple and __new__

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#221]
Units object are everywhere and there are a lot of them.

I am wondering if something like this:

```python
class Unit(namedtuple(...), SharedRegistryObject):

```

or this:

```python

      def __new__(cls, ...):
            if <arguments> in <somecache>:
                    return <cache object>
            object = <build object>
            return
```

or both?

- is possible?
- is useful?
- is a good idea?

**Comment by MatthieuDartiailh** [comment]
If you are worried about memory consumption the first thing we can do is to slot it. And I am not sure why you say Unit are everywhere as they are never used internally (only UnitsContainer is used).

**Comment by hgrecco** [comment]
The most used pint object is udict (with 1891 copies after Registry initialization). There are some multiple times (meter **3 is like 77 times). But I doubt that we can do this immutable.

**Comment by hgrecco** [comment]
Checked! I am closing this now.
