### ISSUE TITLE
wraps does not convert default values for optional arguments

### ISSUE THREAD

**Issue by rkingsbury** [hgrecco/pint#225]
If I define a function that takes Quantity inputs and has an optional argument with a default value like so:

    def myfunc(x,y=1*ureg('meter')):
        return x + y

It works just fine with only the required argument

    >>> a = 1 * ureg.meter
    >>> myfunc(a)
    <Quantity(2, 'meter')>

But if I try to use [wrapping](http://pint.readthedocs.org/en/latest/wrapping.html) on it:

    @ureg.wraps('meter',('meter','meter'))
    def myfunc(x,y=1*ureg('meter')):
        return x + y

and I only supply the required argument, wraps fails to convert the optional argument to a magnitude, leading to a DimensionalityError:

    >>> a = 1*ureg.meter
    >>> myfunc(a)
    ...
    DimensionalityError: Cannot convert from 'meter' to 'dimensionless'

Looking at this issue with the debugger shows that the argument I supplied is converted into a magnitude by wraps, but the optional one is still a quantity. Of course everything works fine if both arguments are given:

    >>> a = 1*ureg.meter
    >>> myfunc(a,a)
    <Quantity(2, 'meter')>

Obviously this makes it difficult to use wraps with complex functions.

**Comment by hgrecco** [comment]
Wraps works by taking arguments given by the user and converting them before passing them to the function. In other words, the function (and therefore the function definition) works without units.

In other words, this should work (I cannot test it right now)
```python
@ureg.wraps('meter',('meter','meter'))
def myfunc(x,y=1):
    return x + y
```

I think we could change the decorator to make your way of writing work but It will make it too complex. My feeling (but I am open to opinions) is that adding something like this explanation to the docs might be enough. Thoughts?

**Comment by hgrecco** [comment]
I am closing this right now. Feel free to reopen if necessary.
