### ISSUE TITLE
More convenient way to extract magnitude in specific units

### ISSUE THREAD

**Issue by bgamari** [hgrecco/pint#227]
As mentioned in https://github.com/hgrecco/pint/issues/214#issuecomment-69291571 it would be nice to have a function to get the magnitude in a given set of units. This would look something like,
```python
def into(self, unit):
    return (self / unit).to('').magnitude
```

Such that one could do something like the following,
```python
u = pint.UnitRegistry()
a = 5 * u.liters / u.second
print a.into(u.cm^3 / u.year)
```

The name is up for debate. `as` would be great but unfortunately it's a keyword. I have needed a function like this quite often so I'm rather partial to the short length of `into` but it's arguably a bit terse.

**Comment by hgrecco** [comment]
+1 on adding such a function.

Let's bikeshed the name. I do not like `into` as it seems to me that it should do an in place conversion (currently done by `ito`). Your previous name (`magnitude_as`) was clear but to long. 

Some random thoughts:
- `m_as`
- `mag_as`

other ideas?

**Comment by bgamari** [comment]
@hgrecco Either of your suggestions seem like they'd be fine (albeit in both cases a bit terse). It's too bad all of the obvious choices have been eaten up as keywords.

**Comment by hgrecco** [comment]
Implemented in develop.

**Comment by natezb** [comment]
I wasn't sure where to put this, I can open a new issue if you prefer.

I think this method will be very useful. However, I like the idea of it accepting a `str` for the units as well, like `Quantity.to()` does. e.g. you can do `q.to('ms')` currently, but not `q.m_as('ms')`.

**Comment by hgrecco** [comment]
No need for a new PR. I agree that the current implementation is unnecessary limited. Would you like to submit a Pull Request for this?
