### ISSUE TITLE
Barrel vs Barrel

### ISSUE THREAD

**Issue by noise** [hgrecco/pint#228]
I noticed that barrel is using US Oil Barrel size of 42 US gallons. It's probably more common to convert barrels to other units when talking about beer, e.g. # of US pints in a 1/2 bbl (US beer barrel). 

It might be worth splitting barrel into:
  us_oil_barrel = 42 * gallon
  us_liquid_barrel = 31.5 * gallon
  us_beer_barrel = 31 * gallon
  imperial_barrel = 36 * imperial_gallon

See:
  https://en.wikipedia.org/wiki/Barrel_(unit)

**Comment by hgrecco** [comment]
I think you are right. Would you like to submit a PR against develop.
