### ISSUE TITLE
Add unittest and continuous integration

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#236]
Hello,

I will be nice if you could add continuous integration.
Travis is great for this.

Kind regards

**Comment by hgrecco** [comment]
Since the beginning of the project we have unittesting, CI, and coverage report.

Take a look at:

https://github.com/hgrecco/pint/tree/master/pint/testsuite
https://travis-ci.org/hgrecco/pint
https://coveralls.io/r/hgrecco/pint

**Comment by scls19fr** [comment]
Oh sorry!

Maybe you should add a Travis and Coveralls badge

**Comment by scls19fr** [comment]
I was looking for a test directory outside of package
