### ISSUE TITLE
Metrics prefix and engineering notation

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#237]
Hello,

Support for metric litteral prefix will be nice:

see http://stackoverflow.com/questions/15733772/convert-float-number-to-string-with-engineering-notation-with-si-prefixe-in-py/15734251#15734251

and also https://gist.github.com/thorsummoner/aed154cbba0cf9f61182

Kind regards

**Comment by hgrecco** [comment]
I do not understand what you mean by this. Metric prefixes are available in Pint since 0.1

**Comment by scls19fr** [comment]
I'm new to this lib. So please excuse me
I'm not looking for metrics units but just to prefix ("k" "M" "G" "T" ...)

**Comment by scls19fr** [comment]
I don't know for example if I have a distance in "centimeter" how I can just get "centi" (prefix). But that's maybe a misunderstanding from my side.

**Comment by scls19fr** [comment]
In [39]: distance = 1.0 * ureg.meter

    In [40]: distance
    Out[40]: <Quantity(1.0, 'meter')>

    In [41]: distance*1000
    Out[41]: <Quantity(1000.0, 'meter')>

Is there a way to automatically get `<Quantity(1.0, 'kilometer')>`

**Comment by hgrecco** [comment]
You can just do:
```python
>>> distance = 1000. * ureg.meter
>>> distance.to('km')
<Quantity(1.0, 'kilometer')>
```
We are adding a way to automatically provide a compact representation in 0.7 See #224

**Comment by scls19fr** [comment]
Can you from Quantity get value (`1.0`), prefix (`kilo`) and unit (`meter`) ?

**Comment by hgrecco** [comment]
try: `q.magnitude` and `q.units`
or 
```
ureg.parse('kilometer')
```
You cannot get `kilo` and `meter` from `q` because q might be a compound unit `kilometer/second`

**Comment by scls19fr** [comment]
maybe you should should consider that kilometer/second is composed of kilo and meter/second.

I fact the problem is that lack of "prefix". a physical value is composed of numerical value (without prefix), a prefix and a unit. You are considering prefix as part of unit.

**Comment by hgrecco** [comment]
I thing that is very confusing. What happens when you have `kilometer/nanosecond`?

**Comment by scls19fr** [comment]
It should calculate kilo/nano (10^3/10^9 = 10-^6) so prefix will be micro and unit is meter/second

**Comment by scls19fr** [comment]
Working with prefix with dimensionless quantities should also be allowed

    ureg['kilo']

   ureg['nano']

    ureg['kilo/nano']

**Comment by hgrecco** [comment]
Why would you write `ureg['nano']` instead of `1e-9`? What is the use case of your feature request?

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen with more information if you still think is necessary.
