### ISSUE TITLE
Add Travis, Coverage, Pypi badge

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#238]
It will be nice to add Travis, Coverage, Pypi badge to frontpage

**Comment by scls19fr** [comment]
For example:

    [![Build Status](https://travis-ci.org/hgrecco/pint.svg?branch=master)](https://travis-ci.org/hgrecco/pint)

Some other example for Pypi https://pypip.in/

**Comment by jonemo** [comment]
Given the discussion in https://github.com/hgrecco/pint/pull/241, this can probably be closed as #wontfix.

**Comment by bilderbuchi** [comment]
This issue can be closed, those badges are there now.

**Comment by hgrecco** [comment]
thanks
