### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#239]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with pint. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable pint on @Sourcegraph by going to https://sourcegraph.com/github.com/hgrecco/pint and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by hgrecco** [comment]
Done!

**Comment by scls19fr** [comment]
Thanks
