### ISSUE TITLE
Prefered compatible units

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#242]
Hello,

    q = 10*ureg.volt/ureg.ampere
    <Quantity(10.0, 'volt / ampere')>

    q2 = q.to_base_units()
    <Quantity(10000.0, 'gram * meter ** 2 / ampere ** 2 / second ** 3')>

It will be great to be able to factor unit and get

    <Quantity(10.0, 'ohm')>

TI 92 and TI 89 calculator (with Computer Algebra System) had such a feature.

I saw

    q2.compatible_units()
    frozenset({u'Z_0', u'ohm', u'statohm'})

maybe a kind of "prefered" order should be defined (that's probably hard to implement)
and a method should return most prefered compatible unit.

Kind regards

**Comment by hgrecco** [comment]
Yes. This is long desired feature (See #15).  Following your code, we need first to define a sorting order for the output of `compatible_units` and we do not have yet a good way to do it. (That is why we return a frozenset and not a tuple). See the discussions in #89 

But it gets more complex. For example, certain compound units (eg. km**2 / degK) cannot be represented in a single unit. So we need to do a combinatorial scan of how it can be written in terms of existing units. I have some code in my private repo that used OrthogonalMatchingPursuit to find the shortest combination of units (base and derived) with the same dimensionality of the input units. It was working for some cases, but not giving good results in others.

I am +1 on this if it can be achieved. Please look at the issues that I pointed for previous discussions and also at #151

**Comment by hgrecco** [comment]
I am closing this as it can be partially be achieved with Systems. See #215
