### ISSUE TITLE
Abbreviated unit names not always shorter

### ISSUE THREAD

**Issue by FilipeMaia** [hgrecco/pint#243]
Certain units, like electron volt, are longer when using abbreviated units.
Using the default format they come out at "eV". With the abbreviated format they print as "electron_volt".

Same happens with hartree.

**Comment by hgrecco** [comment]
You are right! Good catch. The concept of abbreviations came after the first definition file. Feel free to fix them in default_en.txt. The rule is quite simple, if the equal signs (`=`) defines positions
- the first is the canonical name of the unit.
- the third is the symbol/abbreviated name

So:
<Canonical name> = <definition> = <symbol/abbreviated name>

Make a Pull Request against develop and I will merge it.
.

**Comment by hgrecco** [comment]
Fixed in develop. Thanks
