### ISSUE TITLE
Printed units have "m**1" instead of just "m"

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#244]
Here is an MWE showing what I think is a strange final result.

```
In [66]: a = ureg.m**4/ureg.s**3
In [67]: z = ureg.m
In [68]: (a**(2/3.)*z**(-5/3.)).to_base_units()
Out[68]: <Quantity(1.0, 'meter ** 1 / second ** 2')>
```

I would expect the result to be ` <Quantity(1.0, 'meter / second ** 2')>`

**Comment by hgrecco** [comment]
It should, but it is actually not a problem of Pint. Is the way floating point operations work. The operation behind your calculation is `2/3. * 5/3.` and when you try it in the REPL:
```
>>> 2/3. * 5/3.
1.111111111111111
```

What is wrong about Pint is that is not showing that there are more digits.

**Comment by mankoff** [comment]
That makes sense. My actual code (not the MWE) has an exponent of 1.000000000002.

Seems like in your example, Pint should show that the exponent is 1.1, not 1. That is a separate bug. In the case of 1.0000000002, Pint ought to treat it as 1, and then not show the exponent at all. Of course, there comes a point betwixt the two where it isn't clear what to do. Maybe a value `ureg.eps` could be set with reasonable defaults but customizable to threshold where numbers are rounded or not...

**Comment by hgrecco** [comment]
Yep. Can you close this bug and open another just for this? I think we need to implement something like what you are proposing. Additionally we will need to document this behaviour.

**Comment by mankoff** [comment]
See #245
