### ISSUE TITLE
Exponents with decimal digits may not be handled properly

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#245]
This bug manifests in two ways: 1) Not showing fractional exponents when necessary, and 2) Showing exponents when not necessary. See also #244.
### Case 1

```
In [14]: a = ureg.m**4/ureg.s**3
In [15]: z = ureg.m
In [16]: (a**(2/3.)*z**(-5/3.)).to_base_units()
Out[16]: <Quantity(1.0, 'meter ** 1 / second ** 2')>
```

It looks like the result should be `m / s ** 2`, not `m ** 1 / s ** 2`, but `(2/3.)*(-5/3.)` is `-1.1111`, so the `1` exponent should be `1.1111`.
### Case 2

```
In [26]: ureg.m**1.000001
Out[26]: <Quantity(1.0, 'meter ** 1')>
```

Should be treated as:

```
In [29]: ureg.m**1
Out[29]: <Quantity(1, 'meter')>
In [30]: ureg.m
Out[30]: <Quantity(1, 'meter')>
```
### Proposal

Add a `ureg.eps`, `ureg.round`, `ureg.sigfig` or similar variable with sensible default, customizable by the user. That variable sets a threshold that is used to adjust either the values themselves, or the pretty-printed representation of them.

**Comment by hgrecco** [comment]
I am +1 on this. We just need to find a good name that conveys exponent, rounding and format. I would set the default in 0.001 (or similar)

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if neeeded.
