### ISSUE TITLE
Exception raised when calling ureg.<unit>.dimensionality - performance issue

### ISSUE THREAD

**Issue by patituccia** [hgrecco/pint#251]
When trying to check the dimensionality of an item in the unit registry, e.g. <code>ureg.m.dimensionality</code> it causes Quantity's <code>def dimensionality(self)</code> to be called which in turn calls <code>return self.\_dimensionality</code> and then Quantity's <code>def \_\_getattr\_\_(self, item)</code>.
This code end up raising the exception:
<code>            raise AttributeError("Neither Quantity object nor its magnitude ({0})"</code>
<code>                          "has attribute '{1}'".format(self._magnitude, item))</code>

There seems to be two issues with that:

a) <code>\_\_getattr\_\_</code> never tries to check if <code>\_dimensionality</code> actually exists in self (Quantity) so the exception is raised and dealt with in the previous level.

b) The exception raising code converts the magnitude from array to string and this causes this to be very slow (for long arrays). In one particular calculation that we do 10 iterations of it were taking 101 seconds, and by just changing the exception code to be <code>raise AttributeError("Neither Quantity object nor its magnitude has the specified attribute")</code> reduced the total time to 4 seconds.

**Comment by hgrecco** [comment]
This works fine in the current develop.
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.m
<Unit('meter')>
>>> ureg.m.dimensionality
<UnitsContainer({'[length]': 1.0})>
```
 I have not checked the performance yet but it should be fine. I am also not sure if this will be the final implementation as we are leaking `UnitsContainer` and we are not sure that this is the right way yet.

**Comment by patituccia** [comment]
Hi hgrecco

Thanks for you reply. 
The functionality does work fine. I am raising the issue because of how it works. The performance is just a side effect to the fact that the implementation of <code>Quantity.\_\_getattr\_\_</code> is not checking for the existence of the passed attribute (<code>\_dimensionality</code> in this case) on self (i.e. the Quantity instance).

**Comment by patituccia** [comment]
Hi hgrecco,

Thanks for your reply.

Yest it works as intended, it is just slow if that exception is raised many times for many Quantity instances so b) is definitely an issue. When I said 10 iterations of our calculation, that means that <code>\_\_getattr\_\_</code> was called around 70k times out of which the exception was raised around 20k times, and the consequent conversion of array to string for the exception text added a lot of time to the operation as described.

I looked more carefully into a) and it isn't an issue as overriding <code>\_\_getattr\_\_</code> means that its just called when the attribute is not found in the instance. I am relatively new to Python and missed that point.

**Comment by hgrecco** [comment]
Then we should address this before the next version.
