### ISSUE TITLE
Documentation does not mention uncertainties support

### ISSUE THREAD

**Issue by lebigot** [hgrecco/pint#257]
I just had a professor of physics who was asking me for support for units in the uncertainties package: I mentioned him Pint.

I just checked the documentation, and this feature does not appear at http://pint.readthedocs.org/en/latest/. It would be useful if it could be advertised.

**Comment by jdreaver** [comment]
Is [this](http://pint.readthedocs.org/en/latest/measurement.html) what you were looking for?

**Comment by hgrecco** [comment]
Maybe we should point it out in the features in the main page.

**Comment by lebigot** [comment]
@hgrecco Exactly my suggestion: in fact, this feature is needed by some people, and they don't use Pint because they don't think they can handle uncertainties with it. :)

**Comment by hgrecco** [comment]
Fixed in develop. Thanks.
