### ISSUE TITLE
Support for the math module

### ISSUE THREAD

**Issue by lebigot** [hgrecco/pint#259]
Since Pint support things like `numpy.sqrt(…)`, it would be nice if it allowed people to use the math module as well (for instance through a `pint.pintmath` module).

One consequence of this is that people try the following, but it fails:

```
from uncertainties import umath

umath.sqrt(<pint number with units>)
```

Removing this limitation would be nice.

I guess that using new `pintmath` module instead would be the simplest thing to do?

**Comment by hgrecco** [comment]
The recommended way when you require other operations apart from `+`, `-`, `*`, `/` and `**` is to use NumPy. Using the python `math` module will require monkey patching (which I am against) or wrapping (which is what you are suggesting and I will fine with it). 

But doing `umath.sqrt` will still fail as `umath` knows nothing about `pint`. The only way to make it work would be to dispatch from `umath` to an hypothetical `pintmath`.

**Comment by lebigot** [comment]
This makes sense.

The wrapping of the math module would work too, with Pint calling `umath` when needed, right?

Now, I'm not saying that this should be done: hopefully I can make NumPy functions directly handle uncertainties like you did for Pint, in a way compatible with Pint. That will help the people who want units *and* uncertainties.

**Comment by hgrecco** [comment]
If we create a `pintmath` module in pint, then `umath` should dispatch to `pintmath` and `pintmath` to `umath`. That is the only way it would work.

**Comment by dmwelch** [comment]
Related ticket:  https://github.com/hgrecco/pint/issues/276
