### ISSUE TITLE
Incorrect units in result

### ISSUE THREAD

**Issue by lebigot** [hgrecco/pint#260]
```
from pint import UnitRegistry
from uncertainties import unumpy

un = UnitRegistry()
print unumpy.sqrt(4*(un.m)**2)
```
prints `2.0`, *with no units*.

**Comment by hgrecco** [comment]
The problem is how uncertainties deals with math operations. It works just fine with numpy
```
>>> import pint
>>> import numpy as np
>>> np.sqrt(4*(ureg.meter)**2)
<Quantity(2.0, 'meter')>
```

**Comment by lebigot** [comment]
So, Pint interacts in a more natural way with NumPy.

Can you tell me the principle behind your handling of NumPy? I never found anything in NumPy's documentation about how to handle something like `numpy.sqrt()` for numbers with uncertainties (that's why I created `uncertainties.unumpy`).

Furthermore, do you have suggestion about how I could handle `numpy.sqrt()` for numbers with uncertainties *in a way which is compatible with Pint*?

**Comment by hgrecco** [comment]
Yes. Supporting Numpy without monkey patching is something I think Pint does really good (and we are quite proud.) We basically override the `__array_*` methods and dispatch there. You can do the same thing in `ufloat`. This is what I was mentioning here: https://github.com/lebigot/uncertainties/issues/19

If you support `numpy.sqrt`, it will automatically work with pint. :-D

**Comment by hgrecco** [comment]
I am closing this as the title is misleading and most is discussed in #259
