### ISSUE TITLE
scruple definition is incorrect

### ISSUE THREAD

**Issue by takluyver** [hgrecco/pint#262]
pint defines a scruple as 20 grams - a few sources I found with a quick search all show a scruple as approx 1.3 grams. I think it should be 20 *grains*.

It looks like there's a similar problem with the drachm/apothecary's dram - it should be 60 grains, not 60 grams.

See table here: http://en.wikipedia.org/wiki/Apothecaries%27_system#English-speaking_countries

**Comment by hgrecco** [comment]
Fixed. Thanks
