### ISSUE TITLE
Are you Serializing Pint Units? How? How can Pint (or Pint docs) help?

### ISSUE THREAD

**Issue by willstott101** [hgrecco/pint#266]
It would be really nice if the [Serialization](http://pint.readthedocs.org/en/0.6/serialization.html) page mentioned Python's json library. I would expect it to offer nothing except perhaps clarification on the best way to do this:

    class QtyJSONEncoder(JSONEncoder):
        def default(self, o):
            if isinstance(o, _Quantity):
                return str(o)
            return super(QtyEncoder, self).default(o)

Or just simply a recommended way for checking if a quantity is a Quantity object or not. Importing _Quantity seems naughty. As I see it, 90% of the time, the string representation is better than a split form, so I am using this in my Django app, rather than splitting to natives (which is what I assume is the recommended method).

**Comment by hgrecco** [comment]
I agree that would be nice to provide a way of doing this or at least some discussion. Basically, the *split to native* and then saving to a binary file is the best way if you want to preserve the precision. The string representation (splited or not) is always truncated. If you can live with this, the `str(q)` is nice and easy as well as easy to understand in the output file. It also can be retrieved using `parse_expression`. 

I would like to hear how other people does it. I am changing the title of the question to get more people involved.

**Comment by hgrecco** [comment]
I have added more examples to the docs and a link to the serialize library which can be useful.

http://pint.readthedocs.org/en/latest/serialization.html
