### ISSUE TITLE
Register (nm) nautical miles as unit for parse_expression

### ISSUE THREAD

**Issue by scls19fr** [hgrecco/pint#269]
Hello,

I need to parse distance strings ("1000m", "1nm" (nautical miles), "1ml" (statute miles))

I'm trying

    from pint import UnitRegistry
    ureg = UnitRegistry()
    ureg.parse_expression("1m")
    <Quantity(1, 'meter')>

works fine but

    ureg.parse_expression("1nm")

returns `<Quantity(1, 'nanometer')>`

which is correct is most case... but not mine.

I would to have "nm" being recognized as nautical miles.

Is there a way of doing this ?

Kind regards

**Comment by hgrecco** [comment]
There is an unavoidable name clash between that and nanometer. The only way would be to create a restricted definition set for your purpose, removing nanometer. But might hamper the usage for other purposes.

**Comment by scls19fr** [comment]
does your API provide a way to deregister 'nm' of being nanometer and  to add a new rule to register nm as a unit for nautical miles ?

**Comment by hgrecco** [comment]
The problem with nanometer is that you will need to deregister the prefix (`nano`, abbreviated `n`) and/or `meter` (abbreviated `m`). Right now there is no way to `undefine` a unit. The easiest way is that you copy and edit this file https://github.com/hgrecco/pint/blob/master/pint/default_en.txt and the load it explicitely:
```python
import pint
ureg = pint.UnitRegistry('myfile.txt')
```

You can get the syntax from here:

http://pint.readthedocs.org/en/latest/defining.html

(also the API to define units)

**Comment by scls19fr** [comment]
Maybe you should define in your API something that load "classic" definitions of units and which can be overloaded by user definition. User definitions being considered before standard definition for `parse_expression` function.

I've found an ugly a workaround. I use a regex to split numerical values from units and use a dictionary to convert "my" units (nm) to something that Pint can understand.

**Comment by hgrecco** [comment]
I am closing this right now. Feel free to reopen.
