### ISSUE TITLE
Adding support for atomic units

### ISSUE THREAD

**Issue by jvtrudel** [hgrecco/pint#271]
Thank you for this marvellous library. I expect that its use will change me life (for the best I hope).

Having said that, I'd like to know I you plan to add support to handle atomic units. I need to translate atomic units to other unit system et vice versa. I already did it by modifying the default file, but it is rather a limited implementation for the moment.

I'd like to do something that is more general because I plan to publish codes (as [heavySide](https://github.com/jvtrudel/heavyside.git) for example) that relate on pint for handling atomic units. 

  - Have you already done some effort in that direction already?
  - What would it need to a solution to be as complete as possible?
  - Have you a better idea for generic naming that au_time, au_energy, au_WhateverUnitYouHaveToHandle?

**Comment by hgrecco** [comment]
Sorry for the long delay. Nothing has been done in that direction but I will be happy to merge a PR for that. Did you manage to do something?

**Comment by jvtrudel** [comment]
Yes and no. I did it for my own purpose some time ago, but a lot seem to changed in pint since then. I'll try to look at it in the next weeks and I'll try a PR.

**Comment by hgrecco** [comment]
The public API of Pint is completely backwards compatible. We have done a
few things under the hood and also added new features. For your particular
purpose, there a few things that might be useful. Maybe the concept of
Systems and groups: https://github.com/hgrecco/pint/issues/215

>
If you outline the scope of your needs, I will be happy to discuss it with
you.

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen or open anew issue if needed.
