### ISSUE TITLE
How to import module with wraps from subfolder?

### ISSUE THREAD

**Issue by dreyeslastiri** [hgrecco/pint#274]
I have a folder structure:
dir\
  - \__init\__.py
  - main.py
  - subfolder\
    - \__init\__.py
    - foo.py

And a module Conc in foo:
<pre><code>@ureg.wraps( 'g/L',('hr','g/hr','L') )
def Conc(time,flow,vol)
    self = time*flow/vol
    return self</code></pre>

When running Conc in foo itself, it gives the expected result: 60.0 gram / liter
<pre><code>if __name__ == '__main__':
    time1=Qty(20.0,'hr')
    flow1=Qty(30.0,'g/hr')
    vol1=Qty(10.0,'L')
    result=Conc(time1,flow1,vol1)
    print result </code></pre>

But when I try to do this by importing Conc from the script main.py
<pre><code>from subfolder.foo import conc
time1=Qty(20.0,'hr')
flow1=Qty(30.0,'g/hr')
vol1=Qty(10.0,'L')
result=conc(time1,flow1,vol1)
print result </code></pre>

I then get the error
ValueError: A wrapped function using strict=True requires quantity for all arguments with not None units. (error found for hour, 20.0 hour)

I do not want to set strict=False because the verification of units is relevant for me.

How can I work with wraps when importing the module?

**Comment by hgrecco** [comment]
Your code is fine and works. I have just tested it. are you sure your bug is not someplace else

**Comment by dreyeslastiri** [comment]
Thanks for the confirmation.
The problem was related to the import of the UnitRegistry. I missed the fact that only one UnitRegistry can be imported at each run.
It seems that, when working with folders outside of the Python installation directory, the imported UnitRegistry must be in the same directory level as the lowest imported module that uses pint.
Please let me know if this interpretation is correct.

**Comment by hgrecco** [comment]
It doesn't, you just need to be sure that you are using a single registry.

**Comment by hgrecco** [comment]
feel free to reopen
