### ISSUE TITLE
Taking sqrt of meter**2

### ISSUE THREAD

**Issue by eulerreich** [hgrecco/pint#276]
Taking the sqrt of a value with unit meter**2 will throw an error

```
DimensionalityError: Cannot convert from 'meter ** 2' to 'dimensionless'
```
 when the expected behavior is returning a value with unit meter

**Comment by hgrecco** [comment]
It works fine for `**.5` and `numpy.sqrt`, but not for Python's `math` module (which I guess is what you are using). 
```
>>> import pint
>> ureg = pint.UnitRegistry()
>>> q = 1. * ureg.meter ** 2.
>>> q ** .5
<Quantity(1.0, 'meter')>
>>> import numpy as np
>>> np.sqrt(q)
<Quantity(1.0, 'meter')>
```
In order to make it work you would need to wrap the math module, with Pint aware functions.

**Comment by hgrecco** [comment]
Sorry for the crazy open close!. If you would like to submit a math module, I will be happy to merge it

**Comment by hgrecco** [comment]
Feel free to reopen if needed.

**Comment by pablodm00** [comment]
hello! this has been inactive for a while but i have detected an issue related to this. when you use Decimal for a fractional exponent (eg `Decimal(2.5)**Decimal(0.5)`), this raises an error as i think pint is currently unable to handle this. see details in https://github.com/hgrecco/pint/discussions/2150

thanks, 
Pablo
