### ISSUE TITLE
Decorator wrapper to check the dimensions on function input args

### ISSUE THREAD

**Issue by kaidokert** [hgrecco/pint#282]
There is a ureg.wraps decorator that converts from builtins to pint quantities. Is anyone interested in decorator that checks correct dimensionality on input variables ? I found i needed this in my own library that uses Pint a lot.
The gist is here, i can make this into a pull request if there is interest

https://gist.github.com/kaidokert/7e23f4593cc7b4b69c92

**Comment by hgrecco** [comment]
Yes! I would like a PR in relation to this. Take a look at #198 #196 and #195

**Comment by kaidokert** [comment]
Couple of small questions. I'm not sure about naming the API calls properly for a straightforward and self-explanatory use, so @ureg.require_units ? @ureg.require_dimensions ? 

Second, in my usage and the gist i posted, i do not enforce or check return value there ( different from @ureg.wraps ). My reasoning is this : if i'm writing a library that manipulates quantities and it expects inputs from unknown code, checking their dimensionality attribute is probably the least offensive type checking, as exact type checking in kind of un-pythonic. If the duck has a dimension of length, you can reasonably try to calculate how many of them fit in the phone booth.

However, returning correct type from the same library call should be ensured by the unit tests on my code, rather than at run-time by the wrapper function. 

The reasoning is different for @ureg.wraps having a return type spec, as it is intended to actually perform conversions on a wrapped function. Does that make sense ?

**Comment by hgrecco** [comment]
Thanks for looking into this. 

Indeed this is different from `wraps`. `wraps` is not a checker, but rather a way to encapsulate non-pint aware code. That is why it takes quantities, pass their (converted) magnitude into the function and then use the return value as the magnitude of a new quantity.  Your line of reasoning  make sense. If we follow this idea, we need to make it clear in the docs as it will have a different API compared to `wraps`. (again, it is not a problem just need to be clear). IF we want to have the same API, we could allow  `None` as a way to skip it (this is what we do in `wraps`)

Regarding the naming, another possibility will be `check`. It is small and clear. I think we should have just one that works for both units and dimensions.

Regarding the implementation, in `wraps` we parse the input variables during decorations. This is better as it avoid an overhead when calling the wrapped function. Take a look at the `wraps` code.

... and make the PR against develop

**Comment by hgrecco** [comment]
By the way, what do you think about #195 and #196 ?

**Comment by hgrecco** [comment]
Merged
