### ISSUE TITLE
Change value of existing quantity

### ISSUE THREAD

**Issue by julietbravo** [hgrecco/pint#288]
I'm not quite sure where to put this; whether I missed something in the documentation, or whether this might be a feature request....

One problem I'm running into with Pint is how to change existing variables / quantities, without losing the units. For example, when I say `dt = 1 * ureg['s']`, how can I change `dt` without losing the units, or again having to write `dt = 2 * ureg['s']`? This is a bit problematic in Python since writing `dt=..` will always give you a new variable instead of changing the existing one, but for that I would expect something in Pint like `dt.set_value(2)`?

**Comment by julietbravo** [comment]
As a more complete example; how should one handle a situation like this:
```
mass = 0 * ureg['kg']
volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']
mass = rho * volume
```
This always works, even if I start off from `mass = 0 * ureg.astronomical_unit`

**Comment by hgrecco** [comment]
You can't do that with the public API, but you can directly change the internal attribute:

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> q = 2 * ureg.meter
>>> q
<Quantity(2, 'meter')>
>>> q._magnitude = 8
>>> q
<Quantity(8, 'meter')>
```

However, I would not recommend this. I am not sure I understand your use case, can you describe it in more detail?

**Comment by julietbravo** [comment]
I'm mostly interested in units checking, not so much in conversions and/or having units attached to my variables (e.g. for documentation) With my example from above:
```
volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']
mass = rho * volume
```
`mass` automatically becomes `<Quantity(1.2, 'kilogram')>` which is correct, but if I had accidentally written `mass = rho / volume` I get the incorrect units for mass. If using the `=` operator we could only change the value of an object (instead of creating a new one) this would be possible:
 ```
mass = 0 * ureg['kg']
volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']
mass = rho / volume  # Would have to throw error
```
But that of course isn't possible in Python. This does work when using arrays:
```
mass = np.zeros(1) * ureg['kg']
volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']
mass[0] = rho / volume  # Throws error
```
What would be the easiest way to achieve similar unit checking on scalars?

**Comment by hgrecco** [comment]
I see now, in general I would say that 
```python
volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']
mass = rho * volume # Throws error
```
is a no go. In Python, variables are labels or tags of a value. I think that the behavior you are proposing will be confusing.

But Pint provides a few nice things for type checking:
- In the current version Function wrapping, see http://pint.readthedocs.org/en/0.6/wrapping.html
- In the the next version we added checking, see #283 

I guess the best way would be to define a property and use it in a class (untested code)

```python

import pint
ureg = pint.UnitRegistry()

class PhysicalValue(object):

    def __init__(self, default_value):
        self.val = default_value
        self.dim = default_value.dimensionality

    def __get__(self, obj, objtype):
        return self.val

    def __set__(self, obj, val):
        if val.dimensionality != self.dim:
            raise ValueError # or a pint.DimensionalityError
        self.val = val


class Planet:

    mass = PhysicalValue(0 * ureg.kg)


volume = 1 * ureg['m**3']
rho = 1.2 * ureg['kg*m**-3']

earth = Planet()
earth.mass = rho * volume
earth.mass = rho / volume # Error
```

**Comment by hgrecco** [comment]
I hope this was helpful. I am closing it, feel free to reopen.
