### ISSUE TITLE
Missing electricial rule for farad * ohm

### ISSUE THREAD

**Issue by chrisspen** [hgrecco/pint#289]
How do you define a rule so that multiplying farad * ohm returns seconds?

I see you already have all these electrical units defined, along with some rules for auto-converting to other units, but nothing for this particular relationship. 

I tried implementing this rule myself, but your documentation on [contexts](http://pint.readthedocs.org/en/latest/contexts.html) is unclear. It only seems to work for general unit containers like "[time]" and "[length]", but there's no equivalent containers for farads and ohms.

I tried modifying the definition for seconds in default_en.txt to:

    second = [time] = farad * ohm = s = sec

but that had no effect.

What's the appropriate way to add this rule?

**Comment by hgrecco** [comment]
By default, pint does not automatically convert to base units unless you ask for it:
```
>>> ureg = pint.UnitRegistry()
>>> q = 1 * (ureg.farad * ureg.ohm)
>>> q
<Quantity(1, 'farad * ohm')>
>>> q.to_base_units()
<Quantity(1.0, 'second')>
```
or you can use `q.to(unit)` to convert to any other unit of your choice

**Comment by chrisspen** [comment]
Ah, thanks for the clarification.
