### ISSUE TITLE
Precision loss with absorbed offsets

### ISSUE THREAD

**Issue by muraj** [hgrecco/pint#290]
Found this issue when converting temperatures.  When converting Celsius to Fahrenheit, the following math is done:

degK = degC + 273.15
degF = (degK - 255.372222) \* 9.0/5.0

for degC = 3, degF = 37.4000004

in python:

> > > 3.0*9.0/5.0 + 32.0
> > > 37.4

The problem is the fact the offset (32.0) was absorbed inside the scaling factor, assuming the following is true:

(degK - (273.15 - 32.0 \* 5.0/9.0)) \* 9.0/5.0 == (degK - 273.15) \* 9.0/5.0 + 32.0

Which is not the case with floating point, especially repeating decimals.

> > > (degK - (273.15 - 32.0*5.0/9.0)) \* 9.0 / 5.0
> > > 37.39999999999999
> > > (degK - 273.15) \* 9.0/5.0 + 32.0
> > > 37.4

Offsets should be calculated outside the scaling factor to reduce floating point precision issues.

**Comment by hgrecco** [comment]
Sounds like a good idea! Would you like to submit a PR?

**Comment by ddebrunner** [comment]
I think this also may be a symptom of this issue, conversion from `degC` to `degF` is incorrect, 0C does not result in exactly 32.0.
https://www.nist.gov/pml/weights-and-measures/si-units-temperature

```
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity
home = Q_(0, ureg.degC)
print(home.to('degF'))
```

The above gives: `32.00000039999997 degF`

**Comment by pinkynrg** [comment]
And viceversa of course 32 degrees F is not exactly 0 degrees C:

```
reg('32 degF').to('degC')
<Quantity(-2.2222218376555247e-07, 'degC')>
```

**Comment by gnarlium** [comment]
Bumping this given that it's pretty major bug. This is what I'm struggling with right now. `pint` doesn't seem to be able to convert temperatures without losing precision. For example:
```
print(q(32.1, ureg.degF).to('degC'))
print(q(32.01, ureg.degF).to('degC'))
print(q(32.001, ureg.degF).to('degC'))
print(q(32.0001, ureg.degF).to('degC'))
print(q(32.00001, ureg.degF).to('degC'))^^^
print(q(32.000001, ureg.degF).to('degC'))
print(q(32.0000001, ureg.degF).to('degC'))
print(q(32.00000001, ureg.degF).to('degC'))
print(q(32.000000001, ureg.degF).to('degC'))
print(q(32.0000000001, ureg.degF).to('degC'))
```
results in...
```
0.05555533333335916 degC
0.0055553333333477894 degC
0.0005553333333523369 degC
5.533333336416035e-05 degC
5.33333337671138e-06 degC
3.3333333249174757e-07 degC
-1.6666666624587378e-07 degC
-2.1666664906661026e-07 degC
-2.216666530330258e-07 degC
-2.2216664774532546e-07 degC
```
Kelvin is incorrect as well...
```
print(q(32, ureg.degF).to('degK'))
273.1499997777778 kelvin
```
When:
32°F == 0°C == **273.15**K

**Comment by pinkynrg** [comment]
Should I open another issue for the below issue? I tried version 0.11 but it doesn't look to be working yet.

```
reg('32 degF').to('degC')
<Quantity(-2.2222218376555247e-07, 'degC')>
```
