### ISSUE TITLE
units with non-ascii names

### ISSUE THREAD

**Issue by tobiasli** [hgrecco/pint#292]
There are non-ascii characters in the default unit definition file. But trying to parse them raises exceptions do to what seems like faulty parsing. Is there any workaround?

```python
>>> from pint import UnitRegistry
>>> UNITS = UnitRegistry()
>>> UNITS.parse_expression(u'1 ångström')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\pint\unit.py", line 1251, in parse_expression
    raise UndefinedUnitError(unknown)
UndefinedUnitError: 'ngstr' is not defined in the unit registry
```

I'm working with some Norwegian units which have non-ascii characters in them (i.e. å), but the module does not seem to support unicode characters even though they exist in the unit definition.

**Comment by tobiasli** [comment]
My bad. Support is there, something else is wrong. Closing issue.

**Comment by tobiasli** [comment]
Updated original entry.

**Comment by hgrecco** [comment]
This works in Python 3 as it allows unicode identifiers.

**Comment by hgrecco** [comment]
it also works with the development version of pint in Python 2.7

**Comment by tobiasli** [comment]
Ported to 3.4 and everything works smoothly.

**Comment by hgrecco** [comment]
Glad to hear!
