### ISSUE TITLE
Unit-type retrieval

### ISSUE THREAD

**Issue by gusmaogabriels** [hgrecco/pint#293]
Suppose I wanted to integrate a time series in which data points have unit, say, kg/hr and now I integrated it over a period and want now its unit to be only kg. For that, I would need to retrieve the original time-type unit 'hr' from the source data. 

Is it anyhow possible?

In fact, could it be implemented a unit structure that would link irreducible dimensions and their corresponding units (but no base_unit)?

Best regards and thanks in advance!
Gabriel

**Comment by gusmaogabriels** [comment]
i have dug my way through.

As an example: assume you have data points of units metric_ton/hr and you integrate it over a period of 1 day with reference time-unit of seconds.
The ultimate unit would be metric_ton/hr*1day, which, when converted to base unit, spits out grams.

    from pint import UnitRegistry as ureg

    ureg = ureg()

    def revert_units(base,actual):
        comp = lambda x : ureg.Quantity.compatible_units(ureg(x))
        conv_array = []
        # derive conversion array
        for ubase in base.units.keys():
            for uactual in actual.units.keys():
                if bytes(comp(ubase))==bytes(comp(uactual)):
                    conv_array.append([ubase,actual.units[uactual]])
        # create new unit, compatible with the actual one on the base value basis
        new_unit = 1
        unit_gen = lambda x, y : ureg(x)**y
        for conv_item in conv_array:
            new_unit *= unit_gen(*conv_item)
        return actual.to(new_unit)

Example:

        base = 10*ureg('t/hr')
        actual = base*1*ureg('day')
        
        actual.to_base_units()
                = 240000000.0 gram
        revert_units(base,actual)
                = 240.0 metric_ton

**Comment by hgrecco** [comment]
Something like this might be a nice addition to pint. Like a simplification that preserves the user choices. What I do not get is why you use bytes before comparison.

**Comment by gusmaogabriels** [comment]
Thank for the prompt feedback, hggrecco.

The objective of using bytes is to simplify the __eq__ comparison.
the lambda function comp would return the output object from ureg.Quantity,compatible_unit (...), which is a list-alike object which I do not know how handle the __eq__ operator.
Therefore, so as to simplify the comparison and going from the assumption that objects will only ensue the same results for bytes if they are identical, we go from a comparison of lists-alike objects to integer numeric values.

There may be other way to circumvent this. If you come up with one, please, let us know!

Best regards,
Gabriel

**Comment by hgrecco** [comment]
I think you could skip the compatible units part. Maybe something like this:
```python
if ureg.get_dimensionality(ubase) == ureg.get_dimensionality(uactual):
```

and then if you get the exponent of the ubase, you can simplify the other part:
```python
new_unit = 1
for ubase, exponent in base.units.items():
```
and then
```
new_unit *= ureg.uactual ** exponent
```

**Comment by gusmaogabriels** [comment]
That is what I thought could be done at first. But it has the same function as the .to 

What I needed was to find dimensions-types that match (in the example mass) and convert that.I could not find a way to retrieve only the mass unit from ubase, and then I had to loop over the units of both ubase and uactual and compare those of the latter that match those from the first.

**Comment by hgrecco** [comment]
I do not mean to remove the looping. Notice that I am comparing the dimensinality of ubase and uactual (not base and actual).

**Comment by gusmaogabriels** [comment]
You are totally right! I got lost here at a certain point... I am coding a bunch of stuff while replying.

My bad! Your solution would fit like a glove.

**Comment by hgrecco** [comment]
Try it and let me know. Then we would need to find a nice name to add it.

**Comment by gusmaogabriels** [comment]
I have already tried it and it works like a charm.

**Comment by hgrecco** [comment]
post the new code here for future reference. Thanks!

**Comment by gusmaogabriels** [comment]
The code follows below. Thanks a lot, hgrecco! 

    from pint import UnitRegistry as ureg

    ureg = ureg()    
    
    def revert_units(base,actual):
    # derive conversion array
    new_unit = 1
    for ubase in base.units.keys():
        for uactual in actual.units.keys():
            if ureg.get_dimensionality(ubase) == ureg.get_dimensionality(uactual):
                # create new unit, compatible with the actual one on the base value basis
                new_unit *= ureg(ubase)**actual.units[uactual]
    return actual.to(new_unit)
