### ISSUE TITLE
Temperature Ideea

### ISSUE THREAD

**Issue by romarro** [hgrecco/pint#294]
Hi I know that adding subtracting dividing and multiplying Temperatures or offset quantities is a pain in the ass, but I what to share you some ideas I had when trying to write C# code for units:

the offset unit is defined as: x=val+offset where offset is a constant.
if we want to add say x+y the results should be val_x+val_y+offset for same offsets
if we want to multiply say 2_x the results always should be 2_val_x+offset
if we want to divide say x/2 the result should be val_x/2+offset

the offset should be applied only after the calculation is done!

the same goes for the converting degC to milidegC the offset isn't modified 

the only problem I see is when you have to do x*x but this is always done in K not in other unit
and K doesn't have any offset.

there is some complication when wanting to add degC+degF. this can be solved by making the following assumptions:
say x is in degC and y is in degF

(x.to(degK)+y.to(degK)-(0degC).to(degK)).to(degC) the first unit in the calculation

if we want to do a mean for multiple temperatures then the operator + is applied only at 2 operands at a time so say :
x+y+z+t = {[(x+y)+z] +t} ->{[(x.to(K)+y.to(K)-0C.to(K))+z.to(k)-0C.to(K)]+t.to(K)-0C.to(K)} which is equivalent with val_x+val_y+val_z+val_t +offset 
so the offset doesn't participate at the operation.

Hope you can understand what I am saying

P.S.
if there is 1/x[degC] it really means 1/x[delta_degC] let's say you have a function and you want to aproximate as a series you only work with val and not with the offset

regards,

Vlad

**Comment by hgrecco** [comment]
Thanks for all your thoughts.I do not see how we can do this algorithmically and efficiently in Pint with a simple code. But I will be happy to consider a PR if you have something.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
