### ISSUE TITLE
Converting concentrations from mass/L to mol/L

### ISSUE THREAD

**Issue by jeblackburn** [hgrecco/pint#297]
Greetings.

I have a question that might help me start researching a solution to a thorny problem in the conversion of lab test results between the two sets of units most commonly used.

In the medical field it's fairly common to test the concentration of salts such as Calcium or Sodium in fluids like blood or spinal fluid. Two common units used to express these measurements are something like mg/dL, and mmol/dL, for example. The problem, of course, is that for a given concentration of a salt in mg/dL, the conversion to mmol/dL is dependent on the molecular weight of the salt involved. So the coefficient will be different for Calcium than for Sodium, and so on.

How would we best achieve this? I could imagine introducing constants to express the molecular weights for each of the elements we're expecting to encounter. We could brute-force the conversion by specifying units for each element: mgCa, mmolCa, mgNa, mmolNa, and so on, I guess. Any ideas for addressing this more cleanly?

Thanks,
Jon Blackburn

References/examples:
http://www-users.med.cornell.edu/~spon/picu/calc/cacalc.htm

**Comment by hgrecco** [comment]
Pint has the concept of contexts (http://pint.readthedocs.org/en/0.6/contexts.html) which allows you to convert between incompatible units by providing additional information. You can create a Calcium context, activate it and then let pint do the work. But you would still need to create a context for each element. I do not see any way to avoid it.

**Comment by jeblackburn** [comment]
This is exactly what I was looking for. I'll give it a whirl and let you
know how it pans out.

**Comment by rkingsbury** [comment]
@jeblackburn you might have a look at [pyEQL](https://github.com/rkingsbury/pyEQL/tree/develop), which is a library I wrote that uses pint under the hood but builds other tools specifically for solution chemistry.

**Comment by jeblackburn** [comment]
Thanks! I'll take a look.

**Comment by hgrecco** [comment]
@jeblackburn Cool library! Nice to hear about this. Let us know if you need anything.
