### ISSUE TITLE
Use empty string for formatting abbreviated dimensionless units

### ISSUE THREAD

**Issue by cpascual** [hgrecco/pint#300]
Hi,

Currently (using git checkout  2c67bba...) the formatting of dimensionless units always yields "dimensionless" (both with and without the abbreviated format specifier "~"). I think it would be nice to return an empty string when the abbreviated format of a dimensionless unit is requested.

With an example:
~~~~
"{}".format(Quantity(1))   -->  '1 dimensionless'
"{:~}".format(Quantity(1))  --> '1 '
~~~~

If you think that this is a good suggestion, I would be happy to do a pull request.

An implementation that works for me (maybe not the optimal one) is modifying `_Unit.__format__` with an early return in the case of abbreviated dimensionless units:

~~~~
    def __format__(self, spec):
        spec = spec or self.default_format

        if '~' in spec:
            if self.dimensionless:
                return ''
            units = UnitsContainer(dict((self._REGISTRY._get_symbol(key),
                                         value)
                                   for key, value in self._units.items()))
            spec = spec.replace('~', '')
        else:
            units = self._units

        return '%s' % (format(units, spec))
~~~~

**Comment by hgrecco** [comment]
I like this. Can you submit a PR?

**Comment by cpascual** [comment]
Sure. Just did. 
PS: I don't know how/if it can be submitted as part of this same issue, so I just created it independently as #303

**Comment by hgrecco** [comment]
I will merge it next week. Thanks!
