### ISSUE TITLE
Handling of reciprocal units

### ISSUE THREAD

**Issue by rkingsbury** [hgrecco/pint#301]
Currently pint does not appear to support conversion between reciprocal units, such as ohms (resistance) and Siemens (conductance = 1/ohms).

```
In [9]: R = ureg('1 ohm')
In [10]: R.to('S')
DimensionalityError: Cannot convert from 'ohm' ([length] ** 2 * [mass] / [current] ** 2 / [time] ** 3) to 'siemens' ([current] ** 2 * [time] ** 3 / [length] ** 2 / [mass])
```

I haven't thought deeply yet about how handling of reciprocally-defined units is different or more complicated than regular unit conversions, but if @hgrecco doesn't see any major obstacles to implementing this within pint's existing architecture, I'm happy to work on it and submit a PR.

Thoughts?

**Comment by hgrecco** [comment]
Indeed this is not supported because the dimensionality is different. What is your proposal (conceptually)?

**Comment by rkingsbury** [comment]
After thinking about it more, I realize that this could be handled quite well with contexts, e.g:

```
@context electricity = elec
    [length] ** 2 * [mass] / [current] ** 2 / [time] ** 3 <-> [length] ** -2 * [mass] **-1 / [current] ** -2 / [time] ** -3: 1 / value
@end
```

I might work something up and send in a PR to have a context like this included by default. In the documentation you use the example of wavelength <-> frequency, which are units that are equivalent only under certain circumstances (hence the use of a special context). Ohms and Siemens are _always_ inversely related, so I guess that's why I expected the conversion to work out of the box.

What I'm saying is that for the general case of reciprocal units, no changes are needed. However, for some specific cases (like ohms <-> Siemens), I might advocate that appropriate conversion rules be added to pint by default. What do you think?

**Comment by hgrecco** [comment]
I am fine with adding more contexts. However, implicit conversion should only be added if there is not source of confusion or error.

**Comment by FrEaKmAn** [comment]
If I understand correctly, this could be very easily solved with contexts? Does it make sense to automatically create contexts? For example, for kWh/m^3 to automatically create context 1 / m^3/kWh?

**Comment by hgrecco** [comment]
@FrEaKmAn Indeed. I still think such type of implicit behaviour is confusing and potentially error prone. If somebody can come up with a good syntax, we can definitely consider. Feel free to reopen.
