### ISSUE TITLE
Is there a way to avoid float precision problems?

### ISSUE THREAD

**Issue by stevosn** [hgrecco/pint#302]
Hey there!
I encounter the following problem with the general [float precision](https://docs.python.org/2/tutorial/floatingpoint.html):

`a = ureg('50 nm')`
`print(a)`
50 nanometer
`print(a.to('m'))`
5.0000000000000004e-08 meter

I understand that this is a general problem with the binary representation of float numbers. I guess this problem occurs when converting by multiplying with 1e-XX, since:
```
print(50e-7)
print(50 * 1e-7)
print(50e-8)
print(50 * 1e-8)
print(50e-9)
print(50 * 1e-9)
```
5e-06
4.9999999999999996e-06
5e-07
5e-07
5e-08
5.0000000000000004e-08

May be this could be circumvented by using *significant digits*? For the example above this would be n_significant = 2, then:
```
from scipy import log10
order_magn = int(log10(a.magnitude / a.to('m').magnitude))
print(order_magn)
print(round(a.to('m'), order_magn + 2))
```
9
5e-08 meter

What do you think?

**Comment by hgrecco** [comment]
This is a general problem with floating point representation. You can use [decimal](https://docs.python.org/3/library/decimal.html) if you like:
```python
>>> from decimal import Decimal
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> x = Decimal(50) * ureg.nm
>>> print(x)
50 nanometer
>>> print(x.to('m'))
5.0E-8 meter
```

If you just want to change the way is printed, just used [standard formatting code](https://docs.python.org/3/library/string.html#formatstrings): 
```python
>>> x = 50 * ureg.nm
>>> print('{:3g}'.format(x.to('m')))
```

**Comment by stevosn** [comment]
Ah, thanks for the hint with decimal..

I will try it out..

**Comment by stevosn** [comment]
Ah, thanks for the hint with decimal..

I will try it out..

Supp:
Yes that would definitely do the job! Thanks, again.
S

**Comment by evandavey** [comment]
This seems to break for some unit types

```
In [39]: x = Decimal(100) * ureg.nm

In [40]: x.to('m')
Out[40]: <Quantity(1.00E-7, 'meter')>

In [41]: x = Decimal(100) * ureg.nF

In [42]: x.to('F')
Out[42]: <Quantity(1.000000000000000300E-7, 'farad')>
```

**Comment by onealj** [comment]
In [1]: from decimal import Decimal

In [2]: Decimal(100) / Decimal(1e9)
Out[2]: Decimal('1E-7')

In [3]: Decimal(100) * Decimal(1e-9)
Out[3]: Decimal('1.000000000000000062281591458E-7')

In [4]: Decimal(100) / Decimal('1e9')
Out[4]: Decimal('1.00E-7')

In [5]: Decimal(100) * Decimal('1e-9')
Out[5]: Decimal('1.00E-7')

Versions:
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
IPython 2.4.1 -- An enhanced Interactive Python.
Ubuntu 16.04.3 LTS
Celeron N2840 x86_64

**Comment by JesterEE** [comment]
@onealj I don't understand the point of this post. Your outputs are all expected results. If you don't understand why, please refer to the decimal documentation or dig into the module.
