### ISSUE TITLE
Precision loss using prefixes

### ISSUE THREAD

**Issue by dmwelch** [hgrecco/pint#306]
When converting meters to nanometers:
```python
>>> import pint
>>> x = 1.0 * pint.UnitRegistry().meter
>>> x.ito('nm')
>>> x.magnitude == 10.0**9  # should be true
False
>>> x  # the repr() is going to lie to us...
<Quantity(1000000000.0, 'nanometer')>
>>> x.magnitude  # caught in the act
999999999.9999999
```
TTD saves the day again!  Huzzah!

**Comment by hgrecco** [comment]
As long as we work with floating point numbers inside Pint this will always be the case. The most common case is:
```python
>>> 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1
0.9999999999999999
```
If you want precision we would need to use decimal or fraction, which might make things much slower in certain circumstances.

**Comment by dmwelch** [comment]
Thanks, @hgrecco for time!  I hope I can explain myself adequately here.

We're converting between units and subunits which is handled exactly in Python which most users will expect, IMO.  If I was performing the addition operation in your example, I would expect Pint to behave just as Python (and correct the precision loss or anticipate it).  Pint's behavior introduces error where there shouldn't be any, i.e. a liter is always 1000 milliliters _by definition_.  For example:

```python
>>> x = 1.0 * 10 ** -9
>>> x  # Correct and expected for conversion between unit and subunits
1e-09
>>> x.as_integer_ratio()
(4835703278458517, 4835703278458516698824704L)
>>> m = ureg.meter()
>>> m.ito('nm')
>>> y = m.magnitude
>>> y  # If I cast to int(), I've lost a nanometer (not due to uncertainty!)
999999999.9999999
>>> y.as_integer_ratio()
(8388607999999999, 8388608)
```
The docs imply, for better or for worse, that the units are "tacked on" and don't affect the computations in any way so it's important that users are aware of this behavior.  Is this an issue in Numpy or Pint and where is it documented?  

Would it be helpful to add a unit test and mark as an expected failure in case this changes in the future?

**Comment by hgrecco** [comment]
Actually Pint is not doing it worst than Python. The actual calculation is transform meters to nanometers. That is dividing `1 meter` by the conversion factor from meters to nanometers (`1e-9`).

If you do that calculation in Python you get exactly the same result:
```python
>>> 1./1e-9
999999999.9999999
```

Pint could work around this by doing:
```python
>>> 1 * 1e+9
1000000000.0
```
but you will need to add some logic regarding which calculation is best (If you fix it naively for nanometer, it will be broken for gigameters).

**Comment by dmwelch** [comment]
Why wouldn't it work for gigameters?  Sorry, I may be missing something really obvious here!

```python
>>> 1 * 1e-9  # nanometer --> meter (or meter --> gigameter) 
1e-09
>>> 1 * 1e9  # meter --> nanometer (or gigameter --> meter)
1000000000.0
```

**Comment by hgrecco** [comment]
Because if you fix it for nanometers (that is you multiple by 1e+9) then for gigameter you will divide by 1e-9 and you have the same problem. Your example show this very clear. In one case you are multiplying by 1e-9 and in the other by 1e9. You are making a decision what operation to use. What I am saying is the the simple algorithm is just divide by the converting factor (1e-9) and this leads to the problem as I have shown before.

**Comment by dmwelch** [comment]
Why do we have to use the ```/``` operator at all?  The change in sign for the exponent is already sufficient.  Looking at the ```ScaleConverter``` class (https://github.com/hgrecco/pint/blob/master/pint/converters.py#28), why not store the exponent instead of the scalar integer like so:
```python
class ScaleBase10Converter(ScaleConverter):
    """A linear transformation for base 10 conversion
    """

    is_multiplicative = True

    def __init__(self, exponent):
        self.exponent = exponent
        self.scale = 10 ** self.exponent

    def from_reference(self, value, inplace=False):
        if inplace:
            value *= 10 ** (-1 * self.exponent)
        else:
            value = value * 10 ** (-1 * self.exponent)

        return value
```

**Comment by hgrecco** [comment]
I do not follow how this will apply in a simple manner to a more complex case.

Imagine that the user wants to convert: 
1. from `3 Newton` to `kilogram * nanometer / hour ** 2` 
2. from `3 kilogram * nanometer / hour ** 2`  to `Newton`

Can you describe the algorithm that you will follow in each case to avoid precision loss?

**Comment by hgrecco** [comment]
I am closing this by now. Feel free to open if needed.
