### ISSUE TITLE
Time conversion

### ISSUE THREAD

**Issue by FrEaKmAn** [hgrecco/pint#310]
Hi

I have multiple units:
- CFM
- m3/min
- m3/h

When I define a quantity, I want to use it in the calculation with total hours per year (8760). That means I need to convert m3/min and CFM to hours. Currently I do this by doing ifelse and defining right to_unit. In case of CFM it's ft^3/h, and for other units it's m^3/h.

Everything works, but I'm wondering if there is maybe an easier way to convert from minute to hour (or any other time unit: seconds, days, months, ..)? I'm looking for something like

```
Quantity(...).to_time('hours')
```

Is there anything in pint to support this?

**Comment by hgrecco** [comment]
Sorry, but I do not follow. You can convert between time units as any other unit:
```
>>> x = 35 * ureg.hours
>>> x.to('minutes')
<Quantity(2100.0, 'minute')>
```

but I guess this is not what you are looking for.

**Comment by FrEaKmAn** [comment]
Yes, but the whole unit is m^3/min, m^3/h or CFM. The idea is to easier convert between units if unit has a time dimension.

**Comment by hgrecco** [comment]
I understand now. In the past we discussed the idea of having such function but we did not have enough time to implement it.

**Comment by FrEaKmAn** [comment]
Ok, is there a way to get time unit from the main unit?

**Comment by hgrecco** [comment]
Maybe is a good time to discuss the API and some open questions we had then. 
1.- Do we force the unit in? For example, if the units is Newton, do we "open it" to transform seconds to hours?
2.- How shall the API look like? Maybe something like `q.using('hours')` 

Is this useful and general enough that is worth to be added? thoughts?

**Comment by FrEaKmAn** [comment]
1. Yes, it might look strange for Newton unit, but I don't see any problems for other units (m3/min <-> m3/h). If it has time unit, it can be converted.

2. Yes, using(...) makes sense to me. But somebody might use it incorrectly. For example: will q.using('ft3') convert from m3/min to ft3/min? No.

**Comment by saroele** [comment]
I'm interested in this feature.  I'm new to pint, but if I read this, I get the impression that in version 0.6, you cannot easily convert `liter/min` to `m³/second` , is that correct?

**Comment by hgrecco** [comment]
@saroele You can do that easily
```python
>>> import pint
ureg = pint.UnitRegistry()
>>> q = 3 * ureg.liter / ureg.minute
>>> q
<Quantity(3, 'liter / minute')>
>>> q.to('m^3/second')
<Quantity(5e-05, 'meter ** 3 / second')>
```

What you cannot do is replace with conversion one unit with another.

**Comment by hgrecco** [comment]
I am delaying this until we find a clear API

**Comment by JoyMonteiro** [comment]
Was thinking of using something similar, though it is not a critical requirement.
How about ``q.per('s')`` ?  ``per`` will make clear that you are only modifying the
denominator.

**Comment by bloer** [comment]
If I understand the issue, there is a partial solution for this with the `to_reduced_units` function:

    >>> import pint
    ureg = pint.UnitRegistry()
    >>> flow = 10*ureg['m**3/min']
    >>> year = 24*365.25*ureg['hour']
    >>> volume = flow*year
    >>> volume
    <Quantity(87660.0, 'hour * meter ** 3 / minute')>
    >>> volume.to_reduced_units()
    <Quantity(5259600.0, 'meter ** 3')>

If flow is in CFM, `volume.to_reduced_units()` will have units of `ft**3`.  But that function won't reduce compound units, so for example `slpm*minute` does not reduce.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
