### ISSUE TITLE
Conversion between inverted units

### ISSUE THREAD

**Issue by FrEaKmAn** [hgrecco/pint#311]
Hello

We work with air compressors and track their efficiency. The unit is kWh/m^3. This unit is different in USA and it's CFM/kW. Units are the same, just inverted.

I tried to do

    ureg = UnitRegistry()
    ureg.define('CFM = ft^3/min = cfm')

    unit = ureg.parse_units('CFM/kW')
    quantity = ureg.Quantity(20, unit)

    print quantity.to('kWh/m^3')

and this will fail. But if I invert quantity

    quantity = 1 / ureg.Quantity(20, unit)

then it works. Makes sense.

My question is. When you do unit conversion checking, would it also make sense to check if inverted units are compatible? Because kWh/m^3 and m^3/kWh units are totally compatible yet I'm not able to convert between them.

**Comment by hgrecco** [comment]
See #301 in which a similar issue has been raised. The answer is that if you can come up with a good solution which is not error prone, we will be happy to incorporate it. But implicitly trying an inverse conversion is not an option.

**Comment by FrEaKmAn** [comment]
Hm, OK. Based on #301, I could solve this with contexts. Lets continue discussion there.
