### ISSUE TITLE
Pressure abbreviated unit names are long_underscored_strings

### ISSUE THREAD

**Issue by jChapman** [hgrecco/pint#313]
When trying to print a psi value using `~` I noticed that I would get a really long name.
    >>> import pint
    >>> u = pint.UnitRegistry()
    >>> u.psi
    <Unit('psi')>
    >>> a = 1.11 * u.psi
    >>> format(a)
    '1.11 psi'
    >>> format(a, '~')
    '1.11 pound_force_per_square_inch'

Related issue: https://github.com/hgrecco/pint/issues/243

**Comment by jChapman** [comment]
Looks like travis is having a problem w/ conda

    0.00s$ conda update --yes conda
    /home/travis/build.sh: line 45: conda: command not found
    The command "conda update --yes conda" failed and exited with 127 during .
    Your build has been stopped.

**Comment by hgrecco** [comment]
Fixed conda and merged you patch. Thanks!
