### ISSUE TITLE
Get system of specified unit

### ISSUE THREAD

**Issue by lardissone** [hgrecco/pint#315]
Is possible to get the system an unit belongs?

I have something like this:

    weight = ureg('70kg')

I've seen in the code that already exists a method called `get_system` on `UnitRegistry` class, but when I call it,like `weight.get_system()` it returns: **AttributeError: Neither Quantity object nor its magnitude (70)has attribute 'get_system'**

**Comment by hgrecco** [comment]
`get_system` is a method of a UnitRegistry, not a Quantity (weight is a Quantity). 

Going back to your question, there is no such function yet but it might be good to add it.

**Comment by lardissone** [comment]
Ahh, makes sense.  
Yes, I think that `get_system` in the Quantity level would be very helpful!

**Comment by lardissone** [comment]
Genius!

**Comment by hgrecco** [comment]
The api is really simple

>>> q.units.systems

Where q is a quantity.
Or if you just want one unit

>>> ureg.meter.systems
