### ISSUE TITLE
Conversion of same unit

### ISSUE THREAD

**Issue by VlamV** [hgrecco/pint#316]
I have an issue with converting between same units with different magnitude

&gt;&gt;&gt;ur = UnitRegistry()    <br>
&gt;&gt;&gt;ur.parse_expression('1*cm').to(ur.parse_expression('10*cm'))   <br>
\<Quantity(1, 'centimeter')\>

I would expect for the answer to be 0.1 centimeters

**Comment by hgrecco** [comment]
When you convert Pint uses the unit (ignoring the magnitude). Originally we only allowed units here but we decided that providing a quantity was a common case and therefore useful to have.

**Comment by VlamV** [comment]
Any idea when the new feature will be added?
Is there another way to achieve the wanted behavior?
Thanks
