### ISSUE TITLE
`"{:.0Lx}".format(…)` should give only the order of magnitude, no mantissa

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#322]
`"{:.0Lx}".format(…)` gives an unexpected result:

```
In [28]: print("{:.0Lx}".format(30.0*ureg.m))
\SI[]{3e+01}{\meter}
```

As I asked for zero significant digits, correct would be to show only the order of magnitude and leave out the mantissa entirely, i.e.:

`\SI[]{e+01}{\meter}`

**Comment by hgrecco** [comment]
This is the expected behavior as it mimics Python formatting: 
```
>>> '{:.0}'.format(30.0)
'3e+01'
```

I think that you are looking for:
```
>>> print("{:.0fLx}".format(30.0*ureg.m))
\SI[]{30}{\meter}
```
(Notice the **f**)

**Comment by gerritholl** [comment]
Nope, I'm looking for something that produces

`\SI[]{e1}{\meter}`

**Comment by hgrecco** [comment]
What type of numeric format is that?

**Comment by gerritholl** [comment]
It prints only the order of magnitude, i.e.

10¹ m

without any prefix.

But I recognise your argument that the `.0` equivalent to `.1` behaviour mimics Python, which in turn mimics much older behaviour.  So consistency in this case means that getting only the order of magnitude without any prefix is not possible directly from `pint`, which I can accept.

**Comment by hgrecco** [comment]
Indeed is not possible directly with python formatting strings. You can do something like:
```
>>> import math
>>> q = 30 * ureg.meter
>>> '10^{{{0}}} {1.units}'.format(int(math.log10(q.magnitude)), q)
'10^{1} meter'
```

**Comment by jllanfranchi** [comment]
I'd add that you can call `to_root_units()` if the desired behavior is to get the order of magnitude *independent* of "prefixed" units. So, for example, 30 m yields the same result as 0.03 km by doing the following:
```python
>>> import math
>>> q = 0.03 * ureg.kilometer
>>> q_ = q.to_root_units()
>>> '10^{{{0}}} {1.units}'.format(int(math.log10(q_.magnitude)), q_)
'10^{1} meter'
```
