### ISSUE TITLE
Magnitude types and transformations

### ISSUE THREAD

**Issue by emilienkofman** [hgrecco/pint#323]
Hi,

I'm not completely sure if this is a bug or if this is the expected behavior. Please let me know if I don't use pint correctly:
```python
>>> from pint import UnitRegistry
>>> ur = UnitRegistry()
>>> Q_ = ur.Quantity
>>> from fractions import Fraction
>>> Q_(Fraction(2,3),ur.s)
<Quantity(2/3, 'second')>
>>> Q_(Fraction(2,3),ur.s).to(ur.ms)
<Quantity(666.666666667, 'millisecond')>
```
As I used the type Fraction, I expected to get a Fraction, namely `Fraction(2000,3)` in this example. If this is a bug, how could I try to fix it?

**Comment by hgrecco** [comment]
It would be very nice to fix it but I do not think is possible without hitting a severe performance hit. The reason of this "bug" is shown in the following snippet:
```python
>>> from fractions import Fraction
Fraction(3, 2)
>>> Fraction(3,2)*.1
0.15000000000000002
```

**Comment by emilienkofman** [comment]
Ok what do you mean with "severe performance hit"? Do you mean that specializing the conversion in the case of `Fraction` magnitude would cause a performance hit in the case of `Float` magnitude? Generally speaking is performance a big issue in pint? If I cannot fix it in pint, is there a trick that I can use to achieve this?

**Comment by hgrecco** [comment]
You can try to fix it in Pint but I think that the calculation will be efficient enough for every day use (I might be wrong here). Additionally, it will be annoying to implement. Pint calculates the conversion factor and then multiplies it by the magnitude. The conversion factor is calculated as float by multiplying floats (which are obtained from parsing the definitions). So yo will need to change the parser works to output fractions.

There is simpler, fast (both to run and implement), not so accurate alternative which might be good enough for you. In the UnitRegistry code locate the function that does the conversion and change the conversion factor to Fraction using the `Fraction.from_float` when the magnitude is a fraction. The relevant code starts here:

https://github.com/hgrecco/pint/blob/master/pint/unit.py#L1109

If it performs well, I will be happy to merge i.

**Comment by hgrecco** [comment]
Thanks a lot! Merged.
