### ISSUE TITLE
Parser Safety for Untrusted Input

### ISSUE THREAD

**Issue by zaccrites** [hgrecco/pint#325]
The tutorial in the documentation mentions that Pint uses `eval` under the hood and that parsing untrusted input is discouraged. Is this still the case? Comments in the threads for issues #267 and #226 seem to imply that there is a newer, safer parser coming. Is this available in 0.6, or will this have to wait until 0.7?

**Comment by hgrecco** [comment]
The new parser is available in the master and develop branch. I would say that the new parser is safe, but I would like to have more eyes on it before we declare it safe in doces.

**Comment by zaccrites** [comment]
Why do you hesitate to call it safe? Does it still invoke `eval` in its roots?

**Comment by hgrecco** [comment]
It does not use eval any more. I have looked it much more and tried to break it without success. I will be happy to call it safe now.
