### ISSUE TITLE
Non-deterministic results in conversions

### ISSUE THREAD

**Issue by nevsan** [hgrecco/pint#327]
When executing certain conversions, it's possible to get results that differ between subsequent Python sessions. The differences are a result of floating point math being non-associative. If unit conversion factors are multiplied in a different order, small floating point errors can change direction. An example of this phenomenon is shown below:
```python
In [1]: 200 * 1e-3 / 1e-9
Out[1]: 200000000.0

In [2]: 1 / 1e-9 * 200 * 1e-3
Out[2]: 199999999.99999997
```
Pint essentially stores units in a dictionary (the UnitContainer object), and since the keys in such a dictionary are unordered, the order in which they will be multiplied during a conversion is non-deterministic. The following short script will exhibit different results as they are run in subsequent Python sessions.
```python
# pint_bug.py
from pint import UnitRegistry
units = UnitRegistry()

u1 = units.carat
u2 = units.ng
print([k for k in (u1._units / u2._units)])
print((1 * u1).to(u2).magnitude)
```
Running the test script multiple times
```bash
$ python pint_bug.py
['carat', 'nanogram']
200000000.0
$ python pint_bug.py
['nanogram', 'carat']
199999999.99999997
```
While there may not be a good solution for eliminating this floating point math error, I think we should at least make the unit conversion order deterministic to invoke the least surprise (and pain) upon users.

**Comment by hgrecco** [comment]
Agreed. I will be merging this in a few hours. Thanks.

**Comment by hgrecco** [comment]
This is again a problema related to floating point numbers.
Take a look at the current code:
```python
>>> from pint import UnitRegistry
>>> from decimal import Decimal
>>> ureg = UnitRegistry(non_int_type=Decimal)
>>> print([k for k in (u1._units / u2._units)])
['carat', 'nanogram']
>>> print((1 * u1).to(u2).magnitude)
2.000E+8
```
