### ISSUE TITLE
fractional inches

### ISSUE THREAD

**Issue by filipgoc** [hgrecco/pint#329]
Hi, 
i'd love to add support for fractional inches (to metric) conversion. 
Having to collaborate in the US being raised on metric system gets nuts. 
Would anyone kindly point me in the right direction?

I think some sort of lookup table within the unit_definitions.txt would be the easiest (to hardcode 1/2 in as .5 in), but not sure how to do it.

Currently, pint does not support fractions as input.

Thus
.5 in to mm is fine
but 
1/2 in to mm does not compute

**Comment by hgrecco** [comment]
Pint does not support parsing fractions but you can use them using the Python fractions module.
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> from fractions import Fraction
>>> Fraction(1, 2) * ureg.inch
<Quantity(1/2, 'inch')>
>>> _.to('mm')
<Quantity(12.7, 'millimeter')>
```

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen if needed.
