### ISSUE TITLE
SIUnitx Formatter can't handle fractional powers

### ISSUE THREAD

**Issue by bryanwweber** [hgrecco/pint#330]
Hello,
I am using Pint 0.6, but I also set up a separate function to duplicate the siunitx formatter for myself, since it doesn't exist in 0.6. In working with it, I found that it is unable to print fractional powers (e.g. 0.5) because the power is expected to be an integer: https://github.com/hgrecco/pint/blob/5c409ea6695170b74f63ba39fbc64162c482730b/pint/formatting.py#L206

A simple fix is to test if the power is an integer:
    
    return r'\tothe{{{:d}}}'.format(int(power)) if power.is_integer() else r'\tothe{{{:.1f}}}'.format(power)

Of course, knowing the precision required for the float is the next problem.

**Comment by hgrecco** [comment]
Nice catch. Can you submit a PR?
