### ISSUE TITLE
Quantities using multi-dimensional ndarrays fail to render using IPython.lib.latextools.latex_to_png

### ISSUE THREAD

**Issue by natezb** [hgrecco/pint#335]
Let's start with the problem code. If you're using the Spyder IPython console (and I'd guess the IPython Qt console, though I haven't tested this), output of certain Quantities will fail:

```
In [1]: Q_(np.zeros((2, 3)), 'V')
Out[1]: Failed to render latex: 
$[[ 0.  0.  0.]
^
Expected end of text (at char 0), (line:1, col:1) 
```

The IPython console detects `Quantity._repr_latex_()` and uses its output, which contains newlines from `format(some_multidimensional_array)`. Spyder's IPython console uses `IPython.lib.latextools.latex_to_png()` to render the latex (unlike the IPython notebook, which instead uses `latex_to_html()`). This ultimately uses matplotlib's TeX parser, which chokes on multi-line input.

The parsing method that the IPython notebook uses does not choke on the newlines, but it does seem to strip them out.

The simplest course of action that makes sense to me is to remove any newlines in `Quantity._repr_latex_()` before returning the result.

**Comment by hgrecco** [comment]
Your solution seems ok, but maybe is better to output a latex matrix. 

https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays

If IPython or spyder rendering latex using a package like amsmath we can even use bmatrix

**Comment by hgrecco** [comment]
Maybe using this: http://www.malloc47.com/producing-latex-from-numpy-arrays/ 
but taking into account the number formatting

**Comment by hgrecco** [comment]
The issue stays open to have a pretty print

**Comment by natezb** [comment]
I agree that a  pretty-print for 2D matrices would be nice, but I don't think matplotlib's [Mathtext](http://matplotlib.org/users/mathtext.html) supports anything other than simple TeX, including e.g. the `amsmath` package.

**Comment by hgrecco** [comment]
Just checked that the array environ works on IPython:
```python
\left( \begin{array}{ccc}
a & b & c \\
d & e & f \\
g & h & i \end{array} \right)
```
I will code this for 0.7.1
