### ISSUE TITLE
Trouble with non-multiplicative units

### ISSUE THREAD

**Issue by rkingsbury** [hgrecco/pint#339]
I've been using pint for a long time as part of a solution chemistry library ([pyEQL](https://github.com/rkingsbury/pyEQL)). The recent upgrade to 0.7 has caused my project to stop working, owing to errors about non-multiplicative units

```
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 727, in __mul__
    return self._mul_div(other, operator.mul)
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 675, in _mul_div
    offset_units_self = self._get_non_multiplicative_units()
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 1312, in _get_non_multiplicative_units
    offset_units = [unit for unit in self._units.keys()
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 1313, in <listcomp>
    if not self._REGISTRY._units[unit].is_multiplicative]
KeyError: ''

```

I've read the relevant sections of the documentation and set `unit.autoconvert_offset_to_baseunit = True' , but I'm not able to figure out what is going on here. Is there any sort of "migration guide" or other resource I can use to figure out how to modify my code to work with these new changes?

Thanks for any help.

**Comment by hgrecco** [comment]
Sorry for the inconvenience. We will look at it right away. Can you show me what is the calculation you are doing?

**Comment by rkingsbury** [comment]
The calculation that triggers the error is:
```
temp_list.append(float(item) * ureg(use_units))
```
Where item = '0.042' and use_units == 'dimensionless'

It appears that I can resolve the error if I change the code to something like:
```
temp_list.append(ureg.Quantity(float(item),use_units))
```
The problem is that I use the multiplication construct (magnitude * ureg(unit)) to assign units in lots of places throughout the project. Maybe this is bad practice on my part, but if there's a way to work around this issue without changing all that code, I'd definitely prefer it.

In any event, looking at the changelog from 0.6 to 0.7, I can't find anything obvious that would affect the behavior above, but obviously I don't have a deep understanding of the pint code.

**Comment by rkingsbury** [comment]
OK, I'm able to trigger this error just by creating a dimensionless unit, which is what my code above is trying to do:
```
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> ureg('1 dimensionless')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pint/unit.py", line 1269, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x : self._eval_token(x, case_sensitive=case_sensitive,
  File "/usr/local/lib/python3.4/dist-packages/pint/pint_eval.py", line 83, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 727, in __mul__
    return self._mul_div(other, operator.mul)
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 675, in _mul_div
    offset_units_self = self._get_non_multiplicative_units()
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 1312, in _get_non_multiplicative_units
    offset_units = [unit for unit in self._units.keys()
  File "/usr/local/lib/python3.4/dist-packages/pint/quantity.py", line 1313, in <listcomp>
    if not self._REGISTRY._units[unit].is_multiplicative]
KeyError: ''
```

**Comment by hgrecco** [comment]
This works fine:
```python
>>> ureg('')
<Quantity(1, 'dimensionless')>
```

In any case I will fix this to have backwards compatibility

**Comment by hgrecco** [comment]
It is a problem with the new parse/evaluator. I wil push the fix tonight.

**Comment by hgrecco** [comment]
I have just pushed a fix for this, please install from github and let me know if it works for your. It would also be nice to know if you encounter any other problem. If everything is fine we will push the 0.7.2 version

Again, Sorry for the inconvenience.

**Comment by rkingsbury** [comment]
It works! I ran all the automated tests and typical workflows with my project and didn't encounter any other problems. Thanks so much for the speedy fix.

**Comment by rkingsbury** [comment]
Is there anything else holding up the push of v0.7.2?

**Comment by hgrecco** [comment]
Done!
