### ISSUE TITLE
problems with: user defined unit-systems

### ISSUE THREAD

**Issue by laufert** [hgrecco/pint#342]
Hi guys,

currently I'm working with pint 0.7.2 and try out the new Unit System functionality. I want to perform a couple of unit-system transformations and run into some issues. From the [latest pint doc](http://pint.readthedocs.org/en/latest/systems.html) I saw the following example:

``` python
import pint
print('pint version: {0}'.format(pint.__version__))

ureg = pint.UnitRegistry(system='mks')
q = 3600. * ureg.meter / ureg.hour
print('default_system: {0}'.format(ureg.default_system))
print('q: {0}'.format(q.to_base_units()))

ureg.default_system = 'cgs'
print('default_system: {0}'.format(ureg.default_system))
print('q: {0}'.format(q.to_base_units()))
```

which runs fine. Now I wanted to define some user specific default systems. One way to work with user defined default systems is to save the definition in a extra file and load them with `ureg.load_definitions('/your/path/to/my_def.txt')`. 

But there seem to be a another way to generate systems directly in the code, with out saving the definition to a separate file. In the testsuit `test_systems.py` I found the following way to define a new system:

``` python
lines = ['@system mmkgms using international',
                  'millimeter',
                  'kilogram',
                  'millisecond',
                  ]

s = ureg.System.from_lines(lines, lambda x: x)

ureg.default_system = 'mmkgms'
print('default_system: {0}'.format(ureg.default_system))
print('q: {0}'.format(q.to_base_units()))

```

But this version dose not work as I expect it to work. I expect a `1.0 millimeter / millisecond` and got a `1.0 meter / second` .

Can someone help me to solve this problem? Or dose I have to keep the extra file solution?

Thanks
Tilo

**Comment by hgrecco** [comment]
Just replace this:

```python
s = ureg.System.from_lines(lines, lambda x: x)
```
by
```python
s = ureg.System.from_lines(lines, ureg.get_base_units)
```

As a side note, indeed everything in Pint can be done via a definition text file or programmatically
But please note that the `from_lines` corresponds to parsing the definitions file and therefore it is not really the API to use programatically. We are still working to define a convenient, easy to use API. Suggestions accepted!

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
