### ISSUE TITLE
Wrapping numpy.linalg.inv causes "RuntimeWarning: divide by zero encountered in reciprocal"

### ISSUE THREAD

**Issue by iamthad** [hgrecco/pint#343]
I have gotten a functional matrix inverse for a matrix with consistent units.

```
  @units.wraps('=A**-1', ('=A'))
  def inv(a, *args, **kwargs):
      return numpy.linalg.inv(a, *args, **kwargs)
```

The return value appears to be correct. However, when I call it on a matrix with zeros, I get the following warning:

```
C:\Users\{me}\AppData\Local\Continuum\Anaconda2\lib\site-packages\pint\quantity.py:855: RuntimeWarning: divide by zero encountered in reciprocal
  magnitude = new_self._magnitude ** _to_magnitude(other, self.force_ndarray)
```

Is this a bug? Or how should I avoid this?

Complete test code attached
[invtest.zip](https://github.com/hgrecco/pint/files/163644/invtest.zip)

**Comment by hgrecco** [comment]
Again, I am glad to see #195 in use!

Regarding your questions, I can confirm what you are seeing. In general, we should behave as close as possible to the unwrapped function. So this is something that we need to fix. Additionally using

```python
J = numpy.diag([1224, 2923, 2345])
```

should work in the wrapped function as well as we are not imposing a particular unit.

**Comment by hgrecco** [comment]
This is fixed.
