### ISSUE TITLE
Parsing dimensionless quantities

### ISSUE THREAD

**Issue by JesterEE** [hgrecco/pint#346]
Sometimes I use pint to get simple user input (e.g. strings) into appropriately parsed magnitudes and units.  It's actually quite good at this task even though it is not using the package to it's fullest and is certainly easier than rolling a custom parser when it already has such a good implementation.  My issue is that when parsing an input that may or may not have a unit attached, it causes downstream code protection (e.g. try...except clauses) due to the fact that a string without a unit is parsed as a float type and not an instance of the Quantity class.  Here's sample code to illustrate:

```python
import pint
print(pint.__version__) # 0.7.2
ureg = pint.UnitRegistry()

qty_str = '123.456 dimensionless'
qty = ureg.parse_expression(qty_str)
print(type(qty))  # <class 'pint.unit.Quantity'>
print(qty.magnitude) # 123.456
print(type(qty.magnitude)) # <type 'float'>

qty_str = '123.456'
qty = ureg.parse_expression(qty_str)
print(type(qty)) # <type 'float'>
print(qty.magnitude) # AttributeError: 'float' object has no attribute 'magnitude'
print(type(qty.magnitude)) # ...
```

Since when using `parse_expression` on a string we are explicitly asking pint to take our input and match it a Quantity object, the default result of a float for a unitless quantity is not what I would expect.  While this behavior may be convenient for interactive coding, it doesn't lead to programatically similar results even though it executes without error/warning.

What does everyone else think about this?  Is it a design flaw or a design feature?  I always get the 2 confused :wink:.

**Comment by rec** [comment]
Just a note that I ran into this some time ago and just worked around it in the obvious way, but I'm :+1: that `parse_expression` should always return something of the same type.

**Comment by hgrecco** [comment]
The rationale to do this what the following:
1. `parse_expression` should  output the most convenient type (which can be int, float, Quantity or a Measurement (in the near future!). It is like a call to `eval` with knowledge of units in the registry (and a few other goodies)
2. If you want always a Quantity object, use the Quantity constructor:
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.Quantity('123.456 m')
<Quantity(123.456, 'meter')>
>>> ureg.Quantity('123.456 dimensionless')
<Quantity(123.456, 'dimensionless')>
>>> ureg.Quantity('123.456')
<Quantity(123.456, 'dimensionless')>
``` 

I am open for this discussion but what do you think?  In any case, I think the docs should be improved about this.

**Comment by ryanpdwyer** [comment]
I thinking explaining this in the docs would be nice; I've used the library for a few years and didn't realize this difference between the constructor and `parse_expression`.

**Comment by JesterEE** [comment]
@hgrecco Honestly, I didn't even try giving `Quantity` a string!  I just didn't know I could do it!  I think that solution is just fine, though I do agree the documentation and the tutorial guide could use a simple addition of this use case to highlight the functionality.

Also, as of Pint 0.7, it looks like pint_eval.py does does safe evaluations for `parse_expression` instead of `eval` (which is great).  There is a warning about eval safety on the tutorial that can now probably be removed.

I am satisfied with this solution and think we can close this issue unless you would rather leave it open as a reminder to clean up the documentation for this functionality.  I leave that up to you.

Thanks!

**Comment by rec** [comment]
Hah!  Silly me.  I also agree - the `Quantity` constructor is more than sufficient, just a hint in the dox would do it!

**Comment by hgrecco** [comment]
@JesterEE The warning is removed. We did keep a note saying to prevent users of older versions of pint.

I do think we need to add something about this to the docs. Any volunteer?

**Comment by JesterEE** [comment]
Opened pull request #352 to add some documentation about this feature.

**Comment by hgrecco** [comment]
Merged. Thanks a lot
