### ISSUE TITLE
Pickling with Pint

### ISSUE THREAD

**Issue by alexfeld** [hgrecco/pint#349]
When pickling custom objects that use the ```pint.unit.Unit``` class, the pickling process fails. It seems that only the ```Quantity```  and ```Measurement``` classes can be pickled.  The error raised is

```
AttributeError: 'Unit' object has no attribute 'Unit'
```

**Comment by hgrecco** [comment]
We have only recently stabilized  `Unit` for the public API and that is why pickle support is not there yet. We should do it. Having said that, I have never required such thing as most of the time I am using `Quantity` objects.

By the way ... have you seen my new library [Serialize](https://github.com/hgrecco/serialize) It is a wrapper around 8 different formats that makes saving and loading easy. Even for custom classes.

**Comment by alexfeld** [comment]
Ah, that makes sense. I agree that it's probably not functionality that is commonly used. I have been using pint to store my units but not actually storing my data in ```Quantity``` objects due to some of the operations that I need to perform. 

I have seen Serialize but decided to use the pickle modules shipped with python. cPickle is working fine for me now but if it turns into a problem I'll take another look at Serialize

**Comment by FireByTrial** [comment]
I am running into this issue on a project I am working on, do you have any updates on this issue and it's status?

**Comment by hgrecco** [comment]
I have pushed a fix for this but I was not able to test it enough
