### ISSUE TITLE
Array comparisons return a single boolean if arrays are 0

### ISSUE THREAD

**Issue by avirshup** [hgrecco/pint#351]
When I compare two numpy array quantities that are both all zeros, I get a single boolean value, but would expect to get an _array_ of booleans.

 **Steps to reproduce**

``` python
x = np.zeros(4) * ureg.meter
y = np.zeros(4) * ureg.meter
return x==y
```

returns `True`

**Expected behavior**<br>
As described in #75, the return value should be `array([ True,  True,  True,  True], dtype=bool)`
We get the expected behavior if the arrays are non-zero, e.g.,

``` python
x = np.ones(4) * ureg.meter
y = np.ones(4) * ureg.meter
x==y
```

This is with Pint 0.7.2 installed from PyPI, Python 2.7.6 [GCC 4.8.2] installed with apt-get on Ubuntu 14.04. I've also observed this with pint 0.6.

**Comment by hgrecco** [comment]
To summarize:

```python
>>> pint.__version__
'0.7.2'
>>> x = np.ones(4) * ureg.meter
>>> y = np.ones(4) * ureg.meter
>>> x==y
array([ True,  True,  True,  True], dtype=bool)
```
but 
```python
>>> (0 * x) == (0 * y)
True
```
This is indeed confusing and needs to be fixed.
