### ISSUE TITLE
Abbreviating kilo/meg/giga/byte or kibi/mebi/gibi/byte does not work

### ISSUE THREAD

**Issue by NahsiN** [hgrecco/pint#354]
Hi, great package! Just a teeny tiny issue. Using Python3 with pint v0.7.2 installed using pip3 on Ubuntu 14.04

`print('{0:P}'.format(1*ureg('MiB')))` outputs
> 1 mebibyte

`print('{0:~P}'.format(1*ureg('MiB')))` outputs
> 1

Most other abbreviations work, just not these ones.
Cheers

**Comment by hgrecco** [comment]
I actually think that this is the same problem as #356

**Comment by hgrecco** [comment]
Thanks a lot for reporting! It is now solved
