### ISSUE TITLE
Simplifying Units or Removing Redundant Units

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [hgrecco/pint#355]
Is there a function that will simplify or remove the redundant units.
Example
ureg('in')*ureg('s')/ureg('cm')
    displays the units "in * s / cm"
function_that_simplifies_units(ureg('in')*ureg('s')/ureg('cm'))
    displays the units "s"

**Comment by ryanpdwyer** [comment]
The `to_base_units()` method will do what you want.

```
> q = ureg('in') * ureg('s') / ureg('cm')
> q.to_base_units()
<Quantity(2.54, 'second')>
````

**Comment by BebeSparkelSparkel** [comment]
Thanks for your help

**Comment by hgrecco** [comment]
And since 0.7 you can choose which are the base units. See http://pint.readthedocs.org/en/0.7.2/systems.html
