### ISSUE TITLE
Short abbreviation of 'count' unit is '', but abbreviation of 'count/year' is 'count/year'

### ISSUE THREAD

**Issue by bqpd** [hgrecco/pint#356]
```python
In [1]: import pint
In [2]: ureg = pint.UnitRegistry()
In [3]: "{:~}".format(1*ureg.ft)
Out[3]: '1 ft'
In [4]: "{:~}".format(1*ureg.count)
Out[4]: '1 '
In [6]: "{:~}".format(1*ureg.count/ureg.year)
Out[6]: '1.0 count / year'
```

**Comment by t-brink** [comment]
I also encountered this. It seems to be related to units that are dimensionless: I saw it with `"{:~}".format(ureg.cm/ureg.inch)` which simply gives an empty string. The long version works.

Digging around a bit: `pint.unit._Unit.__format()` does return an empty string if `self.dimensionless` is `True` (currently line 103). Units like "cm/in" or "count" currently have that set to `True`. There are two possibilities: 1) you want 1cm/in to be dimensionless, in which case the formatting code needs to be changed; 2) 1cm/in should not be dimensionless.

Please let me know if you need more info and thanks for writing this very useful package!

**Comment by t-brink** [comment]
Hmm, the formatter seems to be generally a bit broken with the short formatting version: `"{:~}".format(Q_(1, ureg.dimensionless))` returns "1 " with a superfluous space at the end.

**Comment by hgrecco** [comment]
Thanks a lot for reporting! The extra space is still there but the main issue is solved.
