### ISSUE TITLE
Drop Support for Python 2.6, 3.0, 3.1 and 3.2?

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#358]
More and more scientific projects are dropping Python 2.6, 3.0, 3.1 and 3.2 support (Some are even dropping Python 3.3 support)

What are your thoughts about this?

**Comment by hgrecco** [comment]
Some information:
http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
https://mail.scipy.org/pipermail/numpy-discussion/2015-December/074283.html
https://github.com/pydata/pandas-datareader/issues/160

**Comment by MatthieuDartiailh** [comment]
I have no problem at all dropping those.

**Comment by noahl** [comment]
Dropping support for those versions is fine with me.

**Comment by yrevaz** [comment]
Dropping support for those versions is fine with me too.

**Comment by cmft** [comment]
I'm agree.

**Comment by hgrecco** [comment]
Another reason to drop 2.6 support: inspect.getcallargs is available in Python > 2.7 and will make using args and kwargs in wraps and check much easier.

**Comment by hgrecco** [comment]
Pint 0.8 is out. We will now start refactoring code to remove the 2.6, 3.0, 3.1 and 3.2 compat layer.
