### ISSUE TITLE
pint 0.6: loading default_en_0.6.txt in ipython notebook produces many errors

### ISSUE THREAD

**Issue by whoburg** [hgrecco/pint#361]
I'm trying to maintain backwards compatibility with pint 0.6 and pint 0.7.2 in my project. I am only able to reproduce the following error in an ipython notebook, not in regular python or ipython.

Using pint 0.6,

```python
from pint import UnitRegistry
UnitRegistry("default_en_0.6.txt")
```
produces
```
ERROR:pint.util:In line 362, cannot add '@system mks' need more than 1 value to unpack
ERROR:pint.util:In line 363, cannot add 'meter' need more than 1 value to unpack
ERROR:pint.util:In line 364, cannot add 'kilogram' need more than 1 value to unpack
ERROR:pint.util:In line 365, cannot add 'second' need more than 1 value to unpack
ERROR:pint.util:In line 366, cannot add '@end' need more than 1 value to unpack
ERROR:pint.util:In line 368, cannot add '@system cgs' need more than 1 value to unpack
ERROR:pint.util:In line 369, cannot add 'centimeter' need more than 1 value to unpack
ERROR:pint.util:In line 370, cannot add 'gram' need more than 1 value to unpack
ERROR:pint.util:In line 371, cannot add 'second' need more than 1 value to unpack
ERROR:pint.util:In line 372, cannot add '@end' need more than 1 value to unpack
ERROR:pint.util:In line 374, cannot add '@system imperial' need more than 1 value to unpack
ERROR:pint.util:In line 375, cannot add 'yard' need more than 1 value to unpack
ERROR:pint.util:In line 376, cannot add 'pound' need more than 1 value to unpack
ERROR:pint.util:In line 377, cannot add '@end' need more than 1 value to unpack
```
Ultimately, I'd like pint 0.6 to be able to read in `default_en.txt`, so that I can use that as my unit definitions and still be compatible with users on pint 0.6 or pint 0.7.2. At the very least, it seems like pint 0.6 should be able to read in `default_en_0.6.txt`?

**Comment by hgrecco** [comment]
Thanks for pointing this out. Indeed, definitions from an older version will work in a newer version (but not necessarily the other way around because of new features being added to Pint). Therefore if you have an extra definition file for 0.6, it should also work for 0.7.

As you mentioned, `default_en_0.6.txt` should be readable by 0.6. But it seems that there was an error during the merge that went unnoticed. The `@system` definitions are new to 0.7. Can you try deleting them and checking that it work?

**Comment by whoburg** [comment]
yes, removing the system commands eliminates those errors; opened #362 with those deletions.
