### ISSUE TITLE
nautical_miles, nanomiles, and inline comments

### ISSUE THREAD

**Issue by whoburg** [hgrecco/pint#366]
Inline comment in `default_en.txt` appears to break nautical_miles formatting and "nmi" lookup:

```python
In [1]: from pint import UnitRegistry

In [2]: ureg = UnitRegistry()

In [3]: "{:~}".format(ureg("nautical_mile"))
Out[3]: '1 nmi # exact'

In [4]: ureg("nmi")
Out[4]: <Quantity(1, 'nanomile')>
```

**Comment by hgrecco** [comment]
Maybe we can just support it by patching the SourceIterator https://github.com/hgrecco/pint/blob/b2287c5e0f345bcc691d158324b2abeddbb51962/pint/util.py#L694

**Comment by whoburg** [comment]
I just reinstalled pint with `pip install pint==0.7.2`, and this issue still exists. Should it really be closed?
