### ISSUE TITLE
mass conversion

### ISSUE THREAD

**Issue by yrevaz** [hgrecco/pint#369]
I want to express the newtonian constant of gravitation in particular units. I can to that with the following script:

`import pint

ureg = pint.UnitRegistry()
ureg.load_definitions('default_en.txt') 

G = 1* ureg.newtonian_constant_of_gravitation

ureg.default_system = 'mysys'
print G.to_base_units()
`

where the file _default_en.txt_ contains:

`
my_distance = 3.085678e21  * centimeter
my_mass     = 1.989e43     * gram 
my_velocity = 1e5	   * centimeter/second
my_time     = my_distance/my_velocity

@system mysys
    my_distance
    my_mass
    my_time
@end
`
In this case, I get the correct answer:

> 43018.9662045 my_distance ** 3 / my_mass / my_time ** 2

I would like now to the same programmatically. For that, I did:

`
import pint
ureg = pint.UnitRegistry()
ureg.define("my_distance = 3.085678e21 * centimeter")
ureg.define("my_mass = 1.989e43 * gram") 
ureg.define("my_velocity = 1e5 * centimeter/second") 
ureg.define("my_time   = my_distance/my_velocity") 

lines = ["@system mysys","my_distance","my_mass","my_time"]
ureg.System.from_lines(lines, ureg.get_base_units)

G = 1* ureg.newtonian_constant_of_gravitation
ureg.default_system = 'mysys'
print G.to_base_units()

`

But the, I get:

> 2.16284395196e-39 my_distance ** 3 / gram / my_time ** 2

Which is nearly correct except that the unit  _gram_
 has not been transformed to _my_mass_.

**Comment by hgrecco** [comment]
The programatic API for defining systems is still under discussion. We are still working to define a convenient, easy to use API. Suggestions accepted!

Right now, just change this
```python
ureg.System.from_lines(lines, ureg.get_base_units)
```
to:
```python
ureg.System.from_lines(lines, ureg.get_root_units)
```

Ps.- It seems that you are using Python 2. Can you comment on #358 ?

**Comment by yrevaz** [comment]
On 04/25/2016 03:16 PM, Hernan Grecco wrote:
>
> The programatic API for defining systems is still under discussion. We 
> are still working to define a convenient, easy to use API. Suggestions 
> accepted!
>
> Right now, just change this
>
> ureg.System.from_lines(lines, ureg.get_base_units)
>
> to:
>
> ureg.System.from_lines(lines, ureg.get_root_units)
thanks a lot !
>
> Ps.- It seems that you are using Python 2. Can you comment on #358 
> <https://github.com/hgrecco/pint/issues/358> ?
>
done.

yves
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/hgrecco/pint/issues/369#issuecomment-214316214>
>


-- 
                                                
---------------------------------------------------------------------
   Dr. Yves Revaz
   Laboratory of Astrophysics (LASTRO)
   Ecole Polytechnique Fédérale de Lausanne (EPFL)
   Observatoire de Sauverny     Tel : +41 22 379 24 28
   51. Ch. des Maillettes       Fax : +41 22 379 22 05
   1290 Sauverny             e-mail : Yves.Revaz@epfl.ch
   SWITZERLAND                  Web : http://people.epfl.ch/yves.revaz
---------------------------------------------------------------------
