### ISSUE TITLE
Formatting with short units ignores unit prefix

### ISSUE THREAD

**Issue by t-8ch** [hgrecco/pint#370]
Formatting with `~` (`~P`, ...) leads to wrong results if unit prefixes are used.

Steps to reproduce:

```python
import pint
ureg = pint.UnitRegistry()

print('''
 :  {0}
~:  {0:~}
P:  {0:P}
~P: {0:~P}
'''.format(1 * ureg.second / ureg.millisecond))
```

Actual output:

```
 :  1.0 second / millisecond
~:  1.0 
P:  1.0 second/millisecond
~P: 1.0 
```

Expected output:

```
 :  1.0 second / millisecond
~:  1000.0
P:  1.0 second/millisecond
~P: 1000.0 
```

Normalizing the value explicitly using `.to('dimensionless')` works fine.

**Comment by t-brink** [comment]
I think that is the same problem as #356, see my analysis there. Although I would say the expected output would be

```
 :  1.0 second / millisecond
~:  1.0 s / ms
P:  1.0 second/millisecond
~P: 1.0 s/ms
```

At least that's what happened with version 0.6.

**Comment by hgrecco** [comment]
Thanks a lot for reporting! Indeed @t-brink is right, pint should not simplify unless explicitly required. 
This is now solved.
