### ISSUE TITLE
Unit does not support `__ne__`

### ISSUE THREAD

**Issue by skschneider** [hgrecco/pint#372]
`Unit` defines `__eq__`: https://github.com/hgrecco/pint/blob/004610b3ff78155d4660f1ac94002bd5509717ff/pint/unit.py#L197

`Unit` also defines `__lt__`, `__le__`, `__ge__`, `__gt__`: https://github.com/hgrecco/pint/blob/004610b3ff78155d4660f1ac94002bd5509717ff/pint/unit.py#L222

Unit does not appear to define `__ne__`.

```
>>> import pint
>>> r = pint.UnitRegistry()
>>> 
>>> # Compare same instance.
... b = r.Unit('byte')
>>> b == b
True
>>> b != b
False
>>> 
>>> # Compare different instances.
... r.Unit('byte') == r.Unit('byte')
True
>>> r.Unit('byte') != r.Unit('byte')
True
```

I didn't check other classes.

**Comment by hgrecco** [comment]
Would you like to submit a patch?
