### ISSUE TITLE
Support sqrt()

### ISSUE THREAD

**Issue by chrisspen** [hgrecco/pint#373]
Python's standard `sqrt()` doesn't seem to be supported.

    >>> import pint, math
    >>> ureg = pint.UnitRegistry()
    >>> math.sqrt(1*ureg.meter**2)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/myproject/.env/local/lib/python2.7/site-packages/pint/quantity.py", line 374, in __float__
        raise DimensionalityError(self._units, 'dimensionless')
    pint.errors.DimensionalityError: Cannot convert from 'meter ** 2' to 'dimensionless'

Since sqrt(A^2) == A, I would expected pint to automatically convert sqrt(meter**2) to meter instead of throwing an exception.

**Comment by hgrecco** [comment]
See #276 for more info

**Comment by hgrecco** [comment]
Feel free to reopen if needed

**Comment by chrisspen** [comment]
I can live with **.5. I didn't realize the workaround was that simple.
Thanks.
