### ISSUE TITLE
Request for more pint-specific exceptions during pint_eval

### ISSUE THREAD

**Issue by moltman** [hgrecco/pint#374]
Recently ran into an error which raised a general Exception and bubbled up our application. Is it possible to create for Pint-specific exceptions for this so we don't have to do a blanket catch Exception at such a low level.

We already wrap certain Pint calls with try-except on TokenError, UndefinedUnitError, etc which helps us very specifically know when we have unit errors, but we're adverse to try: except Exception.

File ".../lib/python2.7/site-packages/pint/unit.py", line 1271, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x : self._eval_token(x, case_sensitive=case_sensitive,
  File ".../lib/python2.7/site-packages/pint/pint_eval.py", line 88, in evaluate
    raise Exception('missing unary operator "%s"' % op_text)
Exception: missing unary operator "/"

**Comment by hgrecco** [comment]
That is indeed a nice adition. Maybe you can look at [pint eval](https://github.com/hgrecco/pint/blob/master/pint/pint_eval.py) to propose some specific errors.

**Comment by moltman** [comment]
Will evaluate and send along some thoughts, happy to contribute if you agree with the proposal

**Comment by hgrecco** [comment]
Done
