### ISSUE TITLE
Registry Reorganization

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#375]
I have just pushed to develop a reorganization of the UnitRegistry
1.- It has moved to its own file
2.- It has been splitted into different registries, each providing different capabilities (base, non-multiplicative, systems, contexts). UnitRegistry (which is exported) provides all of them
3.- `load_definitions` is cleaner, as it provides an API to register new `@` directives and its parsers

It is a little bit slower (probably because there are more function calls). However I think it is worth it because:
1.- The code is cleaner.
2.- The code is easier to understand, fix and improve due to the separation of concerns.
3.- In principle, somebody could extend the registry easily.
4.- In principle, somebody could use a simple registry if it does not require all the functionality. 

Let me know what you think.

There are two more things I would like to do:
1.- Improving Error reporting See #374 
2.- See if there is room for performance improvement
3.- Remove the need to call _after_init using metaclasses.

**Comment by MatthieuDartiailh** [comment]
3 - Should be fairly straightforward by overwriting the \_\_call\_\_ of the metaclass.

**Comment by hgrecco** [comment]
This was done and merged
