### ISSUE TITLE
Include mole (as in avogadro's constant) as possible nondimensional unit

### ISSUE THREAD

**Issue by tomchor** [hgrecco/pint#380]
This suggestion of improvement might not be extremely useful, but I was somewhat surprised when I tried to convert `1e10` to moles (divide by avogadro's constant) and couldn't do it (I was actually trying to convert from 10^10 molecules per square centimeter to nanomoles per square meter).

I suppose it could work like

``` python
In [6]: Q_ = ureg.Quantity
In [7]: Q_(10.**10, '1')
Out[7]: <Quantity(10000000000.0, 'dimensionless')>
In [8]: Q_(10.**10, '1').to('mole')
```

This should work, but it throws me this error

```
DimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'mole' ([substance])
```

which I think is wrong, because 'mole' is not substance: it is also dimensionless. I understand that mole is assigned as substance as a simplification (because generally you want moles_of_something_which_has_molar_mass), but still I think this could be done without much effort.

Similarly, by extension, maybe in future the following could also be included:

```
In [8]: Q_(10.**10, '1').to('dozen')
```

and other similar nondimensional units.

Cheers

**Comment by swiftfish** [comment]
Avogadro Constant is already defined in constants_en.txt:
avogadro_number = 6.02214129e23 mol^-1 = N_A
``` python
In [14]: an = Q_('N_A')
In [15]: q = Q_(10.**10)
In [16]: (q / an).to('mole')
Out[16]: <Quantity(1.66053892103219e-14, 'mole')>
```
You could also define a [context](http://pint.readthedocs.io/en/0.7.2/contexts.html):
``` python
In [17]: c = pint.Context(name='avogadro', aliases=('n_a',))
In [18]: c.add_transformation('[]','[substance]', lambda ureg, x: x / ureg.avogadro_number)
In [19]: ureg.add_context(c)
In [20]: with ureg.context('n_a'):
   ....:    moles = q.to('mole')
In [21]: moles
Out[21]: <Quantity(1.66053892103219e-14, 'mole')>
```
[Definitions](http://pint.readthedocs.io/en/0.7.2/defining.html) can be added. Dozen can be defined as follows:
``` python
In [22]: ureg.define('dozen = 12 * count = dz')
In [23]: baker_dozen = Q_(13, 'count')
In [24]: baker_dozen.to('dz')
Out[24]: <Quantity(1.0833333333333333, 'dozen')>
```

**Comment by tomchor** [comment]
Thanks. I had searched for the Avogadro constant and didn't find it. Seeing now that it is defined as `"N_A"` makes me think that it might be better to include a more-intuitive alias such as simply `"avogadro"`. Opinions?

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
