### ISSUE TITLE
Unexpected Behavior when defining offset units

### ISSUE THREAD

**Issue by cintronej** [hgrecco/pint#381]
Hi, 

I'm trying to define a new unit with as an offset pressure, specifically to make a gauge pressure which is offset by 1 atm. 

When I add the following line into the default_en.txt file:
`barg = 1 * bar; offset: 101325 = bar_gauge`

I get the following output:

``` python
Q_(0, 'barg').to('bar')`
>>> 0.00101325 bar
```

However, when I amend the line to this, do I get the correct conversion. 
`barg = 100000000 * bar; offset: 101325000 = bar_gauge`

``` python
Q_(0, 'barg').to('bar')
>>> 1.01325 bar
```

In fact, it doesn't appear that the bar unit above has any effect as I can have the line read:
`barg = 100000000 * pascal; offset: 101325000 = bar_gauge`
and still convert properly.

Thanks

Edit:
On further inspection, it appears that the unit just before the ';offset' does have an effect on the delta term. I.e. this definition:
`barg = 100000000 * pascal; offset: 101325000 = bar_gauge`

produces this behavior: 

``` python
dp = Q_(10, 'barg') - Q_(5, 'barg')
dp.m_as('bar')
>>> 5000.0
```

I can fix this by making the definition:
`barg = 100000000 * mpascal; offset: 101325000 = bar_gauge`

I get the correct result:
produces this behavior: 

``` python
dp = Q_(10, 'barg') - Q_(5, 'barg')
dp.m_as('bar')
>>> 5.0
```

This seems to make a little more sense to me now conversion wise. However, arriving at using mpascals is not so straightforward.

**Comment by rkuczens** [comment]
The mpascal is equivalent to 1.0 g / m / s, which are the base unit for mass, length, and time. This may be highlighting a bug in the offset calculation, which is worked around when the multiplicative unit value is 1.

**Comment by srgkoshelev** [comment]
Bumping an old thread.
@rkuczens is right, the unit of the offset and, possibly, the delta part have to be written in basic units.
Thus
`psig = pound_force_per_square_inch; offset: 14.7 = pound_force_per_square_inch_gauge`
gives incorrect
```python
print (Q_(14.7,ureg('psig')).to(ureg.psi))
>>>4.264109489268151e-06 pound_force_per_square_inch
```

```python
print (Q_(0,ureg('psig')).to(ureg.psi))
>>>2.1320547446340754e-06 pound_force_per_square_inch
```

And
`psig = 6.895*10**6 * g/(m*s**2); offset: 14.7*6.895*10**6 = pound_force_per_square_inch_gauge`
gives correct
```python
print (Q_(14.7,ureg('psig')).to(ureg.psi))
>>>29.4010349285039 pound_force_per_square_inch
```
```python
print (Q_(0,ureg('psig')).to(ureg.psi))
>>> 14.700517464251948 pound_force_per_square_inch
```

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
