### ISSUE TITLE
How to handle ppm and ppmv

### ISSUE THREAD

**Issue by tomchor** [hgrecco/pint#384]
I am trying to figure out a way to handle ppm (g/g) and ppmv (mole/mole) in pint but can't. Since I can't find `ppm` inside `constants_en.txt` and `default_en.txt` I'm guessing it's because there is no native support for that. Is there a suggested way to deal with that?

What I've tried:

```
In [3]: ureg.define('ppm = 1e-6*g/g')

In [4]: a=1*ureg['ppm']

In [5]: a
Out[5]: <Quantity(1, 'ppm')>

In [7]: a.to('g/g')
Out[7]: <Quantity(1.0, 'dimensionless')>
```

I expected the last output to be `<Quantity(1.0e-6, 'dimensionless')>`. I'm trying to figure out a way to define ppm such that

```
a * gram = 1e-6 grams
```

and similarly with ppmv.

Cheers

**Comment by tomchor** [comment]
Update: kind of made it work by defining as

    ureg.define('ppm = mg/kg')

but I'm not sure if that's correct

**Comment by noahl** [comment]
I would take the attitude that the units in 'g/g' (and 'mole/mole') are
abbreviations. Try defining two new dimensions: 'g mixture' and 'g solute'.
Then define ppm as 'g solute / g mixture'. Multiplying a ppm value by 'g
mixture' should produce a correct value with units 'g solute', and
similarly with ppmv.

I hope that helps.

**Comment by hgrecco** [comment]
Exactly as @noahl said. Closing now, feel free too open another if needed.
