### ISSUE TITLE
Format does not support abbreviated printing of units

### ISSUE THREAD

**Issue by david-zwicker** [hgrecco/pint#385]
According to the documentation the format modified `:~` converts units to their abbreviated form. This certainly works when quantities are printed, but units are not abbreviated if only units are printed, see example below.

```
import pint
ureg = pint.UnitRegistry()
x = 2 * ureg.meters

print('{0}'.format(x))
#2 meter

print('{0:~}'.format(x))
#2 m

print('{0.units}'.format(x))
# meter

print('{0.units:~}'.format(x))
# meter
```

Here, I would expect the last line to just print `m`. Is there a way to get the abbreviated unit without the magnitude? This would be helpful for labeling plots.

**Comment by hgrecco** [comment]
This is was fixed.
