### ISSUE TITLE
numpy: matrix multiplication by left give wrong results

### ISSUE THREAD

**Issue by canesin** [hgrecco/pint#39]
Hi, this is a issue related to #37 , multiplication by left don't work with a numpy matrix, as matrices are not commutative for multiplication. It don't fail, it give wrong results.

https://gist.github.com/canesin/6115159

**Comment by hgrecco** [comment]
Review once that  #905 is implemented

**Comment by jthielen** [comment]
Based on https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.matrix.html, NumPy matrices should no longer be used, instead, regular arrays should be used. So, can this be closed as wontfix due to upstream deprecation?

**Comment by hgrecco** [comment]
Agreed!
