### ISSUE TITLE
Comparing Quantities from different UnitRegistry's gives confusing error message.

### ISSUE THREAD

**Issue by movermeyer** [hgrecco/pint#392]
The following code fails:

```
import pint
from datetime import datetime, timedelta

ureg = pint.UnitRegistry()
SPEED_LIMIT = ureg('100 kph')

def too_fast(meters, t1, t2, speed_limit):
    ureg = pint.UnitRegistry()

    distance = meters * ureg.meter
    seconds = (t2-t1).total_seconds() * ureg.second

    print repr(distance / seconds), repr(speed_limit)
    print type(distance / seconds), type(speed_limit)
    speed = (distance / seconds)
    return speed > speed_limit

meters = 50
t1 = datetime.utcnow()
t2 = t1 + timedelta(seconds=3600)
print too_fast(meters, t1, t2, SPEED_LIMIT)

```

with the confusing error:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    print too_fast(meters, t1, t2, SPEED_LIMIT)
  File "test.py", line 16, in too_fast
    return speed > speed_limit
  File "env/lib/python2.7/site-packages/pint/quantity.py", line 927, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
  File "env/lib/python2.7/site-packages/pint/quantity.py", line 914, in compare
    raise ValueError('Cannot compare Quantity and {0}'.format(type(other)))
ValueError: Cannot compare Quantity and <class 'pint.unit.Quantity'>
```

Which lead me to print out the types to confirm that the types were correct:

```
>>>print repr(distance / seconds), repr(speed_limit)
<Quantity(0.0138888888889, 'meter / second')> <Quantity(100, 'kph')>

>>>print type(distance / seconds), type(speed_limit)
<class 'pint.unit.Quantity'> <class 'pint.unit.Quantity'>
```

I would have expected my function to return False, and not crash.

Eventually, I realized that the problem could be worked around by using the same `UnitRegistry` for everything. However, in some cases this is simply not practical.

Results:
- `Quantity`'s should be comparable, regardless of which `UnitRegistry` was used to create them. 
- Failing that, the error message should give some explanation as the types appear to be correct
  - Possibly by changing the `__str__` method for `Quantity` to show the instance of the `UnitRegistry` it was created from.

**Comment by movermeyer** [comment]
For example, when you try to multiply units of different registries, it gives a meaningful error message:

```
q1 = UnitRegistry().meter
q2 = UnitRegistry().meter
q1 * q2
```

```
ValueError: Cannot operate with Unit and Unit of different registries.
```

Comparisons should give an equally useful message.

**Comment by mprat** [comment]
I agree; just ran into this with my Python program running multiple processes and all of them using `UnitRegistry` objects (my processes are `spawn`ed not `fork`ed so the registries are re-created in each process).

It seems like at least for the "built-in" quantities this should be possible.

**Comment by hgrecco** [comment]
This behaviour is by design but with the default registry implemente this should be alleviated.
