### ISSUE TITLE
Add support for median, average, and others

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#396]
I've been trying to add support for more ufuncs that keep units, by adding items to `__copy_units`.  Unfortunately, many ufuncs start with calling `asarray` or `asanyarray`, and we probably don't want to mess with those: people calling `asarray` will not expect to get a `Quantity` in return.  Is there another way this could be achieved?

Relevant ufuncs include: `median`, `average`, `percentile`, `expand_dims`, `atleast_1d`, `atleast_2d`, `atleast_3d`, `tile`, `rot90`, and others.

**Comment by hgrecco** [comment]
I tried this in the past. The problem is that numpy calls asanyarray which does not accept anything that is not a subclass of ndarray.

**Comment by hgrecco** [comment]
Revisit after #905
