### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by ChristianTremblay** [hgrecco/pint#404]
@hgrecco I thought you would appreciate knowing that we are using Pint in our library called pyhaystack that will be used in building data analysis. Thanks for your work. 

An issue was the easiest way to reach you. 

Apologize for any inconvenience.

**Comment by hgrecco** [comment]
Good to know! Thanks a lot.  By the way, would you like to submit a patch to:

https://github.com/hgrecco/pint_downstream_tester

It is basically a meta tester for pint. Before releasing a new pint version, I trigger travis to test this repo, which in turns test a few projects using pint against the new version. It helps me to avoid breaking downstream code.

**Comment by ChristianTremblay** [comment]
It is an excellent reminder for us to continue building the test suite for the module :-)
I would have absolutely no problem adding pyhaytsack to your list. In fact, I will talk with my partner so we could add hszinc which is the library we develop to parse haystack data. We deal with pint unit registry inside hszinc and we use it in pyhaystack.

In your script, I guess it would be better to restrict the tests to only those implying pint ? Or you just grab everything by default (with the assumption that the master branch should be stable and every test should pass)

To match the units read on project-haystack servers (www.project-haystack.org) we create the unit registry on the spot. Does it impact your tests ?

You can have a look if you want to the library used by pyhaystack (hszinc)
https://github.com/vrtsystems/hszinc/blob/master/hszinc/pintutil.py

Any suggestion to improve our design is welcome !

**Comment by sjlongland** [comment]
That's actually not a bad idea, incorporating the downstream projects' test cases.  From the `hszinc` perspective, I've more or less adopted "git flow" as the branching structure, so the `master` branch is always the latest stable.

That said, I recognise that Travis don't have infinite job build times.  The `hszinc` tests aren't hugely long, but they can soon add up if a lot of projects are added, so I'm not sure how well this will scale over time.

**Comment by hgrecco** [comment]
The `pint_dowstream_tester` tests in only executed before a new release (and when somebody contributes a new project). So it is not so much.

**Comment by hgrecco** [comment]
I am closing this now. Thanks!
