### ISSUE TITLE
Calculation with unpickled Quantities fails

### ISSUE THREAD

**Issue by pmaunz** [hgrecco/pint#405]
I create a pickle file with

    from pint import UnitRegistry, set_application_registry
    import pickle
    ureg = UnitRegistry()
    set_application_registry(ureg)
    Q = ureg.Quantity
    with open("pint.pkl", 'wb') as f:
        pickle.dump(Q(50, 'ms'), f)
        pickle.dump(Q(50, 'ns'), f)

Then I read the Quantities from the pickled file (in ANOTHER script)and try to divide the two unpickled quantities:

    from pint import UnitRegistry, set_application_registry
    import pickle
    ureg = UnitRegistry()
    set_application_registry(ureg)
    Q = ureg.Quantity
    with open("pint.pkl", 'rb') as f:
        t1 = pickle.load(f)
        t2 = pickle.load(f)

    print(t1 / t2)

This fails with the following Traceback:

    Traceback (most recent call last):
      File "C:/Users/pmaunz/PyCharmProjects/IonControl34/tests/pintunpickle.py", line 10, in <module>
        print(t1 / t2)
      File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py", line 738, in __truediv__
        return self._mul_div(other, operator.truediv)
      File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py", line 675, in _mul_div
        offset_units_self = self._get_non_multiplicative_units()
     File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py", line 1312, in _get_non_multiplicative_units
        offset_units = [unit for unit in self._units.keys()
      File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py", line 1313, in <listcomp>
        if not self._REGISTRY._units[unit].is_multiplicative]
    KeyError: 'millisecond'

I tracked the reason to the __new__ method of Quantity. If the unit is given as string, it is entered in `self._REGISTRY._units` if it is given as `UnitsContainer`  (as in the case of unpickle) or `UnitDefinition` it is not added to `self._REGISTRY._units` and the subsequent division fails.

**Comment by hgrecco** [comment]
We need to fix this. Give me a few days.

**Comment by pmaunz** [comment]
Thanks. I am using the following workaround for now. Basically by saving the unit as a string it gets added to the REGISTRY upon loading. It did pass all the unittests, but I am sure there is a more efficient or more elegant solution. A unittest could use the multiprocessing module (see http://stackoverflow.com/questions/38417527/python-pint-module-with-multiprocessing ). This is actually the way I stumbled upon the bug.

    diff --git a/pint/quantity.py b/pint/quantity.py
    index 3f30a25..695866a 100644
    --- a/pint/quantity.py
    +++ b/pint/quantity.py
    @@ -57,7 +57,7 @@ class _Quantity(SharedRegistryObject):

         def __reduce__(self):
             from . import _build_quantity
    -        return _build_quantity, (self.magnitude, self._units)
    +        return _build_quantity, (self.magnitude, str(self._units))

         def __new__(cls, value, units=None):
             if units is None:
