### ISSUE TITLE
unit prefix does not respect case_sensitive setting on parse_expression

### ISSUE THREAD

**Issue by FireByTrial** [hgrecco/pint#408]
when using `parse_expression` with `case_sensitive=False` the prefix case is not ignored. For example the following case will work (units is a unitRegistry): 

``` python
x = units.parse_expression("kiloGrams", case_sensitive=False)
```

but the following will raise an exception:

``` python
x = units.parse_expression("Kilograms", case_sensitive=False)
```

here is the exception:

```
pint.errors.UndefinedUnitError: 'Kilograms' is not defined in the unit registry
```

**Comment by hgrecco** [comment]
Just the units names can be case insensitive. In the prefix will lead to a class between Mega and milli (unless we separate between complete and abbreviated prefixed)

**Comment by jpeacock29** [comment]
For what it's worth, capitalization is also used to distinguish certain units, besides just prefixes. For example, 1 Calorie = 1000 calorie. It seems like better behavior would raise an error for units that are case-ambiguous.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
