### ISSUE TITLE
to_compact() fails for product of quantities

### ISSUE THREAD

**Issue by pmaunz** [hgrecco/pint#409]
`infer_base_unit` as currently implemented will not accept the product of quantities with the same dimension. That is `(Q(1, 'kilometer') * Q(1, 'millimeter')).to_compact()` will fail with an exception. A possible fix can be found in pull request #412. A full example of the error is below. 

    >>> import pint
    >>> u = pint.UnitRegistry()
    >>> Q = u.Quantity
    >>> q = Q(1, 'millimeter') * Q(1,'kilometer')
    >>> print(q)
    1 kilometer * millimeter
    >>> q.to_compact()
    ---------------------------------------------------------------------------
     DimensionalityError                       Traceback (most recent call last)
    <ipython-input-9-ab02a9e4eb72> in <module>()
    ----> 1 q.to_compact()

    C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py in  to_compact(self, unit)
        360             unit = infer_base_unit(self)
        361 
    --> 362         q_base = self.to(unit)
        363 
        364         magnitude = q_base.magnitude

    C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py in to(self, other, *contexts, **ctx_kwargs)
        282         other = to_units_container(other, self._REGISTRY)
        283 
    --> 284         magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
        285 
        286         return self.__class__(magnitude, other)

    C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\quantity.py in _convert_magnitude_not_inplace(self, other, *contexts, **ctx_kwargs)
        250                 return self._REGISTRY.convert(self._magnitude, self._units, other)
        251 
    --> 252         return self._REGISTRY.convert(self._magnitude, self._units, other)
        253 
        254     def _convert_magnitude(self, other, *contexts, **ctx_kwargs):

    C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\unit.py in convert(self, value, src, dst, inplace)
       1030         dst = to_units_container(dst, self)
       1031 
    -> 1032         return self._convert(value, src, dst, inplace)
       1033 
       1034     def _convert(self, value, src, dst, inplace=False):

    C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\pint\unit.py in _convert(self, value, src, dst, inplace)
       1067 
       1068         if src_dim != dst_dim:
    -> 1069             raise DimensionalityError(src, dst, src_dim, dst_dim)
       1070 
       1071         # Conversion needs to consider if non-multiplicative (AKA offset

    DimensionalityError: Cannot convert from 'kilometer * millimeter' ([length] ** 2) to 'meter' ([length])

**Comment by hgrecco** [comment]
Merged in develop!. Thanks
