### ISSUE TITLE
Should the multiplication/division by foreign objects be implemented?

### ISSUE THREAD

**Issue by efroustey** [hgrecco/pint#418]
When using objects that emulate numeric types, the right-multiplication or division by a Quantity produces a Quantity object whose magnitude is the result of the foreign object's `__rmul__()`. Here is a minimal example:

``` python
import pint
ureg = pint.UnitRegistry()

class A:
    def __rmul__(self, other):
        # Dummy implementation
        return self

q = 1*ureg.meter
a = A()
qa = q*a
print(qa.__repr__())
```

which prints something like:

``` python
<Quantity(<__main__.A object at 0x7f4f9f6bc048>, 'meter')>
```

As I'm working with objects of type `A` (to stick to my example), I need both the right- and left-multiplications to return `A`s, so the current behavior is problematic. To circumvent this, I forced the `_to_magnitude()` function of the `compat` package to raise a `TypeError` for non-numeric types, but I'm wondering if this is a right thing to do...

**Comment by hgrecco** [comment]
As far as I know you are the first trying this. Have you tried adding your type to compat `NUMERIC_TYPES`?

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
