### ISSUE TITLE
subtraction in parse_expression doesn't work if there are spaces: "missing unary operator"

### ISSUE THREAD

**Issue by micklat** [hgrecco/pint#423]
```
> python -c "import pint; print pint.UnitRegistry()('1-1')"
0
> python -c "import pint; print pint.UnitRegistry()('1 - 1')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pint/registry.py", line 825, in parse_expression
    return build_eval_tree(gen).evaluate(lambda x: self._eval_token(x,
  File "pint/pint_eval.py", line 83, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File "pint/pint_eval.py", line 88, in evaluate
    raise Exception('missing unary operator "%s"' % op_text)
Exception: missing unary operator "*"
```

This is with pint c5925bfdab09c75a26bb70cd29fb3d34eed56a5f, python 2.7.2.

**Comment by onealj** [comment]
```
>>> string_preprocessor('1 - 1')
'1 -*1'
```

The input_string breaks from the regex substitution pair `(r"([\w\.\-])\s+(?=\w)", r"\1*"),  # Handle space for multiplication` in _subs_re.

This may have worked prior to https://github.com/hgrecco/pint/commit/fc81211e259711e88c5463b9286910fc68415fd0
But the real question, does UnitRegistry('1-1') even make sense? I don't see anything that resembles this format in
http://pint.readthedocs.io/en/0.7.2/tutorial.html#string-parsing or /pint/testsuite/test_util.py

**Comment by hgrecco** [comment]
This was fixed long time ago but forgot to close.
