### ISSUE TITLE
Calling the ufunc in __array_wrap__ is probably a bad idea

### ISSUE THREAD

**Issue by eric-wieser** [hgrecco/pint#424]
Since by that point, the ufunc has already run once. Although putting it in `__array_prepare__` may also not solve the problem, since that:

> `__array_prepare__` **should not attempt to access the array data** or resize the array, it is intended for setting the output array type, updating attributes and metadata, and performing any checks based on the input that may be desired before computation begins.

**Comment by hgrecco** [comment]
I agree but there is no other way, as far as I now. I discuss this in the past with the numpy devs but there was no big interest to do provide a way to circunvent it. Recently the has been a discussion to add a new way to do this. It is still unstable.

**Comment by eric-wieser** [comment]
Here's a possible workaround:

* `__array_prepare__`:
   * check unit compatibility, raising exceptions if needed
   * convert arguments in `args` in-place to the same units (using `.ito`, perhaps). Store the old units and magnitudes
* `__array_wrap__`
   * restore the magnitude/units of `args` back to what they were

Does this work?

**Comment by hgrecco** [comment]
Take a look at https://github.com/numpy/numpy/issues/4072

**Comment by eric-wieser** [comment]
Also, there's some work in the pipeline to fix this with `__numpy_ufunc__`/`__array_ufunc`.

What are your thoughts on my proposed workaround above?

**Comment by hgrecco** [comment]
Your workaround looks ok in theory. If you like, prototype it and we test it.

However, at the end the numpy devs need to provide a good way to do this.

By the way, have you seen #326 ?
