### ISSUE TITLE
Equality is not transitive

### ISSUE THREAD

**Issue by eric-wieser** [hgrecco/pint#427]
```python
>>> from pint import UnitRegistry
>>> u1 = UnitRegistry()
>>> u2 = UnitRegistry()
>>> v1 = 1*u1.dimensionless
>>> v2 = 1*u2.dimensionless
>>> v1 == 1
True
>>> v2 == 1
True
>>> v1 == v2
ValueError: Cannot operate with Unit and Unit of different registries.
```
Is there a justification for not allowing _dimensionless_ quantities to be compared between unit registries?

**Comment by hgrecco** [comment]
No, it is just a by an undesired side effect. I think this should be allowed.

**Comment by eric-wieser** [comment]
Do you think we should also allow:

```
>>> x1 = 0*u1.V
>>> x2 = 0*u2.m
>>> x1 == 0
True
>>> x2 == 0
True
>>> x2 == x1
True
```

It doesn't seem unreasonable to me that `0` should be equal regardless of unit (ignoring C and F which have arbitrary meanings of 0)

**Comment by eric-wieser** [comment]
Just tested this in head - this test passes just fine.
