### ISSUE TITLE
Best way to handle dBSPL?

### ISSUE THREAD

**Issue by jrbrodie77** [hgrecco/pint#428]
Pint is great! Thanks for writing it.

Any advice on handling dBSPL?  e.g.

pressure = ur('1 pascal')
dBSPL = 20 \* np.log10(pressure/ur('20 micropascal'))

This works and returns 'dimensionless' but it would be great if I could somehow have 'log units' and have dBSPL show up as the unit.  Any way to do it?

**Comment by onealj** [comment]
Take a look at issue #71 and #249 for logarithmic units. Some work still needs done to get a general purpose solution.

For unit subtraction, see #248. While this might not come up in dBSPL, it comes up in other logarithmic units, converting between dBm and dBW, for example.

**Comment by hgrecco** [comment]
I am closing this, let's focus the discussion in #71
