### ISSUE TITLE
Unable to decorate a class method

### ISSUE THREAD

**Issue by saurabh02** [hgrecco/pint#431]
Hello,

Here's a very simple example in an effort to decorate a class method using Pint,

``` python
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

class Simple:
    def __init__(self):
        pass

    @ureg.wraps('m/s', (None, 'm/s'), True)
    def calculate(self, a, b):
        return a*b

if __name__ == "__main__":
    c = Simple().calculate(1, Q_(10, 'm/s'))
    print c
```

This code results in the below ValueError. 

``` python
Traceback (most recent call last):
   c = Simple().calculate(1, Q_(10, 'm/s'))
  File "build/bdist.macosx-10.11-intel/egg/pint/registry_helpers.py", line 167, in wrapper
  File "build/bdist.macosx-10.11-intel/egg/pint/registry_helpers.py", line 118, in _converter
ValueError: A wrapped function using strict=True requires quantity for all arguments with not None units. (error found for m / s, 1)
```

It seems to me that the issue here may be with class instances being passed to the pint decorator. Would anyone have a solution for fixing this?

Thanks
Saurabh

**Comment by MatthieuDartiailh** [comment]
I think you need to declare the unit of self as being None.

**Comment by hgrecco** [comment]
Indeed. `self` is an argument
```python
    @ureg.wraps('m/s', (None, 'm/s', 's'), True)
    def calculate(self, a, b):
        return a*b
```
The assigment will be:
- `self`: `None`
- `a`: `'m/s'`
- `b`: `'s'`

**Comment by saurabh02** [comment]
Great, thanks, that worked!

Can I ask you a quick simple follow-up question? If I code the same class as follows (decorating the constructor class instead)

```python
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

class Simple:
    @ureg.wraps(None, (None, None, 'm**3'), True)
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def calculate(self):
        return self.a*self.b

if __name__ == "__main__":
    c = Simple(2, Q_(20, 'm**3')).calculate()
    print c
```

I get the output,

```python
40.0
```

This is a float type. Is there a way to instead automatically output a pint Quantity object with magnitude and correct units, i.e. 40.0 m**3? 

Thanks
Saurabh

**Comment by hgrecco** [comment]
Sorry fo the long delay. Indeed you can do that by decorating with wraps and just setting the return units to m**3.
