### ISSUE TITLE
Defining a new system programmatically

### ISSUE THREAD

**Issue by mgab** [hgrecco/pint#432]
Hi,

First, thanks for the great package!

I want to change the base units of my unit registry. Of course, I'd rather use the default registry of definitions, as it is already gorgeously complete.
If I understood it correctly, a `system` defines the base units. Then, the [documentation](https://pint.readthedocs.io/en/stable/systems.html) does not mention any way to define custom systems.
Looking at the `default_en.txt` file, though, the syntax is straightforward. So one option would be to modify/copy the file and add a new system with my base units of choice.

However, I'm spoiled by this great package and dear to ask for more. I'd love a way to programmatically define a system, and in fact some API was proposed in #90 and #215. However, both issues are closed and I could not find how you can define systems programmatically.

Is there a way to define a system programmatically? Is there part of the implementation missing? if so, it is being discussed anywhere else?

Thanks!

**Comment by hgrecco** [comment]
Thanks for your support. Indeed this is not settled yet. We would like to have a convenient, ergonomic, easy to use, hard to misuse API. 

I would be very happy if people start discussing this (even if they cannot implement it). In particular I would like to see some example code **USING** the (not yet existing) API so we can discuss.

**Comment by hgrecco** [comment]
By the way, this was also (kind of) raised in #342

**Comment by mgab** [comment]
Closing the behavior discussed in this issue is already offered and well [documented](https://pint.readthedocs.io/en/stable/user/systems.html)!
