### ISSUE TITLE
New diemension

### ISSUE THREAD

**Issue by GTres** [hgrecco/pint#433]
Hi,
I like pint.

How to create a new dimention in a file mydef.txt

I put into the file mydef.txt:
`[areaindx] = [length] ** 2 / [length] ** 2`

If i write:

```
from pint import UnitRegistry
ureg = UnitrRegistry()
ureg.load_definitions('mydef.txt')
a = ureg('20 cm ** 2  m ** 2')
print('Standar: {!s}'.format(p))
print('Pretty: {:~P}'.format(p))
print('Latex: {:~L}'.format(p))
print('Type: ', p.dimensionality)
```

The output is:

```
Standar: 23.0 centimeter ** 2 / meter ** 2
Pretty: 23.0
Latex: 23.0
Type: dimensionless
```

I want the output:

```
Standar: 23.0 centimeter ** 2 / meter ** 2
Pretty: 23.0 cm²
Latex: 23.0 cm^{2}
Type: '[areaindexada]'
```

Thanks for your help

**Comment by eric-wieser** [comment]
How did you make 20 turn into 23, and `[length^2]` turn into `[]`? Your output does not match your code

It doesn't make sense to have dimensions derived from another dimension. The whole idea of dimensions is that they should be totally orthogonal to each other and form a basis.

**Comment by eric-wieser** [comment]
Note that your code is still correct, but the only way it's exposed is through:

    >>> ureg.get_dimensionality('[areaindex]`)
    UnitContainer({})

**Comment by hgrecco** [comment]
I am closing this, feel free to reopen if needed.
