### ISSUE TITLE
Comparison is valid in places that arithmetic is not

### ISSUE THREAD

**Issue by eric-wieser** [hgrecco/pint#434]
Compare:

```
>>> u1 = pint.UnitRegistry()
>>> u2 = pint.UnitRegistry()
>>> 1*u1.m == 1*u2.m
True
>>> (1*u1.m - 1*u2.m).m == 0
ValueError: Cannot operate with Quantity and Quantity of different registries.
```

It seems weird to allow comparison but not arithmetic

**Comment by jules-ch** [comment]
I think we can close this one.
The problem come from the operation `1*u1.m - 1*u2.m`, a solution to this is `((1*u1.m).m - (1*u2.m).m) == 0`.
