### ISSUE TITLE
deg and radians dimensionality == dimensionless?

### ISSUE THREAD

**Issue by sanzoghenzo** [hgrecco/pint#436]
```
from pint import UnitRegistry
ur = UnitRegistry()
a = 1 * ur.deg
print a.dimensionality
>>>>dimensionless
print (a.to(ur.rad).dimensionality)
>>>>dimensionless
```

I'm especting dimensionality to be "angle" or something like that.
I easily modified default_en.txt to reflect the intended behavior, but I think it could be a safe default for everyone.

**Comment by zplizzi** [comment]
Angles are considered to be dimensionless. In fact, anything that can't be defined in terms of a _physical_ unit is considered dimensionless. They may still have units, but units and dimensions are not the same. Check out [this answer](http://physics.stackexchange.com/a/193699/85874) for a better explanation of why.

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen.
