### ISSUE TITLE
Ratio of Two Quantities with Same Unit

### ISSUE THREAD

**Issue by chaseliu** [hgrecco/pint#438]
Is it possible to return Quantity(0.5, 'mole / mole') instead of Quantity(0.5, 'dimensionless')? I noticed that Quantity(0.5, 'mmole / mole') is OK but the ratio of same unit always has a 'dimensionless' unit. It would be nice if the user can choose to whether to simplify the unit or not.

**Comment by hgrecco** [comment]
It is not possible because of the way it is implemented (units is a dictionary, and the units are the keys). You can create a new unit if you like ('whatever_moles').
