### ISSUE TITLE
Unit checking for zero value

### ISSUE THREAD

**Issue by zplizzi** [hgrecco/pint#440]
It seems like the value `0` is handled specially in some parts of Pint, in the sense that the zero value doesn't always require units. For example, `(1 * ureg.mm) + 0` is valid, yet `(1 * ureg.mm) + 1` is (obviously) not.

So, I'm wondering if this should also be valid (it currently isn't):

``` python
@units.check("[length]")
def test(a):
    print(a)

test(0)
```

I'm not entirely sure it should be, but it definitely feels awkward to have to write `test(0 * units.meters)` or something.

**Comment by onealj** [comment]
Should 0 as a dimensionless quantity behave as a wild card? A dimensioned number plus a non-dimensioned number--even if that non-dimensioned number is an identity--doesn't make sense to me. I think distinguishing between a dimensioned and dimensionless 0 makes the most sense.

`(1 * ureg.mm) + (0 * ureg.mm)`

If it's inconvenient for users to deal with adding a number to a quantity where the number might be zero and where the dimensions were dropped, then they could always copy the units from the other quantity:

    q = 1 * ureg.mm
    r = 0
    q + (r * q.units)

But I don't think this would be needed with dimensional 0 and users' consistently carry units through their calculations (which they would need to do for non-zero values anyways).

**Comment by hgrecco** [comment]
Getting everything together in #1753
