### ISSUE TITLE
siunitx formatter does not preserve order of units

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#441]
The `{:Lx}` siunitx formatter does not preserve the order of units.  In the example below, the order of units has completely changed when using the siunitx formatter:

```
In [57]: q = ureg.Quantity(1, "count * m ** 2 * sr / cm / mW")

In [58]: print("{:~}".format(q))
1 count * m ** 2 * sr / cm / mW

In [59]: print("{:Lx}".format(q))
\SI[]{1}{\per\centi\meter\count\meter\squared\per\milli\watt\steradian}
```

**Comment by gerritholl** [comment]
This is due to the `sorted` call in `pint/formatting.py`, function `siunitx_format_unit(units)`, line 214, but it should probably call `formatter` defined on line 101?

**Comment by hgrecco** [comment]
Thanks!
