### ISSUE TITLE
Compare units from different registry that are similar

### ISSUE THREAD

**Issue by nowox** [hgrecco/pint#445]
I would like to use Pint to work with quantities of different devices. These devices can have the same or different definitions of units. If they are the same, I would like to allow these registry to work together. 

My current workaround is to have a master registry singleton that takes a registry and return an unified registry. The master class knows the used registry and if the input registry is similar another one already in the known registry list, the registry from the database is returned. 

```
a = pint.UnitRegistry()
b = pint.UnitRegistry()
c = Registry(a)
d = Registry(b)
e = c.meters * d.meters
```

I don't like this workaround. Is there any better solution?

**Comment by hgrecco** [comment]
The suggestion is http://pint.readthedocs.io/en/0.7.2/tutorial.html#using-pint-in-your-projects

Will that work for you?

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
