### ISSUE TITLE
UnitsContainer does not implement __contains__

### ISSUE THREAD

**Issue by bryanwweber** [hgrecco/pint#447]
It would be extremely useful to be able to test the dimensions that make up a Quantity using `in`. However, as of 0.7.2, `UnitsContainer` doesn't implement `__contains__` in a way that permits this:

```
>>> dim = Q_(20.785, 'J/(mol)').dimensionality
>>> print(dim)
[length] ** 2 * [mass] / [substance] / [time] ** 2
>>> print('a' in dim)
True
>>> print('temperature' in dim)
True
```

As of now, the easiest way to accomplish this is to cast the `UnitsContainer` to a string, and then do the comparison.

**Comment by hgrecco** [comment]
I agree. Anyone would like to make a PR?
