### ISSUE TITLE
Support degree sign

### ISSUE THREAD

**Issue by iamthad** [hgrecco/pint#449]
The degree sign should be supported.

Current behavior:

    >>> import pint
    >>> units = pint.UnitRegistry()
    >>> Q_ = units.Quantity
    >>> Q_('90°')
    <Quantity(90, 'dimensionless')>

Expected behavior:

    >>> import pint
    >>> units = pint.UnitRegistry()
    >>> Q_ = units.Quantity
    >>> Q_('90°')
    <Quantity(90, 'degree')>

It does not appear to be possible to just define the degree sign as a unit alias in the unit registry, possibly because the degree sign is not letter-like.

**Comment by hgrecco** [comment]
Indeed this is due to the fact we use the python tokenizer.  Same problem with #429. I would like to see a better way to dealing with all these things.
