### ISSUE TITLE
Conversion fails

### ISSUE THREAD

**Issue by martinwk** [hgrecco/pint#451]
Dear developers,
I just started pint and so far it is great! I am currently in a project where we need to model some adsorbtion on active carbon. Typically we have then the concentration in the liquid en the concentration in the substrate (=active carbon) which can both be converted between moles and grams easily. NOte however that the unit of the concentration on the substrate is g/g_substrate which could be considered dimensionless

```
from pint import UnitRegistry
ureg = UnitRegistry()
ureg.define('g_substrate = g')

concentration_fluid = 10 * ureg('g/L')
concentration_substrate = 2e3 * ureg('g/g_substrate')

mw = 55 * ureg('g/mol')
print concentration_fluid.to('mol/L', 'chemistry', mw = mw)
print concentration_substrate.to('mol/g_substrate', 'chemistry', mw = mw)
```
An empirical relation between these concentration is given by the Freundlich isotherms with:
concentration_substrate = Kf * concentration_fluid ** n_inv
with Kf and n_inv some constants with unit (g / g_substrate) / (g/L) ** n_inv and dimensionless respectively.
Say n_inv = 0.3 then 
```
Kf = 20 * ureg('(g/g_substrate)/(g/L) ** 0.3')
```

Now I want to convert the units of Kf into (mol / g_substrate) / (mol/L) ** n_inv but this gives me an error. 
```
print Kf.to('(mol/g_substrate)/(mol/L)', 'chemistry', mw = mw)
```
Error message:
```
DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'gram ** 0.7 * liter ** 0.3 / g_substrate' ([length] ** 0.9 / [mass] ** 0.3) to 'liter / g_substrate' ([length] ** 3 / [mass])
```
Am I doing something wrong?

**Comment by dimapu** [comment]
Hi martinwk, 

### How to overcome it for now
Please check this code. Here, I first convert `concentration_fluid` and `concentration_substrate` to `mol/g_substrate` and `mol/L` and then calculate the quantity `Kf`, which will have required dimension. 

    from pint import UnitRegistry
    ureg = UnitRegistry()
    ureg.define('g_substrate = g')
    concentration_fluid = 10 * ureg('g/L')
    concentration_substrate = 2e3 * ureg('g/g_substrate')
    mw = 55 * ureg('g/mol')
    n_inv = 0.3

    Kf1 = concentration_substrate.to('mol/g_substrate', 'chemistry', mw=mw) / ( concentration_fluid.to('mol/L', 'chemistry',  mw=mw) ** n_inv)
    print(Kf1)
    print(Kf1.to_base_units())
    print(Kf1.to('(mol/g_substrate)/(mol/L)**0.3'))

Please note that the unit is `'(mol/g_substrate)/(mol/L)**0.3'` and not `'(mol/g_substrate)/(mol/L)'` as you have in your code.

### Why error appears 
I think it is due to a limited set of possible conversions in a `'chemistry'` context. I don't understand details of the algorithm in `pint.util.find_shortest_path()` completely, but guess it would be hard to implement it for arbitrary power `n_inv`. Even for [mass]**2 it already fails:

    mass = 10 * ureg('g')
    print(mass.to('mol', 'chemistry',  mw=mw))  # g -> mol conversion works

    mass_squared = 10 * ureg('g**2')
    print(mass_squared.to('mol**2', 'chemistry',  mw=mw))  # g**2 -> mol**2 conversion fails

**Comment by martinwk** [comment]
Hi dimapu,
Thanks for your quick reply. To bad it is currently not possible to treat this problem in an elegant manner. Your approach might work, although a little verbose. The full workaround would look somethin like this

```


from pint import UnitRegistry
ureg = UnitRegistry()
ureg.define('g_substrate = L')

concentration_fluid = 10 * ureg('g/L')
concentration_substrate = 2e3 * ureg('g/g_substrate')

mw = 55 * ureg('g/mol')
n_inv = 0.3

Kf = 20 * ureg('(g/g_substrate) / (g/L) ** ' + str(n_inv))
dummy_concentration_fluid = 1 * ureg('g/L')
dummy_concentration_substrate = Kf * dummy_concentration_fluid ** n_inv

dummy_concentration_substrate = dummy_concentration_substrate.to('g/g_substrate')

Kf_mol = (dummy_concentration_substrate.to('mol/g_substrate', 'chemistry', mw = mw) / (dummy_concentration_fluid.to('mol/L', 'chemistry', mw = mw)) ** n_inv)

print mw**(n_inv-1) * Kf  # manual conversion from (g/g_substrate) / (g/L)**n_inv  to (mol/g_substrate) / (mol/L) **n_inv
print Kf_mol  # 

```

Note how I make the dimension g_substrate to be in Liters (although it represents actually grams); when using g_sustrate=g, it throws an error. It would be nice if I could make a user defined thing equivalent to [length], [mass] etc.

Most clean is now to use the manual conversion (see end of snippet)

**Comment by hgrecco** [comment]
As @dimapu said, you cannot convert from distinct dimensions. But I do not think is a short coming of the `find_shortest_path` but rather that the relation is not defined.

You can teach pint how to do it by expanding the context. In other words, you can teach Pint the Freundlich isotherms. Take a look at: http://pint.readthedocs.io/en/0.7.2/contexts.html

and ping back if you need help.

**Comment by martinwk** [comment]
Thank you very much for your reply, I did not realize the full potetential of contexts yet. This looks promising. However, I am still struggeling. What I got so far is:
```


import pint
ureg = pint.UnitRegistry()
ureg.define('g_substrate = g')

concentration_fluid = 10 * ureg('g/L')
concentration_substrate = 2e3 * ureg('g/g_substrate')

mw = 55 * ureg('g/mol')
n_inv = 0.3

Kf = 20 * ureg('(g/g_substrate) / (g/L) ** ' + str(n_inv))

c = pint.Context('freundlich')
c.add_transformation('[length] ** 0.9 / [mass] ** 0.3',
                     '[length] ** 0.9 * [substance] ** 0.7 / [mass]',
                     lambda n_inv, mw, x: mw ** (n_inv-1) * x)
ureg.add_context(c)
print Kf.to('(mol/g_substrate)/(mol/L) ** ' + str(n_inv), 'freundlich', mw = mw, n_inv=n_inv)
```
which still gives the error
```
raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 
'gram ** 0.7 * liter ** 0.3 / g_substrate'           ([length] ** 0.9 / [mass] ** 0.3)
to 'liter ** 0.3 * mole ** 0.7 / g_substrate'       ([length] ** 0.9 * [substance] ** 0.7 / [mass])
````
which asks for the relation I just implemented. Directly as a follow up question, can I give n_inv as an argument to the definition of the relation as well? Like in:
```
c.add_transformation('[length] ** (3*n_inv) / [mass] ** n_inv',
                     '[length] ** (3*n_inv) * [substance] ** (1-n_inv) / [mass]',
                     lambda n_inv, mw, x: mw ** (n_inv-1) * x)
```
I guess this won't work, do you have some thoughts how to make this work?

**Comment by hgrecco** [comment]
This is a precision error. If you do:
```python
>>> f = lambda n_inv, mw, x: mw ** (n_inv-1) * x)
>>> f(n_inv, mw, Kf).dimensionality
<UnitsContainer({'[length]': 0.8999999999999999, '[mass]': -1.0, '[substance]': 0.7})>
```

Solving this requires changing the way we handle exponents.
