### ISSUE TITLE
parameter for @ureg.check

### ISSUE THREAD

**Issue by martinwk** [hgrecco/pint#465]
Hi, 
The more I work with pint the more I am amazed with its completeness. Nevertheless, I have an issue with a constants with somewhat exotic unit. It is the Freundlich constant, Kf:
```
[Kf] = (g/g_adsorbent) * (L/g)**n_inv
```
now if I want to check whether input to some function has the right units, I could use the @ureg.check decorator.
```
@ureg.check('g/L', 'g/g_adsorbent', '(g/g_adsorbent) / (g/L) ** n_inv', None)
def myFunc(c, q, Kf, n_inv):
    ...
```
which is the same as
```
@ureg.check('=A', '=B', '=B / A**n_inv', None)
def myFunc(c, q, Kf, n_inv):
    ...
```
This doesn't work as far as I understand. Is it possible to make this work? The issue here is of course that the unit of Kf depends on the value of n_inv and can therefore not be hard coded.

**Comment by hgrecco** [comment]
This does not work right now but it might be a good addition. But it might be better to combine it with contexts, something like:

```python
@ureg.check('=A', '=B', '=B / A**n_inv', None, context='spectroscopy', context_values=dict(n_ninv=3))
def myFunc(c, q, Kf, n_inv):
```

(We need to find a better syntax (I dislike particularly context_values)  but you get the idea.

**Comment by martinwk** [comment]
Ok thanks for letting know. I get your idea but I don't know for  a better syntax though

**Comment by hgrecco** [comment]
I think I came with a nice, composable, solution
