### ISSUE TITLE
dir(ureg.sys.US) raises a KeyError

### ISSUE THREAD

**Issue by AntoineGX** [hgrecco/pint#472]
Hello,

Thanks a lot for this very useful package.
I get an error when trying to know which units are available within the US unit system:

```
>>> import pint
>>> ureg=pint.UnitRegistry()
>>> dir(ureg.sys.US)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pint\systems.py", line 290, in __dir__
    return list(self.members)
  File "C:\Anaconda3\lib\site-packages\pint\systems.py", line 305, in members
    self._computed_members |= d[group_name].members
KeyError: 'USCSVolume'
```

Pint version is 0.7.2, running with Python 3.5.1 :: Anaconda 2.5.0 (32-bit).

**Comment by hgrecco** [comment]
Yes. There is a bug in the definition file that says USCSVolume instead of USCSVolumeOther. However, this points to another bug: this error should be nicer!
