### ISSUE TITLE
units need explicit magnitude (and functions missing?)

### ISSUE THREAD

**Issue by mankoff** [hgrecco/pint#475]
I just upgraded to 0.7.2. I think I was on 0.6 until recently. Things have changed... and I don't see mention of this change in the changelog (although the changelog is rather technical and developer-oriented, not user-oriented).

Specifically, I have a lot of code that used to work that looked like:

    g = ureg.gravity.to_base_units()
    i2c = ureg.inch.to(ureg.cm)

I now need to explicitly add a magnitude, **and** an extra set of parenthese:

    g = (1 * ureg.gravity).to_base_units()
    i2c = (1 * ureg.inch).to(ureg.cm)

Was this change intentional? Was I doing something incorrect before?

**Comment by hgrecco** [comment]
Sorry for being so late to answer (I completely overlooked this). Yes the API change was intentional but should have been better explained. Sorry.
