### ISSUE TITLE
Feature request: throw a switch in the Registry to make all quantities behave dimensionless

### ISSUE THREAD

**Issue by AllenDowney** [hgrecco/pint#477]
I have a particular use case I am thinking of and would like to explain what I am looking for and see if it is feasible.  @hgrecco, are you available for a phone call or video chat?

**Comment by AllenDowney** [comment]
I have found a really hacky way to do what I want.  I seems to be working, as shown in this example:

https://github.com/AllenDowney/ModSimPython/blob/master/code/odeint_example.ipynb

@hgrecco if you have a chance to look, I would love to know if there is a better way, or if this is a feature that could be pulled into Pint.

**Comment by hgrecco** [comment]
The way to do this is by wrapping. See wraps in the documentation.
