### ISSUE TITLE
Gb/s parses as "gigabarns / second" by default

### ISSUE THREAD

**Issue by bobpoekert** [hgrecco/pint#478]
To reproduce:
```python

import pint
ureg = pint.UnitRegistry()

print ureg('20 Gb/s')
```

It returns `<Quantity(20.0, 'gigabarn / second')>`
It should return `<Quantity(20.0, 'gigabit / second')>`

**Comment by gerritholl** [comment]
The barn is a [Non-SI unit accepted for use with the SI](http://www.bipm.org/en/publications/si-brochure/table8.html).  I could not find any mention of use of the bit from BIPM, so from that point of view it makes sense to give precedence to the barn.  The pint website mentions that it does not restrict the use of SI prefixed with non-SI units.  Changing the current behaviour would break any code using units of barn.

**Comment by hgrecco** [comment]
Agreed with @gerritholl . However, I would agree for some sort of grouping (using the Systems/Group) API if it improves the situation.
