### ISSUE TITLE
Hosting this on Anaconda (again?)

### ISSUE THREAD

**Issue by stadelmanma** [hgrecco/pint#485]
I am looking to add pint into my current project to replace my own light weight unit conversion module and was searching around to see if it was offered on Anaconda. It seems it [was](https://anaconda.org/auto/pint/files) but it's terribly out of date now. 

Is there any interest in keeping an up to date release on Anaconda Cloud? I also noticed your PyPi bage only shows up to 3.5 but I can use pip to install it on Python 3.6 as well. 

Cheers,
Matt

**Comment by dopplershift** [comment]
pint is available on the [conda-forge channel](https://conda-forge.github.io), which is a community-supported channel with over 1500 packages. This will install it:
```sh
conda install -c conda-forge pint
```
Files are available [here](https://anaconda.org/conda-forge/pint).

**Comment by stadelmanma** [comment]
Ah I am surprised conda-forge didn't show up when I searched, I tried a myriad of phases in Google. It might be good to add that line above to the main README and either remove or redirect the old page. Since the only place conda-forge shows up in the repository is this specific issue, granted pip works just fine as well and the only reason I asked is because I figured I wasn't looking in the right place.

If you'd like a PR for the issue I'll be glad to make the adjustments.

**Comment by dopplershift** [comment]
I can't speak for the pint project, since I don't have commit rights. 😁 

I'm just the guy who made the conda-forge recipe since I use pint for my own projects.

**Comment by hgrecco** [comment]
Please make a PR and I will merge. I like conda a lot and I will be happy if we make it easier for conda lovers.

**Comment by dopplershift** [comment]
@hgrecco  a PR for what exactly? Noting how to install using conda-forge?

**Comment by stadelmanma** [comment]
My intent was to just throw  `conda install -c conda-forge pint` into the README below the pip installation instructions.

**Comment by hgrecco** [comment]
@stadelmanma That is right, as complementary information below pip's instruction.

Out of curiosity, why you use conda for this? I use conda a lot but mostly for binary packages. For the rest, I just use pip

**Comment by dopplershift** [comment]
I think conda maintains consistent dependency within an environment, while pip seems to just ensure that the most recent thing you install has its requirements fulfilled. i.e. A needs numpy < 1.12, while B needs >=1.12. Pip will happily let you install A, then B. Conda will complain.

Also conda uninstall is guaranteed to work (i.e. remove all the packages' files), while IIRC pip is not.

**Comment by stadelmanma** [comment]
I use the conda environment in the [modeling package](https://github.com/stadelmanma/netl-AP_MAP_FLOW) I've created to make it more cross-platform friendly. I have a small unit conversion wrapper built in that now uses pint and it's just easier to install everything from a single source, especially for non-technical users. 

I might eventually host the modeling package on conda-forge as well just to simplify things even further (especially on the Windows side).
