### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#488]
(I apologise if this is the wrong place to ask)

I realised I inadvertently rely on some fixes [made in April 2016](https://github.com/hgrecco/pint/commit/a3ecba3c0cbba8e016deeef024c227d69a83c2f4).  I'm not sure if I wish to go through the effort of making my code work without those fixes.  Is there any time plan for a new pint release, 0.7.3 or 0.8?

**Comment by hgrecco** [comment]
I was not able to give **Pint** the love it needs in the last months. Together with the fact that there is a very nice community of users and developers around Pint, I have decided that it is time to share the control over the repo. I am looking into the best way to do it. 

Ideally I would like something like a merge bot in which authorized users could give a +1 or similar and then the bot will do the merge (after ensuring that tests are passing). I think this will be the best way to help the community grow.

I have been looking into options:
- https://github.com/graydon/bors
- https://github.com/rust-community/bors
- https://github.com/bors-ng/bors-ng
- https://github.com/barosl/homu

but without any clear winner. 

If we do not find any, we do it the traditional github way. But a merge bot would be nice.

Hope you are willing to participate!

**Comment by hgrecco** [comment]
Other options: 
- https://github.com/lgtmco/lgtm
- https://zappr.opensource.zalan.do/

**Comment by hgrecco** [comment]
I have chosen  https://github.com/bors-ng/bors-ng

Let's see if it helps things flow

**Comment by hgrecco** [comment]
See #494
