### ISSUE TITLE
wraps for functions with parameters in arbitrary quantities 

### ISSUE THREAD

**Issue by rpuntaie** [hgrecco/pint#489]
Hello,

I've found pint quite nice and wanted to adopt it for our project, but then I failed to wrap my functions.
The following two test cases, added to test_unit.TestRegistry.test_wraps, fail:

```
    f4 = ureg.wraps(10*ureg.uA, [None, ], strict=False)(func)
    self.assertEqual(f4(3.), 30 * ureg.uA)

    f5 = ureg.wraps(10*ureg.uA, [5*ureg.uA, ], strict=False)(func)
    self.assertEqual(f5(10*ureg.uA), 20 * ureg.uA)
```

How can one achieve such wrapping?

If this is not possible I probably can fix it and provide a pull request.

Best, Roland

**Comment by hgrecco** [comment]
Hi! Wraps works by transforming quantities into the required units, feeding the magnitude to the function (which should return a number/array/etc but not a quantity), and then adding the unit to the output. So it is fine that all this cases fail. What are you trying to achieve?

**Comment by rpuntaie** [comment]
Well, the functions I want to wrap return a number whose unit is e.g. 10uA or they expect a number parameter whose unit is 5uA.

**Comment by hgrecco** [comment]
If the units of both are uA, you can just do:
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> def f(x): return x
>>> g = ureg.wraps(ureg.uA, ureg.uA)(f)
>>> g(3 * ureg.uA)
<Quantity(3.0, 'microampere')>
```

**Comment by rpuntaie** [comment]
But the function's unit is e.g. 10uA. A number 1 would mean 10uA. A number 2 would mean 20uA. If I use pint and forward 20uA to the wrapper, the actual value given to the function should be 2. For a return value of 2, the wrapper should give me 20uA. 

I've made a pull request which allows to do that.

Sometimes functions (in C) have such strange units, because it allows to adjust the range of wanted physical current to fit into for example a uint16_t.

**Comment by hgrecco** [comment]
This would collide with other things in Pint. `10uA` is not a valid unit is a quantity with magnitude 10 and unit uA. You could define a unit easily: `ureg.define('Ten_uA = 10 uA')`

**Comment by rpuntaie** [comment]
It may collide with the basic idea behind pint, but I don't see any problem as an extension to `wraps`. If you do, please elaborate.

**Comment by rpuntaie** [comment]
I've tried what you proposed:

        >>> from pint import UnitRegistry
        >>> u = UnitRegistry()
        >>> def func(x):
        >>>     return x
        >>>
        >>> u.define('_10uA=10 uA')
        >>> u.define('_5uA=5 uA')
        >>> f5 = u.wraps("_10uA", ["_5uA", ], strict=False)(func)
        >>> f5(10*u.uA) #1.9999999999999998 _10uA
        >>> f5(10*u.uA) == 20*u.uA #False
        >>> f5(10*u.uA).to(u.uA) #19.999999999999996 microampere
        >>> f5(10*u.uA).to(u.uA) == 20*u.uA  #False because of precision

I nevertheless ask you to accept my pull request,
because it seemed obvious to me that it ought to work like that
when I first tried.  I was surprised it didn't. 
That is to say

- it is more intuitive to use wraps() like suggested in the pull request:

        >>> f5 = ureg.wraps(10*u.uA, [5*u.uA, ], strict=False)(func)
        >>> f5(10*ureg.uA) == 20*ureg.uA #True

New units as above can still be made, if wanted.  One might though like to hide
the special unit for the function as an implementation detail, which also means
that the defined units should never show up, but they do. One needs to convert
them to the normal power of 10 units.  
It generally feels more natural to use the normal units. This can be done
when using the change in the pull request.

**Comment by hgrecco** [comment]
The problem that I see is that this breaks for non multiplicative units. Right now you can do:
```python
ureg.wraps(ureg.celsius, (ureg.celsius,))
```

but I think if you do do: 
```python
ureg.wraps(10 * ureg.celsius, ( 5* ureg.celsius,)) 
```

it will not work.

**Comment by rpuntaie** [comment]
No existing feature has been compromised with my change. So this still works:
```
u.define('celsius2=2*celsius')
f1=u.wraps(u.celsius2,(u.celsius2), False)(fun)
assert f1(4).to(u.celsius)==8*u.kelvin
```

But now also this:

```
f2=u.wraps(2*u.delta_degC,(2*u.delta_degC), False)(fun)
assert f2(3)==2*3*u.delta_degC
```
