### ISSUE TITLE
Formatting Exponents on Magnitudes

### ISSUE THREAD

**Issue by jdriordan** [hgrecco/pint#491]
```
units = pint.UnitRegistry()

s  = units.second
m  = units.metre

x = 1.23e100 * s**2 / m**0.5

print('Latex:   {x:~L}, \nUnicode: {x:~P}'.format(x=x))
```
gives
```
Latex:   1.23e+100 \frac{s^{2}}{m^{0.5}}, 
Unicode: 1.23e+100 s²/m⁰.⁵
```

where I would like/expect 

```
Latex:   1.23 \times 10^{100}\ \mathrm{s}^{2}\mathrm{m}^{-0.5}, 
Unicode: 1.23×10¹⁰⁰ s²/m⁰⋅⁵
```
The changes are primarily in using explicit scientific notation as opposed to 'e' and also;

Latex:
- no \frac for units
- upright font for units

 Unicode:
 - U+22C5 (dot operator) instead of the normal un-superscipted decimal point in the meter exponent (see https://github.com/hgrecco/pint/issues/60)

I know that some of the LaTeX issues are remedied by using the siunitx pacakge, but at least for my use case (jupyter), that's not an option as far as I'm aware.

Also, this problem is (somewhat) remedied by using `uncertainties`:
`G=((6.674080000000001 ± 0.000000000000021)×10⁻¹¹) m³/kg/s²`
but it would be nice if the mean and uncertainty should had separate exponents.

((6.674080000000001 ± 0.000000000000021)×10⁻¹¹) m³/kg/s²

I don't think anyone re-parses LaTeX or pretty unicode and so it shouldn't be an issue to change the output to make it more presentable. If this is agreeable as-is I'm happy to make a pull request.

**Comment by hgrecco** [comment]
Thanks for your suggestion. The idea looks good to me. Submit a PR!

**Comment by JayPalm** [comment]
I'd like to further suggest that `{\times}` is used instead of `\times` so that there is no space between the coefficient and the base.
Using the example above:

`Latex:   1.23 {\times} 10^{100}\ \mathrm{s}^{2}\mathrm{m}^{-0.5}, 
Unicode: 1.23×10¹⁰⁰ s²/m⁰⋅⁵`

vs

`Latex:   1.23 \times 10^{100}\ \mathrm{s}^{2}\mathrm{m}^{-0.5}, 
Unicode: 1.23 × 10¹⁰⁰ s²/m⁰⋅⁵`

**Comment by hgrecco** [comment]
Agreed. Submit a PR

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
