### ISSUE TITLE
recursive wraps for iterable arguments?

### ISSUE THREAD

**Issue by ftroude** [hgrecco/pint#492]
Apologies:
- for my English
- for being a newbie at Github (no formatting, etc)

Linked to issue #196, would it be feasible to add an argument - e.g., recursive=True/False - to apply the conversion on every quantity inside a list/tuple argument of the function? 

For example, I am making a function receiving a list of point coordinates (in m) in order to return a sympy Polygon instance. How to make ureg.wraps convert all the point coordinates before computation?

**Comment by hgrecco** [comment]
It is an interesting idea and I do think that there might space for it. We need to make the API clear. I had a problem like that in past but I ended up creating a Quantity with a magnitude array (insteand of an array of quantities).

The code was something like:
```python
qv = [ q.m_as(mylist[0].units) for q in mylist] * mylist[0].units
```

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
