### ISSUE TITLE
spurious warning in exp/log of quantity with large 'fraction'

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#493]
When taking the exponent of a dimensionless quantity, in the situation where the unit is far from `"1"`, we get an overflow despite the final result being correct:

```
In [161]: numpy.exp(ureg.Quantity(1e18, 'ns/Gs')) 
/dev/shm/gerrit/venv/stable-3.5/bin/ipython3:1: RuntimeWarning: overflow encountered in exp
Out[161]: 2.7182818284590451
```

I don't know if it's possible to adapt the value passed to `exp` before `exp` is evaluated?  I believe that in the current implementation, `exp` is evaluated twice.

**Comment by hgrecco** [comment]
Indeed exp is evaluated twice because there is no way to tell numpy that the class is going to take care of it. AFAIK there is no workaround for this yet. See the last paragraph in this page from the pint docs: https://pint.readthedocs.io/en/0.7.2/numpy.html#comments

**Comment by hgrecco** [comment]
I am closing this now, feel free to reopen if needed
