### ISSUE TITLE
0.8 is coming in April 15, and 0.9 will be faster due to new committers

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#494]
Just a quick update. It has been a year since the last release and it is definitely time for new one. The largest change is the refactoring of the registry (which I have been using for a while and works nicely). But there a lot of other very valuable features and bug fixes already merged.

I would also like to mention that we are now using https://github.com/bors-ng/bors-ng to improve the PR approval workflow. This will be supported by giving members of the community committers rights.

Thanks!

**Comment by movermeyer** [comment]
Hooray!

Now that 0.8 is out, could you make [a GitHub Release](https://github.com/hgrecco/pint/releases)?

**Comment by hgrecco** [comment]
Done! Somehow the tag was not pushed properly. Thanks for pointing this out.
