### ISSUE TITLE
Frequency in spectroscopy context

### ISSUE THREAD

**Issue by egranstedt** [hgrecco/pint#505]
Several previous issues have brought up challenges related to distinguishing between frequency and angular frequency:

- https://github.com/hgrecco/pint/issues/63
- https://github.com/hgrecco/pint/issues/182

This issue is related to those above, but I want to illustrate peculiar behavior within the spectroscopy context.  In particular, note:
frequency [Hertz, cycles/second, 1/time] = c [speed of light, length/time] / wavelength [length]
omega [angular frequency, radians/second, 1/time] = 2 * pi * c [speed of light, length/time] / wavelength]

Consider the following python code:
```
print("convert photon wavelength to frequency")
wl = 656.46  # Hydrogen Balmer-alpha wavelength in vacuum, [nm]

print("first without pint:")
import numpy as np
c = 299792458.0  # speed-of-light in vacuum [m/s]
print('freq: {:.03g} Hz (cycles/second)'.format(c/(wl*1e-9)))
print('omega: {:.03g} radians/second'.format(2*np.pi*c/(wl*1e-9)))

print("")
print("then using pint")
import pint
ureg = pint.UnitRegistry()

l = wl * ureg.nm
print(l.to('Hz', 'sp'))
print(l.to('1/second', 'sp'))
print(l.to('cycles/second', 'sp'))
print(l.to('rad/second', 'sp'))
```

The following output is produced:
```
convert photon wavelength to frequency
first without pint:
freq: 4.57e+14 Hz (cycles/second)
omega: 2.87e+15 radians/second

then using pint
4.56680464918e+14 hertz
4.56680464918e+14 / second
7.26829534052e+13 turn / second
4.56680464918e+14 radian / second
```

The last two conversions using pint are wrong.  Is there a way to resolve this issue within the spectroscopy context?

**Comment by hgrecco** [comment]
Thanks for your message. 

Context rules are defined in terms of dimensions (not units) and within the spectroscopy context a `[length]` to `[frequency]` conversion is defined. The frequency here is the temporal frequency not the angular frequency. The problem to support your needs right now is that `cycle` and `radian` are dimensionless as well. Therefore `hertz` and `turn / second` both have the same dimensionality: `1 / [time]`. A rule for angular frequency will collide with a rule for temporal frequency.

Making angles dimensional is an [old idea ](http://nvlpubs.nist.gov/nistpubs/jres/66B/jresv66Bn3p97_A1b.pdf). But I have never seen it in use. 

However, there were some ideas about supporting an extra layer of information in pint that allows to distinguish the `role` (on the absence of a better word) of the unit. This could be done by adding information in the base unit definition. For example:

```
meter = [length] = m = metre
radian = [:angle] = rad
bit = [:information]
count = [:]
```

In this way, the context could incorporate a rule for `[frequency] *  [:angle]` which will not collide with this.

**Comment by hgrecco** [comment]
Closing this for the time being.
