### ISSUE TITLE
Allow constants within units (e.g. for "L/100km")

### ISSUE THREAD

**Issue by jni** [hgrecco/pint#507]
A very common unit in car fuel economy is L/100km. Currently, as far as I can tell, there is no way to express this in pint. There's probably other similar common measurements.

As a side note, it would also be good if pint knew how to compute reciprocals directly. (ie (30 ureg.miles / ureg.imperial_gallon).to('L/100km')

**Comment by dopplershift** [comment]
cc @kgoebber

**Comment by hgrecco** [comment]
This is not possible right now as the parser will (correctly) interpret the 100 as a number (not part of the unit. It could be mimicked by prepending a symbol to 100 like `L/_100km`. 

Regarding your second point, there is not simple and safe way to achieve this in a global, generic manner. However, contexts are exactly provided for this purpose.

**Comment by jni** [comment]
@hgrecco Ah, cool, I didn't know about [contexts](https://pint.readthedocs.io/en/0.8/contexts.html)! However, I don't know how to specify one in this case — what should I use instead of [length] and [frequency] for these fuel economy units? Or is that text arbitrary?

Generally, though, I would argue that there is a generic way: try to convert to target units, and if that fails, try the reciprocal, and if that fails, raise. Am I missing some horrible failure case?

Regarding 100km, would you say then that I should define my own unit of distance, _100km = 100km, and then let pint do its magic, probably with a context? Also, would a contribution be welcome that defined `_\d+.?\d*` as a valid modifier to any unit, meaning that number of units? I can see other uses for this, like computing 500m split times.

**Comment by hgrecco** [comment]
I do not like guessing the user intention in this type of things. In the long shot, it can raise unexpected bugs in scientific code. I would agree with a `to_inverse()` (or better named) method.

Regarding your other suggestion, it is interesting. How about opening another issue to discuss the specifics.

**Comment by jni** [comment]
@hgrecco it turns out that `_unit` is reserved usage!

```python
import numpy as np
import pint
u = pint.UnitRegistry()
u.define('_100km = 100 * kilometer')  # <- this works fine, but...!
volt_fuel_economy = np.array([16.0, 21.]) * u.kWh / u._100km
```
```pytb
--------------------------------------------------------------------------
AttributeError                           Traceback (most recent call last)
<ipython-input-9-f2647540c462> in <module>()
----> 1 volt_fuel_economy = np.array([16.0, 21.]) * u.kWh / u._100km

~/conda/envs/36/lib/python3.6/site-packages/pint/registry.py in __getattr__(self, item)
    196     def __getattr__(self, item):
    197         if item[0] == '_':
--> 198             return super(BaseRegistry, self).__getattribute__(item)
    199         return self.Unit(item)
    200 

AttributeError: 'UnitRegistry' object has no attribute '_100km'
```

(note lines 197-198 in the traceback). Would you want to modify this behaviour, or use a different leading character for the sorts of things we've discussed in this issue?

**Comment by hgrecco** [comment]
I think looking for another character is a good idea. Any suggestions?

**Comment by jni** [comment]
I thought maybe there was some obscure additional non-alphanumeric character that would be a valid Python start of identifier, but it doesn't look like it:

https://en.wikibooks.org/wiki/Python_Beginner_to_Expert/Native_Types

If you're ok with dropping Python 2 support, non-ASCII characters could work, e.g. ø100km. (This is easy to type in macOS, alt-o, dunno about Win or Linux.) For Py2.7 one could also use the common ASCII replacement oe, (oe100km), though this looks even more obscure.

Incidentally, in the meantime, as a hack in the notebook I'm working on, I've used `l00km` (lowercase-L). Clearly this is not a solution I would recommend. 😂

**Comment by jni** [comment]
Come to think of it, the use proposed in this issue (`_` followed by numeric values) is sufficiently distinct from `_` followed by known units/constants that both cases could be accommodated without ambiguity. Would you welcome a PR to do this?

**Comment by hgrecco** [comment]
I agree. Submit a PR.

**Comment by jni** [comment]
@hgrecco sorry for the slow response, this is still in my backburner. But, this tweet made me think of this issue and I had to comment:

https://twitter.com/baym/status/976660962785857538/photo/1

Your comment ("I do not like guessing the user intention in this type of things.") seems very wise indeed! 😆😆😆

**Comment by hgrecco** [comment]
:-)

**Comment by jni** [comment]
@hgrecco is there a specific reason why this was closed? I apologise for letting it fall by the wayside, but I still am interested in this...
