### ISSUE TITLE
Abbreviated form for 'Becquerel' is incorrect

### ISSUE THREAD

**Issue by bloer** [hgrecco/pint#508]
If I do:

    In []: rate = 25*units['mBq/kg']

    In []: print(rate)
    25.0 milliBq / kilogram

    In []: print('{:P}'.format(rate))
    25.0 milliBq/kilogram
 
    In []: print('{:~P}'.format(rate))
    25.0 mbecquerel/kg

The abbreviated ('~') form is longer than the default form. As an aside, I think 'Becquerel' is supposed to always be capitalized.

**Comment by hgrecco** [comment]
Thanks, can you submit a PR?

**Comment by oqibidipo** [comment]
> I think 'Becquerel' is supposed to always be capitalized.

Nope. SI units are written in lowercase, except when used in a context where any noun would be capitalized. The symbol of a unit is capitalized when the name of the unit is derived from proper name.

**Comment by hgrecco** [comment]
I am closing this now based on @oqibidipo comments. Feel free to reopen if necessary.

**Comment by dopplershift** [comment]
The comment addressed the capitalization, but there's still the problem that the abbreviated form is using the full word `becquerel`.
