### ISSUE TITLE
speed of light 

### ISSUE THREAD

**Issue by jrmagers** [hgrecco/pint#514]
I'm trying to compute the speed of light from the permitivitty and permeability of free space:
```
epsilon0 = ureg('8.854187817e−12 F/m')  # permitivitty of free space
mu0 = ureg('4*pi*1e-7 H/m')             # permeability of free space
c = 1/np.sqrt(mu0*epsilon0)             # speed of light in free space
```
Unfortunately, this raises the following error:

`DimensionalityError: Cannot convert from 'meter / elementary_charge ** 0.5 / farad ** 0.5 / henry ** 0.5' ([length] / [current] ** 0.5 / [time] ** 1.5) to 'meter / second' ([length] / [time])`

**Comment by hgrecco** [comment]
Thanks your comment. There is something wrong with your `-` sign (elementary charge has nothing to do here).

Look this works just fine:
```python
>>> epsilon0 = ureg('8.854187817 * 10**-12 F/m')  # permitivitty of free space
>>> mu0 = ureg('4*pi*1e-7 H/m')             # permeability of free space
>>> 1/np.sqrt(mu0*epsilon0)    
<Quantity(299792458.0105029, 'meter / farad ** 0.5 / henry ** 0.5')>
```
or in different units
```python
>>> epsilon0 = ureg("8.85418782e-12 m**-3 kg**-1 s**4 A**2")
>>> mu0 = ureg("1.25663706e-6 m kg s**-2 A**-2")
>>> 1/np.sqrt(mu0*e0)
<Quantity(299792458.13099605, 'meter / second')>
```

But if I copy and paste your code:
```
>>> ureg('8.854187817e−12')
<Quantity(106.250253804, 'elementary_charge')>
```
But If I write it directly
```
>>> ureg("8.854187817e-12")
8.854187817e-12
```

Your minus sign is not the [standard one](http://www.fileformat.info/info/unicode/char/2d/index.htm) but rather the [Math one](http://www.fileformat.info/info/unicode/char/2212/index.htm):
```python
>>> ord('-') 
45
>>> ord('−') # your minus
8722
```

Feel free to submit a PR to include this in parsing

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen if unclear.
