### ISSUE TITLE
Clarification on pint and classes

### ISSUE THREAD

**Issue by jetheurer** [hgrecco/pint#517]
This is less of an issue and more of a misunderstanding of how to use Pint.

I've noticed the following behavior, given this class:

```
class Test(object):
    @ureg.wraps(None, (None, ureg.km), True)
    def __init__(self, a):
        self.a = a
```

When I create:

```
t = Test(3*ureg.m)
print(t.a)
```

I find that the attribute a is of type=float and has a value of 0.003.

Pint has done the unit conversion, but not propagated the units to the attribute.  As in this [StackOverFlow comment](https://stackoverflow.com/questions/39477522/unable-to-get-right-units-when-decorating-a-class-constructor-with-pint), I was expecting the units to stay on the attribute.  Is there pattern for using pint and classes?

**Comment by hgrecco** [comment]
The main idea behind `wraps` is to provide a safe and fast way to do units aware calculations within units unaware (and usually faster) fucntions. `wraps` works by giving **magnitudes** (not Quantities) to the body of the function/method  (It does not really matter if it is within a class or not). 

Therefore:
```python
class Test(object):
    @ureg.wraps(None, (None, ureg.km), True)
    def __init__(self, a):
        self.a = a

t = Test(3*ureg.m)
print(t.a)
```
gives the Pint Quantity Object `3*ureg.m` to the wrapped `__init__`
the decorator:
1. ignores the first argument (self) 
2. transforms the second from meter to km and returns it magnitude `0.003`
3. calls the original `__init__` with (self, `0.003`)

That is what you are seeing in `t.a`. I have never seen people stumbling here (but a lot of people stumble with `self`:-D ) But re-reading the docs, I do think the concept (stated above) is not clear enough. Maybe we can take the chance to clarify both. Would like to submit a PR?

By the way, I think that the docs are quite good but  can be better, both in content and organization. If anybody wants to champion this or start collection ideas, feel free to open another issue.

**Comment by hgrecco** [comment]
Closing this for the time being. Feel free to reopen.
