### ISSUE TITLE
Magnitude vs Value

### ISSUE THREAD

**Issue by MilesCranmer** [hgrecco/pint#525]
Hi,
I am part of a team that is using pint to develop a high-throughput stream processing library, "Bifrost": https://github.com/ledatelescope/bifrost.

In pint, does "magnitude" refer to "value" or "absolute value" in a Quantity object? If it is the latter, shouldn't the magnitude of a negative value be a positive?

E.g.,
``` python
>>> import pint
>>> u = pint.UnitRegistry()
>>> my_quantity = -1.0*u.m
>>> my_quantity.magnitude
-1.0
```

Cheers,
Miles

**Comment by hgrecco** [comment]
Hi there. Thanks for the question. We use the usual naming for a [Physical Quantity](https://en.wikipedia.org/wiki/Physical_quantity): 
> A physical quantity can be expressed as the combination of a magnitude expressed by a number – usually a real number – and a unit

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen if unclear.
