### ISSUE TITLE
Concentration Units

### ISSUE THREAD

**Issue by mmcdermott** [hgrecco/pint#526]
Hi, 

Is there any reason concentration units (in particular molarity, mol / L) is not included as a default unit in Pint? It is very easy to define on its own, but it seems well-used enough to warrant inclusion in the defaults list. If there are no objections to adding it, I'm happy to submit a PR doing so.

**Comment by hgrecco** [comment]
Great! Submit a PR and let's see how it plays out with the rest of the default unit definitions

**Comment by mmcdermott** [comment]
Awesome, ok, cool. PR is here. https://github.com/hgrecco/pint/pull/527

Great project, by the way, this is really useful.
