### ISSUE TITLE
String formatting behavior for full/abbreviated units backwards for temperatures

### ISSUE THREAD

**Issue by JJLuan** [hgrecco/pint#529]
Trying to get the abbreviated form of temperature units results in the full form, and getting the full form results in an abbreviated form. Also happens with delta_deg* units. 

```
>>> foo = ureg.Quantity(100,'degF')
>>> '{:~}'.format(foo)
'100 fahrenheit'
>>> '{:}'.format(foo)
'100 degF'
>>> bar = ureg.Quantity(100,'m')
>>> '{:}'.format(bar)
'100 meter'
>>> '{:~}'.format(bar)
'100 m'`
```

**Comment by hgrecco** [comment]
it is backwards in the registry.

**Comment by hgrecco** [comment]
This is fixed now. Thanks for reporting.
