### ISSUE TITLE
Using byte instead of bit as base

### ISSUE THREAD

**Issue by ratoaq2** [hgrecco/pint#530]
Given a quantity: `q = 2 * units.MB`

Is there an easy way to get number of bytes when casting it to int?
`int(q)` to return `2000000` instead of `16000000`

Is there something that I need to register or define in order to have this behavior?

**Comment by hgrecco** [comment]
You can convert to byte and get the magnitude:
```python
>>> q.to('byte').magnitude
2000000.0
```

or shorter:
```python
>>> q.m_as('byte')
2000000.0
```

**Comment by ratoaq2** [comment]
But there's no way that I could change the cast behavior? Without explicit using `Quantity` class api? 

I know that's possible to register new units. Is it possible to change the base unit reference?
