### ISSUE TITLE
ureg.check fails to check dimensionless quantity

### ISSUE THREAD

**Issue by AntoineGX** [hgrecco/pint#532]
Hello,

Thank you for this useful package.

I think there is an issue with the quantity type checking decorator. It doesn't raise any exception when the passed quantity is not dimensionless as expected.

Consider the following example:
```
import pint
ureg = pint.UnitRegistry()
@ureg.check(ureg(''))
def f(x):
    return 2*x
print(f(ureg.Quantity(1, '')))
print(f(ureg.Quantity(1, 'm')))
```
The first call to "f" is correct, the second one should raise an exception but it doesn't happen.

Thanks to take some time to analyze this issue.

**Comment by hgrecco** [comment]
Fixed. I will release a new version soon. Thanks for reporting
