### ISSUE TITLE
Pint unit notation violates ISO 80000:1

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint#536]
[ISO 80000-1](https://en.wikipedia.org/wiki/ISO_80000-1), section 7.2.2, notes:

> A solidus (/) shall not be followed by a multiplication sign or a division sign on the same line unless parentheses are inserted to avoid any ambiguity. In complicated cases, negative powers or a horizontal bar may be used.

However, pint gives:

```
In [5]: "{:~}".format(ureg.Quantity(1, ureg.W*ureg.m**-2*ureg.sr**-1*ureg.Hz**-1))
Out[5]: '1 W / Hz / m ** 2 / sr'
```

which explicitly violates the prohibition as outset in ISO 80000-1.  The correct notation would be:

W Hz⁻¹ m⁻² sr⁻¹

Or, if we must stick to ASCII:

W Hz**-1 m**-2 sr**-1

**Comment by hgrecco** [comment]
I like the idea of making Pint compliant with ISO 80000-1. Maybe we can add it first with a flag to avoid breaking existing code.

**Comment by lpdon** [comment]
Is there any way to replace all divisions and have multiplication in units such as the ASCII suggested representation? E.g:

kg * m * rad ^ -1 * s ^ -2 instead of kg * m / rad / s ** 2

**Comment by hgrecco** [comment]
Closing this for the time being. Feel free to reopen.
