### ISSUE TITLE
Parsing temperatures from string

### ISSUE THREAD

**Issue by zplizzi** [hgrecco/pint#537]
I often want to parse a unit from string, eg from a config file. Normally I would do this like `ureg("1 mm")` or `ureg.Quantity("1 mm")`, which works fine. However, this doesn't work when parsing temperatures. Running `ureg("1 degC")` returns an `OffsetUnitCalculusError`, as does using `Quantity()`. Is there a better way to do this?

**Comment by CalebBell** [comment]
Hello Zack,
When I need to parse temperatures, I try to keep everything in Kelvin. If I can't, I set ureg.autoconvert_offset_to_baseunit = True

The conversion will work fine with that flag set.

Sincerely,
Caleb

**Comment by hgrecco** [comment]
Indeed, this is done for consistency with the way Pint interprets Python code. For example:
```python
>>> 1 * ureg.degC
```

I am closing this now. Feel free to reopen if necessary.
