### ISSUE TITLE
wraps does not properly convert returned Quantity

### ISSUE THREAD

**Issue by mvernacc** [hgrecco/pint#539]
When a function returns a Quantity, the wraps decorator does not convert the units of the Quantity. Instead, it creates a new Quantity, whose magnitude is the returned Quantity.

Example:

```python
from pint import UnitRegistry
ureg = UnitRegistry()


@ureg.wraps(ureg.inch, ())
def f():
    return 1 * ureg.meter


x = f()
print 'repr(x) --> {:s}'.format(repr(x))
print 'repr(x.magnitude) --> {:s}'.format(repr(x.magnitude))

```

Expected output:

```
repr(x) --> <Quantity(39.37, 'inch')>
repr(x.magnitude) --> 39.37
```

Actual output:

```
repr(x) --> <Quantity(1 meter, 'inch')>
repr(x.magnitude) --> <Quantity(1, 'meter')>
```

I am using pint version 0.8.1 on windows 7.

**Comment by dopplershift** [comment]
I don't think you should be using `wraps` on a function that is capable of returning a `Quantity`, it's really meant for dropping and re-attaching units to functions that are unit-unaware:
```python
from pint import UnitRegistry
ureg = UnitRegistry()


@ureg.wraps(ureg.inch, ())
def f():
    return 39.97
```

**Comment by hgrecco** [comment]
@dopplershift is right. I think you are looking for a way to ensure the output is in inches. There is no such convenient function implemented in Pint. But feel free to describe your use case. I am closing this until then.
