### ISSUE TITLE
Stripping or removing units from a variable/numpy array

### ISSUE THREAD

**Issue by Geekly** [hgrecco/pint#544]
I'm sure this is possible, but I can't find the method to do so in the documentation. I'm working through some issues with the scale in matplotlib and need to convert my numpy arrays back to a dimensionless format to verify it's plotting what I think it is. What's the "correct" way of doing this, and could it be added to the documentation?

**Comment by dopplershift** [comment]
You want the `.magnitude` attribute. For more information, see [here](https://pint.readthedocs.io/en/0.7.2/tutorial.html).

**Comment by Geekly** [comment]
Thanks so much. I think I searched for "strip", "remove", and "dimensionless" without any luck.
