### ISSUE TITLE
units comparison

### ISSUE THREAD

**Issue by alexfeld** [hgrecco/pint#548]
After updating to 0.9dev the following no longer works
```(python)
Quantity.units == ureg.dimensionless
```

It appears the issue is that `Quantity.units` is returning a `UnitsContainer` whereas `ureg.dimensionless` is a `Quantity`. Thus the following works

```(python)
Quantity.units == ureg.dimensionless.units
```

I'm not sure if there is a better way to do this type of checking, and I'm not really sure if this is a bug from a coding perspective. However, it was a change in behavior from previous versions so I thought I should note it here.

**Comment by alexfeld** [comment]
It appears that the behavior change has affected all of the previous `UnitsContainer` behaviors. Before it was possible to multiply and divide `Quantity` instances by `UnitsContainer` instances. I assume that this was intentional but didn't see any mention of a change in the logs.

**Comment by alexfeld** [comment]
Digging further, it appears that there is inconsistent behavior between operating systems. Take the code
```(python)
import pint
ureg = pint.UnitRegistry()
ureg.meter
```
On Linux this returns `<Quantity(1, 'meter')>`, but on Windows this returns `<Unit('meter')>`. Unfortunately, since on the Linux version the `UnitsContainter` math operations don't appear to be working it does not appear that there is a way to write cross-platform unit comparisons.

**Comment by hgrecco** [comment]
There is nothing in pint that is OS dependent. I guess you are installing different versions. Can you check?

**Comment by alexfeld** [comment]
My apologies, you were right. I had an old version installed that I forgot to remove. This was the cause of all of the issues. This issue is resolved.

Alex
________________________________

**Comment by hgrecco** [comment]
Great!
