### ISSUE TITLE
How to deal with zero?

### ISSUE THREAD

**Issue by NOhs** [hgrecco/pint#556]
I often try to write code that works in both ways: with and without units. However, I always get in trouble when initializing a variable to 0.

e.g. 

```python
time_used = 0. * total_time.units

while time_used < total_time:
    time_used += step
    yield step

yield time_used - total_time
```

Here I explicitly have to use pint functionality or else it cannot add times to a unitless quantity. But now this doesn't work without units anymore, because float has no member `.units`.

**Comment by dopplershift** [comment]
It's not so much an issue with 0 as it is a challenge to do generic initialization. I'm not sure how I feel about it, but this should work:
```python
time_used = 0. * total_time
```

**Comment by NOhs** [comment]
Ah true. I didn't think about that.
