### ISSUE TITLE
setup_matplotlib produces an error

### ISSUE THREAD

**Issue by srgkoshelev** [hgrecco/pint#558]
I tried executing the example from [https://pint.readthedocs.io/en/latest/plotting.html](official website). The result was:
`Traceback (most recent call last):
  File "D:\Personal\Python repo\ODH-analysis\test.py", line 7, in <module>
    ureg.setup_matplotlib(True)
  File "D:\Python34\lib\site-packages\pint\registry.py", line 203, in __getattr__
    return self.Unit(item)
  File "D:\Python34\lib\site-packages\pint\unit.py", line 45, in __new__
    inst._units = inst._REGISTRY.parse_units(units)._units
  File "D:\Python34\lib\site-packages\pint\registry.py", line 767, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "D:\Python34\lib\site-packages\pint\registry.py", line 877, in _parse_units
    return super(NonMultiplicativeRegistry, self)._parse_units(input_string, as_delta)
  File "D:\Python34\lib\site-packages\pint\registry.py", line 792, in _parse_units
    cname = self.get_name(name)
  File "D:\Python34\lib\site-packages\pint\registry.py", line 475, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'setup_matplotlib' is not defined in the unit registry`

Does this feature still exist and is supported?

I'm running Python 3.4, matplotlib 2.1.0, pint 0.8.1

**Comment by dopplershift** [comment]
That function is only available in the next release of pint. To have it work today, you'd need to install from git master.

**Comment by srgkoshelev** [comment]
I see. Thank you for the prompt response!

**Comment by hgrecco** [comment]
I think is time for a new release, what do you think?

**Comment by dopplershift** [comment]
Sounds good to me!

**Comment by hgrecco** [comment]
I will fix some of the opened issues and go ahead

**Comment by dneise** [comment]
Hello, I ran into the same issue today. Any news on this?

**Comment by jondoesntgit** [comment]
Did a fresh install with pip. Still having this issue.

**Comment by dopplershift** [comment]
New release hasn't happened yet, so I wouldn't expect it to work on anything but an install from git.

**Comment by jklymak** [comment]
At some point you might move to the "latest" docs not pointing at the dev version.  This confused me for a while, as I expected the docs to be for a stable version.
