### ISSUE TITLE
Cannot print arrays with ureg.default_format set to a non-empty string. 

### ISSUE THREAD

**Issue by ethan92429** [hgrecco/pint#559]
Here is the simplest way to recreate the problem with raw pint:
```
import pint
u=pint.UnitRegistry()
u.default_format = '.4g'
hi = [1,2,3,4,5]*u.m
print(hi)
```
It generates the following error:
```
    print(hi)
  File "/Users/ethankeller/.local/lib/python3.6/site-packages/pint/quantity.py", line 140, in __str__
    return format(self)
  File "/Users/ethankeller/.local/lib/python3.6/site-packages/pint/quantity.py", line 186, in __format__
    mstr = format(obj.magnitude, mspec).replace('\n', '')
TypeError: unsupported format string passed to numpy.ndarray.__format__
```
So it appears the [builtin format function can't take the '.4g' format string](https://stackoverflow.com/questions/24170519/python-typeerror-non-empty-format-string-passed-to-object-format) to use with an ndarray. This means that anytime the ureg.default_format field is set, you can't print ndarray Quantity classes.

**Comment by hgrecco** [comment]
This is not implemented yet, but I would be happy to merge a PR. I think the right way would be to use numpy infrastructure for this maybe via a context manager as the one described [here](https://stackoverflow.com/questions/2891790/how-to-pretty-printing-a-numpy-array-without-scientific-notation-and-with-given)

**Comment by jules-ch** [comment]
Encountered the same issue. I'm going to submit a PR with  [numpy.printoptions](https://docs.scipy.org/doc/numpy/reference/generated/numpy.printoptions.html) to handle Quantity formatting with array.
