### ISSUE TITLE
UnicodeDecodeError loading default units under non-ASCII path (Python 2 only)

### ISSUE THREAD

**Issue by deanishe** [hgrecco/pint#560]
If the path to `pint` contains non-ASCII, loading the default units fails with decoding error (`'ascii' codec can't decode byte XXX`) under Python 2.

**NOTE: I can work around this issue by explicitly passing the Unicode path to `default_en.txt` to `UnitRegistry` on instantiation.**

## Versions

- macOS 10.12.6
- pint 0.8.1
- python 2.7.14
- setuptools 36.6.0

## Example

```sh
in ~/Desktop/fööbär
❯ ll
total 4.0K
drwxr-xr-x  8 XXX staff  272 Oct 17 20:34 Pint-0.8.1-py2.7.egg-info
drwxr-xr-x 39 XXX staff 1.3K Oct 17 20:35 pint
-rw-r--r--  1 XXX staff   61 Oct 17 20:34 test.py
in ~/Desktop/fööbär
❯ cat test.py
import pint

print(pint.__file__)

ur = pint.UnitRegistry()

in ~/Desktop/fööbär
❯ python3 test.py
/Users/XXX/Desktop/fööbär/pint/__init__.py
⧗ 2s in ~/Desktop/fööbär
❯ python2 test.py
/Users/XXX/Desktop/fööbär/pint/__init__.pyc
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    ur = pint.UnitRegistry()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 75, in __call__
    obj._after_init()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 1269, in _after_init
    super(SystemRegistry, self)._after_init()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 175, in _after_init
    self.load_definitions('default_en.txt', True)
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 368, in load_definitions
    raise ValueError('While opening {0}\n{1}'.format(file, msg))
ValueError: While opening default_en.txt
'ascii' codec can't decode byte 0xcc in position 21: ordinal not in range(128)
in ~/Desktop/fööbär
✖ 1 ❯
```

After commenting out the `except Exception` block in `pint.registry.BaseRegistry.load_definitions()`, I get the following error from `setuptools`:

```python
/Users/XXX/Desktop/fööbär/pint/__init__.pyc
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    ur = pint.UnitRegistry()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 75, in __call__
    obj._after_init()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 1269, in _after_init
    super(SystemRegistry, self)._after_init()
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 175, in _after_init
    self.load_definitions('default_en.txt', True)
  File "/Users/XXX/Desktop/fööbär/pint/registry.py", line 356, in load_definitions
    with closing(pkg_resources.resource_stream(__name__, file)) as fp:
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1227, in resource_stream
    self, resource_name
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1592, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1543, in _fn
    return os.path.join(base, *resource_name.split('/'))
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 21: ordinal not in range(128)
```

I [ran into the issue](https://www.alfredforum.com/topic/10872-ascii-codec-cant-decode/) with [an Alfred workflow](https://github.com/deanishe/alfred-convert) based on `pint`, as they can be installed in arbitrary directories.

**Comment by hgrecco** [comment]
Thanks for the detailed report. This is the type of things that are really annoying about the unicode/str story.

I was not able to find online a clean, cross-platform way to deal with this. A fix might be wrapping the `file` argument in the `string_types` if branch of `load_definitions` with `compat.u` (which makes a unicode object in Python2). If you submit a Pull Request, we can test it with travis and see how it goes.

**Comment by deanishe** [comment]
> This is the type of things that are really annoying about the unicode/str story.

I swear an awful lot of these issues would disappear if Python (2 and 3) defaulted to UTF-8 instead of ASCII.

> which makes a unicode object in Python2

It already is a Unicode object thanks to `unicode_literals`. I also tried using `b'default_en.txt'`, but `setuptools` throws an exception either way.

It looks like it would require a fair bit of refactoring to get `pint` to work with non-ASCII paths in Python 2. In addition to `pkg_resources`, the parser also throws a `UnicodeDecodeError` when it reaches an `@import` statement, as the file contents have already been decoded by that point.

I'm not sure it's worth addressing the issue, tbh. It should only ever arise when someone has bundled `pint` instead of installing it, and in that case, they must also know where `default_en.txt` is in relation to their own code, so they can explicitly pass a Unicode path to `UnitRegistry()`.

It's documented now in this issue. I reckon that's enough.
