### ISSUE TITLE
Allow a number to be passed to UnitRegistry.parse_expression

### ISSUE THREAD

**Issue by KOLANICH** [hgrecco/pint#564]
For now if you pass a number it raises.
I guess it should check if the quantity passed a number.

**Comment by hgrecco** [comment]
This works just fine
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.parse_expression('1')
1
```

**Comment by KOLANICH** [comment]
It's not a number, its a ```str```

**Comment by ikicic** [comment]
A partial workaround that works for floats and Quantities is `ureg.parse_expression(str(x))`. Does not work for Decimal though.

**Comment by KOLANICH** [comment]
>A partial workaround that works for floats and Quantities is ureg.parse_expression(str(x))

It's not a workaround. The real workaround is to craft an own function wrapping that one and use it.

**Comment by ikicic** [comment]
Of course, this was the quickest thing that covered my case.

I first thought it was more complicated, but on the second read, it seems like adding the following two lines to the top of `UnitRegistry.parse_expression` is enough:
```py
def parse_expression(self, input_string, ...):
    """..."""
    if isinstance(input_string, (float, int, Decimal)):
        return input_string
    ...
```
https://github.com/hgrecco/pint/blob/master/pint/registry.py#L878

If that's it, I can make a pull request.

**Comment by hgrecco** [comment]
My problem with this fix is that it opens the door to fix any possible type problem. `parse_expression` argument is called `input_string`. Why are you calling `parse_expression` if you have something which is not like that?

**Comment by KOLANICH** [comment]
OK
