### ISSUE TITLE
Eliminate evil from pint.definitions

### ISSUE THREAD

**Issue by KOLANICH** [hgrecco/pint#565]
```eval``` is evil when working with untrusted data.

**Comment by hgrecco** [comment]
Please elaborate which part of the codebase you propose to modify and how.

**Comment by KOLANICH** [comment]
https://github.com/hgrecco/pint/blob/c5925bfdab09c75a26bb70cd29fb3d34eed56a5f/pint/definitions.py#L89
https://github.com/hgrecco/pint/blob/c5925bfdab09c75a26bb70cd29fb3d34eed56a5f/pint/definitions.py#L111

**Comment by hgrecco** [comment]
These functions are called when defining new units therefore it is unlikely that they will be called with untrusted data. However, feel free to submit a PR to fix it.

**Comment by KOLANICH** [comment]
>These functions are called when defining new units therefore it is unlikely that they will be called with untrusted data.

In fact I do exactly this in my code. I load currency exchange ratios from a remote website and create a pint units for each currency.

**Comment by hgrecco** [comment]
Just curious but why not using any of the packages designed for that purpose such as 
[this](https://pypi.python.org/pypi/money/1.3.0) or [this](http://alexprengere.github.io/currencyconverter/)?

**Comment by KOLANICH** [comment]
Just have thought about ```pint``` first. I have a JSON file like
```js
{
"supplierName":
{
"products":
[
{
"cost": "€250",
"amount":"10 mg",
"concentration":"0.01±0.01"
},
{
"cost": "$250",
"amount":"1 mg",
"concentration":"0.02±0.01"
},
{
"cost": "25000 RUR",
"amount":"1 mg",
"concentration":"0.015±0.005"
}
....
]
}
}

So
1 I already use pint. So I thought about just defining a unit first. The only principal problem is that I can't define a unit with ```Decimal``` scale.
2 I have to parse the prices from strings.  It seems that ```money``` doesn't have this feature.
3 ```currency_converter``` uses the data by ECB. I live in Russia, so I have to use the data by CBRF.

**Comment by hgrecco** [comment]
I see. Then I would say, let's fix the decimal first and move with the rest afterwards.

**Comment by KOLANICH** [comment]
I wonder when this will be fixed. Recently pybitmessage users were hacked because of some dev have used `eval`, so I guess that any eval on data should be considered a backdoor.

**Comment by hgrecco** [comment]
This was fixed some time ago.

**Comment by KOLANICH** [comment]
Thank you.
