### ISSUE TITLE
Dimensionless stuff should be a pint object, not a number

### ISSUE THREAD

**Issue by KOLANICH** [hgrecco/pint#570]
```python
ureg("1")
```
returns an ```int``` instead of pint object.
It should return a pint object in order to make it possible to call pint-specific methods on it like ```plus_minus```

**Comment by hgrecco** [comment]
This is like this by design. The idea is to use the simplest object possible when parsing.

If you want a Pint Quantity, be explicit. For example:
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg.Quantity("1")
<Quantity(1, 'dimensionless')>
>>> ureg.Quantity("1 meter")
<Quantity(1, 'meter')>
```
or 
```python
>>> ureg("1") * ureg.dimensionless
<Quantity(1, 'dimensionless')>
>>> ureg("1 meter") * ureg.dimensionless
<Quantity(1, 'meter')>
```
