### ISSUE TITLE
Add U+2126 into the registry for ohm

### ISSUE THREAD

**Issue by KOLANICH** [hgrecco/pint#573]

**Comment by KOLANICH** [comment]
Why was it closed as "completed" if it is not implemented?

```
import pint

ureg = pint.UnitRegistry()
ureg.parse_expression("1 \u2126") # UndefinedUnitError: 'Ω' is not defined in the unit registry
```

**Comment by hgrecco** [comment]
We are going to open an specific issue for everything unicode related. There are 3 to 5 issues out there which are all have the same root.
