### ISSUE TITLE
How to add an alias to an existing default units definition

### ISSUE THREAD

**Issue by gmyers18** [hgrecco/pint#580]
The current definition for gallon from [default_en.txt](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L369) is:

`gallon = 8 liquid_pint = gal = liquid_gallon = US_liquid_gallon`

Is there any way to programmatically add 'galUS' as an additional alias for gallon, short of explicitly restating the default definition, e.g.:

`ureg.define(gallon = 8 liquid_pint = gal = liquid_gallon = US_liquid_gallon = galUS)`

This seems to work, but doesn't necessarily feel like the most optimal approach.

**Comment by DavidLutton** [comment]
You were adding a adding extra alias.
This shows adding galUS made of units of US_liquid_gallon
```
import pint

ureg = pint.UnitRegistry()
Q_ = ureg.Quantity

print(Q_(1, 'US_liquid_gallon').to('pint'))
```
8.0 pint
```
ureg.define('galUS = US_liquid_gallon')  # add alias
print(Q_(1, 'galUS').to('pint'))
```
8.0 pint

**Comment by DavidLutton** [comment]
@gmyers18 does this work for you?

**Comment by gmyers18** [comment]
Yes, this works.  I was more curious if there was a programmatic approach for adding an additional alias to an **existing** canonical name, rather than defining a new canonical name, which is what I believe your suggestion does.  At the end of the day I admit that these behave identically, I was simply trying to avoid an additional conical name if there was another way.
