### ISSUE TITLE
Unit registries and wrapper error is obscure

### ISSUE THREAD

**Issue by srgkoshelev** [hgrecco/pint#581]
Hi, guys!

I have encountered an error when (mistakenly) tried to convert quantities from one registry into another. The issue is that the error message for the wrapper (that performed the conversion) is rather obscure and it takes time to figure out what is wrong. The error message mentions the issue about conversion that doesn't make much sense:

```
(error found for {0}, {1})'.format(args_as_uc[ndx][0], new_values[ndx]))
ValueError: A wrapped function using strict=True requires quantity for all arguments with not None units. (error found for meter / second, 1 meter / second)
```
I had to play around a bit until I figured it out. I don't know if it is possible to make it more clear but it seems like a good idea.

Attached files:
test2 - definitions and creation of the first registry
test3 - shows the difference between using the imported registry and a new, locally created registry. Imported registry works perfectly, while new registry (obviously) creates an error.

[test2.py.txt](https://github.com/hgrecco/pint/files/1450742/test2.py.txt)
[test3.py.txt](https://github.com/hgrecco/pint/files/1450743/test3.py.txt)

**Comment by hgrecco** [comment]
It seems to me that the problem is that you are mixing registries. As described in the docs, you should use only 1 registry in your application. Try that and let me know.

**Comment by srgkoshelev** [comment]
Yes, the problem is indeed because I mixed registries. I was trying to point out that it is rather hard to understand that from the error message. It would be nice to clarify the error message, if possible.

Thank you for your help!

**Comment by hgrecco** [comment]
You are right. It actually gives a useful message outside the wrapper
```python
>>> 3 * ureg.km > 3 * ureg2.meter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hernan/Documents/code/pint/pint/quantity.py", line 1123, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
  File "/Users/hernan/Documents/code/pint/pint/quantity.py", line 1110, in compare
    raise ValueError('Cannot compare Quantity and {0}'.format(type(other)))
ValueError: Cannot compare Quantity and <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
```
We should try to put this inside the wrapper

**Comment by hgrecco** [comment]
Linking this to #1753
