### ISSUE TITLE
Bug with Q_ and liters

### ISSUE THREAD

**Issue by srgkoshelev** [hgrecco/pint#582]
Apparently, there's a bug in creating quantity using `Q_ = ureg.Quantity function`:
```python
print (Q_(3, ureg('kg/L')))
>>>3 gram / meter ** 3
print (3*ureg('kg/L'))
>>>3000000.0 gram / meter ** 3
```
with first one being incorrect. Or I completely misunderstand the difference of the two approaches.

P.S. I am working on a project using your units so I might have to spam you with more bugs/suggestions =)

**Comment by hgrecco** [comment]
It works fine for me. 
```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> Q_ = ureg.Quantity
>>> print (Q_(3, ureg('kg/L')))
3 kilogram / liter
>>> print (3*ureg('kg/L'))
3.0 kilogram / liter
```

Can you provide more details about your installation?

**Comment by srgkoshelev** [comment]
Hmm, that is weird.
I have
Python 3.4.3
Pint 0.8.1
Windows 7 x64
don't know what else might be of interest.

I doublechecked the issue, it seems that the issue arises when `ureg.auto_reduce_dimensions = True`.

**Comment by hgrecco** [comment]
You should not call `Q_(<number>, ureg(<string>)`
ureg(<string>) gives you a Quantity and that parameter should be a parameter

**Comment by srgkoshelev** [comment]
Oh, I see. I guess I didn't understand the docs well enough. Sorry about that.

Any chance it could throw an exception or something? It is easy to miss and just get a completely different result from what is expected.

Thank you for your help!

**Comment by hgrecco** [comment]
No problem and don't feel sorry. On the contrary, is good to find this things that should be improved.

**Comment by hgrecco** [comment]
This is now fixed.
