### ISSUE TITLE
Formatting {:%}

### ISSUE THREAD

**Issue by srgkoshelev** [hgrecco/pint#592]
I am still using 0.8.1 so this might have been fixed by now.

It seems that pint doesn't handle `'{:%}'.format(Q_(0.2, ureg.dimensionless))` producing `20% dimensionless`.

I have changed formatting.py, after line 208:
from
```
def format_unit(unit, spec, **kwspec):
    if not unit:
        return 'dimensionless'
```
to
```
def format_unit(unit, spec, **kwspec):
    if not unit:
        if spec == '%':
            return ''
        else:
            return 'dimensionless'
```
which seems to do the job resulting in `20%` without the `dimensionless` part.

As I am using an older version and I am not sure this is the best solution I decided to open the issue as compared to initiating pull request.

Thank you.

**Comment by hgrecco** [comment]
This was fixed. Feel free to reopen if needed.
