### ISSUE TITLE
problem with operator.itruediv and numpy

### ISSUE THREAD

**Issue by bloer** [hgrecco/pint#607]
Sorry if this has been reported already (I'm on 0.8.1),  but I'm getting surprising behavior using operator functions with ndarrays. 

    >>> x = np.ndarray(10, dtype=float)
    >>> x
    array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])
    >>> x = np.arange(10, dtype=float)
    >>> x
    array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
    >>> x /= ureg.second
    >>> x
    <Quantity([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.], '1 / second')>
    >>> 
    >>> x = np.arange(10, dtype=float)
    >>> operator.itruediv(x,ureg.second)
    <Quantity([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.], '1 / second')>
    >>> x
    array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
    >>> 

I get the correct behavior using the literal `/=` operator, but `operator.itruediv` acts like `operator.truediv`.  I didn't think it was even possible to make these two actions behave differently. 

I notice that `ndarray.__itruediv__` (and `ifloordiv`) are defined incorrectly in the documentation: 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.__itruediv__.html .  So maybe this is a numpy bug?  However ndarrays perform as expected with arguments other than Quantities and units.

**Comment by hgrecco** [comment]
I think this does not apply anymore. Feel free to reopen if needed.
