### ISSUE TITLE
extended formatting types give wrong precision

### ISSUE THREAD

**Issue by bendavis78** [hgrecco/pint#609]
For example:
    
    >>> n = Q_(math.pi, 'km')
    >>> print('{:.2f}'.format(n))
    3.14 kilometer
    >>> print('{:.2P}'.format(n))
    3.1 kilometer
    >>> print('{:.2~}'.format(n))
    3.1 km

I would expect the `~` and `P` formatting type to have similar behavior to `f`.

**Comment by jules-ch** [comment]
`~` and `P` are just formatter spec that change how units is formatted.
Magnitude formatting uses traditional python formatting specs.

Just add an `f` to your spec for Fixed-point notation.

https://docs.python.org/3/library/string.html#format-specification-mini-language

```python
>>> print('{:~.2f}'.format(n))
3.14 km
```
