### ISSUE TITLE
Incomplete documentation for the L, Lx and H formatters

### ISSUE THREAD

**Issue by bonderado** [hgrecco/pint#611]
Using pint 0.8.1with IPython 5.5.0 + Python 3.6.4 in a Debian Buster installation.

Thanks for this marvelous module, I am very satisfied with it.
I just found out that the 'L', 'Lx' and 'H' formatters can be combined with the 'f' formatter.
This is a nice feature that remains 'hidden' in that it does not appear in the documentation:
in this way it could be changed/removed without notice. If it were mentioned explicitly in the documentation, it would be easier to find it (or make it easy to deprecate if the  formatter behavior is modified in incompatible ways).

Examples:

import pint
u = pint.UnitRegistry() 
q = 10.23456*u.m/u.s
print(f"{q}", f"{q:5.3}", f"{q:5.3f}",
    f"{q:5.3L}", f"{q:5.3Lx}", f"{q:~5.3fL}", f"{q:5.3Lx}",
    f"{q:5.3H}", f"{q:5.3fH}", f"{q:~5.3fH}",
    sep='\n')

output:
10.23456 meter / second
10.2 meter / second
10.235 meter / second
10.2\ \frac{\mathrm{meter}}{\mathrm{second}}
\SI[]{ 10.2}{\meter\per\second}
10.235\ \frac{\mathrm{m}}{\mathrm{s}}
\SI[]{ 10.2}{\meter\per\second}
10.2 meter/second
10.235 meter/second
10.235 m/s

P.S: to combine  'Lx' with '~' does not make sense, but if done the tilde is silently ignored (7th line of output).

**Comment by hgrecco** [comment]
Link to #1757
