### ISSUE TITLE
round(quantity) behaves differently on Py2/Py3

### ISSUE THREAD

**Issue by natezb** [hgrecco/pint#612]
Python 3 introduces the `__round__` special method, while Python 2 first calls `__float__`, then rounds that float. This fact, coupled with the current implementation of `Quantity.__round__`, creates an inconsistency when rounding dimensionless quantities. In Python 2:

    >>> q = Q_('(1 s) / (10 ms)')
    >>> q
    <Quantity(0.1, 'second / nanosecond'>
    >>> float(q)
    100.0
    >>> round(q)
    100.0

In Python 3:

    >>> q = Q_('(1 s) / (10 ms)')
    >>> q
    <Quantity(0.1, 'second / nanosecond'>
    >>> float(q)
    100.0
    >>> round(q)
    <Quantity(0.0, 'second / millisecond')>

It's arguably nice that the Python 3 version will return a Quantity, but this results in some odd and confusing results:

    >>> int(round(q))
    0
    >>> int(q)
    100

One obvious solution is to have `__round__` return `round(float(self))` for dimensionless quantities, though this would be inconsistent with non-dimensionless values since it doesn't return a `Quantity`.

This also raises the question of whether the current implementation is desirable for non-dimensionless quantities, since it may give a very different value depending on what the quantity's current units are. I suppose the alternative would be to convert to base units, then round (optionally converting back), or to disallow rounding non-dimensionless quantities altogether.

**Comment by hgrecco** [comment]
We are moving to a Python 3 only package. If rounding still a problem, please open another Python 3 only issue.
