### ISSUE TITLE
Need bigger warning for unsupported scipy functions

### ISSUE THREAD

**Issue by flutefreak7** [hgrecco/pint#620]
I was running an analysis that used scipy.special.erf and scipy.special.erfc and got bit by pint today.  It appears that the magnitude of the quantity was silently used by the function without proper dimensionality reduction.

While I understand that this is simply a byproduct of how pint works, I wish there had been a warning that this could occur.

For supported numpy ufunc's like exp the dimensionality reduction to dimensionless magnitude is performed.

 I'd rather either a safe option where Quantities are not usable by unsupported numerical libraries, or behavior that always resolves dimensionless magnitudes when cast to a float, or a big monster warning in the pint documentation that when sending quantities into unsupported functions, there's no telling what magnitude you are sending without explicitly doing `erf(x.m_as(''))` for example.

**Comment by dopplershift** [comment]
Unfortunately, that's a problem with how numpy works: `np.array(pint_array)` silently strips units. I'm not aware of any way pint can even issue a warning in this case.

**Comment by kanhua** [comment]
I think you can issues some warning for this. My way of doing is printing some warnings then a ufunc tries to access only the magnitude part of the quantity.
I added two lines of ```print()```  in ```__getattr__()``` of ```_Quantity``` class in ```quantity.py```, see below:

```python
def __getattr__(self, item):
    # Attributes starting with `__array_` are common attributes of NumPy ndarray.
    # They are requested by numpy functions.
    if item.startswith('__array_'):
        if isinstance(self._magnitude, ndarray):
            print("Warning: the units are stripped")
            return getattr(self._magnitude, item)
        else:
            # If an `__array_` attributes is requested but the magnitude is not an ndarray,
            # we convert the magnitude to a numpy ndarray.
            print("Warning: the units of this non-ndarray are stripped")
            self._magnitude = _to_magnitude(self._magnitude, force_ndarray=True)
            return getattr(self._magnitude, item)
```

You should then get some warning message printed when an unsupported ufunc is called. You may want to replace them with proper ```Warning``` class if you wish.

**Comment by flutefreak7** [comment]
Definitely simple to do a from warnings import warn then use warn() instead of print(). Warnings get shown differently in some terminals or in Jupyter Notebook for example (where they are rendered in red). Additionally warnings can be ignored programmatically if the user wishes as opposed to print statements. Finally, just for completeness, a warning is better than using logging.warn which I'm pretty sure would go unseen if the user isn't using logging.

**Comment by kanhua** [comment]
You are absolutely right. Using print() is not a very proper fix. You can replace these statement with of any level of warning if you wish, or even throw an exception. I only intend to show that the exact places of code that you can add the warning to address your need.
I guess the author of Pint may have his own reason to let the process of unit-stripping go silent. I am not quite sure whether most of users would appreciate this warning, and that's why I hesitate to  submit a proper version of pull request of this.

**Comment by hgrecco** [comment]
Submit a PR, please but also add a way to silent warnings.

Regarding your the question about unit-stripping with numpy, I have actually been looking for a way to avoid this for a while. We even talk to the numpy people about this but there was (at the time, not sure now) no way to do this properly as discussed in #232  and others. The solution would be to derive a pint class from ndarray.

**Comment by dopplershift** [comment]
I think `__array_ufunc__` (fully added in numpy 1.13) might make some better behavior possible now. There are also active discussions about adding `__array_concatenate__` and an interface for declaring duck-typing arrays. (See https://mail.python.org/pipermail/numpy-discussion/2018-March/077849.html)
