### ISSUE TITLE
Defining unit with "pi" leading to errors

### ISSUE THREAD

**Issue by agerlach** [hgrecco/pint#624]
I am trying to specify offset units for representing and converting from True and Magnetic North, given a magnetic declination, i.e.  `deg_Mag = deg_True - declination`. In doing so, I think I may have come across a bug when using `pi` in a unit definition. Below I create two unit definitions, one using `pi` and the other using the numerical value for pi. Both definitions are able to convert from deg_Mag to deg_True, but when going from deg_True to deg_Mag, the unit defined using `pi` is off by a scale factor of 1/pi. FYI, I am using v0.8.1 of pint.

```python
import math
import pint
ureg = pint.UnitRegistry(autoconvert_offset_to_baseunit = True)

ureg.define('rad_True = radian')
ureg.define('deg_True = degree')

declination = (10. * ureg.degree).to(ureg.radian)

unitstr_degMag = f"deg_Mag = pi / 180 * radian; offset: {declination.magnitude} = degmag;"
unitstr_degMag2 = f"deg_Mag2 = {math.pi} / 180 * radian; offset: {declination.magnitude} = degmag2;"

ureg.define(unitstr_degMag)
ureg.define(unitstr_degMag2)

print((0 * ureg.deg_Mag).to(ureg.deg_True)) # Expect 10 deg_True, prints 10.0 deg_True
print((0 * ureg.deg_True).to(ureg.deg_Mag)) # Expect -10 deg_Mag, prints -31.41592653589793 deg_Mag

print((0 * ureg.deg_Mag2).to(ureg.deg_True)) # Expect 10 deg_True, prints 10.0 deg_True
print((0 * ureg.deg_True).to(ureg.deg_Mag2))  # Expect -10 deg_Mag2, prints -10.0 deg_Mag2
```

**Comment by agerlach** [comment]
I also just tested this using the `master` branch and get the same behavior.

**Comment by hgrecco** [comment]
This is is fixed in the current master.
