### ISSUE TITLE
wraps gives strange errors when using wrong units

### ISSUE THREAD

**Issue by virtuald** [hgrecco/pint#635]
Was trying this:
```
@units.wraps(None, ('length', 'mass'))
def test(l, m):
    print(l, m)
    
test(5*units.inch, 5*units.kg)
```

Got this error:

```
pint/registry.py in _is_multiplicative(self, u)
    906         l = self._dedup_candidates(self.parse_unit_name(u))
    907         try:
--> 908             u = l[0][1]
    909             return self._units[u].is_multiplicative
    910         except KeyError:

IndexError: tuple index out of range
```

Should this check for IndexError in addition to KeyError?

**Comment by virtuald** [comment]
Also, it occurs to me that length/mass probably aren't valid units. Seems like wraps() should preparse its args to ensure that they're valid?

**Comment by hgrecco** [comment]
`wraps` requires a unit. If you want to check for dimensionality, use `check` (see [here](http://pint.readthedocs.io/en/latest/wrapping.html#checking-dimensionality)) and remember to specify a valid dimension name (in your case `[length]` and `[mass]`, notice the square brackets)

**Comment by hgrecco** [comment]
Linking to #1753
