### ISSUE TITLE
Display Issue in Jupyter Output Cells ?

### ISSUE THREAD

**Issue by rebcabin** [hgrecco/pint#639]
I can only approximate Jupyter in this little markdown box. Please see this Jupyter notebook for a minimal sample: https://www.dropbox.com/s/deumlmc7b54zepn/PintDisplayIssueInOutputCells.ipynb?dl=0 

Scalar quantities display fine:

    Q(42,'m/s^2')
>     42 meter/second2

Vector quantities don't display properly in output cells:

    Q([42], 'm/s^2')
>     \[\begin{pmatrix}42\end{pmatrix} meter/second2\]

Other things that produce LATEX output do display properly in output cells, however, so this may not be a broken Jupyter install on my box:

```
from sympy import Symbol, Function
from sympy import init_printing
init_printing()
​
q     = Function('q')
theta = Function('theta')
t     = Symbol('t')
​
q(t)**2 + theta(t)**2
```
>     q2(t)+θ2(t)

Pint output will display properly in markdown cells, using the notebook extension Python Markdown (https://goo.gl/2JS57x). I have the following expression in this markdown cell, and Python Markdown interprets it into MathJax {‍{Q([42], 'm/s^2'}‍}

>     (42) metersecond2

**Comment by hgrecco** [comment]
I think this has been fixed long ago.
