### ISSUE TITLE
Adding apples and oranges

### ISSUE THREAD

**Issue by andreacortis** [hgrecco/pint#640]
Hello,
I would like to add apples and oranges :)
I know how to add apples to each other and how to add oranges to each other 

```
from pint import UnitRegistry
ureg = UnitRegistry()
quantity = ureg.Quantity

ureg.define('apple = [apple]')
ureg.define('orange = [orange]')

assert quantity(3, 'apple') + quantity(4, 'apple') == quantity(7, 'apple') 
assert quantity(3, 'orange') + quantity(4, 'orange') == quantity(7, 'orange')
```

I also know how to enforce the correct behavior of not mixing dimensionalities.

```
from pint import DimensionalityError
try:
    quantity(3, 'apple') + quantity(4, 'orange') 
except DimensionalityError as e:
    print('Cannot add {0} and {1}'.format(e.__dict__['dim1'], e.__dict__['dim2']))

```

At this point I have two questions:

1. how I can define a units `fruit`, such that:

ureg.define('fruit = [fruit]')
assert quantity(3, 'apple') + quantity(4, 'orange') == quantity(7, 'fruit') 

2. is there a way to enforce the type of the magnitude, such that for the dimensionality 
  `orange`, `apple`, and `fruit` it is always of type `int` (or any other arbitrary type for that matter)?

Thanks!

p.s. Fantastic package!!!

**Comment by hgrecco** [comment]
This is not possible with Pint as it breaks the distinction between units and dimensions.
