### ISSUE TITLE
Incorrect answers with numpy ufuncs and the out keyword

### ISSUE THREAD

**Issue by ngoldbaum** [hgrecco/pint#644]
Consider the following example:

```python
import numpy as np
from pint import UnitRegistry

u = UnitRegistry()

a = [1, 2, 3]*u.g
b = [1, 2, 3]*u.kg
out = np.zeros(3)

print(np.add(a, b, out=out))
```

With `Pint 0.8.1`, I get `[2. 4. 6.]` as the output of this script, when I would expect either `[1001. 1002. 1003.]`, `[1.001 1.002 1.003]` or similar with units attached. `Pint` returns the correct answer when `out` is not specified.

**Comment by hgrecco** [comment]
Can you check without the out keyword?

**Comment by ngoldbaum** [comment]
This script:

```python
import numpy as np
from pint import UnitRegistry

u = UnitRegistry()

a = [1, 2, 3]*u.g
b = [1, 2, 3]*u.kg

print(np.add(a, b))
```

prints `[1001. 2002. 3003.] gram`, so indeed it has to do with using `out`.

**Comment by hgrecco** [comment]
I wonder if when #630 is merged, this issue will be fixed.

**Comment by ngoldbaum** [comment]
I get the same wrong answer with numpy 1.12.1 installed.

**Comment by jthielen** [comment]
Just to note it down so it doesn't get forgotten, this issue (along with most other issues with optional arguments in NumPy ufuncs) remains after the refactor in #905.

**Comment by hgrecco** [comment]
This works in 
Numpy: 1.20.1
Pint: 0.17
