### ISSUE TITLE
Pandas support using new API

### ISSUE THREAD

**Issue by wisp3rwind** [hgrecco/pint#645]
The most recent pandas release (0.23) introduces [extension types](http://pandas.pydata.org/pandas-docs/version/0.23/extending.html#extending-extension-types) which I believe provide a natural way to integrate pint types into pandas dataframes on a per row/column basis. Is this a feature that could be merged here (assuming no breakage when older/no pandas is installed)?
If so, I'd be interested in researching that possibility further and maybe even implementing it myself. As a disclaimer, I've only started using pint quite recently and am not very proficient with pandas either and I'm not sure when I really get the time to do this. In any case, if someone else beats me to coding the feature, that'd be perfect, too :)

Related issues (which I _haven't_ read fully):
- #401 
- https://github.com/pandas-dev/pandas/issues/10349,
- an early user of the new API is [cyberpandas](https://github.com/ContinuumIO/cyberpandas)

**Comment by hgrecco** [comment]
I would be very interested to support this. Maybe you can describe here how you envision this. But I would really like to see this happening.

**Comment by bilderbuchi** [comment]
@hgrecco is this closed as wontfix, works already, or refer to pint-pandas?
