### ISSUE TITLE
Allow conversion to dimension without specifying unit?

### ISSUE THREAD

**Issue by benmehlman** [hgrecco/pint#647]
I had written my own unit system when I found Pint.  Pint is much more complete so I decided to switch to Pint.  But there is one thing my system does which Pint does not seem to do, which I would like to suggest:

In my own system, I too have a concept of "context" for conversion between dimensions, unlike Pint.. so in my system, if you define a transformation between [count] and [mass]:  

1 * each = 200 * g

..then, you can do conversions between those dimensions. or any dimension for which the system can find a path:

Quantity(1, 'each').to('pound')
Quantity(1, 'each').to('gram')

The result will be "0.440925 pound", and "200 gram", same as with Pint.

But in my system you can also do conversions specifying only the dimension:

Quantity(1, 'each').to_dimension('mass')

The result will be "200 gram".

In this case, my system uses the unit in which the transformation was expressed.  If the transformation had been expressed in ounces, the result would be returned as ounces.

In my application, the inter-dimension transformations are entered by humans and the units in which these humans choose to express the transformation may have semantic significance, so I would like to preserve these units in the output.   Because I have thousands of potential transformations, these are stored in a database.. it is not possible to know them ahead of time.

If you find this to be a useful feature that you would merge, but don't have time to look at it yourself, let me know and I'll take a crack at implementing it.

Thanks for the great work!

**Comment by hgrecco** [comment]
It is an interesting idea that indeed is not very far from Pint context. I think it would be nice to have it.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
