### ISSUE TITLE
Turn off latex rendering in jupyter notebooks

### ISSUE THREAD

**Issue by nbren12** [hgrecco/pint#654]
I have been wrapping some pretty large numpy arrays with pint lately. Unfortunately, viewing these arrays with mathjax rendering ends up crashing my web browser. I searched the docs for a way to turn off the default rendering, but I could not find anything. Is there an easy way to do this?

**Comment by hgrecco** [comment]
No but we should add it. Please propose an API so we can discuss it an implement it.

**Comment by nbren12** [comment]
I am not sure what would fit best with pint at the moment. Maybe something like `pint.set_jupyter_output_style('string')`?

**Comment by nbren12** [comment]
That sounds good to me. I don't quite understand what __repr_html__ do
though. Does jupyter/ipython look automatically look for those methods when
rendering output?

**Comment by jondoesntgit** [comment]
I know that matplotlib has an rc params setting. Perhaps we can implement something like that. Pint could also read from a config file on load...

**Comment by hgrecco** [comment]
Moving the discussion to #765
