### ISSUE TITLE
A function to convert to engineering notation

### ISSUE THREAD

**Issue by jondoesntgit** [hgrecco/pint#656]
Are there plans to convert units to engineering notation?

```python
>>> from pint import _DEFAULT_REGISTRY
>>> ureg = _DEFAULT_REGISTRY
>>> Q_ = ureg.Quantity
>>> force = Q_('85 newtons')
>>> area = Q_('12 in^2')
>>>
>>> pressure = force / area
>>> pressure
<Quantity(7.083333333333333, 'newton / inch ** 2')>
>>> pressure.to('newtons', engineering_prefix=True)
<Quantity(10.979188625043918, 'kilopascal')>
```
What I'd like is a function that will return the unit with an automatically-defined prefix (kilo, mega, giga, micro, etc...). It makes it much easier for plotting purposes.

**Comment by hgrecco** [comment]
This has been discussed but never implemented. There was a function to find the optimal prefix though (i.e. the one with the most convenient number)

**Comment by hgrecco** [comment]
Look at: `to_compact`

**Comment by jondoesntgit** [comment]
`to_compact` is exactly what I'm looking for!

Let me put it in the docs
