### ISSUE TITLE
Printing mu for micro in LaTeX formatted output

### ISSUE THREAD

**Issue by sigvaldm** [hgrecco/pint#662]
How about having 

```
s = ureg['microampere']
'{:~L}'.format(s.u)
```

output `'\\mathrm{{\\mu}A}'`? I.e. with `{\\mu}` instead of `u`? Very nice software by the way!

**Comment by hgrecco** [comment]
We do not have an API right now to specify LaTeX code. We do have a way to specify a pretty printed version as shown [here](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L18).

I see two ways:
1. We hardcode certain transformations into the LaTeX printer
2. We provide a way to specify in the the definition a LaTeX version.

**Comment by sigvaldm** [comment]
Sorry for the delay. Since I am not very familiar with the inner workings of Pint (nor have I made my own units definition file) I find it a bit hard to give a qualified answer. Given you already have a nice definition file with a syntax for specifying pretty printed prefixes (I suppose that's the API you refer to) alternative 2 seems the most clean for me. It avoids special cases.

**Comment by bonderado** [comment]
In my opinion, the only reason to use **um** in a LaTeX document is if we are citing verbatim someone who did that: if we do a calculation with pint it is unlikely that we are citing anyone and the micro prefix would be the only special case ever,  so option 1 is not that bad.

If we really want to be flexible, though, I would propose that **\\mu** should be the default, also for use in plot labels, sincethe Lx formatted quantities are not supported by matplotlib and matlab.

**Comment by hgrecco** [comment]
I am closing this until we have a concrete solution. One way would be to have a pluggable output layer. If anyone wants to champion this, please open a new PR.
