### ISSUE TITLE
Use 'µm' as abbreviation of micrometer?

### ISSUE THREAD

**Issue by ericpre** [hgrecco/pint#666]
Is there a reason to use `'um'` and not `'µm'`, considering that the last one is the correct abbreviation according to the SI units? 

```python
import pint
ureg = pint.UnitRegistry()

q = ureg('µm')
print('{~}'.format(a))
```
will output '1 um'.

**Comment by jondoesntgit** [comment]
Three things:

The 'mu' symbol may not work in all environments. It should be fine in more modern systems where unicode is ubiquitous, but we probably can't make that guarantee for older systems.

Secondly:

Using 'u' as a substitue for 'micro' is pretty standard among the engineers here at Stanford, so it isn't that unusual...

Thirdly:

Pint coded in such a way as to give the end user a lot of control. If you want to change the 'u' to a 'µ', edit [this line](https://github.com/hgrecco/pint/blob/8edd45f35599071fac19f784619cc1871baa6c7e/pint/default_en.txt#L18) in your `default_en.txt` file.

**Comment by ericpre** [comment]
Thanks for the quick reply and the hint.
This would work on my local install but it wan't when it is used in another library and particularly for unit testing?

**Comment by francisco-dlp** [comment]
In this case wouldn't it suffice to replace
```
micro- = 1e-6  = u- = µ-
```
with
```
micro- = 1e-6  = µ- = u-
``` 
to make µ the default abbreviation? I understand why ``u`` was a better choice before Python 3 was widespread and all OSs had good UTF support, but why keeping this constraint today?

**Comment by jondoesntgit** [comment]
Perhaps legacy compatibility?

AFAIK (from discussions on #577 and #652), @hgrecco and others want to keep backwards compatibility for 2.7, the packages that have pint as a dependency, etc...

**Comment by ericpre** [comment]
I just had a look at the [string formatting section](http://pint.readthedocs.io/en/latest/tutorial.html#string-formatting) of the pint tutorial and tested the following in python 2.7:

```python
from pint import UnitRegistry
ureg = UnitRegistry()
accel = 1.3 * ureg['meter/second**2']

from __future__ import unicode_literals # as documented in the tutorial
print('The pretty representation is {:P}'.format(accel))
```
output:
```
The pretty representation is 1.3 meter/second²
```

And the following works also fine:
```python
a = 1.0 * ureg(u'Å')
print(u'The pretty representation is {:~P}'.format(a))
```
output:
```
The pretty representation is 1.2 Å
```
It should be fine with python 2.7.

**Comment by jondoesntgit** [comment]
Thinking about my own usage, I usually would input a unit with `Quantity('1 us')`, and want the pretty print to be with a micro symbol.

One pitfall that I anticipate is supplying the units to LaTeX in Matplotlib, where the micro symbol would need to be escaped. But there's usually a fair amount of monkey patching that goes into plotting anyway...

**Comment by ericpre** [comment]
Using unicode with Latex in matplotlib figure is a different story, but it should be possible according to the [documentation](https://matplotlib.org/2.2.2/tutorials/text/usetex.html?highlight=usetex#usetex-with-unicode).

**Comment by KOLANICH** [comment]
I also propose to add `GREEK SMALL LETTER MU` (`μ`) into this prefix.

**Comment by josselex** [comment]
@KOLANICH 
I also support this.
I just started to use pint and expected this to work.
Should be no problem now with python 3 deployed everywhere.

**Comment by KOLANICH** [comment]
https://github.com/hgrecco/pint/pull/627/files
