### ISSUE TITLE
NumPy 1.15 FutureWarning from deprecated non-tuple indexing

### ISSUE THREAD

**Issue by jthielen** [hgrecco/pint#669]
Since I've upgraded to NumPy v1.15, I've been getting the following warning from https://github.com/numpy/numpy/pull/9686 when I've been running tests in MetPy with Pint v0.8.1:

```
  .../pint/quantity.py:1281: FutureWarning: Using a non-tuple sequence for
multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of
`arr[seq]`. In the future this will be interpreted as an array index,
`arr[np.array(seq)]`, which will result either in an error or a different
result.
    value = self._magnitude[key]
```

If you would like, I could put in PR to fix this by wrapping the non-tuple sequences with `tuple()`, but I'm not sure what you would like to have done with the Travis builds so that NumPy 1.15 is used. Thanks!

**Comment by hgrecco** [comment]
I think this should be fixed now, right?

**Comment by jthielen** [comment]
Yes, I'm not sure what ended up fixing it, but I no longer get this warning on either NumPy 1.15 or the most recent 1.17.
