### ISSUE TITLE
sth to the power of a dimensionless quantity is not a quantity anymore

### ISSUE THREAD

**Issue by cod3licious** [hgrecco/pint#670]
pint version 0.8.1

a dimensionless quantity `q` does not stay a quantity when you compute `2**q` or `3**q` etc. even though `np.exp(q)`, i.e., `2.71**q` works. (For regular, i.e. non-dimensionless quantities you get an error like `DimensionalityError: Cannot convert from 'hour' to 'dimensionless'`.)

```python
# creating a dimensionless quantity
In [1]: ureg = pint.UnitRegistry(auto_reduce_dimensions=True, autoconvert_offset_to_baseunit=True)
In [2]: q = ureg.parse_expression("") 
# it shows up like a quantity
In [3]: q
Out[3]: <Quantity(1, 'dimensionless')>
# when applying some transformation it still stays a quantity
In [4]: np.cos(q)
Out[4]: <Quantity(0.5403023058681398, 'dimensionless')>
# but not when you compute the power of sth
In [5]: 2**q
Out[5]: 2
# however exp, i.e. 2.71...**q works...
In [6]: np.exp(q)
Out[6]: <Quantity(2.718281828459045, 'dimensionless')>
```

**Comment by dopplershift** [comment]
I think in general it’s just a pain to use the library if the type of object you get from a calculation changes depending on the operation. It means you have to start doing manual casting or `hasattr(obj, ‘units’)` all over your code.

**Comment by jondoesntgit** [comment]
Maybe, but I can't think of an example of when you would expect anything other than a float from an exponential.

**Comment by dopplershift** [comment]
I don’t want math on my `Quantity` instances to be polymorphic across the library. Full stop. If I put a `Quantity` into a calculation, I don’t want that type to change. We have a way in `pint` to make a `float`: `Quantity(f, ‘dimensionless’)`.

I come at this not from a unit purity point of view, but as someone who is implementing a large library of unit-aware calculations. Changing types when you don’t have to is an interoptibility nightmare; it’s doubly terrible when you try to teach using the library to scientists who are barely comfortable writing code.

Given that `pint` supports `cos`, `sin`, etc. and `exp` that would nominally return “floats” and do so using `’dimensionless’`, the sensible option IMO is to do the same from `x**Quantity` (i.e. `__rpow__`).

**Comment by dimapu** [comment]
@jondoesntgit Exponent or cosine etc. of a dimensional quantity does not make sense mathematically ([wikipedia](https://en.wikipedia.org/wiki/Dimensional_analysis#Polynomials_and_transcendental_functions.)).

**Comment by jondoesntgit** [comment]
Is the reason for the discrepancy between `2**q` and `np.exp(q)` that the `**` operator is `math.exp`? I notice that the math library for trig returns floats, not `Quantity`

    >>>import math
    >>>math.cos(q)
    0.5403023058681398

**Comment by dalito** [comment]
I agree with @dopplershift that exponentiation or trigonomic functions should not change the type. If the user passes in a dimensionless Quantity pint should return a dimensionless Quantity.

**Comment by cod3licious** [comment]
Background & why for me it is important to keep a dimensionless Quantity a Quantity: I have a bunch of variables, some have units, others are dimensionless. Then I apply several functions like `log`, `sqrt`, `exp` and `2**` to all these variables (to generate new features that I use for predicting something later on) and I check which operations are legal by catching the `DimensionalityError`. However, if the return values are sometimes a Quantity and sometimes a regular float, I can't run the same code on dimensionless and non-dimensionless Quantities, which would make the code a lot messier.

**Comment by jondoesntgit** [comment]
From the docs:

> If you want pint to automatically perform dimensional reduction when producing new quantities, the UnitRegistry accepts a parameter auto_reduce_dimensions. Dimensional reduction can be slow, so auto-reducing is disabled by default.

Do we want to include an option where dimensionless quantities can be converted into floats automatically?

**Comment by cpascual** [comment]
> Do we want to include an option where dimensionless quantities can be converted into floats automatically?

Personally, I prefer APIs to be simple and not depend on many configurations (especially not changing return types). And, considering that ["Explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/), I would prefer to require the user of pint to cast explicitly if she wants.

**Comment by hgrecco** [comment]
I agree with @cpascual here. I like this to work without having to check what is `q3`

```python
>>> q3 = q2 * q1
>>> q3.units
```

**Comment by awa5114** [comment]
I'm noticing that `np.log10` on a dimensionless quantity also returns an `np.float64` object. Also wondering whether this issue in `pint-pandas` is not related https://github.com/hgrecco/pint-pandas/issues/25
