### ISSUE TITLE
Quantity multiplied with numpy boolean doesn't raise error

### ISSUE THREAD

**Issue by znicholls** [hgrecco/pint#673]
```python
>>> import numpy as np
>>> import pint
>>> ureg = pint.UnitRegistry()
# this behaves as expected
>>> True * ureg.meter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zebedeenicholls/Documents/AGCEC/Misc/pint/pint/unit.py", line 150, in __mul__
    return self._REGISTRY.Quantity(other, self._units)
  File "/Users/zebedeenicholls/Documents/AGCEC/Misc/pint/pint/quantity.py", line 102, in __new__
    inst._magnitude = _to_magnitude(value, inst.force_ndarray)
  File "/Users/zebedeenicholls/Documents/AGCEC/Misc/pint/pint/compat/__init__.py", line 79, in _to_magnitude
    raise TypeError('Invalid magnitude for Quantity: {0!r}'.format(value))
TypeError: Invalid magnitude for Quantity: True
# this does not
>>> np.bool_(True) * ureg.meter
<Quantity(1, 'meter')>
```

surely we want the behaviour to be the same for both?

**Comment by cpascual** [comment]
> I would agree on making a change that make the same output for both

+1

> (I prefer the first, i.e. raising a TypeError)

I am not necessarily disagreeing, but... why that preference?

While I agreein that booleans with units make little sense, pint in general does not care what you use for magnitude when constructing a Quantity  (e.g. it allows `"somestring" * ureg.meter`)... so treating booleans differently may be seen as an inconsistency.

**Comment by znicholls** [comment]
> pint in general does not care what you use for magnitude when constructing a Quantity

this also seems surprising no?

**Comment by cpascual** [comment]
Yes, it is surprising, but IMHO it is a feature of pint: it allows you to create and operate with quantities whose magnitude is of an arbitrary type (it essentially allows [Duck Typing](https://en.wikipedia.org/wiki/Duck_typing)). 

For example, one can create a pint quantity using a [Decimal](https://docs.python.org/2/library/decimal.html) instance for the magnitude, and pint behaves as expected out-of-the-box:

```python
import pint
from decimal import Decimal
ureg = pint.UnitRegistry()
a = Decimal('0.1') * ureg.meter
b = Decimal('0.3') * ureg.meter
assert not bool(a + a + a - b ) 
```

**Comment by hgrecco** [comment]
As an addtional example:
```python
>>> np.bool(True) * ureg.meter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/grecco/anaconda3/lib/python3.6/site-packages/pint/unit.py", line 156, in __mul__
    return self._REGISTRY.Quantity(other, self._units)
  File "/Users/grecco/anaconda3/lib/python3.6/site-packages/pint/quantity.py", line 101, in __new__
    inst._magnitude = _to_magnitude(value, inst.force_ndarray)
  File "/Users/grecco/anaconda3/lib/python3.6/site-packages/pint/compat/__init__.py", line 84, in _to_magnitude
    raise TypeError('Invalid magnitude for Quantity: {0!r}'.format(value))
TypeError: Invalid magnitude for Quantity: True
```

I am closing this as I do not see any clean way to do this.
