### ISSUE TITLE
github HEAD: wrong units when working with bits

### ISSUE THREAD

**Issue by dschien** [hgrecco/pint#675]
Hi

I observe the following behaviour with the code at commit 8edd45f35599071fac19f784619cc1871baa6c7e
```
from model import ureg, Q_
e = Q_('1 J / bit') * Q_('1 bit')
e.units
```
I would expect the output to be `J`, but the result is `J/bit`.

With the release 0.8.1, the value of  `e.units` is `gram meter2/second2` - which is an energy unit. 

BTW - is there any way to ask pint to simply this (e.g. to `Joules` or `watt_hours`) without explicit conversion ? In other words, I don't want to call `e.to(ureg.watt_hours)`.

Many thanks

**Comment by hgrecco** [comment]
Let's go step by step. I cannot reproduce the bug. I still get `J`. Can you double check?

**Comment by dschien** [comment]
Just did the following:

```
python3 -m venv pint
source pint/bin/activate
python
```
then in the console
```python
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry(auto_reduce_dimensions=True)
>>> Q_ = ureg.Quantity
>>> e = Q_('1 J / bit') * Q_('1 bit')
>>> e.units
<Unit('joule / bit')>
```

**Comment by hgrecco** [comment]
Can you use `auto_reduce_dimensions=False`?

**Comment by dschien** [comment]
Then it works.

**Comment by hgrecco** [comment]
I think I have identified the proble.
```python
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry(auto_reduce_dimensions=True)
>>> Q_ = ureg.Quantity
>>> e = Q_('1 bit')
>>> e.units
<Unit('dimensionless')>
>>> e.units._units
<UnitsContainer({})>
```

`bit` is being simplified. Maybe we do need to fix #674

**Comment by hgrecco** [comment]
or implemente the role (https://github.com/hgrecco/pint/issues/505)

**Comment by hgrecco** [comment]
Thanks for reporting. If you can explain in more detail the other questions I would be happy to provide some feedback later.
