### ISSUE TITLE
Feature request: possibility to set a default format with magnitude only

### ISSUE THREAD

**Issue by chernals** [hgrecco/pint#687]
Is there already, or would it be possible to implement a custom format to allow string conversion to provide the magnitude only?

**Comment by jondoesntgit** [comment]
I’ll often just put the “.m” to get the magnitude out.

Along this vein, is there a way to limit the precision of the output ?

**Comment by cpascual** [comment]
> ... a custom format to allow string conversion to provide the magnitude only?

```python
import pint
ureg = pint.UnitRegistry() 
q = 1.23456 * ureg.volt
print('the quantity magnitude is {0.m:}'.format(q) )
```

>... a way to limit the precision of the output ?

```python
print('the quantity magnitude is {0.m:.2f}'.format(q) )
```

**Comment by jondoesntgit** [comment]
I'm so used to dumping things out in a iPython notebook. I forgot about string formatting.

For completeness:

```python
print(f'the quantity magnitude is {q.m:.2f}')
print('the quantity magnitude is %.2f' % q.m)
```

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if needed.
