### ISSUE TITLE
Pandas interface issues

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint#689]
Non blocking issues raised in https://github.com/hgrecco/pint/pull/684 can be discussed here.

1. It's cumbersome to create dataframes:

````
torque = PintArray(Q_([1, 2, 2, 3], "lbf ft"))

df = pd.DataFrame({"torque": torque})
````

It would be nice to have something like:

````
torque = Q_([1, 2, 2, 3], "lbf ft")

df = pd.DataFrame({"torque": torque})
````

**Comment by rgieseke** [comment]
For a simple example with a Series it's not easily visible that a unit is used.

```python
import pandas as pd
import pint
from pint.pandas_interface import PintArray

ureg = pint.UnitRegistry()
Q_ = ureg.Quantity

a = Q_([1, 20, 30], "m")

s = pd.Series(PintArray(a))
df = pd.DataFrame(PintArray(a))
```

Series s:
```
0     1
1    20
2    30
dtype: pint
```

DataFrame df:
```
          0
0   1 meter
1  20 meter
2  30 meter
```
Maybe there is a way to implement this for a Series object too.

**Comment by andrewgsavage** [comment]
I've hit the same issue before, creating a df in that way doesn't work - you've not got a PintArray stored there. Using pd.DataFrame({0:PintArray(a)}) does work. I found the same issue when using cyberpandas which I'd been using as an example pandas ExtensionArray implementation.


```
    import pandas as pd
    import pint
    from pint.pandas_interface import PintArray
    
    ureg = pint.UnitRegistry()
    Q_ = ureg.Quantity
    
    a = Q_([1, 20, 30], "m")
    
    s = pd.Series(PintArray(a))
    df = pd.DataFrame(PintArray(a))
    print(s)

    0     1
    1    20
    2    30
    dtype: pint
    
    print(df)

              0
    0   1 meter
    1  20 meter
    2  30 meter    

    df.dtypes

    0    object
    dtype: object

    df_=pd.DataFrame({0:PintArray(a)})
    print(df_)

        0
    0   1
    1  20
    2  30

    df_.dtypes

    0    pint
    dtype: object

**Comment by rgieseke** [comment]
Thanks! It wouldn't really make sense to have units in every cell anyhow ....

**Comment by hgrecco** [comment]
Should I close this?

**Comment by rgieseke** [comment]
Thanks for the follow-up! What's the status of the integration, wasn't there a separate repo/project? The link in the docs is 404:

https://pint.readthedocs.io/en/0.9/pandas.rst

**Comment by hgrecco** [comment]
You can see the docs here: 

https://pint.readthedocs.io/en/latest/pint-pandas.html

**Comment by rgieseke** [comment]
Just tested and is kind of still an issue, but that really belongs to `pintpandas` now, so it could be closed i'd say.

**Comment by jules-ch** [comment]
Closing it belongs to pint-pandas.
Is it still an issue & is it tracked in pint-pandas ?
