### ISSUE TITLE
Timedeltas Quantities not acting as expected

### ISSUE THREAD

**Issue by dalymople** [hgrecco/pint#690]
I have been playing around with this package (which is fantastic by the way!) and I have stumbled across some issues with the support for datetime.timedetas. Some of the issues appear to be due to the underlying implementation of the datetime.timedelta objects rather than Pint, but the way they are handled does seem a bit strange.

Expanding on the example in issue #608 

```
>>> ureg = UnitRegistry()
>>> a = datetime.timedelta(seconds=4)
>>> t = ureg.Quantity(a, units='seconds')
>>> t
<Quantity(0:00:04, 'second')>
```

Looks good, lets try some unit conversions.

```
>>> t.to('minutes')
<Quantity(0:00:00.066667, 'minute')>
>>> t.to('hours')
<Quantity(0:00:00.001111, 'hour')>
>>> t.to('days')
<Quantity(0:00:00.000046, 'day')>
```

All good, try some more.

```
>>> t.to('milliseconds')
<Quantity(1:06:40, 'millisecond')>
>>> t.to('microseconds')
<Quantity(46 days, 7:06:40, 'microsecond')>
```

That looks strange, but seems to be simply due to how it is displayed.

The bigger issue to do with functionality is the following;

```
>>> d = ureg.Quantity(10, 'meters')
>>> t = ureg.Quantity(datetime.timedelta(seconds=4), units='seconds')
>>> d/t
TypeError: unsupported operand type(s) for /: 'int' and 'datetime.timedelta'
```

That is not completely unexpected, the exception is raised by the underlying datetime.timedelta  implementation rather than Pint. However it doesn't feel right... the only way around this seems to be not to use a datetime.timedelta like so;

```
>>> t = ureg.Quantity(a.total_seconds(), 'seconds')
>>> d/t
<Quantity(2.5, 'meter / second')>
```

Would a pull request addressing these issues be accepted? I have never submitted a PR before but I would be happy to give it a go if there is support for these changes?

**Comment by jondoesntgit** [comment]
What API would you suggest? Show some sample output perhaps?

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if an API is suggested.
