### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by onewhaleid** [hgrecco/pint#691]
I just started using `pint` yesterday, and I love the thought that has gone into it.

I tried to convert from a combination of unusual units:

    >>> # Convert water head to pressure
    >>> (1 * ureg['mm.H2O']).to('Pa')
    <Quantity(9.80665, 'pascal')>

It works exactly the way I hoped, and is easy to read.

Thank you for your efforts in designing and building this package!

**Comment by hgrecco** [comment]
Thanks for coming by and leaving this message.
