### ISSUE TITLE
Automatically simplify units after multiplication/division

### ISSUE THREAD

**Issue by kvoutyras** [hgrecco/pint#692]
Is there a way to automatically get a unit as a product or division of two different units?
E.g.:
`import pint`
`ureg = pint.UnitRegistry()`

`x=1 x=1 *ureg.milliamps`
`y=2* ureg.watt / ureg.ampere`

`print (x*y)` returns : 
`2.0 milliampere * watt / ampere`

=================

Can I somehow get  2.0 milliwatt  (or 0.002 watt) without having to explicitly type: `(x*y).to('mW')` ?

**Comment by jondoesntgit** [comment]
```python
ureg = pint.UnitRegistry(auto_reduce_units=True)
```

Dimensional reduction can be slow, so if you're having performance issues, you may want to go back to manually running `.to('mW')`

**Comment by dalito** [comment]
With the example from above, auto_reduce_units=True does not give the desired result: Watt is "lost". The unit of the result is "kg⋅m**2⋅s**−3".

So do we want/need a 4th option to just cancel down units the are present multiple times? That may also be fast.

**Comment by jondoesntgit** [comment]
@andrewgsavage see #676.

**Comment by steelman** [comment]
My suggestion, based on my minimal experience with pint, is to enable programmers to define such preferred units for each project. For example, I am using pint to calculate some dimensions of a simple building, amounts of materials required to build it and costs. I know I will enter all* my lengths in centimeters areas in square meters and volumes in cubic meters. At the end I will multiply the amounts by unit prices to get amounts of money. Setting some defaults for this project would make the code more readable (it is more readable than the spreadsheet I used to use).
 
Different default_format settings for different units/dimensionalities  would be great too (#748).

**Comment by hgrecco** [comment]
Lets explore these two ideas:
1. auto reduce same units: 
what would be the API? Do we also auto reduce units with the same dimensionality? What is the cost?
2. default units 
Do we allow the use to define defaults units per dimensionality? How this plays out with Systems?

**Comment by hgrecco** [comment]
I am closing this now. If at some point there is more interest, please suggest and API/PR
