### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#693]
Not that pandas is supported I think that is time for a new release.

TODO

- [ ] add new people to AUTHORS (@znicholls , @andrewgsavage ) and others that have contributed
- [ ] add changes to the CHANGES
- [ ] check that all (supported) Python version are tested in `.travis.yml` with their corresponding latest version of numpy (as available in anaconda)
- [ ] check that all (supported) Python version are tested in `.travis-full.yml` with their corresponding latest version of numpy (as available in anaconda)
- [ ] check and improve docs

Other ideas?

**Comment by znicholls** [comment]
@hgrecco if you know what version we'll go to I can update https://github.com/pandas-dev/pandas/pull/22582

**Comment by znicholls** [comment]
- [ ]  remove comment at top of `pint/pint_array.py`

**Comment by jondoesntgit** [comment]
I'd love to finish up the logarithmic units, but I've got too many other things on my plate right now.

**Comment by hgrecco** [comment]
We can aim to have log units in 1.0 if nobody can make it for 0.9

**Comment by hgrecco** [comment]
We need some volunteers to go through the issues and:

- close those which are resolved
- close those which are not longer relevant
- classify those still valid with a label
- classify those still open with a milestone (I would 0.9 for nasty bugs, 0.9.1 for minor enhancements, 1.0 for large enhancements)

And something similar with the PR

**Comment by jondoesntgit** [comment]
Have you thought about using something like waffle.io for this?

**Comment by hgrecco** [comment]
Let's give it a try

**Comment by jondoesntgit** [comment]
Shucks. It says I have to be a collaborator to move cards around in Waffle.

**Comment by etp404** [comment]
Do you know when version 0.9 is likely to be released? Pandas support is going to be a bit of a game-changer...

**Comment by hgrecco** [comment]
@etp404 I was hoping to do it a few weeks ago but the fact that the extension API is not stable in pandas raised some concerns. There is an option that we could do if everybody in here agrees: we release 0.9 with experimental Pandas support linked to a specific pandas commit (as it is now) and then we release 0.9.1 as soon as Pandas stabilizes the API

**Comment by hgrecco** [comment]
I have released 0.9 ! Hopefully next releases will come more often!

**Comment by hgrecco** [comment]
I hope I have credited everybody correctly. If not, please let me know and I will fix it.
