### ISSUE TITLE
Dimensionality math operation / Problem with offset (ie degC)

### ISSUE THREAD

**Issue by ChristianTremblay** [hgrecco/pint#698]
Let say we have this : 
```
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity

one  = Q_(1)
ten = Q_(10)
two = 2
one_degree_celsius = 1 * ureg.degC
```
I could understand that adding `two` to `one_degree_celsius` may lead to inconsistencies. So I can accept that it will not work.

But if trying to multiply.... this should work
```
ten_degrees_celsius = 10 * ureg.degC
#or 
ten_degrees_celsius = 10 * one_degree_celsius
#or
ten_degrees_celsius = ten * one_degree_celsius

# given multiplying should be ok with dimensionless units.
```

Now if I divide 

```
one_degree_celsius / one_degree_celsius
```
I should obtain `1` dimensionless....
or only 1...
And this works with Kelvin... so I guess there is a bug when offset are added to units

**Comment by sethrj** [comment]
I ran into a similar error. See [the docs on temperature units](https://pint.readthedocs.io/en/0.9/nonmult.html): you should be using `delta_degC` instead of `degC` when manipulating temperature differences and ratios.

**Comment by ChristianTremblay** [comment]
Thanks for pointing that out. Can't tell if I didn't see that or if they recently took care of this but this explains the behviour.

I'll close the issue.
