### ISSUE TITLE
Import breaks with pandas<=0.22.0 installed

### ISSUE THREAD

**Issue by hartelt** [hgrecco/pint#701]
When trying to import pint as pulled from here in an enviroment with pandas 0.22.0 installed, I get an `AttributeError`. This seems to be caused by the attribute pandas.core.arrays not present there.

*Expected Behaviour*: pint detects incompatible version of pandas and deactivates pandas extension.
*Actual Behaviour*: pint cannot be imported, import breaks with `AttributeError`.

```
>>> import pandas as pd
>>> pd.__version__
'0.22.0'
>>> hasattr(pd.core, "arrays")
False
>>> import pint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hartelt/repos/pint/pint/__init__.py", line 18, in <module>
    from .formatting import formatter
  File "/home/hartelt/repos/pint/pint/formatting.py", line 16, in <module>
    from .babel_names import _babel_units, _babel_lengths
  File "/home/hartelt/repos/pint/pint/babel_names.py", line 10, in <module>
    from pint.compat import HAS_PROPER_BABEL
  File "/home/hartelt/repos/pint/pint/compat/__init__.py", line 130, in <module>
    HAS_PROPER_PANDAS = hasattr(pd.core.arrays.base, "ExtensionOpsMixin")
AttributeError: module 'pandas.core' has no attribute 'arrays'
```

As far as I see, the appropriate fix would be refining the detection of the `HAS_PROPER_PANDAS` flag in `pint/compat/__init__.py`, for example by changing the breaking line to: 
```
HAS_PROPER_PANDAS = hasattr(pd.core, "arrays") and hasattr(pd.core.arrays.base, "ExtensionOpsMixin")
```
I'll fork and try this soon. Please confirm that this would be the correct usage of the `HAS_PROPER_PANDAS` flag, since I don't have much experience with the pint code.

**Comment by znicholls** [comment]
that looks like a good fix to me!
