### ISSUE TITLE
Pint for Atomic Units

### ISSUE THREAD

**Issue by dgasmith** [hgrecco/pint#707]
I am looking into using Pint for Atomic Units. These are natural units for quantum mechanical computations (see the wiki [here](https://en.wikipedia.org/wiki/Atomic_units) if curious) and base primarily on a single unit, Hartree, which can be converted to length/energy/etc. Accomplishing energy, mass, length, and frequency can be completed by the following:
```
c1 = pint.Context("energy_frequency")
c1.add_transformation("[energy]", "[frequency]", lambda ureg, val: val / ureg.plancks_constant)
c1.add_transformation("[frequency]", "[energy]", lambda ureg, val: val * ureg.plancks_constant)

c2 = pint.Context("substance_relation")
c2.add_transformation("[energy]", "[energy] / [substance]", lambda ureg, val: val * ureg.N_A)
c2.add_transformation("[energy] / [substance]", "[energy]", lambda ureg, val: val / ureg.N_A)

...
```

Issue 1: With the above, it seems that if each transformation pair must be a different context the conversions are not triggered. I didn't quite understand why this would be the case, but is there any harm in it?

Issue 2: We need quite precise conversions and have slight issues with uncertainties. A good example is going from `Hartree to Hz` which would require `(Hartree -> joule) * Plancks constant = Hz` as `Plancks constant` is defined in `joule * second`; however, we also have the NIST CODATA for `Hartree -> Hz` directly which would be better to perform as the uncertainties for that transform are in general smaller. Is it possible to register all known NIST conversions so that they are applied first before going through generic routes?

**Comment by hgrecco** [comment]
(The energy frequency/context is already there under the name spectroscopy. See [here](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L271) )

1) You can define multiple transformation in one context or do them in multiple contexts and then using multiple of them (enable in pint jargon) together.

2) In principle, the algorithm works by finding the shortest route. Also if multiple context are enabled, it use the topmost (it is implemented using a Dict Chain)

**Comment by dgasmith** [comment]
1. Great, so multiple contexts is fine. The one issue that we noted was that placing the above relations in the same context appeared to invalidate all earlier transformations as they would not correctly trigger.

2. In this case I believe we would need to change the transform so that it examined the unit of the incoming value and used the correct sub transform. Thanks, I guess we will work to code this up.
