### ISSUE TITLE
Allow "Eh" instead of "E_h" as an abbreviation for Hartree

### ISSUE THREAD

**Issue by xxyxxyxyx1** [hgrecco/pint#712]
A simple request. "Eh" is not currently in use, and it would be much nicer to type "Eh" than needing to type two shift-characters in a row. 

"Eh" is the way "Hartree" is commonly written in plaintext, for example in the ASCII output of quantum chemistry/physics programs like ORCA or Turbomole. So for the people who would use Hartrees, "Eh" would be the intuitive unit. Thank you.

**Comment by hgrecco** [comment]
please submit a PR

**Comment by xxyxxyxyx1** [comment]
okay I've done it. my first use of github, so hopefully I didn't do anything odd.
