### ISSUE TITLE
Pandas update

### ISSUE THREAD

**Issue by znicholls** [hgrecco/pint#713]
@andrewgsavage @hgrecco I got tagged in https://github.com/pandas-dev/pandas/pull/22996#event-1891328266

I don't actually know what it does so unless one of you sees something, I just wanted to make sure that we knew that this could make all the pandas stuff fail on the next CI run (and hence we can close this issue fairly quickly).

**Comment by hgrecco** [comment]
All pandas tests are failing now with the following error: 
> TypeError: 1.0 kilogram of type <class 'pint.quantity.build_quantity_class.<locals>.Quantity'> is not a valid type for hashing, must be string or null

Is this maybe related?

**Comment by hgrecco** [comment]
I will be temporarily disabling pandas testing until the pandas API stabilizes as we need to be able to merge other PR. My suggestion is that we create another branch to with pandas testing enabled.

**Comment by hgrecco** [comment]
Done. Another option will be to re-enable it but pulling from a specific pandas commit instead of `git+https://github.com/pandas-dev/pandas.git`

In this way we can continue testing pandas stuff for that specific commit and then conscioulsy bump the version. @znicholls Any idea which pandas commit sha1 were you using?

**Comment by znicholls** [comment]
Good question, I'll have a go in #727

**Comment by hgrecco** [comment]
Maybe you can get it from travis logs

**Comment by znicholls** [comment]
yep good idea! Is there a way to get CI to run on #727?

**Comment by jules-ch** [comment]
Closing this.
I don't think it's still an issue
