### ISSUE TITLE
Support for negative exponent notation

### ISSUE THREAD

**Issue by huard** [hgrecco/pint#715]
In my field (climate), units are often defined with negative exponents, e.g. `m s-1` instead of `m/s`. cfunits supports this type of notation because it's used in the [CF-Convention](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#table-supported-units), but pint seems to interpret the minus as, well, a minus: 

```
----> 1 units.parse_expression('m s-1')

~/.conda/envs/xclim3/lib/python3.6/site-packages/pint/registry.py in parse_expression(self, input_string, case_sensitive, **values)
    838         gen = tokenizer(input_string)
    839 
--> 840         return build_eval_tree(gen).evaluate(lambda x: self._eval_token(x,
    841                                                                         case_sensitive=case_sensitive,
    842                                                                         **values))

~/.conda/envs/xclim3/lib/python3.6/site-packages/pint/pint_eval.py in evaluate(self, define_op, bin_op, un_op)
     81                 raise Exception('missing binary operator "%s"' % op_text)
     82             left = self.left.evaluate(define_op, bin_op, un_op)
---> 83             return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
     84         elif self.operator:
     85             # unary operator

~/.conda/envs/xclim3/lib/python3.6/site-packages/pint/quantity.py in __sub__(self, other)
    678 
    679     def __sub__(self, other):
--> 680         return self._add_sub(other, operator.sub)
    681 
    682     def __rsub__(self, other):

~/.conda/envs/xclim3/lib/python3.6/site-packages/pint/quantity.py in _add_sub(self, other, op)
    578                                _to_magnitude(other, self.force_ndarray))
    579             else:
--> 580                 raise DimensionalityError(self._units, 'dimensionless')
    581             return self.__class__(magnitude, units)
    582 

DimensionalityError: Cannot convert from 'meter * second' to 'dimensionless'
```
My solution so far is to replace `"-"` by `"**-"`, anything else to suggest ? 
Thanks!

**Comment by hgrecco** [comment]
Regarding the first question, I'm afraid it is not possible to do what you require without introducing ambiguity. And Pint motto has always been: "do not guess". We could implement that to parse units but not expressions..

Regarding your second question, it seems to work for me, can you provide more info about what is not working?

(Next time, please do not mix different things in the same issue)

**Comment by huard** [comment]
Fair enough, thanks !

This is embarrassing, I must have forgotten to update the context. Works for me as well. 

Sorry about that, and thanks for the great library.
