### ISSUE TITLE
Define get_application_registry

### ISSUE THREAD

**Issue by Silmathoron** [hgrecco/pint#716]
I have trouble understanding the point of the ``set_application_registry`` given that there is no ``get_application_registry``: what good is it for the user if he has to know he should use a "hidden" variable ``_APP_REGISTRY`` or ``_DEFAULT_REGISTRY`` afterwards?
I am also confused about the existence of these two variables, especially since only ``_DEFAULT_REGISTRY`` is used in the package, while the user can solely change ``_APP_REGISTRY``...

It feels like I am missing something: could you clarify the purpose of all three?

**Comment by hgrecco** [comment]
The problems we are trying to solve are the following:
1. Unpickling requires an instantiated registry
2. Working with multiple packages requires a shared registry.

The way it works now:
- `_DEFAULT_REGISTY` is a Lazy Registry (i.e. it is only instantiated when first used). 
- `_APP_REGISTRY` is the registry used for unpickling operations. It defaults to `_DEFAULT_REGISTRY`
- `set_application_registry` is the way you change the default registry.

Part of this solution came when we were understading the proper use of Pint as it is unique in the way it define units. In most packages, units are part of singleton  (i.e. they are just variables in a module). 
The reason that there is no `get_application_registry` is that the user knows the hierarchy of their package and therefore knows where to get pint registry from.

After using Pint in multiple applications, I think the right way would be:
1. Raise an exception if the user tries to unpickle without setting the application registry (i.e. do not guess!)
2. keep `set_application_registry`
3. remove `_DEFAULT_REGISTY`
4. Maybe, add `get_application_registry`

**Comment by Silmathoron** [comment]
Hi @hgrecco thank you for your answer, I completely agree with your 4 items.
Do you want me to implement it and make a PR?

**Comment by Silmathoron** [comment]
Ow, I thought point 1 was something you meant for people using it, not something you wanted to implement. I can implement a warning, though... (I think it is better than a breaking change)

**Comment by Silmathoron** [comment]
I am currently implementing these changes, however, I have a small question: why is ``logger`` assigned a ``NullHandler``? I thought I would use it to print the warning... should I use the ``warnings`` module?

Also, it is easy to put a warning in ``__reduce__`` to warn about pickling, but warning on unpickling is more tricky.
To the best of my knowledge, I will have to either wrap ``pickle.load`` and ``pickle.loads`` or implement ``__setstate__`` and ``__getstate__``; do you have a preferred option?

**Comment by Silmathoron** [comment]
Sorry for the long delay, I was a bit overbooked lastly.
Just a question: in the doc you use ``from/to_tuple`` to illustrate serialization... why did you chose that over ``pickle.dumps/loads`` directly on a ``Quantity``?
Does that mean I should also raise a warning when calling ``from/to_tuple``?

**Comment by hgrecco** [comment]
Closing this due to #880
