### ISSUE TITLE
"h" should be the abbreviation of hours

### ISSUE THREAD

**Issue by eevleevs** [hgrecco/pint#719]
"hr" is used as an abbreviation for hours, but this is not according to standard (see https://www.bipm.org/en/CGPM/db/9/7/), and much less common than "h" worldwide.

Here "h" is used for the Planck constant, which I think has much less use than the hours symbol. Both "h" and "hr" should be used for hours, to avoid misunderstanding. Planck should be called something else.

**Comment by jondoesntgit** [comment]
Changing this now could break backwards compatibility. An alternate solution would be to define a different registry that is according to the CGPM standard, which would define Planck as something other than `h`, and define hours as `h` and `hr`.

**Comment by hgrecco** [comment]
I think we should put constants into a namespace in the long run. But now I agree with @jondoesntgit here.

**Comment by jondoesntgit** [comment]
How would namespaces mesh with Quanity? Say that I wrote a quantity:

`Q_(1, 'h')`, would the program assume that it's hour, instead of Planck constant? I can see this leading to unintuitive/unexpected behavior for new users.

**Comment by eevleevs** [comment]
Not sure I get this. I think it's much more likely for a new user to expect h for hours rather than Planck.

**Comment by eevleevs** [comment]
By the way I vote for having constants in another registry. They may work the same, but they are a different thing in concept.

**Comment by cpascual** [comment]
> Q_(1, 'h'), would the program assume that it's hour, instead of Planck constant?

If we ignore the backwards-compatibility issues, I think that the actual *intuitive* behaviour is to read `Q_(1, 'h')` as "1 hour".

Also, I think that separating constants from units is a good idea. IMHO constants should be Quantities, not units.

**Comment by jondoesntgit** [comment]
Agreed that it seems uninutivite to define quantities based on units (1.72 Planck constants). I would, however, like to avoid a situation where Pint tacitly interprets u.h as Planck constant and Q_(1, ‘h’) as hour. The symbol should remain constant.

I think Scipy’s units package puts all its constants in a namespace.

**Comment by bilderbuchi** [comment]
> IMHO constants should be Quantities, not units.

Agreed, preferably this or at least separate namespaces for constants would help here. I was also just tripped up by the unintuitive parsing of "1h".

**Comment by akaihola** [comment]
Is there any simple work-around to create a custom unit registry in which `h` stands for hour?

**Comment by larstiq** [comment]
Grepping for `planck` in the codebase finds #82 where the alias `h` for hour was removed (in the opinion of the thread participants, that would be the wrong way around).

That happened in commit ae189a1e143f7f4d2869f20296d5842e62f66bae where `pint/default_en.txt` dropped the `= h`.   That file is loaded in https://github.com/hgrecco/pint/blob/master/pint/registry.py#L268 if `BaseRegistry(filename="")` so it seems at least at that level one should be able to override with a custom registry.  I did not check how the inheriting classes are handling this.

**Comment by jules-ch** [comment]
@hgrecco 

IMO we should make a breaking change for this case, since it is really disturbing for new users & can potentially introduce bugs when using pint.

I like the idea of a dedicated namespace, but it's difficult to implement since we rely only on strings in the file definition.

Following BIPM standard & ISO/IEC 80000 series Quantities and units & IUPAC Green Book, roman font is used for units & italic symbols for quantities to avoid any ambiguity.
This could help us to differentiate between constants, that are quantities.

**Comment by jules-ch** [comment]
It least for the hour vs planck constant case, we can use unicode for planck constant.

**Comment by Flix6x** [comment]
> Is there any simple work-around to create a custom unit registry in which `h` stands for hour?

@akaihola Not sure if you'd qualify this as "simple", but here's a hacky workaround:

```
import importlib.resources as pkg_resources
import pint

# Edit constants template to stop using h to represent planck_constant
constants_template = pkg_resources.read_text(pint, 'constants_en.txt').replace("= h  ", "     ").replace(" h ", " planck_constant ")

# Edit units template to use h to represent hour instead of planck_constant
units_template = pkg_resources.read_text(pint, 'default_en.txt').replace("@import constants_en.txt", "").replace(" h ", " planck_constant ").replace("hour = 60 * minute = hr", "hour = 60 * minute = h = hr")

# Join templates as iterable object
full_template = constants_template.split("\n") + units_template.split("\n")

# Set up UnitRegistry with abbreviated scientific format
u = pint.UnitRegistry(full_template)
u.default_format = "~P"  # short pretty
```
Check:
```
>>> u.Quantity("h").dimensionality
<<< [time]
>>> u.Quantity("planck_constant").dimensionality
<<< [length] ** 2 * [mass] / [time]
```

**Comment by hgrecco** [comment]
@jules-ch 
Checkout my comment here:
https://github.com/hgrecco/pint/issues/1078#issuecomment-950231900

What do you think of this approach
