### ISSUE TITLE
About dimensionless quantity vs plain numbers

### ISSUE THREAD

**Issue by jbriales** [hgrecco/pint#721]
After using pint in a few cases, I wonder: What's the main convenience of keeping dimensionless quantities?
Consider the following use case:
I'm computing a rotation matrix from its description as angle and direction. I'm using an angle with units (either 'deg' or 'rad'), but once I compute the cos and sin of this angle, what remains is dimensionless quantities (as expected).
Then, these dimensionless quantities are carried to the rest of operations and I end up with a rotation matrix that is a np.ndarray of dimensionless Quantities. This, however, is not desirable as it will conflict in some other methods that expect ndarray rather than a Quantity, or simply because we don't need the extra units information in this case (since it's dimensionless, we have the same information than in a plain ndarray).
My function will work with an angle given with pint units, but also with a plain number (assuming it's given in radians). So a straightforward hack here would be to check if the result of cos(angle) is a Quantity, and if so keeping its magnitude to keep a plain number only. This check would be not necessary and everything would turn up (apparently) cleaner if the dimensionless result just turned as a plain number.
That's my main motivation to ask then: What's the use of cos(angle) returning a dimensionless Quantity rather than a plain number? Couldn't we just automatically turn dimensionless quantities into plain numbers?

**Comment by jondoesntgit** [comment]
Referencing: #670

**Comment by hgrecco** [comment]
I think we are doing the right thing keeping a Quantity as described in #670 Additionally, we are doing like Numpy

```python
>>> x = np.arange(10)
>>> x
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> np.sum(x)
45
>>> type(np.sum(x))
<class 'numpy.int64'>
```

I thnk for you application you should cast explicitly.
