### ISSUE TITLE
Missing check method for Quantity

### ISSUE THREAD

**Issue by jbriales** [hgrecco/pint#722]
According to [this doc](https://pint.readthedocs.io/en/latest/wrapping.html#checking-dimensionality) I can check dimensionality of a quantity with:
```
>>> distance = 1 * ureg.m
>>> distance.check('[length]')
```
When I try that in my program I get:
> AttributeError: Neither Quantity object nor its magnitude (0.0125) has attribute 'check'

I searched the codebase and I couldn't find a check method either in my local package or in the Github repository. The closest I found was the _check method in [pint/util.py](https://github.com/hgrecco/pint/blob/master/pint/util.py).
What am I missing here? Is the doc wrong?
I'm using Pint==0.8.1.

**Comment by hgrecco** [comment]
This was not implemented but should be. Would you like to submit a PR?

**Comment by marcosfelt** [comment]
This feature exists in the repo; a new release just needs to be made on PyPi.

**Comment by jules-ch** [comment]
Closed in #658
