### ISSUE TITLE
to_compact() returns awkward unit (ampere/megameter)

### ISSUE THREAD

**Issue by sigvaldm** [hgrecco/pint#724]
First of all, thanks for one of my favorite libraries. Then, an example, followed by a suggestion:

```
$ ipython 
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pint

In [2]: pint.__version__
Out[2]: '0.8.1'

In [3]: ureg = pint.UnitRegistry()

In [4]: x = -200 * ureg['uA/m']

In [5]: x.ito_base_units()

In [6]: x
Out[6]: <Quantity(-0.00019999999999999998, 'ampere / meter')>

In [7]: x.to_compact()
Out[7]: <Quantity(-199.99999999999997, 'ampere / megameter')>
```

I find A/Mm awkward. It seems arbitrary when pint converts the numerator and when it converts the denominator. For example, the above example returns uA/m unless I take the extra step of calling `ito_base_units()`, in which case it returns A/Mm. I wonder if it wouldn't be better to always prefix the numerator for fractional units? E.g. uA/m instead of A/Mm. And who bicycles 20 meters per millihour?

**Comment by hgrecco** [comment]
I agree with your suggestion. Would you like to submit a PR?

**Comment by sigvaldm** [comment]
Sounds fun so I'll see if I can squeeze it in during the next week or two, but I can't promise anything.
