### ISSUE TITLE
Different-registries error after pickle dump-load

### ISSUE THREAD

**Issue by jbriales** [hgrecco/pint#725]
I have saved a pint Quantity into a file with `pickle.dump(...)` then loaded it in a different program execution with `pickle.load(...)`.
In both program executions I create the UnitRegistry in exactly the same way.
However, when comparing or mixing a Quantity that is obtained from the .pkl file via `pickle.load(...)` and a Quantity that is created in the current program execution via the UnitRegistry, I get the error:
> ValueError: Cannot operate with Unit and Unit of different registries.

Following the instructions in the [tutorial](https://pint.readthedocs.io/en/latest/serialization.html), 
my understanding is that in this circumstances everything should work fine. What may be the problem or my misunderstanding?

**Comment by iankharris** [comment]
After some digging, it looks like this is very straightforward:
>>> pint.set_application_registry(ureg)

**Comment by hgrecco** [comment]
This should be fixed in master.
