### ISSUE TITLE
No wheels on PyPi

### ISSUE THREAD

**Issue by darkvertex** [hgrecco/pint#731]
I see a `setup.cfg` so somebody already planned for Python wheels of this package, but I noticed on PyPi it only has the `.tar.gz` file: https://pypi.org/project/Pint/#files

Would be nice if .whl were deployed also.

**Comment by hgrecco** [comment]
agreed. Would you mind submitting a PR?

**Comment by hgrecco** [comment]
You are right, I will do it.

**Comment by darkvertex** [comment]
Since you use Travis, you may wanna check out the pip deployment support:
https://docs.travis-ci.com/user/deployment/pypi/

You can encrypt your password right into the file so that Travis can upload it to PyPI directly on your behalf after a good merge to master.

**Comment by thedrow** [comment]
There are wheels now.
We can close this.
