### ISSUE TITLE
Specifying pint unit as a type hint for NamedTuple causes error

### ISSUE THREAD

**Issue by MirzaD** [hgrecco/pint#733]
Hi, 
I've been using pint to specify unit types via type hinting for my python 3.6 project, and it workes great when annotating function arguments.
However, I've hit a roadblock when trying to specify type hint for NamedTuple property:
```python
class PowderFactorOutputs(NamedTuple):
    explosive_weight_per_rock_volume: unit.kg / unit.m ** 3
    explosive_weight_per_rock_weight: unit.kg / unit.t
    rock_weight_per_explosive_weight: unit.t / unit.kg
```
example above causes an error: `TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got <Unit('kilogram / meter ** 3')>.`

Same type hint will for a function argument like:
```python
def calculate_total_weight_of_blasted_rock(volume_of_rock_blasted: unit.m ** 3,
                                           rock_density: unit.g / unit.cm ** 3) -> unit.t:
```

There is a workaround, not to use class notation for creating NamedTuple, but I was wandering is there a way to fix this, or is this a NamedTuple problem, or am I using it incorrectly :/
Thnx

**Comment by hgrecco** [comment]
The reason is that `NamedTuple` (which is imported from the typoing module) puts more constrains than just like this 
```python
>>> from typing import Sequence
>>> Sequence[ureg.meter]
```
does not work.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.

**Comment by mprat** [comment]
We are still seeing this as an issue when using `pint` with modern Python versions. Any change to re-open this issue?

**Comment by hgrecco** [comment]
What I was trying to explain is that this is not a problem with Pint. What you are doing is the equivalente of:
```python
>>> from typing import NamedTuple
>>> class Example(NamedTuple):
...    value: 32
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/grecco/anaconda3/envs/pint-devel/lib/python3.6/typing.py", line 2144, in __new__
    nm_tpl = _make_nmtuple(typename, types.items())
  File "/Users/grecco/anaconda3/envs/pint-devel/lib/python3.6/typing.py", line 2113, in _make_nmtuple
    types = [(n, _type_check(t, msg)) for n, t in types]
  File "/Users/grecco/anaconda3/envs/pint-devel/lib/python3.6/typing.py", line 2113, in <listcomp>
    types = [(n, _type_check(t, msg)) for n, t in types]
  File "/Users/grecco/anaconda3/envs/pint-devel/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got 32.
```

`unit.kg / unit.m ** 3` is an object (not a type) just as `32`.

If you want to do something like this you will need to use your own `NamedTuple` class.
