### ISSUE TITLE
Custom Unit Dimensionality

### ISSUE THREAD

**Issue by jacobmed** [hgrecco/pint#736]
Hello,

I am trying to define a custom unit with a dimensionality of [framerate].  I am wondering if I am missing part of the syntax?  I can get the math and conversion to work, but when I get the unit's dimensionality attribute, it is returning "dimensionless" instead of "[framerate]."

Here is my test case:

```
from pint import UnitRegistry
ureg = UnitRegistry()
Q_ = ureg.Quantity


ureg.define('frame =  1 / 24.0 second')
ureg.define('[framerate] = [frame] / [time]')
ureg.define('fps = 1 * frame / second')

    
miles = Q_('30 miles')
mph = Q_('60 mph')
print mph.dimensionality
duration = miles / mph
print duration.to('hours')


frames = Q_("900 frames")
fps = Q_('120 fps')
print fps.dimensionality
duration = frames / fps
print duration.to('seconds')
```

Any help is greatly appreciated!
-Jacob

**Comment by jacobmed** [comment]
This is the output from my code.  I include mph because I considered it to be functionally similar.

```
[length] / [time]
0.5 hour
dimensionless
7.5 second
```

**Comment by dalito** [comment]
Why has frame a unit? Shouldn't it be just: `ureg.define('frame =  1 / 24.0 second')`?

**Comment by hgrecco** [comment]
(I did not have time to test what I am suggesting)

I think your are mixing up things. Note, for example, that with your definition fps has dimensiontality 1 / / second / second.

Also derived dimensions must be writen from dimensions. Look for example at the [definition of area](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L68).

**Comment by jacobmed** [comment]
Thanks for your help.  I realized my error was that I was trying to use two separate frame rates (24 fps and 120 fps) and I was confusing the syntax.

All I'm trying to do is create a custom unit that represents a frame, as in film or video frame rates.  I was thinking I'd need a custom dimensionality but I don't really, it's just a sub-unit of time.

```
>>> ureg.define('fps = 1 / 24.0 second')
>>>
>>> frames = Q_("900 fps")
>>> print frames.to("second")
37.5 second
>>>
>>> ureg.define('fps_fast = 1 / 120.0 second')
>>> high_speed_frames = Q_("900 fps_fast")
>>> print high_speed_frames.to("second")
7.5 second
```
