### ISSUE TITLE
New ureg.wraps fails for callables lacking signatures

### ISSUE THREAD

**Issue by natezb** [hgrecco/pint#739]
Callables lacking signatures (e.g. numpy ufuncs) do not work with the new version of `ureg.wraps` introduced in #652. Unsupported callables such as these produce a `ValueError` within `signature()`, e.g.

```
>>> signature(np.log)
ValueError: callable <ufunc 'log'> is not supported by signature
```
I'd imagine it's best if such callables fallback to whatever the old behavior was—presumably ignoring keyword arguments, or disallowing them.

**Comment by natezb** [comment]
Sure, here's a sample. It fails for me on both 2.7 and 3.6:

```
import numpy as np
import pint
ureg = pint.UnitRegistry()
qabs = ureg.wraps('=A', ('=A',))(np.abs)
qabs(-1)
```
The call of `qabs(-1)` will fail due to the use of `signature()` within `_apply_defaults()`. (Note that the specific value of `-1` here is not required).

**Comment by hgrecco** [comment]
Linking to #1753
