### ISSUE TITLE
A way to get the unit of a measurement

### ISSUE THREAD

**Issue by mortoray** [hgrecco/pint#744]
I need to get the specific unit for a measurement. There doesn't appear to be a correct way to do this now so I've resorted to looking at `_units`:

	if volume.units._units == "teaspoon" or volume.units._units == "tablespoon":

In my application, recipes, the source units has meaning, and I adjust the display in such cases.

I want a proper accessor to get this value, or a check function.

**Comment by jondoesntgit** [comment]
What about `volume.unit in [‘teaspoon’, ‘tablespoon’]`

**Comment by mortoray** [comment]
I guess I never saw/considered `u` . Perhaps it needs a better name?

**Comment by jondoesntgit** [comment]
What would you suggest? Most likely, it just needs better documentation...

**Comment by mortoray** [comment]
Either `unit_name` or `unit_type`, the former being a string, the latter an enum/instance. I think I'd prefer something like:

    if `volume.unit_type in [ ureg.teaspoon, ureg.tablespoon]`

I'm not a fan of string constants used like I did.

As to documentation, I've had to look at the source code quite a bit, and use `dir(quantity)` quite often. A lot of what I wanted to do wasn't clear. I'm happy to make a list of what I'm doing, if that helps.  The library is working well, and I'm happy using it.

**Comment by andrewgsavage** [comment]
u is short for units.

I think everything you want is there, just not always obvious.
```python
volume=Q_(1,"tablespoon")
volume.units in ["teaspoon", 'tablespoon']
> True

volume.units in [ureg.teaspoon, ureg.tablespoon]
> True

volume.units == "tablespoon"
> True

str(volume.units)
> 'tablespoon'
```

**Comment by mortoray** [comment]
The code from @andrewgsavage works. I think that's fine. It's an issue of discoverability then, as I couldn't find it in the docs.

**Comment by jules-ch** [comment]
Closing
