### ISSUE TITLE
False positive DimensionalityError

### ISSUE THREAD

**Issue by nealkruis** [hgrecco/pint#757]
I'm trying to convert some wild correlation coefficients to a different set of units. They both have the same dimensionality (`[mass] / [length] ** 0.89 / [temperature] / [time] ** 2.11)`), but I'm getting a dimensionality error with the following example:

`(1.81*ureg['W/(m**2*K*(m/s)**0.89)']).to(ureg['Btu/(hr*ft**2*degR*(miles/hr)**0.89)'])`

`DimensionalityError: Cannot convert from 'second ** 0.89 * watt / kelvin / meter ** 2.89' ([mass] / [length] ** 0.89 / [temperature] / [time] ** 2.11) to 'btu / degR / foot ** 2 / hour ** 0.11 / mile ** 0.89' ([mass] / [length] ** 0.89 / [temperature] / [time] ** 2.11)`

Interestingly, if I separate the numerator and denominator everything works fine:

`(1.81*ureg['J']).to(ureg['Btu'])/(1*ureg['(s*m**2*K*(m/s)**0.89)']).to(ureg['(hr*ft**2*degR*(miles/hr)**0.89)'])`

Perhaps related to #681?

**Comment by hgrecco** [comment]
Indeed this is a rounding error as described in #681. Again the option would be to have some kind of tolerance or to make the exponentes a Fraction class. Not sure what would be the performance penaly. We could add it as optional.
