### ISSUE TITLE
Elide large Latex-formatted arrays

### ISSUE THREAD

**Issue by natezb** [hgrecco/pint#765]
Semi-related to #654.

Jupyter will stall for several seconds when trying to display quantities containing large numpy arrays, since it tries to display and render the whole thing. It might be nice to elide this display beyond a certain practical size, like 1000 elements.

**Comment by jondoesntgit** [comment]
I know that tqdm has some features that detect if it’s in a Jupyter notebook or not.

Numpy and pandas both display ellipses if the array is larger than 60 elements.

**Comment by natezb** [comment]
I don't think that this has to be Jupyter-specific, but it is where I notice the issue, since I otherwise don't tell pint to generate LaTeX. It seems reasonable to me to always elide long arrays, regardless of environment.

**Comment by hgrecco** [comment]
I think that the right way would be to mimic (or use) numpuy formatting options. Recently #759 was merged. I think we can use it here as well

**Comment by hgrecco** [comment]
Any PR for this?

**Comment by ipcoder** [comment]
I would like to emphasize that this is quite an issue for practical use of the package.
Thanks

**Comment by hgrecco** [comment]
Linking to #1757
