### ISSUE TITLE
All units included in international group and mks system

### ISSUE THREAD

**Issue by jules-ch** [hgrecco/pint#766]
Root group of units are added by default to the default group then to the default system of units.

Like this : 
* root group (all units) -> default group (international) -> default system (mks)

This behavior makes useless function like `<Some_Quantity>.get_compatible_units("mks")`, as it will get all compatible units. Filtering by group or system is useless there.

NB: Units in root group are available no matter what in the registry.

I would expect international group to contain only SI or derived SI units defined by CGPM.

Code involved : 
```python
    def _after_init(self):
        super(SystemRegistry, self)._after_init()

        #: Copy units in root group to the default group
        if 'group' in self._defaults:
            grp = self.get_group(self._defaults['group'], True)
            grp.add_units(*self.get_group('root', False).non_inherited_unit_names)

        #: System name to be used by default.
        self._default_system = self._default_system or self._defaults.get('system', None)
```

### Opportunities : 
Moving forward with check like : 

* Q_(1,"lb").is_SI()
* Q_(1,"mph").in_system("mks")

### Proposed solution : 

Make an international group outside of root unit group which contains all SI or SI derived.
Remove include of root units to default group and system

@hgrecco @jondoesntgit  Any thoughts before I submit a PR ?

**Comment by hgrecco** [comment]
Just to add here some context. In the begining ... there was no support for Groups or Systems in Pint. This was added later with an important aspect in mind: do not break existing definition files and do not expect that everything is within a `@group` section. The `root` group was also created as a way to represent Pint previous state. The idea was to have a first version and test the API and I think it has worked really well. It is easy to use and expresive, and does not add an extra burden to those wanting to avoid thit.

Now, going back to your solution. 
1. Make an `international` group outside  `root`: I would suggest against this. There must be a group containing everything and that group is `root`
2. Remove include of root units to default group and system. I would again suggest against this. The ability to select a default group allows you to elide `group` for most definitions avoiding nesting

However, I think your concern is valid and you make a really good point. Right now, the solution is useless for important use cases. So, how about if we do the following change:

Only add to the default group those units that do not explicitely belong to a group.

I think this should do the trick.

**Comment by jules-ch** [comment]
Thanks @hgrecco for the insights.

A bit of history clears some of my questions. And I understand the need for backward compatibility.

As far as I understand it, main use cases of group and system today in pint  are : 
* Use of base units coherent in a system 
    * `to_base_units` function
* Inclusion of group of coherent units in systems

It just seemed weird to me to have all units even imperial units included in mks system and international group.

On your remarks : 
1. Ok on this one
2. Nesting is implicitly done with default group (everything is included in there, even other groups)

I'm ok with your solution.

> Only add to the default group those units that do not explicitely belong to a group.
> I think this should do the trick.

I hope it does not look like I'm chasing unicorns 🦄  as this won't change the API anyway.

**Comment by hgrecco** [comment]
Indeed we are not changing the API, I think we are only changing the parsing rules of the definitions files. And actually the new rule makes sense

Currently
1. There is a **special** group named root where all units are added.
2. For convenience, a default group can be defined which is equivalent to have a `group` directive around all the file
3. group nesting is done with the `using` modifier to the `group` directive. 

Rule 3 exists because you cannot nest `group` directives. i.e. the following is not valid
```
@group External
    @group Internal
    @end
@end
```

and should be written as:
```
@group Internal
@end

@group External using Internal
@end
```

Therefore it does not make sense that all groups are added to the default group as it will be equivalente to group nesting directives.

So by changing rule 2 to: "For convenience, a default group can be defined which is equivalent to have a `group` directive around all orphan units (i.e. those not belonging to a group)" we make everything more consistent in my view.

**Comment by jules-ch** [comment]
Sounds good to me :). I'll submit a PR with this
