### ISSUE TITLE
Units are not combined, km**(0.5)*m**(0.5) 

### ISSUE THREAD

**Issue by swapnilsurdi** [hgrecco/pint#770]
OUTPUT - 
83.91781774515496 kilometer ** 0.5 * meter ** 0.5 / second

entity1 in meter
entity2 in kilometer
entity3 in kilometer
Code - 
 0.88 * (2*entity1*entity2/(1+entity2/entity3))**(1/2)

**Comment by dalito** [comment]
It seems that you are expecting that pint will simplify "combine" by default. This is not the case for performance reasons. pint does combine the units if asked to do so.

```
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> a = 83.9 * ureg.kilometer**0.5
>>> b = 1. * ureg.meter**0.5/ureg.second
>>> a*b
<Quantity(83.9, 'kilometer ** 0.5 * meter ** 0.5 / second')>
>>> (a*b).to_base_units()
<Quantity(2653.15095688, 'meter / second')>
>>>
```

**Comment by swapnilsurdi** [comment]
it just seems logical to combine these units for the final answer. Otherwise I have to use the convert to base unit function.
