### ISSUE TITLE
Pandas/PintArray

### ISSUE THREAD

**Issue by caerus-data** [hgrecco/pint#772]
I'm trying to use Pint alongside Pandas, and have read all the documentation I can find. I'm running the latest Anaconda on Windows 10. Tested in both Python 2.7 and 3.6. Pandas doesn't want to allow me to use a pint.UnitRegistry() unit as a dtype.

What am I missing?

`import pandas`
`import pint`

`print(pandas.__version__)`
 '0.24.1'

`print(pint.__version__)`
'0.9'

`from pint.pandas_interface import PintArray`
ModuleNotFoundError: No module named 'pint.pandas_interface'

`import pkgutil`

`package=pint`
`for importer, modname, ispkg in pkgutil.walk_packages(path=package.__path__,`
                                                      `prefix=package.__name__+'.',`
                                                      `onerror=lambda x: None):`
    `print(modname)`

pint.babel_names
pint.compat
pint.compat.chainmap
pint.compat.lrucache
pint.compat.meta
pint.compat.tokenize
pint.context
pint.converters
pint.definitions
pint.errors
pint.formatting
pint.matplotlib
pint.measurement
pint.pint_eval
pint.quantity
pint.registry
pint.registry_helpers
pint.systems
pint.testsuite
pint.testsuite.helpers
pint.testsuite.parameterized
pint.testsuite.test_babel
pint.testsuite.test_contexts
pint.testsuite.test_converters
pint.testsuite.test_definitions
pint.testsuite.test_errors
pint.testsuite.test_formatter
pint.testsuite.test_infer_base_unit
pint.testsuite.test_issues
pint.testsuite.test_measurement
pint.testsuite.test_numpy
pint.testsuite.test_pint_eval
pint.testsuite.test_pitheorem
pint.testsuite.test_quantity
pint.testsuite.test_systems
pint.testsuite.test_umath
pint.testsuite.test_unit
pint.testsuite.test_util
pint.unit
pint.util

**Comment by andrewgsavage** [comment]
We've moved what was in pint.pandas_interface to a separate module, pintpandas. https://github.com/hgrecco/pint-pandas

You'll want to install that then follow what's in https://github.com/hgrecco/pint/blob/master/docs/pint-pandas.ipynb

**Comment by caerus-data** [comment]
pip install pint-pandas failed - install from github? Conda?

When I run the code you linked to, I get the following error:

TypeError: data type 'pint[lbf ft]' not understood

**Comment by andrewgsavage** [comment]
yea from github, it'll be something like:

git clone https://github.com/hgrecco/pint-pandas.git
cd pint-pandas
pip install -e .

**Comment by caerus-data** [comment]
Resolved by installing pint-pandas from GitHub source

**Comment by awa5114** [comment]
I tried to install this by cloning pint-pandas from github source, using both `setup.py` and `pip install -e .` with no success.

Running the example notebook provided in the repo throws an error as follows:

`TypeError: data type 'pint[lbf ft]' not understood`

Is there anything special we need to know about the dependencies here? I have:
```
# Name                    Version                   Build  Channel
pandas                    0.25.1           py36he350917_0    conda-forge
pint-pandas               0.1.dev0                  dev_0    <develop>
pint                      0.9                      py36_2    conda-forge
```

**Comment by awa5114** [comment]
Allright @andrewgsavage I just read your comments more carefully and it seems like your branch is the one currently compatible with `pandas 0.25.1`. I downloaded a copy of your branch, did a `pip install -e .` and it seems to work... Will this be merged to the main pint-pandas branch anytime soon? Also is pint-pandas destined to remain its own little thing or is integration with either pandas or pint planned for the future?
