### ISSUE TITLE
pandas support

### ISSUE THREAD

**Issue by johnbomidi** [hgrecco/pint#779]
Not sure if this belongs here but hope somebody could help. I was trying to run the example https://pint.readthedocs.io/en/latest/pint-pandas.html#Reading-from-csv

And I keep getting the error that the data frame does not have pint method. 

Is there a specific pandas install that I have to be installing? Is pint-pandas a separate thing from pint that I have to install? Am I missing something obvious ? 

Neat examples and library btw! Thanks.

**Comment by cpascual** [comment]
Maybe this is what you are looking for:

https://github.com/hgrecco/pint-pandas

**Comment by johnbomidi** [comment]
Okay. I did see that. Do I have to separately install that after I install pint?

**Comment by cpascual** [comment]
> Do I have to separately install that after I install pint?

yes 

Note that if you use pip for installing, pint-pandas would automatically install pint and pandas as their required dependencies

**Comment by johnbomidi** [comment]
Great. Thanks!

**Comment by johnbomidi** [comment]
Back on this issue again, as I was trying to set up a new environment working with pint pandas.  I used the resolution earlier which was to install pint-pandas as @cpascual indicated.  But now, the problem still persists after I install it.
I used 

pip install -U git+https://github.com/hgrecco/pint-pandas

and it installed pint 0.9, pint-pandas 0.1.dev0, pandas 0.25.1

and I try that example, https://pint.readthedocs.io/en/latest/pint-pandas.html#Reading-from-csv and it throws the error,
'DataFrame' object has no attribute 'pint'

Am I doing something wrong?

**Comment by MycoBean** [comment]
> Back on this issue again, as I was trying to set up a new environment working with pint pandas. I used the resolution earlier which was to install pint-pandas as @cpascual indicated. But now, the problem still persists after I install it.
> I used
> 
> pip install -U git+https://github.com/hgrecco/pint-pandas
> 
> and it installed pint 0.9, pint-pandas 0.1.dev0, pandas 0.25.1
> 
> and I try that example, https://pint.readthedocs.io/en/latest/pint-pandas.html#Reading-from-csv and it throws the error,
> 'DataFrame' object has no attribute 'pint'
> 
> Am I doing something wrong?

You might need to install pint 0.10.dev0 as well:
`pip install -U git+https://github.com/hgrecco/pint` should work

**Comment by hgrecco** [comment]
Please move this questio to pint-pandas if still necessary
