### ISSUE TITLE
Customize parsing of magnitude's value

### ISSUE THREAD

**Issue by jeblackburn** [hgrecco/pint#78]
Hello. Love this library. It has literally saved us weeks of development time.

I ran into an interesting behavior, which is completely understandable but not quite what we expected.

Calling registry.Quantity('10/1/2013', None) produces a Quantity with 0.004967... as its magnitude (10.0/2013.0 == 0.004967...), by calling eval on the string. I was wondering if there's a way to cleanly substitute a date-aware parsing algorithm for the existing one? We're currently handling such filtering before we call Pint, but it might be better encapsulation for us to to inject such logic into the Pint lib. Just wondering what your thoughts are on the topic.

Thanks again,
Jon Blackburn

**Comment by hgrecco** [comment]
We might be able to do this now with the new parser. Feel free to open a new issue if the need still remains.
