### ISSUE TITLE
Registry-defined unit doesn't properly convert

### ISSUE THREAD

**Issue by caerus-data** [hgrecco/pint#780]
I have a number of datapoints stored as m3/day. I want to convert them to "gpm" a common acronym for gallons-per-minute, not found in the default registry.

I therefore load an external registry, with a number of units that have worked great - I've defined gpm as such

`gpm = gallons/minute`

I've converted the data by setting the dtype within a pandas dataframe, then using .pint.to('gpm') [way simplifying my code, but this works with other values, and other conversions from the external registry] 

- the numbers have definitely been converted, and the new dtype is 'gpm', but the calculations are wrong.

What am I missing?

**Comment by andrewgsavage** [comment]
That sounds odd. Could you post a short version of your code that reproduces the issue?

Other question is whether it's using the US or UK gallon. Could you check the conversion works as expected outside of pintpandas?

**Comment by caerus-data** [comment]
Blimey - how do I specify "US Gallon"?

`gpm= US Gallons/minute` ????

Will explore outside of pintpandas. Thanks as always!

**Comment by caerus-data** [comment]
Apologies - the observed error appears to be a 'user error' in that the units specified in my master table are incorrect. Working to clean up dataset.
