### ISSUE TITLE
Documentation mentions `degK`

### ISSUE THREAD

**Issue by henrikh** [hgrecco/pint#782]
The documentation for temperature units mention `degK`

> The default definition file includes fahrenheits, celsius, kelvin and rankine abbreviated as degF, degC, degK, and degR.

But as far as I can see, the unit defined for the kelvin is just `kelvin`.

**Comment by jules-ch** [comment]
degK is an alias of kelvin as you can see in the default definition file : 

`kelvin = [temperature]; offset: 0 = K = degK`

**Comment by henrikh** [comment]
Thanks for the clarification :)
