### ISSUE TITLE
Inverse wraps function?

### ISSUE THREAD

**Issue by bilderbuchi** [hgrecco/pint#786]
We have `wraps` to enable use of non-quantity functions within "pintified" code.
Would it be attractive to also have the inverse way, i.e. to have something that converts a quantity-using function to "plain magnitudes"? This could be useful when writing functions using quantities, but also using other code that cannot deal with quantitities. (e.g. `scipy.optimize.curve_fit` or `scipy.interpolate.interp1d`)?

This could save (or automate) manual wrangling around the function interface with `bla.to_base_units().magnitude` for parameters and `Q_(returnvalue, 'someunit').

E.g., I have just written a function a second time (without units), and usage looked like this:
```
popt, pcov = curve_fit(arrhenius_nounits, T.to('K').magnitude, curr.to('mA/cm**2').magnitude, p0=(1e-23,1))
E_a_fit = Q_(popt[0], 'J')
mult_fit = Q_(popt[1], 'mA/cm**2')
arrhenius(Q_(600, 'K'), E_a_fit, mult_fit)
```

This could e.g. look like this (name of the wrapper tentative):
```
def energy(mass=Q_(1, 'lb')):
    return mass * ureg.speed_of_light**2

# so you can't deal with Quantities? fine...
base_energy = ureg.casts()(energy)  # pulls the interface to base/SI units by default

# pull the interface to custom units as you wish (e.g. to achieve good scaling/normalisation)
base_energy_custom = ureg.casts(ret=ureg.eV, args=ureg.g)(energy) 

result = base_energy(1.0)  # input in kg, result in J
result = base_energy_custom(1.0)  # input in gram, result in eV
```
Bonus points if the docstring of the resulting function gets an addendum indicating the correct units.

**Comment by hgrecco** [comment]
I think is a good idea. Maybe we can call it unwraps ?

**Comment by SamG-01** [comment]
I agree that this would be very useful. Personally, this would help immensely with numeric integration, as `scipy.integrate.quad` requires both the integration bounds and the output of the function you pass into it to be dimensionless. For example, suppose I had the following:
```python
from scipy.integrate import quad
from pint import UnitRegistry
ureg = UnitRegistry()

h_a, h_b = 1 * ureg.meter, 2 * ureg.meter # integration bounds
m_0 = 1 * ureg.kg # mass of particle

def V(h, m):
    """Returns the gravitational potential of a particle with mass m at height h in Joules."""
    potential = (m * ureg.g0 * h).to(ureg.joule)
    return potential
```

Suppose I want to integrate `V` from `h_a` to `h_b` with `m=m_0`. Knowing that `h` will be in `km`, as of now, I would have to wrap the function manually and integrate:
```python
def V_unitless(h_unitless, m):
    h = h_unitless * ureg.meter
    return V(h, m).magnitude

integral, error = quad(V_unitless, h_a.magnitude, h_b.magnitude, args=m_0)
integral *= ureg.joule * ureg.meter # restores units
```

To make this more convenient, it would be useful to have the unwrapper you suggest here, where:
```python
V_unitless = ureg.unwraps(ureg.joule, [ureg.meter, None])(V)
```

I'm unsure how `strict` mode would work here; perhaps in that case, if you passed an argument of `h_unitless = 1 * ureg.km`, it would convert that to `1000 * ureg.meter` and pass that into `V` instead?

**Comment by hgrecco** [comment]
Linking this #1753
