### ISSUE TITLE
Problem with __name__ in registry.py

### ISSUE THREAD

**Issue by lnmaurer** [hgrecco/pint#787]
I'm using sphinx-automodapi to generate documentation for a project I'm working on, and the  `__name__` *function* in registry.py causes sphinx-automodapi to crash because it's expecting that `__name__` is a *string* (not a function that returns a string).

I don't know enough to say whose fault this is; all I know is that pint causes sphinx-automodapi to choke whereas other packages don't cause problems, so perhaps `__name__` should not be a function.

**Comment by hgrecco** [comment]
I guess that the only way is that you monkey patch it after import

**Comment by lnmaurer** [comment]
Why is `__name__` a function instead of a string?

I've looked into this further since I posted this issue, and as best as I can tell, `__name__` should be the name of the current module in string form. Am I incorrect about that? If not, is it necessary to break that convention in pint?

If I go into the pint source code and simply comment out the `__name__` function, everything I do in pint still works fine (and sphinx-automodapi is happy).

**Comment by cpascual** [comment]
>Why is __name__ a function instead of a string?

I am also curious.

Looking at the code in registry.py, I see that it is  `BaseRegistry.__name__` which is [defined as a function (that returns `'unitRegistry'`)](https://github.com/hgrecco/pint/blob/6e1f2a51c51a2c40c2bfba5514e27131c1170ec2/pint/registry.py#L197). But then (surprisingly for me), the following code does not raise any AssertionError:

```python
import pint
assert type(pint.registry.BaseRegistry.__name__) is str  # <-- shouldn't this fail with current code?
assert type(pint.UnitRegistry.__name__) is str
assert type(pint.registry.__name__) is str
```

And furthermore, doing `print(pint.registry.BaseRegistry.__name__)` outputs `'BaseRegistry'`

So, it looks like the `BaseRegistry.__name__` definition as a method gets shadowed (and  then it could be removed, right?) ... or maybe there is some (metaclass?) magic going on with `BaseRegistry` which escapes me.

**Comment by hgrecco** [comment]
Here is some info about `__name__`:
https://stackoverflow.com/questions/49781234/setting-a-class-name-declaratively

What would happen if we just remove the `__name__` definition? My feeling is that this might be an artifact of the separation of the Registry. Originally, there was just one registry class that did everything. I decided to split it into multiple smaller pieces to simplify testing and development.

**Comment by cpascual** [comment]
Note Guido's excerpt from @hgrecco's link: 

> ...all __dunder__ names are reserved for the implementation and they should
only be used according to the documentation. So, indeed, it's not illegal,
but you are not guaranteed that anything works, either.

... and considering that the docs for `__name__` specify that it should be a "name" (i.e. a string), I think that it might be wise to remove the `def __name__` in ` BaseRegistry`. Specially if its origin/purpose is not clear

**Comment by hgrecco** [comment]
@cpascual Agree

**Comment by cpascual** [comment]
Ok, so I created a PR (#798)

**Comment by lnmaurer** [comment]
Thanks for taking care of this!
