### ISSUE TITLE
Units in default @context arguments

### ISSUE THREAD

**Issue by cpitclaudel** [hgrecco/pint#792]
Default values for context arguments are always dimensionless, which doesn't work well when giving default values for dimensional factors.  For example, in `default_en.txt`:

```
@context(mw=0,volume=0,solvent_mass=0) chemistry = chem
    [substance] -> [mass]: value * mw
    [mass] -> [substance]: value / mw
```

With this definition, `ureg = pint.UnitRegistry(); ureg("1 mol").to("g", "chemistry")` raises an exception (`pint.errors.DimensionalityError: Cannot convert from 'mole' ([substance]) to 'gram' ([mass])`).

Feature request: could default arguments be parsed with `ureg.Quantity` instead?

**Comment by hgrecco** [comment]
In general, I think is a good idea and I do not see any drawback. Maybe we should also have a check in when activating the context that the argument matches the units default units.

**Comment by hgrecco** [comment]
I am closing this for the time being. Feel free to reopen or submit a PR
