### ISSUE TITLE
Using a context results in a 1500x slowdown for .to()

### ISSUE THREAD

**Issue by cpitclaudel** [hgrecco/pint#795]
I ran into performance issues with contexts.  Here is a minimal repro:

```
$ python3 -m timeit -s "import pint; ureg = pint.UnitRegistry(); src = ureg('1 m'); dst = ureg.Unit('km')" "src.to(dst)"
10000 loops, best of 3: 49.3 usec per loop

$ python3 -m timeit -s "import pint; ureg = pint.UnitRegistry(); src = ureg('1 m'); dst = ureg.Unit('km')" "src.to(dst, 'chemistry')"
10 loops, best of 3: 66.7 msec per loop

$ python3 -m timeit -s "import pint; ureg = pint.UnitRegistry(); src = ureg('1 m'); dst = ureg.Unit('km')" "src.to(dst, 'spectroscopy')"
10 loops, best of 3: 67.1 msec per loop
```

In other words, `pint` can do 20'000 conversions per second on my machine with an empty context, but only 15 conversions per second when I give it a context.

**Comment by hgrecco** [comment]
Contexts work by finding the shortests path between two units which are bridged by a context. So, it is expected that is slower, but we should try to make it better than it is now. It would be important to find out what is the bottleneck in this code:
https://github.com/hgrecco/pint/blob/master/pint/registry.py#L1211
The call to `find_shortest_path` or the loop that applies as series of transformation?
Additionally, shouldnt we try to memoize the result? Can we do it efectively in a safe manner taking into account that the contexts can be added and removed (and their arguments can change)?

**Comment by cpitclaudel** [comment]
Hmm, most of the time is spent in parse_unit_name, which is called by _build_cache, itself called by enabled_contexts and disabled_contexts.  Most of the rest of the time is spent in _get_root_units, _get_dimensionality, and from_word.

I profiled using this script:

```python
import pint

ureg = pint.UnitRegistry()
src = ureg('1 m')
dst = ureg.Unit('km')

for _ in range(75):
    src.to(dst, 'spectroscopy')
```

and then running the following:

```
python3 -m cProfile -o bench.prof bench.py 
pip3 install --user snakeviz
snakeviz bench.prof 
```

**Comment by hgrecco** [comment]
If this is true, then you should not see any substantial slowdown if you use the contextmanager 
```python
import pint

ureg = pint.UnitRegistry()
src = ureg('1 m')
dst = ureg.Unit('km')

with ureg.context('spectroscopy'):
    # Profile only starting from here
    for _ in range(75):
        src.to(dst)
```

**Comment by cpitclaudel** [comment]
Yup, using a single context manager makes things very fast.

(The reason I can't use that is that I'm converting many values of various types; concretely I have files `1.txt`, `2.txt`, etc. with various measurements, and a single file `units.txt` specifying which unit to display each value in, and optionally which context to use; then the code iterates over all values and normalizes them by calling `.to()`.  I could sort the values by context and then minimize the number of context switches, but that would require a fairly unnatural reorganization of the code.

**Comment by hgrecco** [comment]
I think the solution could be to create a context aware cache. In that way, it would call `_build_cache` only once

**Comment by cpitclaudel** [comment]
That sounds quite reasonable

**Comment by hgrecco** [comment]
Would you like to submit a PR?

**Comment by cpitclaudel** [comment]
I could look into it.  Quick question: why are self._root_units_cache and self._dimensionality_cache not cleared at the beginning of _build_cache?

**Comment by hgrecco** [comment]
It's a bug. It has not surfaced because it is rare that somebody changes the roots units and/or dimensionality without recreating the registry.

**Comment by cpitclaudel** [comment]
Also, in this function:

```
    def insert_contexts(self, *contexts):
        """Insert one or more contexts in reversed order the chained map.
        (A rule in last context will take precedence)

        To facilitate the identification of the context with the matching rule,
        the *relation_to_context* dictionary of the context is used.
        """
        self._contexts.insert(0, contexts)
        self.maps = [ctx.relation_to_context for ctx in reversed(contexts)] + self.maps
        self._graph = None
```

The call to insert looks suspicious, doesn't it? `contexts` is a list, but `insert` takes a single element.

**Comment by hgrecco** [comment]
It is inserted at the begining of the list

**Comment by cpitclaudel** [comment]
> It is inserted at the begining of the list

But `[1].insert(0, [2])` produces `[[2], 1]`.  Is that really what we want? I thought this code wanted `[2, 1]`, instead.

**Comment by hgrecco** [comment]
you are totally right

**Comment by cpitclaudel** [comment]
OK, I tried to fix both of these in the PR.

**Comment by hgrecco** [comment]
The PR looks good to me. Please remove the commented `print` statement and issue a PR against this repo.

**Comment by cpitclaudel** [comment]
Done and done :)
