### ISSUE TITLE
Have a __version__ attribute with a stable format

### ISSUE THREAD

**Issue by cowo78** [hgrecco/pint#803]
Right now we have `pint.__version__` that can be i.e. '0.8.1' or '0.9' which makes difficult to convert to numbers and implement any kind of workarounds for `<SOMEVERSION> < 0x000900'`.
I suggest to use a constant versioning schema that always includes the same components, i.e. the highly original `<MAJOR>.<MINOR>.<PATCHLEVEL>`.

**Comment by hgrecco** [comment]
I completely agree with you, but just for the record the suggested way to compare versions is:
```python
>>> from packaging import version
>>> version.parse('0.8.1') < version.parse('0.9')
True
>>> version.parse('0.9') == version.parse('0.9.0')
True
```
