### ISSUE TITLE
Non-multiplicative conversions in contexts

### ISSUE THREAD

**Issue by Jellby** [hgrecco/pint#806]
Non-multiplicative (temperature) units have deltas, and absolute units have not. However, non-multiplicative conversion rules can be defined in contexts, giving rise to possible pitfalls. Of course, the user is responsible for knowing what he/she is doing, but maybe something could be done already in the code (perhaps just a warning or a configurable exception).

For instance:

```
>>> ureg.enable_contexts('sp')
>>> ureg.parse_expression('1 eV').to('nm')
<Quantity(1239.8419562851186, 'nanometer')>
>>> ureg.parse_expression('1.1 eV').to('nm')
<Quantity(1127.1290511682896, 'nanometer')>
>>> ureg.parse_expression('1.1 eV-1 eV').to('nm')
<Quantity(12398.419562851175, 'nanometer')>
```

which is fine if we want the wavelength corresponding to the energy difference, but if we want the difference in wavelengths for each energy, we should use:

```
>>> ureg.parse_expression('1.1 eV').to('nm')-ureg.parse_expression('1 eV').to('nm')
<Quantity(-112.712905116829, 'nanometer')>
>>> ureg.parse_expression('2.1 eV').to('nm')-ureg.parse_expression('2 eV').to('nm')
<Quantity(-29.520046578217148, 'nanometer')>
```

**Comment by hgrecco** [comment]
I am not sure how to provide a proper warning. Because it seems that you will need to guess the user intention, right?

**Comment by Jellby** [comment]
Maybe requiring an "I understand the risks" option to `enable_contexts` before being able to use non-multiplicative conversions? One could use the frequency<->energy conversion without the option, but one would need to pass the option in order to use length<->frequency.

**Comment by crusaderky** [comment]
I think it's a -1 from me; it feels too much of a nanny attitude. The fact that ``1/a + 1/b`` is not the same as ``1 / (a + b)`` is thought in middle school...

**Comment by hgrecco** [comment]
I agree with @crusaderky . I think that a user requires this operation should write a function.
