### ISSUE TITLE
Applying numpy.cbrt (cubic root) loses quantity

### ISSUE THREAD

**Issue by omtee** [hgrecco/pint#807]
`pint.__version__`
'0.9'
`a = ur.Quantity(100, "m ** 3")`
`print(a)`
100 meter ** 3
`print(np.sqrt(a))`
10.0 meter ** 1.5
`print(np.cbrt(a))`
4.641588833612779

**Comment by hgrecco** [comment]
Yes. This happens because `sqrt` is handled by pint. I hope that we the recent addition to numpy all these quirks will be removed.

**Comment by sxie22** [comment]
When trying to find a workaround, I found that adding another dictionary entry "cbrt" : 1/3 here in quantity.py seems to work.

https://github.com/hgrecco/pint/blob/d804d936f860bdef7e8641ba08d3819ed3c69f28/pint/quantity.py#L1321
`from pint import UnitRegistry`
`ur = UnitRegistry()`
`a = ur.Quantity(100, "m ** 3")`
`print(a)`
100 meter ** 3
`print(np.sqrt(a))`
10.0 meter ** 1.5
`print(np.cbrt(a))`
4.641588833612778 meter

Could you look into this as a hotfix?

**Comment by jthielen** [comment]
This was not added in #905 (even though it likely would have been easy to do so in retrospect). However, this should be an easy addition by defining a new unit operation in

https://github.com/hgrecco/pint/blob/43fbae24028edcffaf855916d7c68889b93786e0/pint/numpy_func.py#L94-L152

and adding the appropriate entry in:

https://github.com/hgrecco/pint/blob/43fbae24028edcffaf855916d7c68889b93786e0/pint/numpy_func.py#L266-L269
