### ISSUE TITLE
Define unit without symbol

### ISSUE THREAD

**Issue by Jellby** [hgrecco/pint#808]
Is it currently possible to define a unit without symbol (but with aliases) in a text file? Currently we have behavior such as:

```
>>> print('{:}'.format(ureg['1 millenium']))
1 millenium
>>> print('{:~}'.format(ureg['1 millenium']))
1 millenia
```

Surely no one intended "millenia" to be the symbol for millennium (the multiple misspelling is another matter). The unit is defined as:

```
millenium = 1000 * year = millenia = milenia = milenium
```

It is possible to set an empty symbol with

```
millenium = 1000 * year = = millenia = milenia = milenium
```

but that still gives a unit with a symbol (that happens to be an empty string). Is there another way? Or should this be the preferred way, and then the code should change an empty symbol to `None`?

**Comment by hgrecco** [comment]
This is not possible now but maybe we should provide a way to do it. Maybe a `_` ?
