### ISSUE TITLE
Value of newtonian_constant_of_gravitation

### ISSUE THREAD

**Issue by lnmaurer** [hgrecco/pint#816]
I think there is a small error in newtonian_constant_of_gravitation in master. The [2018 CODATA](https://physics.nist.gov/cuu/Constants/Table/allascii.txt) value is 6.674**30**e-11  m^3 kg^-1 s^-2, but the value in constants_en.txt is 6.674**08**e-11 m^3/(kg s^2).

**Comment by Jellby** [comment]
Indeed, somehow the old 2014 value slipped in while doing the update.
