### ISSUE TITLE
Nm resolves to the textile unit number_meter as opposed to a torque in newton metres

### ISSUE THREAD

**Issue by strue36** [hgrecco/pint#817]
Commit 3e5f103 introduced some textile units which included number_meter as Nm.
Commit 3ad5c2b added torque to the default_en units definition file but only includes foot_pound.

I am currently using pint to automatically parse engineering data which includes torques labelled as 'Nm'.

Current behaviour is that these are interpreted as textile units. I would expect the more common unit of newton_meter to take precedence.

My first suggestion would be to just add newton_meter to the torque section but this will probably require number_meter to have 'Nm' removed. This is a similar issue to #269.

@cowo78 do you have any thoughts on this?

**Comment by cowo78** [comment]
Besides what you can find in referenced #269 I'd say that the far more common Newton * meter is a simple composite unit while Number metric is a little more complex. Note also that `Nm` in your case should more correctly be `N*m`. An idea that comes to mind is to move clashing definitions into specific contexts.

**Comment by marcowitz** [comment]
I agree with @strue36 that units commonly used in entire fields (such as engineering) that come from SI units (such as Nm) should have prevalence over single applications (such as textile); at least as long as there is no clash-management implemented.

**Comment by hgrecco** [comment]
This can be done with groups and systems. Clashing is inevitable and Nm should be properly written as N m. Nm is a nonstandard notation.
