### ISSUE TITLE
'tuple' object has no attribute 'magnitude'

### ISSUE THREAD

**Issue by xigrug** [hgrecco/pint#818]
I have a value named bulk
>(<Quantity(3.1854693330982826, 'knot')>,
 <Quantity(1.3009142700496523, 'knot')>)

How to get the magnitude easier

bulk.magnitude return

> AttributeError: 'tuple' object has no attribute 'magnitude'

**Comment by hgrecco** [comment]
That is not a quantity but a tuple of quantities. Just get the first or second element first `bulk[0].magnitude`
