### ISSUE TITLE
Pip installation error for Python 2.7

### ISSUE THREAD

**Issue by ajcse1** [hgrecco/pint#819]
I have encountered same error as discussed [here](https://github.com/conda-forge/metpy-feedstock/issues/27)
I understand that this issue has been fixed in this [commit](https://github.com/hgrecco/pint/commit/bfc74ef9dabbf695f29d5c85a494c8c14faf151f). However, it seems only conda-forge package was updated and not PyPI.

We have a package which is dependent on MetPy, which in turn depends on Pint. There might be some users who will use Python 2.7 until it retires. So, wanted to make sure if there will be any future update to Pint PyPI package?

**Comment by hgrecco** [comment]
We are dropping support for 2.7 in the next version. See #906
