### ISSUE TITLE
Latex being printed in HTML output

### ISSUE THREAD

**Issue by agoose77** [hgrecco/pint#820]
https://github.com/hgrecco/pint/blob/ec6d66380a1317fab09297b52f8387b5b4847069/pint/quantity.py#L227

It should be quite straightforward to use a table for this instead.  I wrote a library called [numpy_html](https://github.com/agoose77/numpy-html) which can repr a numpy array to an html table object, and supports arbitrary dimension `ndarrays`.

**Comment by hgrecco** [comment]
Linking to #1757
