### ISSUE TITLE
Unexpected comparison result with `degree` unit

### ISSUE THREAD

**Issue by tomyun** [hgrecco/pint#823]
Not sure if it was intended, but the comparison between a `degree` value and a plain number yielded a confusing result.

```pycon
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> ureg['30 deg'] <= 5
True
```

Suspected this was a behavior of dimensionless unit, then the result of comparison with a `dimensionless` value turned out to be opposite.

```pycon
>>> ureg['30 dimensionless'] <= 5
False
>>>
```

**Comment by Jellby** [comment]
I guess that is because the degrees are converted to radians before doing the comparison

```
>>> ureg['286 deg'].to_base_units()
<Quantity(4.991641660703783, 'radian')>
>>> ureg['286 deg'] <= 5
True
>>> ureg['287 deg'].to_base_units()
<Quantity(5.009094953223726, 'radian')>
>>> ureg['287 deg'] <= 5
False
```

**Comment by hgrecco** [comment]
exactly. Degree is automatically converted to radian when a float value is required.
