### ISSUE TITLE
Document Abbreviated Unit Convention

### ISSUE THREAD

**Issue by samgoodrich1** [hgrecco/pint#836]
I scoured the documentation and issues until I found where the convention is defined for abbreviated units in the unit registry (https://github.com/hgrecco/pint/issues/243 ). I found the 2 rules about the 1st entry being the canonical name and the 3rd entry being the abbreviated name. In the case of Becquerels, the 3rd label was "becquerel" and the first was "Bq". My solution was to include an identical "Bq" in the 3rd place and push "becquerel" to the 4th place. 

I spent about 1.5 hours trying to figure out how to make {:~L} return an appropriate abbreviation and it would be very nice to have the simple rules described above added to the "String Formatting" section of the documentation. Thank you.

**Comment by hgrecco** [comment]
Would you mind making a Pull Request? I would be very happy to merge it and I think it would be more clear coming from somebody with fresh eyes.

**Comment by samgoodrich1** [comment]
I forked and submitted a pull request for develop. I only added the following lines to tutorial.rst:
.. note::
   The abbreviated unit is drawn from the unit registry where the 3rd item in the 
   equivalence chain (ie 1 = 2 = **3**) will be returned when the prefix '~' is 
   used. The 1st item in the chain is the canonical name of the unit.

The formatting specs (ie 'L', 'H', 'P') can be used with Python string 'formatting 
syntax'_ for custom float representations. For example, scientific notation:

..doctest::
   >>> 'Scientific notation: {:.3e~L}'.format(accel)
   'Scientific notation: 1.300\\times 10^{0}\\ \\frac{\\mathrm{m}}{\\mathrm{s}^{2}}'

and modified the one line for becquerels in default_en.txt. However it looks like you had already fixed this.
