### ISSUE TITLE
Improve OffsetUnitCalculusError message

### ISSUE THREAD

**Issue by bilderbuchi** [hgrecco/pint#839]
Currently, the OffsetUnitCalculusError looks like this:

`Ambiguous operation with offset unit (degC)`

I have encountered people being puzzled by this, not knowing what to do against it. Would you think it a good idea to add a link to the docs at https://pint.readthedocs.io/en/latest/nonmult.html that explain how to resolve this error?

**Comment by hgrecco** [comment]
Yes!
