### ISSUE TITLE
add unit for centibars

### ISSUE THREAD

**Issue by garbled1** [hgrecco/pint#841]
Could you please add centibars as a standard pint unit? It's just 100ths of bar, I know, but it would make my life easier.  :)

If you are curious, it's used in soil moisture sensors. (tensiometers)

**Comment by hgrecco** [comment]
Unlike other unit packages, Pint does not define prefixed units. It just defines the units (like `bar`) and the prefixes (like `centi`), and the parser does the rest. So `centibar` is already supported.
```python
>>> import pint
>>> 10 * ureg('centibar')
<Quantity(10, 'centibar')>
```
or alternative:
```python
>>> 10 * ureg.centibar
<Quantity(10, 'centibar')>
```
