### ISSUE TITLE
isinstance

### ISSUE THREAD

**Issue by the-moog** [hgrecco/pint#844]
I want to check if a user is passing a pint quantity instance or a bare float.

I tried 
if isinstance(value, ureg.volt):
but that fails

Indeed, checking the logic with
v = 1.0 * ureg.volt
isinstance(v, type(ureg.volt))
returns False

Is this intentional behaviour?

Update:
OK, so type(ureg.volt) returns something odd.  Perhaps it should return ureg.Quantity?

**Comment by hgrecco** [comment]
you can do: `isinstance(v, ureg.Quantity)`

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
