### ISSUE TITLE
unit analysis/reduction

### ISSUE THREAD

**Issue by plasorak** [hgrecco/pint#848]
I'm not sure whether this is something that has been envisaged, but I think it'd be nice for pint to do the unit reduction (I'm not sure this the exact word) directly when you try to multiply/divide number with different units.
For example:
```
from pint import UnitRegistry
ureg = UnitRegistry()
Q = ureg.Quantity

density = Q('7.8g*cm^-3').to('metric_ton*m^-3')
volume=Q('10m^3')
print (density*volume)

density = Q('7.8g*cm^-3')
volume=Q('10m^3')
print (density*volume)
print ((density*volume).to('metric_ton'))
```
gives:
```
77.99999999999999 metric_ton
78.0 gram * meter ** 3 / centimeter ** 3
77.99999999999999 metric_ton
```
Doesn't the second result look a bit clunky? Pint should probably make a choice between centimetre and metre and stick to it based on whether the multiplication is done left to right, and simplify the ratio.
Anyway I love this package - great work guys.

**Comment by raimundomartins** [comment]
Worse than that:
```
8*1000*un.kg/un.m**3/pi**2 * 50*un.feet * (185*un.gallon/un.min)**2 * 0.007 / (1.75*un.inch)**5
```
gives:
```
DimensionalityError: Cannot convert from 'gallon ** 1.33333 * kilogram / inch ** 5 / minute ** 2' ([mass] / [length] / [time] ** 2) to 'kilogram / inch ** 1 / minute ** 2' ([mass] / [length] ** 1 / [time] ** 2)
```
which means I have to write
```
(8*1000*un.kg/un.m**3/pi**2 * (50*un.feet).to_base_units() * (185*un.gallon/un.min).to_base_units()**2 * 0.007 / (1.75*un.inch).to_base_units()**5)
```
to get `67886.22162748144 kilogram/(meter second2)`

Since I'm using Pint specifically because I have inputs from all sort of different units, it gets kind of annoying. Otherwise, great package!

**Comment by hgrecco** [comment]
There is a kwarg for that, just create your registry in the following way:
```python
ureg = UnitRegistry(auto_reduce_dimensions=True)
```

**Comment by plasorak** [comment]
Ah, well that surely makes things easier. Thanks.
