### ISSUE TITLE
Context.define for currency conversions

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#853]
I'm trying to use pint to perform currency conversions.
Currency FX rates change by the minute and may be different in different markets/situations - which would be modelled perfectly by a pint.Context.

However, while Context allows defining custom conversion functions between different dimensions, it doesn't seem to allow customizing conversions within the same dimension.

I'm currently using throwaway UnitRegistry objects (very expensive to create):
```python
import pint

ureg_day1 = pint.UnitRegistry()
ureg_day1.define("USD = [currency]")
ureg_day1.define("EUR = 1.11 USD")
ureg_day1.define("GBP = 1.22 USD")

ureg_day2 = pint.UnitRegistry()
ureg_day2.define("USD = [currency]")
ureg_day2.define("EUR = 1.13 USD")
ureg_day2.define("GBP = 1.28 USD")

print((100 * ureg_day1("EUR")).to(ureg_day1("GBP")))
print((100 * ureg_day2("EUR")).to(ureg_day2("GBP")))
```
output:
```
90.98360655737706 GBP
88.28124999999999 GBP
```

I could not find a way to convert 100 EUR to USD on day1 and then convert them back to EUR on day2. This doesn't work:
```python
x = 100 * ureg_day1.EUR
x = x.to(ureg_day1.USD)
x = x.to(ureg_day2.EUR)
x
```
Output:
```
100.0 EUR  # Wrong - it should be 98.23 EUR!
```
Workaround:
```python
x = 100 * ureg_day1.EUR
x = x.to(ureg_day1.USD)
x = x.magnitude * ureg_day2.USD
x = x.to(ureg_day2.EUR)
x
```
Output:
```
98.23008849557525 EUR
```

It would make sense to have instead something like:
```python
import pint

ureg = pint.UnitRegistry()
ureg.define("USD = [currency]")
ureg.define("EUR = <TODO: valid currency, but crash if you attempt conversion>")
ureg.define("GBP = <TODO: valid currency, but crash if you attempt conversion>")

ctx_day1 = pint.Context("")
ctx_day1.define("EUR = 1.11 USD")
ctx_day1.define("GBP = 1.22 USD")

ctx_day2 = pint.Context("")
ctx_day2.define("EUR = 1.13 USD")
ctx_day2.define("GBP = 1.28 USD")

x = 100 * ureg.EUR
print(x.to(ureg.GBP, ctx_day1))
print(x.to(ureg.GBP, ctx_day2))

# x = x.to(ureg.USD)  # crash
x = x.to(ureg.USD, ctx_day1)
x = x.to(ureg.EUR, ctx_day2)
print(x)
```
Output:
```
90.98360655737706 GBP
88.28124999999999 GBP
98.23008849557525 EUR
```

**Comment by jetheurer** [comment]
@crusaderky Was this `<TODO: valid currency, but crash if you attempt conversion>` part implemented in your PR?  I am interested in using it if so!

**Comment by crusaderky** [comment]
@jetheurer I didn't implement any of this yet.

**Comment by jetheurer** [comment]
@crusaderky This is terrific!  Thank you!
