### ISSUE TITLE
Percent (%) sign

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#857]
After defining:
```python
import pint
ureg = pint.UnitRegistry()
ureg.define("% = 0.01 count = percent")
ureg.define("%% = 0.001 count = per_mille")
ureg.define("ppm = 1e-6 count = parts_per_million")
```
This works:
```python
>>> ureg("0.1 percent").to("ppm")
1000.0 ppm
```
But % and %% don't:
```python
>>> ureg("0.1%").to("ppm")
AttributeError: 'float' object has no attribute 'to'
>>> ureg("0.1%")
0.1
```

**Comment by jthielen** [comment]
I think this issue has been around for a while (see https://github.com/hgrecco/pint/issues/429), and there are many different workarounds. For example, MetPy has worked around it outside of pint (see https://github.com/Unidata/MetPy/pull/1057).

But, looking back, @hgrecco's comment about having the pre-processor be pluggable/extensible as a way to resolve this (https://github.com/hgrecco/pint/issues/429#issuecomment-290962922) connects this to https://github.com/hgrecco/pint/issues/851 and https://github.com/hgrecco/pint/issues/799. Based on all this, I think I'm going to try putting together a PR for an extensible pre-processor sometime soon.

**Comment by crusaderky** [comment]
Indeed duplicates #429
