### ISSUE TITLE
Add aliases to already existing definitions

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#860]
I'd like to write a custom definitions file that adds new aliases to definitions from defaults_en.txt - as opposed to creating entirely new units.

However, I could not find a way to do it without scouting for the original definition line and writing it again whole.

For example, defaults_en.txt contains:
```
calorie = 4.184 * joule = cal = thermochemical_calorie = cal_th
```

If I want to add an alias, I have to write in my custom definitions file:
```
calorie = 4.184 * joule = cal = thermochemical_calorie = cal_th = CUSTOM_CAL
```
whereas I'd like to just write something like:
```
calorie = ... = CUSTOM_CAL
```

**Comment by hgrecco** [comment]
We don't  have a public API to modify defintions, but that is something in our TODO list. I would be happy to review and merge a PR. See also #563
