### ISSUE TITLE
' _ ' (unnamed variable) in defaults_en.txt

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#861]
defaults_en.txt contains 19 cases of the character ``_`` used as an alias, e.g.

https://github.com/hgrecco/pint/blob/2afdc4bf5c5727ed9cef6fdaccb00b88813c4a24/pint/default_en.txt#L47
https://github.com/hgrecco/pint/blob/2afdc4bf5c5727ed9cef6fdaccb00b88813c4a24/pint/default_en.txt#L77

Does it define an unnamed, temporary alias (``_`` being a legal Python variable)?
What is its purpose? There is no documentation about it that I could find.

**Comment by hgrecco** [comment]
The position within a definition is relevant to pint. The first is the canonical name, the second is the relation to another defined unit, the rest are aliases being the first alias also the symbol. So `_` indicates there is no symbol and the canonical name should be used.

Thanks for pointing that this is not explained. I think, it would be a great idea to explain the structure of a definition file within the definition file itself ina comment. Would you like to submit a PR?

**Comment by crusaderky** [comment]
Ok, I'll work on a PR
