### ISSUE TITLE
Custom _FORMAT

### ISSUE THREAD

**Issue by mrclary** [hgrecco/pint#873]
https://github.com/hgrecco/pint/blob/c777e3ca392b77a2d48bce7416e5c9cf10321176/pint/formatting.py#L190
Is there a good reason for `_KNOWN_TYPES` to be a `frozenset`? This prevents creating custom unit string formats. For example, one could create a custom unit string format for a package by including the following in a package level `__init__.py`.
```python
import pint
from pint.formatting import _FORMATS, _KNOWN_TYPES

_FORMATS.update({'T': {'as_ratio': True,
                       'single_denominator': True,
                       'product_fmt': ' ',
                       'division_fmt': '/',
                       'power_fmt': '{}^{}',
                       'parentheses_fmt': r'({})',
                       }
                 }
                )
_KNOWN_TYPES.append('T')

ureg = pint.UnitRegistry()
```
Then one can do the following.
```python
In [1]: from <pkg> import ureg
In [2]: u = ureg.Unit('m^-3 * s')
In [3]: u
Out[3]: <Unit('second / meter ** 3')>
In [4]: '{:C}'.format(u)
Out[4]: 'second/meter**3'
In [5]: '{:~C}'.format(u)
Out[5]: 's/m**3'
In [6]: '{:~T}'.format(u)
Out[6]: 's/m^3'
```
Alternatively, `_KNOWN_TYPES` could be replaced with `list(_FORMATS.keys()).append('~')` on lines 
https://github.com/hgrecco/pint/blob/c777e3ca392b77a2d48bce7416e5c9cf10321176/pint/formatting.py#L197 and
https://github.com/hgrecco/pint/blob/c777e3ca392b77a2d48bce7416e5c9cf10321176/pint/formatting.py#L275

Unless I'm missing an easier way to create a custom string format...

**Comment by hgrecco** [comment]
Sorry for the long delay. I think we can change that.

**Comment by mrclary** [comment]
Should I submit a merge request or do you want to investigate further first?

**Comment by hgrecco** [comment]
submit a PR
