### ISSUE TITLE
kb translates to kilobarn instead of kilobyte

### ISSUE THREAD

**Issue by thedrow** [hgrecco/pint#874]
The same goes for `b`, `mb` `Gb` etc.
How do I force pint to parse them as measurements of bytes?

**Comment by dr-shorthair** [comment]
The symbol for byte is usually "B"
https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L143 vs.
https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L206

**Comment by thedrow** [comment]
While you are correct, pint is still very inconsistent with its parsing.
Nobody really writes `kB`.

```
In [8]: ureg.parse_expression("100GB")
Out[8]: 100 <Unit('gigabyte')>
In [9]: ureg.parse_expression("100MB")
Out[9]: 100 <Unit('megabyte')>
In [10]: ureg.parse_expression("100KB")
UndefinedUnitError: 'KB' is not defined in the unit registry
In [11]: ureg.parse_expression("100kB")
Out[11]: 100 <Unit('kilobyte')>
```

**Comment by hgrecco** [comment]
I would argue that pint is actually very consistent. The correct abbreviation for kilo is lowercase `k` while the correct abbreviation for mega is the uppercase `M`(see [here](https://physics.nist.gov/cuu/Units/prefixes.html))

If you want to enable `K` as `k` either edit the definition file or use the `case_sensitive=True` argument for `parse_expression`

**Comment by dr-shorthair** [comment]
> Nobody really writes kB.

Err ... I do, and everyone I know does.

**Comment by gnarlium** [comment]
Okay, saw this and had to +1; yes, 'kB' is the only accepted way to write
it.

Regards,
Joe Parlett IV

**Comment by cpascual** [comment]
>Nobody really writes kB

Even if that was the case (which I do not agree) pint's *default* behaviour should be (and AFAIK is) to strictly enforce standards.
IMHO, relaxations of standards should only be allowed if :

1. they are  explicitly enabled by the user, **and**
2. they are 100% safe ( at least  within a certain well-defined scope)

... and interpreting "kb" as kylobytes by default would violate both conditions

 they do not introduce conflicts **and** are enabled explicitly by the user.
