### ISSUE TITLE
hundredweight/hunderdweight typo

### ISSUE THREAD

**Issue by matthewpearlson** [hgrecco/pint#879]
hunderdweight should be replaced with hundredweight to resolve a typo for both the us/uk and short/long hundredweight units in the default_en.txt 

UK_hundredweight = long_hunderweight = UK_cwt
US_hundredweight = short_hunderdweight = US_cwt
short_hundrdweight = 100 avoirdupois_pound = ch_cwt
long_hunderweight = 112 avoirdupois_pound = lg_cwt

**Comment by dr-shorthair** [comment]
This was fixed in f52122cf7e17beb26d7107fc70833d9df7587e74
