### ISSUE TITLE
setting warnings to errors changes the behaviour of `np.asarray` on quantities

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#892]
Using `warnings.filterwarnings` to promote warnings to errors changes the behaviour of `np.asarray` (or rather `np.array` as `np.asarray` delegates to that):
```python
>>> array = np.arange(10) * ureg.m
>>> np.asarray(array)  # warning emitted because units were stripped
[0 1 2 3 4 5 6 7 8 9]
>>> warnings.filterwarnings("error")
>>> np.asarray(array)  # warning should have become an error, but completely disappeared
array([<Quantity(0, 'meter')>, <Quantity(1, 'meter')>,
       <Quantity(2, 'meter')>, <Quantity(3, 'meter')>,
       <Quantity(4, 'meter')>, <Quantity(5, 'meter')>,
       <Quantity(6, 'meter')>, <Quantity(7, 'meter')>,
       <Quantity(8, 'meter')>, <Quantity(9, 'meter')>], dtype=object)
```

This happens with pint `0.9`, but also with the version from #764 (because `__array_function__` does not allow overloading `np.asarray`)

Edit: I do think this is an issue within numpy, but I think it might help to also track this here. Possibly related: numpy/numpy#9761

**Comment by eric-wieser** [comment]
In some sense this is a feature - numpy was told it was not allowed to convert to an int in the second case, so it picked an object array instead.

What behavior would you like here instead?

**Comment by keewis** [comment]
The use case here is catching warnings in unit tests. Obviously, if the warning -- that was converted to an error -- gets swallowed, the test won't work.

**Comment by keewis** [comment]
what I would like is that warnings get re-raised. So something like:
```python
try:
    ...
except Warning:
    raise
except Exception:
    ...
```

**Comment by jthielen** [comment]
Based on discussion in https://github.com/numpy/numpy/issues/14735, this seems to be a pint issue with using `__getattr__` to handle `__array_*` attributes/methods, in particular, `__array__`. With this in mind, I think that pint should explicitly set the `__array_*` attributes/methods it relies on, or at the very least, explicitly define `__array__` (see also https://github.com/hgrecco/pint/issues/878#issuecomment-531029423)?

**Comment by keewis** [comment]
with the merge of numpy/numpy#14745 this won't happen on numpy master and from 1.18 on. We still need to decide if we want to change pint, though, before we can close this

**Comment by jthielen** [comment]
This relates to some other issues with Pint's handling of `__array_*` attributes, so I've created https://github.com/hgrecco/pint/issues/924 to hopefully discuss this and the other issues in general.
