### ISSUE TITLE
fine_structure_constant is completely wrong

### ISSUE THREAD

**Issue by mikapfl** [hgrecco/pint#893]
Hi,

what I get is:
```python
>>> import pint
>>> u = pint.UnitRegistry()
>>> (1*u.fine_structure_constant).to(u.m/u.m)
<Quantity(1.0, 'dimensionless')>
>>> pint.__version__
'0.9'
```
however, the correct value of the fine structure constant is:
```python
>>> (1/(2*u.c*u.vacuum_permittivity) * u.elementary_charge**2 / u.h).to(u.m/u.m)
<Quantity(0.0072973518649977285, 'dimensionless')>
```
Also, the definition in constants_en.txt (line 67) seems somewhat opaque:
```
fine_structure_constant = (2 * h * R_inf / (m_e * c)) ** 0.5 = α = alpha
```

Cheers,

Mika

**Comment by mikapfl** [comment]
Hi,

this is fixed in master already (somehow the rewriting of the constants fixed it, it seems).
But the error is pretty bad, took me a couple of hours to hunt down. Maybe the fix could be released soonish?

Cheers

Mika

**Comment by hgrecco** [comment]
This is indeed fixed in master. I will be in the 0.10 release
