### ISSUE TITLE
Mouser power-rating odd format should throw exception

### ISSUE THREAD

**Issue by raveslave** [hgrecco/pint#898]
Fetchin parametric data from Mouser.com's search api could result in this odd format to represent power-rating. Note that the output is incorrect though

ureg.parse_expression("50 mW (1/20 W)")
<Quantity(2.5, 'milliwatt * watt')> **<--- !?**

Would be nice to see an exception in this case

correct
ureg.parse_expression("50 mW")
<Quantity(50, 'milliwatt')>

ureg.parse_expression("(1/20 W)")
<Quantity(0.05, 'watt')>

**Comment by dalito** [comment]
Pint treats spaces in the string as multiplication. Given this, how could we detect the string in your example as invalid? I think there is no way or we break other uses e.g. fuel comsuption "4 l / (100 km)".

**Comment by hgrecco** [comment]
See also #555
