### ISSUE TITLE
How to properly deal with dimensionality errors

### ISSUE THREAD

**Issue by bartlettD** [hgrecco/pint#901]
I'm trying to write a python script which uses some variables using pint to implement this formula

![image](https://user-images.githubusercontent.com/2047912/68853115-1f394580-06d1-11ea-8a37-2d8c160fad35.png)

So far I've not had much luck as I keep running into `DimensionalityError`s when trying to use my variables in calculations.

This is the code that I'm trying to run, am I using pint correctly in this case? The value that I'm trying to compute doesn't really have a unit so to speak but I'd still like to use pint in other parts of my program to compute power from current and voltage while being able to easily print in a human readable SI prefix.
```
from pint import UnitRegistry
ureg = UnitRegistry()


#Diode Voltage Drop
VDropD = 1 * ureg.V # Assuming 1V for now.
VinMin = 4 * ureg.V
Vout = 180 * ureg.V

#Nturns = list(range(1,11))
Nturns = 2
#print(Nturns)

Duty = (Vout + VDropD) \
    /(Nturns * VinMin) + Vout + VDropD

print(Duty)
```

When I run the program this is the error I get out. Is there a good way to deal with this? I'm not really trying to do a conversion so is there any way to tell pint just to ignore or skip this? I haven't managed to notice anything in the docs.

`pint.errors.DimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'volt' ([length] ** 2 * [mass] / [current] / [time] ** 3)`

**Comment by dalito** [comment]
The code does not correspond to the formula. Change `Duty = (Vout + VDropD) / (Nturns * VinMin) + Vout + VDropD` to `Duty = (Vout + VDropD) / ((Nturns * VinMin) + Vout + VDropD)`.

**Comment by hgrecco** [comment]
Which by the way is a nice example about how pint can help you find errors! :-D

**Comment by bartlettD** [comment]
You're right, thanks! T'was a silly mistake. Sorry about that!
