### ISSUE TITLE
Bad babel formatting, not as documented

### ISSUE THREAD

**Issue by OJFord** [hgrecco/pint#903]
[Docs](https://pint.readthedocs.io/en/0.9/tutorial.html?highlight=babel):

> Finally, if Babel is installed you can translate unit names to any language
> ```
> >>> accel.format_babel(locale='fr_FR')
> '1.3 mètre par seconde²'
> ```

v0.9.0:
```
>>> ureg=pint.UnitRegistry()
>>> accel = 1.3 * ureg['meter/second**2']
>>> accel.format_babel(locale='fr_FR')
'1.3 {0}\xa0mètre par {0}\xa0seconde²'
>>> accel.format_babel(locale='en_GB')
'1.3 {0} metres per {0} seconds²'
```

i.e. `{0} ` is inserted between the magnitude and units, and before each subsequent compounding unit.

**Comment by hgrecco** [comment]
This is fixed on master
