### ISSUE TITLE
Drop Python 2.7 support?

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#906]
Dropping  Python 2.7 support has popped up a few times recently. I would like to make a list of issues and PR, and arguments to drop (or keep). Furthermore, if we drop: what will be the minimum Python 3 version we will support?

Issues suggesting drop:
- #905

**Comment by jthielen** [comment]
To follow many of the core packages in the scientific Python ecosystem, I would think following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) would be best (so, Python 3.6+ currently).

**Comment by crusaderky** [comment]
At xarray we implemented NEP-29 and we're *very* happy with how many day-to-day problems it solves.
For third-party libraries that aren't numpy and pandas, we've implemented a very aggressive 6 months window and so far (AFAIK) we have not received a single complaint.

**Comment by crusaderky** [comment]
Closes #871
