### ISSUE TITLE
2019 Xmas cleanup 

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#917]
It would be very nice to start 2020 with less open issues and PRs. Merging #905 will help to close / redefine many PRs but I am inviting all the community to review old issues to see if they are still needed. You are also encourage to rewrite old issues into new combined ones.

From a quick look, I could tell we have the following topics:
- Numpy compatibility (Should be dicussed in the context of #905 )
- Scipy compatibility
- Pandas compatibility
- Better/New API to define/redefine: Units/Systems/Groups/Contexts
- Measurements
- Improved wraps/checks
- New unit definitions
- Better error/warning messages
- Better output formatting
- Better documentation

We do not need to solve everything, but I think it will be worth to have a better roadmap.

If you are interest in champion one of these topics (or other):
- create a new issue
- summarize the ideas, problems and solutions
- link the relevant issues (I will close those to clean up)
- start a discussion for a roadmap.

Also, if you encounter issues or PRs that are not longer valid, please flag them and I will close them.

**Comment by dalito** [comment]
Do you plan to create a last Python-2.7-compatible release (0.9.1) before breaking with Python 2.7 in 0.10?

**Comment by hgrecco** [comment]
> Do you plan to create a last Python-2.7-compatible release (0.9.1) before breaking with Python 2.7 in 0.10?

That is the plan, but I want to be as complete as possible. And close to equivalent to 0.10 in features.

**Comment by hgrecco** [comment]
We went down from 230 issues and 23 PRs to 162 and 19 respectively. Let's continue!

**Comment by hgrecco** [comment]
Now we are at 149 issues and 6 PRs.
