### ISSUE TITLE
Automatic inference of units for numeric literals

### ISSUE THREAD

**Issue by artgoldberg** [hgrecco/pint#935]
Consider this equation, the mass action rate law for the chemical reaction 2P -> X:

    rate = k1 * P * (P - 1)) / 2

It has these units:

    k1: 1 / (molecule^2 * second)
    P: molecule
    rate: 1 / second

But it's not dimensionally correct, because the '1' must have the unit molecule.

This creates an inconvenience in our biochemical simulator, as users will need to define a parameter with the right units in place of '1'.

Does Pint contain functionality to infer that '1' has the unit molecule? More generally, I'm suggesting that Pint could have an analysis function that determines the units of numerical literals if and only if the units for the literals are completely unambiguous. Thus, this function would always assign correct units, except when declared terms already had incorrect units.

Thanks
Arthur

**Comment by hgrecco** [comment]
The general rule in Pint is: "Do not guess user intention".  So this will not be an automatic feature. Creating "unit infering function" might be interesting, but not in our roadmap.

However, your particular use case is easy to solve. You can [wrap](https://pint.readthedocs.io/en/0.9/wrapping.html) a function

```python
@ureg.wraps('1/second', ('1 / (molecule^2 * second)', 'molecule')
def rate(k1, P):
    return k1 * P * (P - 1) / 2
```

The value of P, inside the function will be just a number.

**Comment by artgoldberg** [comment]
Thanks Hernan. That makes sense. We'll make a generic function for ourselves.
