### ISSUE TITLE
array function implementation for np.cumprod / np.nancumprod fails with axis

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#939]
Passing a `axis` argument to `cumprod` / `nancumprod` will make them fail. I tracked it down to https://github.com/hgrecco/pint/blob/4c3114c72bdae1e3c5c9f839659169eeb06071cd/pint/numpy_func.py#L62 where `pre_calc_units` can be a string (`"dimensionless"`), but a `Unit` object was expected. The string was created when `implement_func` was called for `cumprod` and `nancumprod` (by the way, `cumprod` also gets implemented with `set_units_ufuncs`). We can fix this by passing `None` as `input_units` instead, but if feasible I'd prefer `"dimensionless"` since that is way easier to read and understand. For that, we might need to preprocess the `input_units` parameter in `implement_func`.

**Comment by hgrecco** [comment]
I think is the same as #867 , right?

**Comment by keewis** [comment]
#867 is about the units of the result if one were to pass `axis` (and existed before #905), while this issue was introduced in #905 when `implement_func` was written. `cumprod` is only defined for `dimensionless`, so the resulting unit is not a problem.
