### ISSUE TITLE
What shall we include for 0.10?

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#955]
I would like to release version 0.10 soon. What shall we include (i.e. wait for)? Please add issues and PR below

**Comment by jthielen** [comment]
If possible, I think it would be great to have the main follow-ups to #905 included, namely #925 and (most of) #845. I have time available these next couple days to be working on these, so hopefully they can be ready soon.

**Comment by crusaderky** [comment]
I'm going to state the obvious: 0.9 was 11 months ago - that's an enormity. If we could move to a monthly release schedule, this kind of discussion would become redundant...

**Comment by hgrecco** [comment]
While I agree, I still think we need to list a few open issues and PRs that we think need to be solved before 0.10 to avoid a half baked release.  My plan is to release on Jan 3/4. What shall we focus on?

**Comment by hgrecco** [comment]
I have just release 0.10. Thanks everybody that contributed to this awesome release. I will writing something on twitter tomorrow summarizing some of the most relevant change.s 

Please test the installation and let me know.

And let's start thinking for 0.11.

**Comment by dopplershift** [comment]
🎉 Congrats and thanks all for the hard work! Conda-forge packages are building and uploading right now.

Coincidentally, I just released MetPy 0.12 which should be compatible with the changes in Pint 0.10 (assuming I didn't miss any failing tests...)

**Comment by hgrecco** [comment]
I have just tweeted something small about this:

https://twitter.com/GreccoHernan/status/1214237245957263370
