### ISSUE TITLE
IndexError on assigning units to empty Numpy array (Pint 0.10)

### ISSUE THREAD

**Issue by rebeccafair** [hgrecco/pint#973]
Since the 0.10 update if I try to assign units to an empty array, I get an IndexError

```
>>> import numpy as np
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> x = np.array([])
>>> x*ureg('kg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\quantity.py", line 1507, in __array_ufunc__
    return numpy_wrap("ufunc", ufunc, inputs, kwargs, types)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\numpy_func.py", line 888, in numpy_wrap
    return handled[name](*args, **kwargs)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\numpy_func.py", line 268, in implementation
    first_input_units = _get_first_input_units(args, kwargs)
  File "C:\Users\mll13652\AppData\Local\conda\conda\envs\py37\lib\site-packages\pint\numpy_func.py", line 69, in _get_first_input_units
    return arg[0].units
IndexError: index 0 is out of bounds for axis 0 with size 0
```

After looking into it a bit more it seems that in `_get_first_input_units`, `_is_quantity_sequence()` incorrectly returns `True` for empty arrays as the final check:
```
all(_is_quantity(item) for item in obj)
```
returns `True` for empty arrays.

One possible fix would be to get `sized` to also check for zero length and return `False`, preventing the check from getting to the above line, and I'd be happy enough to make a PR for this

**Comment by jthielen** [comment]
Good catch, and my apologies for forgetting about the vacuously true `all` in #905! 

I would recommend against changing `sized` however, since an empty array is still "sized" in the ABC sense. A better check would be adding `and len(obj) > 0` to the expression either before or after the `and all(...` line.

**Comment by hgrecco** [comment]
Thanks for reporting so quickly. We need to solve it ASAP. A few thoughts:
- as mentioned by @jthielen `sized` must return `True` for an empty array to avoid breaking ABC
- In the same direction, I think `_is_quantity_sequence` should also return `True` for an empty array. Returning `False` will be misleading with the function name.

So ... either we:
- change the function name
- add a ` len(obj) > 0` where `_is_quantity_sequence` is used

**Comment by jthielen** [comment]
@hgrecco Good point. I'd vote to rename to `_is_sequence_with_quantity_elements` or something similar (it is a little verbose), since that is how I thought of it while reimplementing #764 in #905.

**Comment by hgrecco** [comment]
IMHO verbose is fine. It is an internal function. I rather have it verbose than misleading.

**Comment by hgrecco** [comment]
0.10.1 is on PyPI. Please let me know if it works for you

**Comment by rebeccafair** [comment]
It's all working fine now, thanks for the quick turnaround!

You can thank CI for finding the issue so quickly :)
