### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by dopplershift** [hgrecco/pint#974]
Looks like a bug crept into 0.10 when `PINT_ARRAY_PROTOCOL_FALLBACK` is `'0'`:
```python
import os
os.environ['PINT_ARRAY_PROTOCOL_FALLBACK'] = '0'

import numpy as np
import pint

q = pint.Quantity(np.arange(3, dtype=np.float32), 'm')
np.array(q) # OK
np.array(q, dtype=np.float64) # Error
```
The last one yields:
```pytb
TypeError                                 Traceback (most recent call last)
<ipython-input-5-ba6cd2ac8160> in <module>
      8 np.array(q)
      9 
---> 10 np.array(q, dtype=np.float64)

TypeError: __array__() takes 1 positional argument but 2 were given
```

I think that's because the `__array__` implementation does not accept any args:
https://github.com/hgrecco/pint/blob/a70be489c46c03ca15c2832a308a56a556270461/pint/quantity.py#L1554-L1560

PR with tests incoming...

(attn: @jthielen)

**Comment by dopplershift** [comment]
For the record, this means it's impossible (with the flag enabled) to pass `Quantity` instances to matplotlib plotting unless the dtype matches what matplotlib wants.

**Comment by jthielen** [comment]
Thanks for catching this! I based the implementation off of https://docs.scipy.org/doc/numpy/user/basics.dispatch.html, which doesn't have the additional argument for `__array__`. Do you think this would be a worthwhile upstream doc fix so future array container implementers don't fall into the same trap?

**Comment by dopplershift** [comment]
I think so. It’s a pretty important omission.

**Comment by hgrecco** [comment]
0.10.1 is on PyPI. Please let me know if it works for you

**Comment by dopplershift** [comment]
@hgrecco Oh, thanks for making that! 0.10.1 seems to be working fine for our collection of notebooks.

**Comment by jthielen** [comment]
Here is the upstream issue: https://github.com/numpy/numpy/issues/15292
