### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by dkurniawan3** [hgrecco/pint#980]
setup.cfg specifies the following: `python_requires = >=3.6` as well as classifiers that specify the need for Python 3.6-3.8, however you're building a universal wheel which generates py2 in the platform tag. Is this package meant to be Python 2/3 compatible?

**Comment by dopplershift** [comment]
No, it was decided to remove Python support in #906. I think it's just an oversight that this is left in `setup.cfg`:
```ini
[bdist_wheel]
universal = 1
```
