### ISSUE TITLE
checking for unit compatibility

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#988]
What is the official way to check compatibility between units (or arrays and units)? Right now I'm using
```python
array.check(unit)  # for mixed array / unit
array.dimensionality == unit.dimensionality  # same as above

array.dimensionality == other_array.dimensionality  # for two arrays
unit.dimensionality == other_unit.dimensionality  # for two units
```
but it took me some time to realize this was possible (it is not really obvious to me and I couldn't find it in the docs -- I might have missed it, though).

I usually put this in a function named something like `is_compatible` to make it a little bit more robust. If there is no such function yet, is there any interest in adding one?

**Comment by keewis** [comment]
I was thinking about a top-level function like
```python
def is_compatible(unit1, unit2):
    def get_dimensionality(obj):
	if isinstance(obj, (unit_registry.Quantity, unit_registry.Unit)):
            unit_like = obj
	else:
            unit_like = unit_registry.dimensionless

	return unit_like.dimensionality

    return get_dimensionality(unit1) == get_dimensionality(unit2)
```

**Comment by hgrecco** [comment]
I would also agree with a top level function (I still think that a method for Quantity and Unit would be nice also).

PS.- I think you have a bug in your code, `unit_registry.dimensionless` will return a bool`.

Regearding making it unit aware, the easiest way is to add the folowing arguments to your function
`*contexts, **ctx_kwargs` and then try to convert the quantity and check for errors:
```python
try:
    quantity.to(new_unit, *contexts, **ctx_kwargs)
    return True
except pint.errors.DimensionalityError:
    return False
```
It woud be nice to have a context aware `get_dimensionality` but is not possible because there will be multiple results.

**Comment by keewis** [comment]
the bug happens when not using the default registry: then the `isinstance` check will always return `False` so the unit gets lost. I think using `hasattr(obj, "dimensionality")` instead could help.

Regarding your proposed implementation: that could work, but only when quantities are involved (i.e. it works the same way as `Quantity.check`).

**Comment by hgrecco** [comment]
I think the implementation could go along the following lines:

In Quantity
```python
def is_compatible(self, other, *contexts, **ctx_kwargs):
    if contexts:
        try:
            self.to(other, *contexts, **ctx_kwargs)
            return True
        except pint.errors.DimensionalityError:
            return False
    if isinstance(other, (Quantity, Unit)): 
        return self.dimensionality == other.dimensionality 
    if isinstance(other, str):
        return self.dimensionality == self._REGISTRY.parse_units(other).dimensionality
    return self.dimensionless
```

In Unit:
```python
def is_compatible(self, other, *contexts, **ctx_kwargs):
    if contexts:
        try:
            (1 * quantity).to(other, *contexts, **ctx_kwargs)
            return True
        except pint.errors.DimensionalityError:
            return False
    if isinstance(other, (Quantity, Unit)): 
        return self.dimensionality == other.dimensionality 
    if isinstance(other, str):
        return self.dimensionality == self._REGISTRY.parse_units(other).dimensionality
    return self.dimensionless
```
Top level function:
```python
def is_compatible(obj1, obj2, unit_registry=None, *contexts, **ctx_kwargs):
    ureg = unit_registry or pint._DEFAULT_REGISTRY # or should be the APP registry????
    if isintance(obj1, (ureg.Quantity, ureg.Unit)):
        return obj1.is_compatible(obj2, *contexts, **ctx_kwargs)
    if isinstance(obj1, str):
        return unit_registry.parse_expression(obj1).is_compatible(obj2, *contexts, **ctx_kwargs)
    return not isinstance(obj2, (ureg.Quantity, ureg.Unit))
```

**Comment by keewis** [comment]
This looks fine to me, but I'd make `unit_registry` a keyword-only argument if it should be possible to specify contexts without passing a different unit registry.

If it's fine with you I'd put in a PR so we can comment on the actual code (and documentation).

Also, `is_compatible` works (it strongly suggests the result is a `bool`), but I would like to suggest `compatible_with` (which feels a little bit more natural, especially as a method). No strong opinion, though.

**Comment by hgrecco** [comment]
> I'd make unit_registry a keyword-only argument if it should be possible to specify contexts without passing a different unit registry.

Agree

> If it's fine with you I'd put in a PR so we can comment on the actual code (and documentation).
That would be great. I would also add this function to the registry itself. 

Regarding the name, for methods I usualy like using verbs. But `check_compatible_with` is very long. Any other ideas?
