### ISSUE TITLE
Question: testing workflow for pint

### ISSUE THREAD

**Issue by 5igno** [hgrecco/pint#990]
Hi,

I am a happy user of pint and cannot thank you enough for making it available as OSS.
I like the way it makes unit conversion and dimensional analysis effortless, all in a small package.
Brilliant :)
To be more accurate, I am a physicist working in optics and electrical engineering. As many users in this circle, I have growing need for logarithmic units as dB, decade, octave, etc.

As the support for these units is missing, I am trying to implement Logarithmic unit conversion myself (see [the commits on my fork of pint](https://github.com/5igno/pint/commits/develop)), but I didn't understand well enough how to test pint as required by your guidelines.

Could you comment on the process you use to test pint?

**Comment by 5igno** [comment]
For the testing the modified library should I follow the guide here?
[pytest/Good Integration Practices](https://docs.pytest.org/en/latest/goodpractices.html#goodpractices)

**Comment by 5igno** [comment]
I am finding this answer on [`pip install -e`](https://stackoverflow.com/questions/42609943/what-is-the-use-case-for-pip-install-e) useful ... but is this the workflow you use to develop pint?

**Comment by 5igno** [comment]
@hgrecco, would you agree that [testing guidelines from numpy](https://docs.scipy.org/doc/numpy/reference/testing.html) also apply to pint? Sorry for the beginners question, but I have no idea of what I am doing ... some reference would be gold.

**Comment by dalito** [comment]
Hi, I am not sure where your troubles come from. The steps are:

- Create a virtual environment (VE)
- Activate this VE
- Install your pint (run `pip install -e .` in the root of your local pint-fork)
- Install optional add-ons like e.g. numpy into your VE (`pip install numpy`)
- Install pytest into your VE (`pip install pytest`)
- Execute `pytest` at the root of your source folder. It will discover and run all tests. 

If you want to test different Python or numpy versions or combinations **locally**, I suggest to use tox (or nox). pint has no config file for tox or nox at the moment. To see what is tested routinely look at `.travis.yml`.

**Comment by hgrecco** [comment]
I think @dalito  provides a great summary. Just one more thing, the numpy guide is great but is intended for a mucha larger project. Therefore, some things like testing only parts, might be an overkill.

**Comment by 5igno** [comment]
Thank you for your input and your patience: I am new to contributing to an open-source projects and wanted to understand the proper way to proceed, rather than submit half-made work.

As for the point I raised about discourse, it seems you guys are fine with using Github issues for Q&A and label them with question. Is that a fair assessment?

**Comment by dalito** [comment]
@5igno, asking such questions here is fine from my point of view. Given the low volume, I think using Git issues are sufficient for pint at the moment.

**Comment by hgrecco** [comment]
I agree with @dalito on this.

**Comment by 5igno** [comment]
OK, i will modify the question accordingly.

**Comment by hgrecco** [comment]
And as I said, feel free to ask any question on the tracker. I am proud and happy to say that the community is very welcoming and helpful

**Comment by 5igno** [comment]
Alright... so I am back to trying submitting a simple PR. I followed the workflow of @dalito but, when running pytest, I get reported of the existance of one error and many warnings, that is without having modified the code in the development branch.

`=== 1 failed, 1036 passed, 27 skipped, 5 xfailed, 26 warnings in 23.94s ===`

Should I neglect the warnings of pytest?

**Comment by jules-ch** [comment]
About the warnings you can skip them in your case, those are deprecation warnings that we need to address.
Pint is running a CI Pipeline (Continuous Integration) with Travis  which run all those tests remotely. So don't be afraid to submit a PR & we can tell you what's wrong with it, if some tests are failing.
